### ISSUE TITLE
[question] Pricing for x-chart

### ISSUE THREAD

**Issue by Antonytm** [mui/mui-x#10137]
### Order ID or Support key 💳 (optional)

11111

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to add charts to my project. I tried them and they quite fit my needs even in the current alpha.
https://mui.com/x/react-charts/bars/

But I can't find any information about pricing for them https://mui.com/pricing/

I don't want to use something that will be available only in Premium.
What should we expect for @mui/x-charts?  
If you still are not ready to give full information, can you set at least some base expectations?
E.g. all charts will be available in "community" or nothing in community, all in "Pro", or part in "community", part in "pro", and part in "premium".

### Your environment 🌎

```
N/A
```

**Comment by flaviendelangle** [comment]
On the X product, you can always take for granted that if a feature in available in the free version will remain available forever in the free version.
The only exception is when we don't have the pro version available **AND** the doc clearly says that the feature will be moved to the pro/premium plan when available (it was the case for the row grouping feature of the data grid).

For the charts, the development flow is clear enough so that no feature will ever be released first on the free version and then move away. We will create the pro package when we have a first pro feature. So you don't have to be worry anything you use will always be free :+1:

**Comment by alexfauquette** [comment]
We could keep this issue open until we add charts to the [pricing page](https://mui.com/pricing/)

> I would like to add charts to my project

Hope you will enjoy it 🎉 

Don't hesitate to open issues for missing feature/customization, or to share your project in the discord
