### ISSUE TITLE
TreeDataPath is not updating the treeTable after apiRef.current.updateRows modified data

### ISSUE THREAD

**Issue by cannontechnology** [mui/mui-x#10131]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/mui-treetable-update-29q6wp?file=/demo.tsx 

Steps:

1. https://codesandbox.io/s/mui-treetable-update-29q6wp?file=/demo.tsx 
2. Expand the tree to see the data is sorted properly
3. Click "Update All"
4. Notice the TreeDataPath does not update

### Current behavior 😯

The tree stays grouped the same after updating the underlying data from the server.

### Expected behavior 🤔

TreeDataPath updates the treeTable after apiRef.current.updateRows modified data 

### Context 🔦

Trying to update the data after polling the API.

### Your environment 🌎

<details>
  <summary><code>
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.54)
  npmPackages:
    @emotion/react: latest => 11.11.1
    @emotion/styled: latest => 11.11.0
    @mui/base:  5.0.0-beta.11
    @mui/core-downloads-tracker:  5.14.5
    @mui/icons-material: ^5.14.3 => 5.14.3
    @mui/material: ^5.14.5 => 5.14.5
    @mui/private-theming:  5.14.5
    @mui/styled-engine: latest => 5.13.2
    @mui/system: ^5.14.5 => 5.14.5
    @mui/types:  7.2.4
    @mui/utils:  5.14.5
    @mui/x-data-grid:  6.11.2
    @mui/x-data-grid-premium: ^6.11.2 => 6.11.2
    @mui/x-data-grid-pro:  6.11.2
    @mui/x-license-pro:  6.10.2
    @types/react: 18.2.7 => 18.2.7
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.1.3 => 5.1.6
</code></summary>

</details>

### Order ID or Support key 💳 (optional)

Purchase order no. 10004760

**Comment by MBilalShafi** [comment]
Hey @cannontechnology, thank you for providing the codesandbox example and sysinfo. 

May I ask why are you expecting the tree data path to be updated on `Update All Rows`?
`Update All Rows` is only updating the data of each row, not `path`.

If you see the structure of a `treeData` row, it has a `path` variable, which determines the position of the row in the tree. (Check `createRandomRow` in the codesandbox example). So, since `Update All Rows` is not updating the `path`, the position in the tree is never updated, only the data updates.

Let me know if this is the answer you were looking for. 🙂

**Comment by flaviendelangle** [comment]
Just if case, `getTreeDataPath` should be memoized, otherwise your tree will be computed on every render which is far from ideal.

**Comment by MBilalShafi** [comment]
Great, I'll close the issue in that case, feel free to reopen and let us know if there's something else we can assist you with.
