### ISSUE TITLE
Regression on DataGrid type definition - no way to overload interfaces

### ISSUE THREAD

**Issue by giladv** [mui/mui-x#10142]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

In the past

interfaces like ``GridColDef`` were actual TS interfaces, on the latest version it was changed to types.
problem is, if you want to extend DataGrid with your own column property for example, it is no longer possible to overload the interface like so
```
declare module "@mui/x-data-grid" {
  interface GridColDef  {
    summarize?: boolean;
  };
}
```

### Your environment 🌎

latest everything

**Comment by giladv** [comment]
sorry, missed your reply. 
i would like to extends the functionality with my own summary row for example. 
i'd like to add a new property to the col definition that specifies how it sums up the column values.

**Comment by romgrk** [comment]
We could maybe do something like this:

```typescript
interface GridColDefExtra {}

type GridColDef = (GridBaseColDef | GridActionsDef | GridSingleSelectColDef) & GridColDefExtra
```

But I don't feel super convinced of the need for this.
@MBilalShafi what do you think?
@giladv If you want this,  it would probably be faster if you submit a PR for it.

Relevant code:
https://github.com/mui/mui-x/blob/a0cd6bb38b66a1b330c9d4f73a5d08ee147b1566/packages/grid/x-data-grid/src/models/colDef/gridColDef.ts#L325-L328

**Comment by MBilalShafi** [comment]
> I don't feel super convinced of the need for this.

Yep I agree, I have an impression that what @giladv is implementing is possible in a better way with using slotProps instead of overriding GridColDef type.

@giladv Could you provide a codesandbox example for visualizing the problem better? That way we might be able to suggest you a better alternative or provide a way to extend the `GridColDef` prop. You can use [this codesandbox example](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) as a starting point if you want.

Thank you!
