### ISSUE TITLE
dragenter event of cells do not bubble in DataGridPro

### ISSUE THREAD

**Issue by bishopj15** [mui/mui-x#10164]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Add dragenter,  event listener to parent component
2. Add DateGridPro as a child with some data so that some rows appear
3. Drag File from file explorer directly over a cell

### Current behavior 😯

dragenter event of parent never triggers

### Expected behavior 🤔

dragenter event of parent triggers

### Context 🔦

I have a drag and drop area over a DataGrid that has worked fine until switching to DataGridPro. The dragenter event no longer bubbles up. dragover and dragleave still bubble as expected

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Could you provide a minimal reproduction test case with the latest version? This would help identify the issue better. 👷
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!

**Comment by bishopj15** [comment]
https://codesandbox.io/s/relaxed-snowflake-s98g93?file=/demo.tsx

Digging a bit deeper I've learned react-dropzone was being so the issue might actually be in that package. The live example shows the event firing as expected with DataGrid but never firing with DataGridPro

**Comment by MBilalShafi** [comment]
This has nothing to do with the **DataGrid** or **DataGridPro** itself, as the events are listened to by an external element and not the grid, bubbling doesn't happen in this case as the absolute element the events are binded to is above the Grid (due to a higher z-index and absolute positioning).

The reason why it doesn't work for the external elements is because of the semantic positioning of the elements.
I've [updated](https://codesandbox.io/s/infallible-khorana-pfl8wg?file=/demo.tsx) the codesandbox to demonstrate both the Grid variants detecting `dragenter` event and detecting the dropzone.

Let me know if this solves your use-case?

**Comment by bishopj15** [comment]
I still see the same behavior in the new example. I don't think it's the positioning. Dragging from system directly over a row cell in DataGridPro does not send up a dragenter the same way DataGrid does. If you drag from anywhere outside the row cell then the event triggers because entering the base of the component does trigger the event in DataGridPro. I've included a GIF demonstrating this

![Drag and drop example](https://github.com/mui/mui-x/assets/3375448/2e3d4157-7480-46d6-b9ce-ccd9355edcb7)

**Comment by bishopj15** [comment]
@MBilalShafi Have you had a chance to look at the above video? Your example does not show the event

**Comment by serhanguney** [comment]
I'm having exactly the same problem. I tried to add inline styles for z-index levels and made sure that the parent element is above data grid pro, and still the same problem.

**Comment by serhanguney** [comment]
As a workaround using `onDragOver` instead of `onDragEnter` seems to be working.

**Comment by segullshairbutt** [comment]
Yeah, I am facing the same problem. I tried to inspect the HTML document through Chrome dev tools and found that virtual-scroller which is handling the virtualization causes these issues. If you make the `z-index: -1` of that virtual scroller `div`. `onDragEnter` works but the problem is that it hides the content added through the virtualization.

**Comment by MBilalShafi** [comment]
Sorry about the delayed response @bishopj15. It seems like it's because of the column reorder feature stopping event propagation for drag events, for example:
https://github.com/mui/mui-x/blob/next/packages/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx#L95

If you could live without the column reorder feature, one fix could be to pass the prop `disableColumnReorder`

I tried this demo and it seems to work as expected for me: https://codesandbox.io/p/sandbox/thirsty-shape-jjfdp9?file=%2FDataGridDemo.tsx

**Comment by MBilalShafi** [comment]
Hey @bishopj15, just an FYI, [version 7 stable](https://github.com/mui/mui-x/releases/tag/v7.1.0) has already been released, let us know if you face any difficulties in migrating to it. Here's the [migration guide](https://mui.com/x/migration/migration-data-grid-v6/) to help you do it.

Thank you!
