### ISSUE TITLE
 Property 'format' does not exist on type 'IntrinsicAttributes & DatePickerProps<unknown, unknown> & RefAttributes<HTMLDivElement>'.

### ISSUE THREAD

**Issue by rwb196884** [mui/mui-x#10189]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

```
  return <DatePicker
    value={props.value ?? null}
    className={props.className}
    disabled={props.disabled}
    format="dd/MM/yyyy"
    placeholder={props.placeholder ?? 'DD/MM/YYYY'}
  />;
```

### Current behavior 😯

 Property 'format' does not exist on type 'IntrinsicAttributes & DatePickerProps<unknown, unknown> & RefAttributes<HTMLDivElement>'.  TS2322

### Expected behavior 🤔

It works.

### Context 🔦

Trying to update from MUI 4

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

?

**Comment by LukasTy** [comment]
Could you confirm which version you are trying to upgrade to?
Is it v5, which would be logical, given that you are on v4? Jumping to v6 can only be done manually.
If it is the v5 you are trying to upgrade to, please refer to [its documentation](https://v5.mui.com/x/api/date-pickers/date-picker/) instead of the latest v6.

Given that you are talking about v4, you are probably using the legacy `@material-ui/pickers`, in such case, please refer to the [migration to lab guide](https://mui.com/material-ui/guides/pickers-migration/) first, then change the dependencies to `@mui/x-date-pickers` to v5.x and follow the [migration from lab guide](https://v5.mui.com/x/react-date-pickers/migration-lab/).
At this point, if everything is working fine, you can follow the [migration to the v6 guide](https://mui.com/x/migration/migration-pickers-v5/). 😉

**Comment by brencodes** [comment]
Oh man, I am so glad someone else had this issue! I was also mistakenly reading the v6 documentation while trying to do this in v5🤦 

This was all I needed, took me an hour to find it haha `inputFormat="yyyy/MM/dd"`

**Comment by flaviendelangle** [comment]
![image](https://github.com/mui/mui-x/assets/3309670/f6824af1-c62e-42ca-96f7-edf600abaf4f)
 

You can find the version you are currently visiting on the top left corner of the documentation.
Clicking on the version allows you to jump to another version of the doc.
