### ISSUE TITLE
[DataGrid] Row Grouping - column does not display its description / tooltip

### ISSUE THREAD

**Issue by JuliaKnaeble** [mui/mui-x#10199]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Codesandbox example using Row Grouping:
https://codesandbox.io/s/sharp-swirles-kmrp47?file=/Demo.tsx

Steps:
1. open the codesandbox example
2. move your cursor over the column "Company"
3. notice that the column description / tooltip for "Company" does not show up

### Current behavior 😯

Columns that use Row Grouping do not display the provided description / tooltip

### Expected behavior 🤔

Columns that use Row Grouping should display their description / tooltip

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: Not Found
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Edge: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react: 11.10.6 => 11.10.6 
    @emotion/styled: 11.10.6 => 11.10.6 
    @mui/base: 5.0.0-alpha.112 => 5.0.0-alpha.112 
    @mui/core-downloads-tracker:  5.12.3 
    @mui/lab: 5.0.0-alpha.114 => 5.0.0-alpha.114 
    @mui/material: 5.11.4 => 5.11.4 
    @mui/private-theming:  5.12.3 
    @mui/styled-engine:  5.12.3 
    @mui/system: 5.11.4 => 5.11.4 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.3 
    @mui/x-data-grid:  5.17.17 
    @mui/x-data-grid-premium: 5.17.17 => 5.17.17 
    @mui/x-data-grid-pro:  5.17.17 
    @mui/x-date-pickers:  5.0.12 
    @mui/x-date-pickers-pro: 5.0.12 => 5.0.12 
    @mui/x-license-pro:  5.17.12 
    @types/react: 18.0.32 => 18.0.32 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.3 => 5.0.3 
```
</details>

**Comment by MBilalShafi** [comment]
That's because the `rowGrouping` column does have its own `colDef` properties which you can customize using the `groupingColDef` prop.

I tried to update your codesandbox to do that for one grouping column: https://codesandbox.io/s/lucid-parm-7jqzc2?file=/Demo.tsx:759-773 (Note that if you want to have a custom tooltip for multiple columns grouping you have to update the code accordingly)

P.S. You should have stable references of the columns prop and groupingColDef prop to avoid unnecessary re-renders of the grid, I tried to memoize the objects in your example.

You can see more details in these documentation sections:
- [Custom grouping column](https://mui.com/x/react-data-grid/row-grouping/#custom-grouping-column)
- [Multiple grouping columns](https://mui.com/x/react-data-grid/row-grouping/#multiple-grouping-columns)
- [Row grouping](https://mui.com/x/react-data-grid/row-grouping/) (in general)

Let me know if this answers your concerns.

Thank You!

**Comment by JuliaKnaeble** [comment]
Thank you al lot, it works!
As the documentation for 'custom grouping column' says 'To customize the rendering of the grouping column, use the groupingColDef prop. You can override the headerName or any property of the GridColDef interface, ..' 
Given the documentation, I assumed that all properties are available and using 'groupingColDef' will simply allow you to costomize / override properties. 
Now, understanding the 'groupingColDef' prop, it seems to me more like it is used to add missing properties and allows manipulation.

**Comment by MBilalShafi** [comment]
Glad it worked!

> Now, understanding the 'groupingColDef' prop, it seems to me more like it is used to add missing properties and allows manipulation.

Yes. The grouping column is not the same column as the actual column on the basis on which it's grouped, it's internally created and it has its own `colDef` which is defined inside the `Grid`, using `groupingColDef` you can override the default properties or add some optional ones.

Since you have the solution now, I'll go ahead and close the issue. Feel free to further clarify if you have more questions.
