### ISSUE TITLE
[pickers] PickersShortcutsItem only exported in the standard date picker package

### ISSUE THREAD

**Issue by Nic-S** [mui/mui-x#10217]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If I want to type shortcuts, I have to import and install the standard package as well:

```tsx
import { DateRange } from '@mui/x-date-pickers-pro'
import { PickersShortcutsItem } from '@mui/x-date-pickers/PickersShortcuts'

export const dateFnsShortcutsItems: PickersShortcutsItem<DateRange<Date>>[] = [...]
...
```

### Expected behavior 🤔

I want import just from pro package:

```tsx
import { DateRange, PickersShortcutsItem } from '@mui/x-date-pickers-pro'

export const dateFnsShortcutsItems: PickersShortcutsItem<DateRange<Date>>[] = [...]
...
```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by Nic-S** [comment]
> Hi, Thanks for your contribution.
> 
> Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

I took your example, the shortcuts are the only component that is not also exported from the pro package (the adapter for example is exported from both o packages)

https://codesandbox.io/s/vibrant-lewin-9pz3q4?file=/Demo.tsx

**Comment by flaviendelangle** [comment]
The community components are re-exported from the pro package but only at the root level

```tsx
import { PickersShortcutsItem } from "@mui/x-date-pickers-pro";
```

The adapters are an exception because they are not exported from the root level at all (because they require third party libraries).

**Comment by sag1v** [comment]
> And the root imports are tree-shaked by your bundler in production mode.
So they are totally safe to use.

@flaviendelangle Im here because i realized that its not true in my case.

This import:

```
import { DatePicker } from '@mui/x-date-pickers-pro'
```

Will break the tree-shake for me.

While this import seems fine.

```
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
```

I think that importing a component of `x-date-pickers` via the pro path (`@mui/x-date-pickers-pro`) breaks tree-shaking is due to the fact that  `@mui/x-date-pickers-pro` is just re-exporting all components in `x-date-pickers`.

See this line from the `index.js` file of `@mui/x-date-pickers-pro`:

```
export * from '@mui/x-date-pickers';
```

![image](https://github.com/user-attachments/assets/eb4d376d-f3e7-4fa7-8286-8dbbc69e51e4)

My question is, is it ok to import directly from `@mui/x-date-pickers` and also install it, or is there a different approach?

**Comment by flaviendelangle** [comment]
Hi @sag1v, how did you check that the tree shaking was not applied to your final bundle?

**Comment by sag1v** [comment]
Via production build (webpack) with webpack analyzer, i saw what is included in the bundle

**Comment by flaviendelangle** [comment]
:/ 

If you have the possibility to create a reproduction case (could be a small Github repo) it would be awesome.
Because our assumption always way that bundler would tree-shake the unused files in this scenario.
I think it has something to do with your bundler configuration, because we have tons of people using root imports from `@mui/material` and if they didn't have tree shaking we would have tons of complains.
But if we forgot something (maybe some specificity of the pickers packages) then we should definitely change our import strategy :grimacing:

**Comment by sag1v** [comment]
Just to be more clear, i do get tree-shaking if i import "non pro" components from the "non pro" library. But when i import "no pro" components from the "pro" library, it breaks.

For example, the `DatePicker` component is a non pro component.

This import (from the non pro lib) is fine:

```
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
``` 

While this import (from the pro lib) will break tree-shaking

```
import { DatePicker } from '@mui/x-date-pickers-pro'
```

I think it happens because the entire non pro lib is exported, this is a node_module package and not a source code. Maybe webpack has issues with that.

I wouldn't mind creating a small repo that reproduce this, but not sure how can i install and use the `pro` package for the example, i mean with what license key?

**Comment by flaviendelangle** [comment]
And if you do:

```tsx
import { DatePicker } from '@mui/x-date-pickers'
```

Do you have tree shaking ?

> I wouldn't mind creating a small repo that reproduce this, but not sure how can i install and use the pro package for the example, i mean with what license key?

If you don't have any license key, you will have a warning in the console and a watermark but nothing that prevents us from testing the tree shaking :+1:
