### ISSUE TITLE
[question] Add another button in GridColumnsPanel

### ISSUE THREAD

**Issue by MrMNO** [mui/mui-x#10265]
### Order ID or Support key 💳 (optional)

45010

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to add a custom button in the GridColumnsPanel footer between HideAll and ShowAll
![150757391-cc430d09-8194-4493-9d7a-b80d7eda3b9e](https://github.com/mui/mui-x/assets/52992611/43b530bc-6b2a-467b-b23a-657c43d6ff6d)
,but I can't find a way to do it.

**Comment by DanailH** [comment]
Hey @MrMNO in order to do that you would need to use the `columnsPanel` component slot and pass in your own extended version of the columns panel. You can use most of the functionality from the components we export. You can check more about it here https://mui.com/x/api/data-grid/data-grid/#DataGrid-slots-columnsPanel and here https://mui.com/x/react-data-grid/components/#overriding-components
