### ISSUE TITLE
[datagrid] `rowSelectionModel` slows down data-grid

### ISSUE THREAD

**Issue by atze187** [mui/mui-x#10301]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/pedantic-jepsen-ynrpsg

Steps:
1. Open sandbox, grid will be rendered
2. select item

### Current behavior 😯

In a data-grid with a lot of rows (~1000+) we are experience a notable drop of responsiveness when utilitizing the rowSelectionModel property (no matter if rowSelectionModel contains items or not). The issue results in massive delays between user action (click) and the clicked item in the data-grid to be visibly marked as selected, at 1000 items anywhere between 0.5 and 1 second, at 3000 items between 2 and 3 seconds.

### Expected behavior 🤔

We expect a reasonable delay between click and visual feedback (< 0.5 seconds) with 3000 items in the grid.

### Context 🔦

As we are currently evaluating the Pro/Premium data-grid as the data-grid of choice for our web frontend we are interested if this is a bug, a known behaviour and eventually if this can be eliminated. In our application we will have more than 1000 items per view, numbers of 2000 to 3000 items is not unusual. 

In the example in the sandbox the amount of items can be adjusted in index.tsx per parameter of the Demo component.

I've checked https://github.com/mui/mui-x/issues/8880 but for our environment there is no notable difference between development and production.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.142
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.124
    @mui/core-downloads-tracker:  5.11.16
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/lab: ^5.0.0-alpha.125 => 5.0.0-alpha.125
    @mui/material: ^5.11.16 => 5.11.16
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.16
    @mui/styles: ^5.11.16 => 5.11.16
    @mui/system:  5.11.16
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @mui/x-data-grid:  6.9.2
    @mui/x-data-grid-premium: ^6.9.2 => 6.9.2
    @mui/x-data-grid-pro:  6.9.2
    @mui/x-license-pro:  6.9.0
    @types/react: ^18.0.26 => 18.0.26
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: 4.4.3 => 4.4.3
</details>

**Comment by romgrk** [comment]
I've taken a look at your live example. I notice that you recreate the full rows array at every render. A first step to find out the performance issue here is that you should `React.useMemo(...)` any expensive computation. Would it be also possible for you to simplify the example as much as possible? It contains a lot of code so it's hard to pinpoint what specifically is triggering the issue.

I'll note that what I observe is that the grid is recreating the treedata structure at every row selection change. This could be a bug on our side, however you should first ensure that you're passing constant data to the grid, otherwise there is no way we can prevent expensive re-computes.

This section of the docs explain how to avoid expensive re-renders: https://mui.com/x/react-data-grid/performance/#extract-static-objects-and-memoize-root-props

**Comment by flaviendelangle** [comment]
The code is weird, it has both `treeData` and `columnGroupingModel`, both can't work at the same time.
Either you are using [Tree Data](https://mui.com/x/react-data-grid/tree-data/) or you are using [Row Grouping](https://mui.com/x/react-data-grid/row-grouping/).
When both are defined, the row grouping takes the precedence I think, but it's not something you want to do.

`getTreeDataPath` and `groupingColDef` should be memoized as well because it causes a lot of computation.


> I'll note that what I observe is that the grid is recreating the treedata structure at every row selection change.

For me it's caused by `getTreeDataPath` not being memoized.
Any time `getTreeDataPath` changes, we rebuild the tree because it might have changed.

For `columnGroupingModel`, we are doing a deep comparison because the object is simpler, so I think it's not problematic not to memoize it.

**Comment by atze187** [comment]
Thanks for you effort! I simplified the sandbox and could track it down to treeData/getTreeDataPath (one of those since getTreeDataPath has no effect when not using treeData). I wonder how I should memoize the getTreeDataPath since it is a function parameter and not a value parameter.

**Comment by romgrk** [comment]
Either you extract the function:

```ts
const getTreeDataPath = row => row.path

function Component() {
  return <DataGrid getTreeDataPath={getTreeDataPath} />
}
```

Or you use:

```ts
<DataGrid getTreeDataPath={React.useCallback(row => row.path, [])} />
```

**Comment by atze187** [comment]
Okay, updated the sandbox, but I don't see any improvement. You can switch between the function being wrapped in a useCallback, the function living outside the component and the function being assigned directly in demo.tsx, lines 93 to 95.

> Any time getTreeDataPath changes, we rebuild the tree because it might have changed.

I don't get how getTreeDataPath could not change when being called for another node when iterating through the nodes as I unterstood this is called for every node being rendered. Wouldn't it be more efficient to provide the path info for all nodes in a separate parameter that is changed by the parent component if neccessary (I guess that the most common scenario is that the path info will not change after being initially computed)?

**Comment by flaviendelangle** [comment]
> I don't get how getTreeDataPath could not change when being called for another node when iterating through the nodes as I unterstood this is called for every node being rendered.

We are talking about the JavaScript reference of the `getTreeDataPath` prop.

If you do the following:

```tsx
const App = () => {
  return (
    <DataGrid getTreeDataPaht={row => row.path}
  )
}
```

Then  on  each render, you are passing a new `getTreeDataPaht` function.
So on each render we are recreating your tree because `getTreeDataPaht` behavior might have changed.
For example it might have moved from `row => row.path` to `row => row.newPath`.

If you memoize the method using `useCallback` (or define it outside of your component) like in the following example:

```tsx
const getTreeDataPaht = row => row.path

const App = () => {
  return (
    <DataGrid getTreeDataPaht={getTreeDataPaht}
  )
}
```

The the grid knows that `getTreeDataPaht` did not change between 2 renders, so it will not re-create the tree because of it.

In your example, if `getTreeDataPath` have no dependence, I'd advise you to define it outside of the component instead of using `React.useCallback`, it's not related to the grid but a general advise for memoization in React.

____


You might have other problems that are causing unwanted re-generation of the tree, but the `getTreeDataPaht` one will always be problematic if not fixed.

For example `isGroupExpandedByDefault` should also be memoized.

As a general rule of thumb, always memoize methods that are not event handler because the grid will likely react to their update.
This is because people might want to update those props to say to the grid that the behavior has changed.
For example changing `isGroupExpandedByDefault` to change the expanded groups (see https://github.com/mui/mui-x/issues/4930#issuecomment-1131853289).

**Comment by atze187** [comment]
I applied your recomendations and the delay between click and visual response went down to 0.2 seconds (measured by hand), which is perfectly fine.

Thank you for that and for responding so quickly, keep up!
