### ISSUE TITLE
[TimePicker] AM/PM is not using System Formats

### ISSUE THREAD

**Issue by MeshkaM** [mui/mui-x#10302]
i always change my Settings in Control Panel>Clock and Region>Region>Formats>Additional Settings>Time>AM symbol and PM symbol to my Customised Formats, I found that Time Picker always Remains at AM/PM instead of using the system format, How can i fix that or is it a bug?

**Comment by noraleonte** [comment]
Hey @MeshkaM 👋 
We currently don't support the customization of AM/PM symbols on the pickers. Is there a specific use-case that you have and need something like this? Maybe I can help you come up with a solution 🛩️

**Comment by noraleonte** [comment]
@MeshkaM It would also be really interesting for us if you could provide with an example that does implement system settings for AM/PM? Maybe there is a library that inspired this question, or a web app that behaves similarly? Thanks!

**Comment by MeshkaM** [comment]
it would have been better if the AM/PM text in those button were Binded to the Local AM/PM so that they follow the Culture of client computers

**Comment by LukasTy** [comment]
> it would have been better if the AM/PM text in those button were Binded to the Local AM/PM if possible so that they follow the Culture of client computers

That was the exact thing we wanted to know - is is possible and have you seen it implemented anywhere?
Because as far as we can see, there is no JS API to access such system-level settings.

We rely on the date adapter localization to provide the correct labels where applicable.
In that regard, I can see one issue that we have with the `TimeClock` component, its meridiem text is hardcoded, whereas the digital clocks use a localized label as seen [in this demo](https://codesandbox.io/s/sleepy-shtern-ljwzmh).

If you know of a way to implement what you are referring to - please provide resources so that we can look into it, otherwise, I'm not sure that we can do anything on this regard. 🤔
