### ISSUE TITLE
[datagrid] Violation: handler took xxxMS (MUI components performance)

### ISSUE THREAD

**Issue by tommdq** [mui/mui-x#10321]
### Steps to reproduce 🕹

Steps:
1. Start a new proyect
2. Install all the mui dependencies as instructed in the documentation
3. Use DataGrid from @mui/x-data-grid with the documentation example

### Current behavior 😯

I'm new to **mui** and i just started a new React proyect with Vite and installed mui and @mui/x-data-grid according to the documentation.

The thing is that i'm getting a laggy user experience and this issue everytime I render some components of **mui** library. It happened with the DataGrid componente but also with the **Modal** which is native to **mui** library.
![image](https://github.com/mui/mui-x/assets/80493479/f7e06b8e-6d26-4eef-ba6c-c2eeca719714)

At first i thought this had to do with redux but as soon as i removed all the **mui** components this warning was removed and everything was back to normal. I have searched for similar threads about it but didn't find a proper solution.

Thanks in advanced !

### Expected behavior 🤔

Do not get a laggy user experience nor the [violation] warning in the console

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!

I'll also note that it's known that MUI core components are quite expensive, sometimes too much to create a good UX in the datagrid. If it's possible for you, you can try using [Joy UI](https://mui.com/joy-ui/getting-started/) or [Base UI](https://mui.com/base-ui/getting-started/) components instead. Otherwise, the core components are going to receive performance optimizations but it will be in the next major release, which is at least a few months away.

**Comment by romgrk** [comment]
@tommdq I'd be happy to take a look at this use-case and investigate performance, but I'd need a small reproducible example.
