### ISSUE TITLE
[pickers] Date pickers MUI version

### ISSUE THREAD

**Issue by matchmakers69** [mui/mui-x#10341]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Context 🔦

In our project we use MUI v5 as well as ```"@mui/x-date-pickers": "5.0.7",```  just wondering if i upgrade mui/x-date-pickers to v6 due to some API changes, would that affect my current version of MUI? Basically just wondering shall I upgrade all MUI packages to version 6? And if yes is there a chence an app stops working? Tbh i would like to possibly upgrade only  mui/x-date-pickers and leave current version of MUI. What is the right approach?

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Hello @matchmakers69 
Thank you for using the pickers package. 🙏 
What version of `@mui/material` are you using?
The current latest release [has v5.8.6](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/package.json#L58) listed as the minimal peer dependency.
If you are already on that version or newer - feel free to upgrade to pickers v6. 😉 

The versions of `x` and `material` libraries are out of sync and will probably remain like that, because of a different release cadence.

**Comment by matchmakers69** [comment]
Out current version of MUI is ```"@mui/material": "5.10.13",``` so correct if i am wrong - i can upgrade pickers only to v6 but leave MUI on v5?

**Comment by LukasTy** [comment]
> so correct if i am wrong - i can upgrade pickers only to v6 but leave MUI on v5?

Yes, you are welcome to upgrade only the pickers library to v6. It is perfectly interoperable with `@mui/material` v5 as noted by the peer dependency.

**Note:** This little version inconsistency will probably remain in the future as well because `@mui/x-date-pickers` will move to v7 major and `@mui/material` will release v6 major.

**Comment by LukasTy** [comment]
> I mean could u plase give me little bit more details how `@mui/x-date-pickers` should be upgraded properly? Thanks

We have a [complete migration guide](https://mui.com/x/migration/migration-pickers-v5/) for that.
You should be able to upgrade your app following the guide. 😉

**Comment by matchmakers69** [comment]
Thank you

**Comment by LukasTy** [comment]
Closing the issue as it does not seem that there are any more open questions.
Feel free to reopen it or create a new issue for a separate problem.
