### ISSUE TITLE
apiRef.current.updateRows() with 'delete' action does not recalculate the row count.

### ISSUE THREAD

**Issue by BluesummersC** [mui/mui-x#10386]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

### Current behavior 😯

1. Setup a DataGrid with server-side pagination and rowCount as a state variable.
2. Populate the DataGrid with multiple rows from server.
3. On add row from server, use apiRef.current.updateRows([data]) to upsert a row.
4. Call apiRef.current.getRowsCount() and verify count increment.
5. Update rowCount with new row count (via state variable) and see pagination update correctly.
6. On delete row from server, use apiRef.current.updateRows([{id: data.id, _action: 'delete'}])
7. Run apiRef.current.getRowsCount(), but row count does not decrement. 

### Expected behavior 🤔

Since upserting using apiRef.current.updateRows() causes apiRef.current.getRowCount() to increment, I would expect deleting a row with the same api call to decrement apiRef.current.getRowCount().

### Context 🔦

This is a simple, real-time display of a server-side table pushed to a front-end. Since the data can grow large, proper pagination is required.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 4.18 Rocky Linux 8.6 (Green Obsidian)
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: Not Found
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.126
    @mui/core-downloads-tracker:  5.12.2
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/material: ^5.12.1 => 5.12.1
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/system:  5.12.1
    @mui/types:  7.2.4
    @mui/utils:  5.12.0
    @mui/x-data-grid: ^6.2.1 => 6.2.1
    @mui/x-data-grid-pro: ^6.2.1 => 6.2.1
    @mui/x-date-pickers: ^6.3.0 => 6.3.0
    @mui/x-date-pickers-pro: ^6.2.1 => 6.2.1
    @mui/x-license-pro:  6.0.4
    @types/react: ^18.2.0 => 18.2.0
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^3.2.1 => 3.2.1
```
</details>

**Comment by cherniavskii** [comment]
Hi @BluesummersC 
Thanks for opening the issue.

I've created a demo to better demonstrate the problem: https://codesandbox.io/s/black-architecture-966f8t?file=/Demo.tsx

As far as I can tell, this is intended behavior.
From the [`rowCount` prop docs](https://mui.com/x/api/data-grid/data-grid/#DataGrid-prop-rowCount):
> Set the total number of rows, if it is different from the length of the value rows prop.

This gives you control of the row count so that you can provide rows in batches, while the grid knows the actual row count.
When the grid receives more rows than `rowCount`, it ignores the `rowCount` since it's objectively wrong. This is why it looks like the grid increases the `rowCount`.

Our recommendation would be to update the `rowCount` accordingly when it's known to be changed.

Does this answer your question?
