### ISSUE TITLE
Scrollbar Flickers During Pagination in MUI X DataGrid

### ISSUE THREAD

**Issue by Alimzade** [mui/mui-x#10460]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. go to page 2 on DataGrid
2. go to page 1 
3. scrollbar briefly appears and disappears during the transition from Page 2 to Page 1

### Current behavior 😯

The scrollbar briefly appears and disappears during the transition from Page 2 to Page 1 in the DataGrid when it should not appear.

### Expected behavior 🤔

The scrollbar should remain hidden and not appear at all during pagination.

### Context 🔦

This issue affects the user experience, causing an unwanted scrollbar to briefly appear and disrupt the page transition in the DataGrid. The expected behavior is for the scrollbar to remain hidden throughout the pagination process.

### Your environment 🌎

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.76)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.16
    @mui/core-downloads-tracker:  5.14.10
    @mui/material: ^5.14.10 => 5.14.10
    @mui/private-theming:  5.14.10
    @mui/styled-engine:  5.14.10
    @mui/system:  5.14.10
    @mui/types:  7.2.4
    @mui/utils:  5.14.10
    @mui/x-data-grid: ^6.15.0 => 6.15.0
    @types/react: ^18.2.14 => 18.2.22
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.0.2 => 5.2.2

**Comment by MBilalShafi** [comment]
@Alimzade Thanks for using MUI X and reporting the issue along with the environment details.

However, I did not manage to reproduce the issue on the default pagination [demo](https://mui.com/x/react-data-grid/pagination/#page-size-options), I tried on several browsers with no luck.

I suspect this might be due to some external CSS in your application. Did you also face the problem in the official docs, if yes, I'd appreciate a small video of the issue along with the browser (or browsers) you can reproduce it on?

Otherwise, you could check if there's a colliding CSS on your side, I'd be happy to take a look at the problem if you can provide a minimal reproduction example in terms of a codesandbox or stackblitz demo. This [demo](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) could be a good starting point.

Thank You.

**Comment by Alimzade** [comment]
Hey @MBilalShafi ,

I've managed to reproduce the issue on CodeSandbox and shared it with you. Just click any menu item, and you'll see the problem in the data grid.

I hope this helps in finding and fixing the bug. Thanks for your help, and good luck.

Best.

**Comment by MBilalShafi** [comment]
Since you are shifting from 10 rows to 5 rows and during re-rendering it was showing a flickered scrollbar during recalculation of the grid height.
I tried to pass the `autoHeight` prop and it seems to fix the issue.

I've updated your codesandbox example.

Let me know if you have some other queries around this.

**Comment by Alimzade** [comment]
I tried adding `autoHeight` property on `<DataGrid` for my project, and it worked like a charm. 

The flickering scrollbar issue is now resolved. Thank you, well appreciated!
