### ISSUE TITLE
[data grid] Use a lazy approach to load master detail panels' content

### ISSUE THREAD

**Issue by HyoilKim** [mui/mui-x#10461]
### Order ID

67616

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

If there is much data in [detail panels](https://mui.com/x/react-data-grid/master-detail/), my application gets out of memory and goes down despite the virtualization when I open the detail data. If you want to reproduce the issue, please change 'quantity' to 50000 or more in this code. How can I improve my code without out of memory?

https://codesandbox.io/s/upbeat-mayer-fdvj58?file=/Demo.tsx

(+ Does the pagination work normally? When I update the code, it seems that the pagination does work )
![image](https://github.com/mui/mui-x/assets/23691938/2f8f4ab2-5b5e-46ea-b1df-a0299e8aaafc)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
Binaries:
Node: 16.15.1 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/bin/yarn
npm: 8.17.0 - /usr/local/bin/npm
Browsers:
Chrome: 114.0.5735.106
npmPackages:
@emotion/react: ^11.9.0 => 11.9.0
@emotion/styled: ^11.8.1 => 11.8.1
@mui/base: 5.0.0-alpha.81
@mui/icons-material: ^5.8.0 => 5.8.0
@mui/material: ^5.8.0 => 5.8.0
@mui/private-theming: 5.8.0
@mui/styled-engine: 5.8.0
@mui/system: 5.8.0
@mui/types: 7.1.3
@mui/utils: 5.13.1
@mui/x-data-grid: 5.8.0 => 5.8.0
@mui/x-data-grid-generator: ^6.6.0 => 6.6.0
@mui/x-data-grid-premium: ^6.6.0 => 6.6.0
@mui/x-data-grid-pro: 6.6.0
@mui/x-date-pickers: ^5.0.11 => 5.0.12
@mui/x-license-pro: ^6.0.4 => 6.0.4
@types/react: 17.0.35 => 17.0.35
react: ^16.10.2 => 16.14.0
react-dom: ^16.10.2 => 16.14.0
typescript: ^4.4.4 => 4.4.4
```
</details>

**Comment by MBilalShafi** [comment]
Hi @HyoilKim, thank you for using MUI X Data Grid and reporting the issue.

We need to suspect this more but I suspect the main issue is that we [try to cache all the detail panel nodes at the grid mount time](https://github.com/mui/mui-x/blob/c5b6322b384b3a9c9eb64de4ccc5e4b6883dafe1/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts#L60) due to which when the panel content is complex the application hits the memory bottleneck.

I think we need to shift to a lay approach just as mentioned as a TODO comment here: https://github.com/mui/mui-x/blob/c5b6322b384b3a9c9eb64de4ccc5e4b6883dafe1/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts#L54-L55

**Comment by HyoilKim** [comment]
Thank you. I have to make a custom table without x-data-grid :(

**Comment by HyoilKim** [comment]
Plus, virtualization is needed other than your TODO('only call getDetailPanelContent when asked for an id')

**Comment by HyoilKim** [comment]
any updates?

**Comment by MBilalShafi** [comment]
Hey @HyoilKim, 
This is already in our backlog and should be picked up as soon as some bandwidth is available.
Thanks for your patience.

Alternatively, you can also try to fix the issue and open up a pull request if you want to speed things up!

**Comment by cherniavskii** [comment]
Hi @HyoilKim 
Regarding the virtualization, I believe the bottleneck in your demo is caused by [setting the detail panel height to `auto`](https://mui.com/x/react-data-grid/master-detail/#infer-height-from-the-content). This effectively disables the virtualization of the Data Grid in the detail panel.
I've forked your demo and set the detail panel height to a constant value to make sure that the nested Data Grid is virtualized: https://codesandbox.io/s/competent-wright-v7ppfk?file=/Demo.tsx
