### ISSUE TITLE
[data grid] Autosizing is not worked

### ISSUE THREAD

**Issue by wt-maker** [mui/mui-x#10479]
the autosize props like this, but it not worked to resize the columns. if i call apiref.current.autosizeColumns(), it will be worked. Is this a normal phenomenon? 
```
autosizeOnMount={true}
autosizeOptions={{
    includeHeaders: true,
    includeOutliers: true
}}
```
From the source code, you can see autosizeColumns is called .

```
useOnMount(() => {
  if (props.autosizeOnMount) {
    Promise.resolve().then(() => {
      apiRef.current.autosizeColumns(props.autosizeOptions);
    });
  }
});
```

**Search keywords**:

**Comment by MBilalShafi** [comment]
@wt-maker Thank you for using MUI X and Data Grid.

Do you mean to say that autosizing is not working on the mount?

Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/mfy4s9?file=/Demo.tsx) _may_ be a good starting point, as you can see the autosizeOnMount works fine in this one.

Thank you!

**Comment by MBilalShafi** [comment]
If the data is lazily loaded using the server, I'd recommend using the API method (`autosizeColumns()`) as the data will presumably not be loaded on Grid initial mount.

Or if you are stopping the grid from being rendered until the data loads and you feel the issue is with grid itself, it's always great to provide a minimal reproduction example (of course with the dummy API calls) and replicate the issue for us to better debug it.

Thank you!
