### ISSUE TITLE
[datagrid] Make certain experimental / unstable features stable

### ISSUE THREAD

**Issue by MBilalShafi** [mui/mui-x#10556]
It has been a while since some features are marked as experimental or unstable, I think we could consider them (or some of them) to be marked as stable or removed from experimental.

### Candidates
- [ ] ✅ **Column grouping (MIT)**: it's been a while since this feature is experimental, I feel it's the right time to make it stable - just wait for sticky headers before starting work on it.
- 🔴  **Lazy loading (Pro)**: I am not sure about this, I'd vote against it since it's likely to be changed with the server side data source.
- [x] ✅ **Clipboard paste (Premium)**: It's fairly new but fairly stable apart from a few minor issues, I feel this could be made stable and be announced freshly in v7
- [x] ✅ **Cell selection (Premium)**: Makes sense along with clipboard paste
- [x] ✅ **Header filters (Pro)**: Header filter has received fair community traction and people have shown interest to use it in the real projects, but a few are reluctant to use in the production apps due to `unstable_` prefix. I think v7 could be a right time to mark it stable. (Example of a user concerned about this: https://github.com/mui/mui-x/issues/10550)
- ~~**ariaV7**: Most likely something to be removed from experimental flags in v7~~ - addressed in https://github.com/mui/mui-x/issues/9874

**Comment by cherniavskii** [comment]
A takeaway from today's discussion on this issue:
We shouldn't keep features unstable/experimental for longer than 1-1.5 months. Otherwise, the adoption is not growing, and we stop receiving any feedback on the feature. At this point, it's better to release the feature as stable and get more feedback, even if it means we will have a need for breaking changes in the future.
