### ISSUE TITLE
Add prop for column grouping header height

### ISSUE THREAD

**Issue by TimonPeng** [mui/mui-x#10615]
### Summary 💡

columnGroupings have fewer data normally so that the height can be smaller, but now the height follows the columnHeaderHeight prop. CSS can't override this dynamically calculated prop either.

Adding a new prop `columnGroupingHeaderHeight` might be possible to set it separately.

**Search keywords**: column grouping header height

**Comment by romgrk** [comment]
Wdym by "can't override the prop"? Have you tried using `!important`? It's meant for that use-case.

For the feature request itself, we can keep it open but we'll wait to have more interest before prioritizing.

**Comment by TimonPeng** [comment]
> Wdym by "can't override the prop"? Have you tried using `!important`? It's meant for that use-case.
> 
> For the feature request itself, we can keep it open but we'll wait to have more interest before prioritizing.

It can be made to barely work by setting the CSS, but since there is logic in the DataGrid that calculates the height, it causes some problems and is an unusable way to go about it.

<img width="615" alt="image" src="https://github.com/mui/mui-x/assets/8691151/c6e2e31c-8272-47e9-882c-ea84a8f3a3bf">

**Comment by romgrk** [comment]
Makes sense. Let's keep this open until we have more interest. Also feel free to submit a PR, this shouldn't be too hard to implement.

**Comment by omgitsfrancis** [comment]
Ran into this same issue when trying to override the group column header style. I'd be interested in this feature as well.

**Comment by pipje2001** [comment]
Same problem here, got it to work for the most part using css. But the filler (MuiDataGrid-filler) calculates the height incorrectly resulting in it being too big. 

I set the column group header (first header row) to `3.75rem`, and the second to `15rem`

Using the `columnHeaderHeight` prop to set the "average" height of each column header sorta works since this prop only accepts height in `px` (numbers only) it doesn't work with `rem` 

One thing to note is that using `columnHeaderHeight` and setting it to the average means that you need to manually specify each column headers height, otherwise it will just take `columnHeaderHeight`.

It would be nice if the datagrid would dynamically calculate the total headers height.

**Comment by burketyler** [comment]
+1 for interest in seeing this implemented. It's something that would be quite useful - i think many designers will want a more compact look for the heading groups, otherwise it can appear a little blocky. Unwilling to go down the CSS fix route given it impacts other height calculations.

**Comment by rodmaia** [comment]
+1
