### ISSUE TITLE
[docs] Demo PickersPlaygroundWrapper crashes

### ISSUE THREAD

**Issue by giuliobracci** [mui/mui-x#10642]
- [ X ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20PickersPlaygroundWrapper%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/x/react-date-pickers/playground/
2. Deselect all the checkbox in 'Available Views'
3. demo *PickersPlaygroundWrapper* crashes

The 'available views' checkboxes should not allow to be all unselected. 

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v6.16.1  |
| Netlify deploy | https://651fcb544d60ea00080c48af--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by LukasTy** [comment]
Thank you for bringing up this issue! 🙏 
Not sure what could be the best solution, but I'm contemplating disabling the last available checkbox so that you could not uncheck all the views. 🤔 
Another option could be to not pass the `views` prop when it's empty, but that would end up being a bit less transparent. 🤷

**Comment by giuliobracci** [comment]
You're welcome! 
Let me know if you need an helping hand on this! :)
