### ISSUE TITLE
[pickers] Customizing selected year on `DatePicker`

### ISSUE THREAD

**Issue by mdkcode** [mui/mui-x#10657]
### Related page

https://mui.com/x/api/date-pickers/date-picker/

### Kind of issue

Missing information

### Issue description

There is a props for selected day that's called day, but where's the same for selected year? or month?

### Context 🔦

 Couldn't change selected year's background color, but was able to change selected day's bg color
slotProps={{
            day: {
              sx: (theme) => ({
                '&.MuiPickersDay-root.Mui-selected': {
                  backgroundColor: theme.palette.primary.main,
                },
                '&.MuiPickersYear-root.Mui-selected': {
                  backgroundColor: theme.palette.primary.main,
                  '&:hover': {
                    backgroundColor: theme.palette.primary.main,
                  },
                  '&:focus': {
                    backgroundColor: theme.palette.primary.main,
                  },
                },
              }),
            }
  }}

**Search keywords**: selected year, customization, MuiPickersYear-root, MuiPickersYear-yearButton

**Comment by noraleonte** [comment]
Hey, @mdkcode 
Thanks for opening this 🎉 
We have a [customization playground](https://mui.com/x/react-date-pickers/date-picker/#customization) in the docs that should hopefully help you find the appropriate way to customize the slots for the the DatePicker. The states of the slots can either be targeted by state classes or `css` pseudo-classes, like you did. 
Let me know if this helps 📘 Also, if you have any feedback about the playground, I would appreciate it!

**Comment by mdkcode** [comment]
I tried everything including this. The default background color of selected year didn't change. Even styles applied to just & .MuiPickersYear-yearButton don't work.

**Comment by LukasTy** [comment]
How have you tried applying your styles? 🤔 
Do not forget that the `sx` prop when applied directly to `DatePicker` or any other picker component with input will not apply the styles to the popup element, because they are in different levels in the DOM structure.
Consider using either `theme` with `styleOverrides` or passing the `sx` prop to a slot inside of the popup, like the `layout`. 🤔 
[Here is an example](https://codesandbox.io/s/gifted-ardinghelli-rl3hz4?file=/src/Demo.tsx) showing both approaches.

**Comment by mdkcode** [comment]
Thank you a lot. Using sx with pickersYearClasses helped me.
