### ISSUE TITLE
[pickers] referenceDate not working as expected

### ISSUE THREAD

**Issue by croraf** [mui/mui-x#10747]
### Steps to reproduce

https://codesandbox.io/s/infallible-poincare-knhmh5?file=/src/Demo.js

`referenceDate` is not working as expected.  Open the provided picker and observe day, hours and minutes.

### Current behavior

1. The provided `referenceDate` date is modified such that the day is set to the last day of the provided month.
2. Hours and seconds are not set at all.

### Expected behavior

When the popup is opened:
1. The provided date should be 18th
2. The provided hours should also be preselected.

**Comment by croraf** [comment]
This should actually be the `referenceDate` property, right?

**Comment by LukasTy** [comment]
Thank you for creating this issue! 🙏 
The `referenceDate` [prop description](https://mui.com/x/api/date-pickers/date-picker/#DatePicker-prop-referenceDate) is as follows: 
> The date used to generate the new value when both `value` and `defaultValue` are empty.

Based on the issue description it seems that what you are looking for is the `defaultValue` if you would not be controlling your value or simply initializing the `value` to the one that you need.
The reference date is useful for setting the default month the calendar should display if the value is empty.
Its time part would be used to initialize the time value after selecting a day.

Could you clarify what you are trying to achieve more specifically so that we can help you in coming up with an implementation suggestion? 🤔

**Comment by croraf** [comment]
I'm controlling the valute (with value and onChange). My value is initially empty so I need the functionality of `referenceDate`.

It is just that the reference date has a bug as shown in the provided sandbox.

**Comment by croraf** [comment]
> As I mentioned, referenceDate prop is designed to aid in refining the selected date but does not do any value selection on its own.

The intended functionality of `referenceDate` prop is exactly what I need. The value needs to be empty. Just the suggested dates in the popup is what I require (which is exactly what `referenceDate` does).

The only problem is that only the `year` and `month` is "suggested" by the popup. `day` and `time` are not accounted correctly.

**Comment by croraf** [comment]
And actually yes, before clicking on the date, the hours and minutes should be "presuggested", so that when clicking on OK immediately, the `referenceDate` should be given to `onChange`

**Comment by flaviendelangle** [comment]
Just to clarify, there is no "pre-suggestion" per say, we are just focusing some day when opening the view and this day is currently `value || defaultValue || now`.

I do agree that focusing the 30th when the 18th is actually the reference date is not the best behavior.
Because if you click on the hours without selecting a date, it will pick the 18th (as it should) and I would feel it more natural if both behaviors were aligned.

The time part can't have a "pre-suggestion" when opening the picker because they don't have the focus.

Here is the change that would focus the 18th:

```diff
diff --git a/packages/x-date-pickers/src/DateCalendar/useCalendarState.tsx b/packages/x-date-pickers/src/DateCalendar/useCalendarState.tsx
index 1754dc47f..25c854a99 100644
--- a/packages/x-date-pickers/src/DateCalendar/useCalendarState.tsx
+++ b/packages/x-date-pickers/src/DateCalendar/useCalendarState.tsx
@@ -162,7 +162,7 @@ export const useCalendarState = <TDate extends unknown>(params: UseCalendarState
 
   const [calendarState, dispatch] = React.useReducer(reducerFn, {
     isMonthSwitchingAnimating: false,
-    focusedDay: value || now,
+    focusedDay: referenceDate,
     currentMonth: utils.startOfMonth(referenceDate),
     slideDirection: 'left',
   });
```

**Comment by croraf** [comment]
No, the `referenceDate` in the way I intend to use it (this should be another feature maybe then), should not be validated until confirmed.

The picker should have all the views (figures) preselected to the time instant provided. The user can then confirm (immediately after opening the popup) the date that is preselected.

**Comment by LukasTy** [comment]
From what you are describing, it seems that you are asking not for a fix in `referenceDate` behavior, but rather a change in how the `defaultValue` behaves.
I'd question the UX part of the mentioned behavior because it might not be trivial for every user to understand this behavior flow. 🤔 

I'm putting this issue up for grooming so that the team can discuss the best solution. 👍

**Comment by croraf** [comment]
@LukasTy No. The `defaultValue` is the `defaultValue`, it is validated and is set as the value of the field in case of an uncontrolled components.

`referenceDate` as it is currently working is completely confusing to me as an user:
- I set date to 18th, but the picker has it set to 30th.
- The hours and minutes do get set to the provided `referenceDate` after picking the date. That is kind of OK, but why not have them preset immediately.

What I suggest seems natural behavior for something called `referenceDate` or `suggestedDate`.

**Comment by flaviendelangle** [comment]
This makes me think of #7500
