### ISSUE TITLE
[datagrid] v7 API: update `GridColDef` methods signatures

### ISSUE THREAD

**Issue by romgrk** [mui/mui-x#10741]
To be able to optimize the performance of the filter & quickfilter, we need to change the API of those two column properties to match the API used for `getApplyFilterFn`.

**Search keywords**:

**Comment by cherniavskii** [comment]
Looking at the `GridColDef` properties, here's a potential list of functions for the signature change:

- `valueGetter`
- `groupingValueGetter`
- `valueFormatter`
- `valueSetter`
- `valueParser`
- `pastedValueParser`

If I understand correctly, only the first 3 could improve performance, as the rest of them are not called on every row.
For `valueSetter` it makes sense to change its signature for consistency.
We could keep the `valueParser` and `pastedValueParser` signatures unchanged though.
@romgrk What do you think?

**Comment by romgrk** [comment]
Yes sounds good. I'm open to either option for the ones that don't affect performance, though if we can make it consistent it would be nice.

`renderCell` might be worth examining, it can also be called a lot.

For `pastedValueParser`, could it affect perfomance if the user pastes a large amount of data?

**Comment by cherniavskii** [comment]
> For pastedValueParser, could it affect perfomance if the user pastes a large amount of data?

Good point, in case of a large amount of data this could affect performance.
It's the same for `valueSetter` and `valueParser` because they're called during clipboard paste if defined.

**Comment by cherniavskii** [comment]
> renderCell might be worth examining, it can also be called a lot.

Yeah, with `renderCell` it will be a bit harder.
We could change the signature like this:
```diff
- renderCell?: (params: GridRenderCellParams<R, V, F>) => React.ReactNode;
+ renderCell?: (
+   value: V,
+   row: R,
+   column: GridColDef<R, V, F>,
+   apiRef: React.MutableRefObject<GridApiCommunity>,
+ ) => React.ReactNode;
```

But the DX is not great if you need to get something you previously got in `params`, take this as an example:
https://github.com/mui/mui-x/blob/a6f117024333fc5ec617901e026d7893f22b5eb6/docs/data/data-grid/column-definition/RenderCellGrid.tsx#L6-L7

Is this recommended?
```js
renderCell: (value, row, column, apiRef) => {
  const rowId = apiRef.current.getRowId(row);
  const cellParams = apiRef.current.getCellParams(rowId, column.field);
  const { hasFocus } = cellParams;
}
```

This feels like a much worse DX to me.
Is there anything we can do to make it better? Maybe pass `cellParams` that will evaluate lazily?

Another thing with `renderCell` is that in `DataGridPremium` we also pass aggregation metadata along with cell params:
https://github.com/mui/mui-x/blob/a6f117024333fc5ec617901e026d7893f22b5eb6/packages/grid/x-data-grid-premium/src/hooks/features/aggregation/wrapColumnWithAggregation.tsx#L114

We will have to pass it as a fifth parameter to `renderCell`:
```diff
renderCell?: (
  value: V,
  row: R,
  column: GridColDef<R, V, F>,
  apiRef: React.MutableRefObject<GridApiCommunity>,
+ aggregation?: GridAggregationCellMeta
) => React.ReactNode;
```

I struggle to rationalize these changes on `renderCell` (and `renderEditCell`) because of the pros/cons ratio:

Pros:
1. Better performance
2. API consistency with other `GridColDef` properties

Cons:
1. The DX feels worse
2. Those are breaking changes that our users will have to deal with
3. This requires a decent effort on our side to make these changes

What do you think?
cc @romgrk @MBilalShafi

**Comment by romgrk** [comment]
Yes ok let's leave it out for now. I'll benchmark the potential impact before bringing that one up again.

Sidenote, we're passing `api` instead of `apiRef` in the cell params, but our selectors require `apiRef`. We should standardize in one way of passing the API around.

**Comment by cherniavskii** [comment]
I propose the following scope then:

1. Change the signatures:
  - `valueGetter`
  ```diff
  - valueGetter?: (params: GridValueGetterParams<R, any>) => V;
  + valueGetter?: (value: V, row: R, column: GridColDef<R, V, F>, apiRef: React.MutableRefObject<GridApiCommunity>) => V;
  ```
  - `groupingValueGetter`
  ```diff
  - groupingValueGetter?: (params: GridGroupingValueGetterParams<R, V>) => GridKeyValue | null | undefined;
  + groupingValueGetter?: (value: V, row: R, column: GridColDef<R, V, F>, apiRef: React.MutableRefObject<GridApiPremium>) => GridKeyValue | null | undefined;
  ```
  - `valueFormatter`
  ```diff
  - valueFormatter?: (params: GridValueFormatterParams<V>) => F;
  + valueFormatter?: (value: V, row: R, column: GridColDef<R, V, F>, apiRef: React.MutableRefObject<GridApiCommunity>) => F;
  ```
  - `valueSetter`
  ```diff
  - valueSetter?: (params: GridValueSetterParams<R, V>) => R;
  + valueSetter?: (value: V, row: R, column: GridColDef<R, V, F>, apiRef: React.MutableRefObject<GridApiCommunity>) => R;
  ```
  - `valueParser`
  ```diff
  - valueParser?: (value: F | undefined, params?: GridCellParams<R, V, F>) => V;
  + valueParser?: (value: F | undefined, row: R, column: GridColDef<R, V, F>, apiRef: React.MutableRefObject<GridApiCommunity>) => V;
  ```
  - `pastedValueParser`
  ```diff
  - pastedValueParser?: (value: string, params: GridCellParams<R, V, F>) => V | undefined;
  + pastedValueParser?: (value: string, row: R, column: GridColDef<R, V, F>, apiRef: React.MutableRefObject<GridApiPremium>) => V | undefined;
  ```
2. Pass the `apiRef` instead of the `api`:
  - `GridRenderCellParams`
  https://github.com/mui/mui-x/blob/ab6fb0e05e4d97d4a1643e789b1dc3a2af62a444/packages/grid/x-data-grid/src/models/params/gridCellParams.ts#L86
  - `GridRenderEditCellParams`
  https://github.com/mui/mui-x/blob/ab6fb0e05e4d97d4a1643e789b1dc3a2af62a444/packages/grid/x-data-grid/src/models/params/gridCellParams.ts#L108
  - `GridSortCellParams`:
  https://github.com/mui/mui-x/blob/ab6fb0e05e4d97d4a1643e789b1dc3a2af62a444/packages/grid/x-data-grid/src/models/gridSortModel.ts#L10

**Comment by cherniavskii** [comment]
@romgrk 
> Yes ok let's leave it out for now. I'll benchmark the potential impact before bringing that one up again.

Did you mean leaving out only the `renderCell` or the overall effort of changing `GridColDef` methods signatures?

**Comment by romgrk** [comment]
Just `renderCell`
