### ISSUE TITLE
Data grid and/or operators for column filters

### ISSUE THREAD

**Issue by adibennun** [mui/mui-x#10771]
### Steps to reproduce

Link to live example: (required)

Steps flow 1:
1. Use a data grid
2. Filter by column x
3. Filter again by column  and use "and" operator. The table will always provide no results in this scenario. It should be restricted to "Or". "And" operator should not be enabled in this scenario.

Steps flow 2:
1. Use a data grid
2. Filter by column x
3. Filter by another column and use "or" operator. This is by 99% not what the user meant. When filtering by multi columns the idea is to get the union of both of them using the "and" operator. "Or operator should not be enabled in this scenario. 

### Current behavior

Steps flow 1:
1. Use a data grid
2. Filter by column x
3. Filter again by column  and use "and" operator. The table will always provide no results in this scenario. It should be restricted to "Or". "And" operator should not be enabled in this scenario.

Steps flow 2:
1. Use a data grid
2. Filter by column x
3. Filter by another column and use "or" operator. This is by 99% not what the user meant. When filtering by multi columns the idea is to get the union of both of them using the "and" operator. "Or operator should not be enabled in this scenario. 

### Expected behavior

if I am filtering for the same column I need to have only “Or”.  "And" will always provide no results in such a scenario and this is simply wrong. 
If I am filtering for the different columns I need to have only “And”. Using "or" will not provide the union of the values coming from different column and the result in 99% is not what the user meant. 

### Context

I was "playing" with the component, wanted to understand the behavior. 

### Your environment

https://mui.com/x/react-data-grid/filtering/ 

**Search keywords**: Data grid and/or operators for column filters
**Order ID**: 2222

**Comment by MBilalShafi** [comment]
Thank you for sharing your opinion. I understand your point around multi-filters for same column vs for different columns. However, currently it's a limitation of filtering that it doesn't allow nested conditions like `(columnA > 10 OR columnA < 20) AND columnB equals 'Test'`, it's either `OR` or `AND`

You could controllably change the behavior to default to `OR` or `AND`. In order to get more detail on how to control a filter, please check the section [Controlled filters](https://mui.com/x/react-data-grid/filtering/#controlled-filters).

We are working on a new version of filter UI solving the problems that it currently has. I'd appreciate if you leave some feedback on the [related issue](https://github.com/mui/mui-x/issues/6419) for that revamp.
