### ISSUE TITLE
DataGridPro with unstable_headerFilters: throw in console: "warning in console: Each child in a list should have a unique "key" prop."

### ISSUE THREAD

**Issue by NKodos** [mui/mui-x#10791]
### Steps to reproduce

Link to live example: [codesandbox example](https://codesandbox.io/s/mui-data-grid-2k57hv?file=/src/App.js)

Steps:
1. Use "@mui/x-data-grid-pro": "^6.16.0",
2. Add DataGridPro component with unstable_headerFilters prop
3. Add column singleSelect type

### Current behavior

Warning in console: Each child in a list should have a unique "key" prop.
Check the render method of `GridFilterInputSingleSelect`...
![image](https://github.com/mui/mui-x/assets/33037595/81b52998-37c8-4a91-b1c7-ac4138d07973)

### Expected behavior

I may have found a place in the source code that is causing this warning. 
In [this line](https://github.com/mui/mui-x/blob/f671a15d85f11882dd0ff340362e8289b7289443/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputSingleSelect.tsx#L31) create `valueOptions` with empty item. 
And in [this line](https://github.com/mui/mui-x/blob/f671a15d85f11882dd0ff340362e8289b7289443/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputSingleSelect.tsx#L38C36-L38C36) generates the `key` property from the value of `value`, which is `undefined`

### Context

This warning does not affect the application logic. But during development this message distracts from useful messages in logs.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: x-data-grid-pro unstable_headerFilters GridFilterInputSingleSelect Warning: Each child in a list should have a unique "key" prop
**Order ID**: 75108

**Comment by MBilalShafi** [comment]
Hey @NKodos, thank you for using MUI X Grid and reporting the issue and doing the investigation about the problem. 🙏 
The issue isn't necessarily related to header filters though, I could also reproduce it with the normal filter panel (open filter with the `singleSelect` column [here](https://codesandbox.io/s/mui-data-grid-forked-tx5gr4?file=/src/App.js:0-914)).

Also, it's interesting to note that the issue doesn't reproduce with the [flat string array type data](https://codesandbox.io/s/mui-data-grid-forked-9356cf?file=/src/App.js) for `valueOptions`, the issue occurs when the `valueOptions` is an array of objects and a customized `getOptionValue` comes into play, which now returns `undefined` instead of `""`

One possible solution could be to make it similar to the default `getOptionValue`:
https://github.com/mui/mui-x/blob/f671a15d85f11882dd0ff340362e8289b7289443/packages/grid/x-data-grid/src/colDef/gridSingleSelectColDef.tsx#L12-L14 which takes into account if the value is an object

Possibly calling the key as `value` would do or you could return a default value from `getOptionValue` if undefined like so:

```diff
- getOptionValue: (option) => option?.name,
+ getOptionValue: (option) => option?.name ?? "",
```

Let me know if it answers your concerns.

**Comment by NKodos** [comment]
> Possibly calling the key as `value` would do or you could return a default value from `getOptionValue` if undefined like so:
> 
> ```diff
> - getOptionValue: (option) => option?.name,
> + getOptionValue: (option) => option?.name ?? "",
> ```

Thanks, indeed your solution helped to get rid of the warning. It was not obvious to me.

> The issue isn't necessarily related to header filters though, I could also reproduce it with the normal filter panel (open filter with the `singleSelect` column [here](https://codesandbox.io/s/mui-data-grid-forked-tx5gr4?file=/src/App.js:0-914)).

When implemented with a normal filter panel, I was unable to reproduce this warning.

**Comment by MBilalShafi** [comment]
I'm glad it worked out for you. Feel free to jump in if there's another related query.
