### ISSUE TITLE
[charts] How to stack BarChart with ResponsiveChartContainer

### ISSUE THREAD

**Issue by jasminediaconu** [mui/mui-x#10894]
### Related page

https://mui.com/x/react-charts/bars/

### Kind of issue

Missing information

### Issue description

I am trying to add the BarChart component inside the ResponsiveChartContainer, however I haven't succeeded at this. I saw the [docs](https://mui.com/x/react-charts/bars/) have been recently updated with a pseudocode mentioning a use case for it. Is it possible to get an example on how to achieve it? 

**Search keywords**: ResponsiveChartContainer, BarChart

**Comment by alexfauquette** [comment]
Hi @jasminediaconu I would be interested to know what you tried to get it working. That would help to improve the developer experience.

To answer your question, here is a minimal example. You need to pass the `series` to the responsive container, and render a `<BarPlot />` inside. Plus to handle some magic done by the `<BarChart />` you should:

- set series property `type: 'bar'` otherwise the lib don't know which series is a bar
- set a `xAxis` with `xAxis={[{ scaleType: "band", data: [1, 2, 3, 4, 5] }]}` or any other kind of data

https://codesandbox.io/s/restless-smoke-l5c9qq?file=/src/Demo.tsx

**Comment by jasminediaconu** [comment]
Hi Alex thanks! I just figured I was trying to use the BarChart component instead of the BarPlot, that's why it wasn't working.

**Comment by AidrinVarghese** [comment]
How can I implement displaying values when hovering over bars and showing corresponding data on the Y-axis in BarPlots?
