### ISSUE TITLE
[tree view] Allow the ability to access extra data in `onNodeSelect` / `onNodeToggle` callbacks

### ISSUE THREAD

**Issue by alfonsoar** [mui/mui-x#10957]
### Summary 💡

It would be helpful to allow passing "extra data" (in addition to `nodeIds`) via the arguments of `onNodeSelect()` and `onNodeToggle`. 
 
 I understand that you could accomplish this by using the `ContentComponent` / `ContentProps` in the `<TreeItem />` as seen in your examples [here](https://github.com/mui/mui-x/blob/cb7dd8fba6eef74070ccfc3171701161890ba473/docs/data/tree-view/overview/IconExpansionTreeView.tsx#L15-L110) but I think having to recreate the entire TreeItem comp is a bit much. There might be a way we can help provide this out of the box or hooks so it's esier. 
 
 I've not thought out the API for the example below fully, but it illustrates where I think it can help. 

### Examples 🌈

Think of something like this: 

```tsx
  const handleToggle = (event: React.SyntheticEvent, nodes: [{id: string, type: string}]) => {
    // Make an assumption that there is a node @ 0
    // One could of-course keep track of all nodeIds and types in some sort of map too. 
    if (nodes[0].type === 'someCoolType') {
        // do something
    }
  };
  
  ...
  <TreeView
        ...
        onNodeToggle={handleToggle}
        ...
        >
        
        <TreeItem nodeId="1" type="someCoolType" />
        
 </TreeView>
```

### Motivation 🔦

I'm building a lazy loaded tree and this would be helpful 

**Search keywords**: extra data tree view onNodeSelect
**Order ID**: 74999

**Comment by alexfauquette** [comment]
@flaviendelangle I struggle to understand what this issue is about but, I assume it's because I lack some context about advanced tree view customization

**Comment by flaviendelangle** [comment]
From what I understand, right now you can't access your item properties inside `onNodeSelect` / `onNodeToggle`.

In #11476 and #11560 we introduced new props `onNodeExpansionToggle` and `onNodeSelectionToggle` that receives the id of the newly expanded / collapsed or selected / deselected node.
But you still can't easily access the other properties of the item.

Solving it in `TreeView` (which uses JSX `TreeItem` elements) will be complex because of 2 reasons:
1. The parent component (`TreeView`) is not aware of those custom props (e.g: `type` in your example)
2. The prop `type` would be passed to the DOM which is not what we want.

In #11059 we created a new component `RichTreeView` which handles the data with an `items` prop instead of JSX children.
With this component, people could either manually retrieve the item:


```tsx
const ITEMS = [
  { id: '0', label: 'Item 0', type: 'someCoolType' },
]

const handleNodeExpansionToggle = (event: React.SyntheticEvent, nodeId: string, isExpanded: true) => {
  if (isExpanded) {
    const type = ITEMS.find(item => item.id === nodeId)!.type;
  }
} 

return (
  <RichTreeView items={ITEMS} onNodeExpansionToggle={handleNodeExpansionToggle} />
)
```

In the future, we could improve the DX by doing something similar to `useGridApiRef` (this also avoids the linear complexity on big datasets).
This could look something like:

```tsx
const ITEMS = [
  { id: '0', label: 'Item 0', type: 'someCoolType' },
]

const instanceRef = React.useRef<TreeViewDefaultInstance>(null);

const handleNodeExpansionToggle = (event: React.SyntheticEvent, nodeId: string, isExpanded: true) => {
  if (isExpanded) {
    const type = instanceRef.getNode(nodeId).item.type
  }
} 

return (
  <RichTreeView items={ITEMS} onNodeExpansionToggle={handleNodeExpansionToggle} instanceRef={instanceRef} />
)
