### ISSUE TITLE
[pickers] incorrect placeholder and empty state displayed when using DD MMM YYYY

### ISSUE THREAD

**Issue by pawelproject** [mui/mui-x#11116]
### Steps to reproduce

Link to live example: [codesandbox](https://codesandbox.io/s/epic-resonance-4mh8dq?file=/src/Demo.tsx)

Steps:
1. click on text field

### Current behavior

displayed 
DD MMMM YYYY

only when month is selected, we see 3 letters

### Expected behavior

DD MMM YYYY

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
Browsers:
firefox 115.4.0esr (64-bit)
```
firefox 
  Output from `npx @mui/envinfo` goes here.
  "@emotion/react": "11.11.1",
    "@emotion/styled": "11.11.0",
    "@mui/material": "5.14.18",
    "@mui/x-date-pickers": "6.18.1",
    "@types/react": "18.2.38",
    "@types/react-dom": "18.2.16",
    "dayjs": "1.11.10",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.3.2"
```
</details>

**Search keywords**: pickers

**Comment by flaviendelangle** [comment]
Duplicates #9509

This is the expected behavior, the linked issues explains why and gives you a workaround to render `MMM` on your month section :+1:

**Comment by LukasTy** [comment]
@flaviendelangle I think we can improve the doc in this regard because this question keeps on popping up. 🤷 
WDYT about adding a section or expanding the demo in https://mui.com/x/react-date-pickers/adapters-locale/#custom-field-placeholder to include the example with custom format and placeholder reflecting that format? 🤔

**Comment by flaviendelangle** [comment]
It's at least the 3rd time so your probably  right
