### ISSUE TITLE
Rename the `dayPickerClasses` variable `dayCalendarClasses`

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#11141]
Renaming missed in v6.0.0
Part of #7902

**Search keywords**:

**Comment by MonstraG** [comment]
Hey, why wasn't this mentioned in the breaking changes of the release https://github.com/mui/mui-x/releases/tag/v7.0.0?

**Comment by LukasTy** [comment]
Because the v7 release only lists breaking changes introduced with that particular release.
This particular change has been released with `@mui/x-date-pickers@7.0.0-alpha.2`.
This particular BC is also [listed in the migration guide](https://mui.com/x/migration/migration-pickers-v6/#%E2%9C%85-rename-the-daypickerclasses-variable-to-daycalendarclasses).
Do you think that something is missing? 🤔

**Comment by MonstraG** [comment]
No, I just totally forgot that migration guide exists, and assumed that the release would list all changes.
