### ISSUE TITLE
[charts] Should tooltipClasses be exported similar to axisClasses?

### ISSUE THREAD

**Issue by cnollite** [mui/mui-x#11150]
### Summary 💡

Similar to the [axisClasses](https://mui.com/x/react-charts/bars/#using-a-dataset) example in the documentation, changing the styling of the tooltip should be able via tooltipClasses.

I tried using `'& .MuiChartsTooltip-markCell' ` for styling the tooltip, but the changes did not apply.

Adding `export * from './tooltipClasses';` to the index.tsx in ChartsTooltip should be enough.

### Motivation 🔦

I would like to change to styling of the charts tooltip, for example hiding the markCell.

**Search keywords**: tooltipClasses

**Comment by LukasTy** [comment]
Thank you for reporting this problem! 🙏 
I can confirm that we should indeed export it. 👌

**Comment by cnollite** [comment]
Could you give me a hint how i use the chartsTooltipClasses to for example hide the color mark inside the tooltip?

`['.${chartsTooltipClasses.markCell} .${chartsTooltipClasses.mark}']:{display: 'none',},`
doesn't seem to work.

**Comment by LukasTy** [comment]
@cnollite Here is a [working example](https://codesandbox.io/p/sandbox/determined-sea-438r25?file=%2Fsrc%2FDemo.tsx).
Did you try targeting the tooltip by adding an `sx` prop on the root chart element?
That wouldn't work, because the tooltip is attached at the end of the body DOM, instead of being a child of root chart element. 🤔

**Comment by taylor-c-williams** [comment]
Hi Lukas, thank you for sharing the code example! I am also trying to hide a mark element and having trouble targeting it. Unfortunately I am not able to use ThemeProvider in my project, and adding `sx` prop with `.MuiChartsTooltip-mark` doesn't work. The mark element is helpful (imo) only when rendering multiple datasets- I feel like disabling it shouldn't be an edge case. Any chance in getting that element exposed?

**Comment by LukasTy** [comment]
@taylor-c-williams Could you clarify how you are trying to apply your styles?
Maybe you could provide a live working example in a StackBlitz or CodeSandbox?
The `chartsTooltipClasses` are already exposed.
I believe that you are having trouble applying your styles, because of DOM structure. The tooltip is an element that is attached to the bottom of the DOM, it's not a child of any Chart.

Currently, I do not see any other way except for global styles to style it without `ThemeProvider`, because the `Tooltip` is from `@mui/base` and it does not support the `sx` prop. 🤔 

@alexfauquette, WDYT, could there be some more for improvement here? Or am I missing something?
Allowing styling only via `ThemeProvider` seems a bit harsh. 🙈

**Comment by alexfauquette** [comment]
There is the option of using `slotProps={{ popper: {sx: { ... } } }}` A bit nested, but it has worked for longtime in the data grid

**Comment by LukasTy** [comment]
Good observation, somehow I failed to make it work initially. 🙈 
So, the following approach "works":
```tsx
slotProps={{
  popper: {
    sx: {
      [`& .${chartsTooltipClasses.mark}`]: {
        backgroundColor: 'red',
        color: 'black',
      },
    },
  },
}}
```
But the problem is that TS is not happy 🙈 
<img width="828" alt="Screenshot 2024-02-28 at 11 46 28" src="https://github.com/mui/mui-x/assets/4941090/d1d25c53-1374-4e2a-8ff1-866c57adfdab">

**Comment by taylor-c-williams** [comment]
Awesome, thank you both for your help! Super appreciated! :octocat: 
This works for me: 
```
slotProps={{
            popper: {
              sx: {
                ["& .MuiChartsTooltip-mark"]: {
                  display: "none",
                },
              },
            },
          }}
```
