### ISSUE TITLE
[Data Grid] Warning: Failed prop type: MUI: The page prop of a TablePagination is out of range (0 to 0, but page is 1).

### ISSUE THREAD

**Issue by mtr1990** [mui/mui-x#11247]
### Steps to reproduce

https://codesandbox.io/p/sandbox/interesting-currying-fvqljg?file=%2Fsrc%2FDemo.tsx%3A261%2C9

### Current behavior

Show

`Warning: Failed prop type: MUI: The page prop of a TablePagination is out of range (0 to 0, but page is 1).`

### Expected behavior

Not show warning

### Context

Go to page 2 and delete all items on that page

https://github.com/mui/mui-x/assets/13531993/2ef3c375-d80a-46dd-a3f9-991c9fb6de82

**Search keywords**: Data Grid warning TablePagination when remove rows

**Comment by michelengelen** [comment]
@MBilalShafi I can confirm this bug. It happens when a page (not necessarily page 1) has no more rows to show after removing rows.

Steps to reproduce:
1. Create a paginated grid with at least 2 pages and allow deleting rows (with an action)
2. delete rows one by one until the page is empty
3. check console for the error

Could you have a look?

**Comment by MBilalShafi** [comment]
@mtr1990 Thank you for reporting the issue, it indeed _is_ a bug, and is related to the lastPage calculation in the GridPagination component. Here's a diff to fix the issue:

```diff
diff --git a/packages/grid/x-data-grid/src/components/GridPagination.tsx b/packages/grid/x-data-grid/src/components/GridPagination.tsx
index 3dd0b76b6..7a7ec95b2 100644
--- a/packages/grid/x-data-grid/src/components/GridPagination.tsx
+++ b/packages/grid/x-data-grid/src/components/GridPagination.tsx
@@ -39,7 +39,7 @@ export const GridPagination = React.forwardRef<HTMLDivElement, Partial<TablePagi
     );
 
     const lastPage = React.useMemo(
-      () => Math.floor(rowCount / (paginationModel.pageSize || 1)),
+      () => Math.ceil(rowCount / (paginationModel.pageSize || 1) - 1),
       [rowCount, paginationModel.pageSize],
     );
```

The was not being computed correctly when `rowCount === pageSize` for example for the render when `rowCount = 10` and `pageSize = 10`, the previous logic was calculating it to be `1` (second page as it's 0 indexed) instead of `0` (first page) and the `@mui/material/TablePagination` was throwing an error.

Feel free to open up a PR with the mentioned diff if you want.

**Comment by BuddhikaGeasman** [comment]
hi! if this is not worked on can i resolve this issue?

**Comment by drfuturenet** [comment]
Hi there, any progress on this one? Otherwise, could you provide a temporary workaround? Thanks you.
