### ISSUE TITLE
[DataGrid] Change `columnUnsortedIcon` in datagrid globally

### ISSUE THREAD

**Issue by cibiniceshops** [mui/mui-x#11320]
### The problem in depth 🔍

I would like to change the `columnUnsortedIcon` for all datagrids in my project.
What would be the best way to achive this. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Chrome
    System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.21 - ~/datenkraft/bb-frontend/node_modules/.bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
  npmPackages:
    @emotion/react: ^11.10.5 => 11.11.1 
    @emotion/styled: ^11.10.5 => 11.11.0 
    @mui/base:  5.0.0-beta.24 
    @mui/core-downloads-tracker:  5.14.18 
    @mui/icons-material: ^5.14.14 => 5.14.18 
    @mui/lab: ^5.0.0-alpha.143 => 5.0.0-alpha.153 
    @mui/material: ^5.14.14 => 5.14.18 
    @mui/private-theming:  5.14.18 
    @mui/styled-engine:  5.14.18 
    @mui/system: 5.14.14 => 5.14.14 
    @mui/types:  7.2.9 
    @mui/utils:  5.14.18 
    @mui/x-charts: ^6.0.0-alpha.17 => 6.0.0-alpha.17 
    @mui/x-data-grid: ^6.12.1 => 6.18.1 
    @mui/x-data-grid-premium: ^6.12.1 => 6.18.1 
    @mui/x-data-grid-pro: ^6.12.1 => 6.18.1 
    @mui/x-date-pickers: ^6.12.1 => 6.18.1 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.0.26 => 18.2.37 
    react: ^18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.9.4 => 4.9.5 

```
</details>

**Search keywords**: datagrid columnunsortedicon
**Order ID**: 73709

**Comment by michelengelen** [comment]
Hey @cibiniceshops 
It is pretty straightforward if you are using the `createTheme` function and `ThemeProvider` component from `material-ui`. Here is a little [demo](https://codesandbox.io/p/sandbox/flamboyant-rgb-x37nfk?file=%2Fsrc%2FDemo.tsx%3A62%2C53) of how that can look like.

Just make sure that you are augmenting the module following [this section](https://mui.com/x/react-data-grid/getting-started/#typescript) of the docs.

**Comment by cibiniceshops** [comment]
The new icons are shown but now I get console warnings on all pages with datagrids:
`Warning: React does not recognize the `sortingOrder` prop on a DOM element`
How do I get rid of that?

**Comment by cibiniceshops** [comment]
Here is the [sample implementation](https://codesandbox.io/p/sandbox/competent-mountain-n94hl7?file=%2Fsrc%2FDemo.tsx%3A7%2C17)

**Comment by michelengelen** [comment]
Hey @cibiniceshops 
My bad ... you have to extract the `sortingOrder` prop from the Icon props, as seen here:
https://github.com/mui/mui-x/blob/e723473706d1c81678249ca61921a9d959cea750/packages/grid/x-data-grid/src/material/icons/GridColumnUnsortedIcon.tsx#L10-L23

I did change this in [this sandbox](https://codesandbox.io/p/sandbox/gracious-shadow-qwklrl?file=%2Fsrc%2FDemo.tsx%3A16%2C28).

Since the interface for `GridColumnUnsortedIconProps` is not exported (reference link below - I'll open a ticket for that) I simply did create the interface in the component itself. It's easy, but shouldn't be needed tbh.

https://github.com/mui/mui-x/blob/e723473706d1c81678249ca61921a9d959cea750/packages/grid/x-data-grid/src/material/icons/GridColumnUnsortedIcon.tsx#L6-L8

Is this fixing your issue?

**Comment by cibiniceshops** [comment]
Thank you @michelengelen

**Comment by michelengelen** [comment]
No problem @cibiniceshops ... glad I could help!
