### ISSUE TITLE
[DataGrid] How do I export the details in a master/details table. 

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#11426]
### The problem in depth 🔍

Hello, 

How do I get the details to export in a datagrid that has matester details. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Export Master Details
**Order ID**: 66765

**Comment by michelengelen** [comment]
Hi @lisaWriteJava ... I am almost certain that this is not possible at the moment, since the way this is constructed (as the details are actually a component that gets rendered in the details panel), but to not misinform you I will loop in our team.

@cherniavskii do we have the capability to export the contents of detail panels?

**Comment by lisaWriteJava** [comment]
Ok, thank you. I was asked by a user if exporting rendered details is possible. If it's not I am sure I saw a configuration to allow hidden data to be exported and printed. I may render the details as a hidden column, Yes it will be big and ugly but,  if the user wants the data I think that this is the only way  unless you say otherwise.

**Comment by michelengelen** [comment]
Lets wait for @cherniavskii ... he has a lot more insight into this than me.

**Comment by evgeniiarts** [comment]
There is one workaround which might work for some use cases.
It isn't the most elegant as it only works when your master detail contents are loaded with the data grid rows. If it is loaded dynamically when you open a master detail, this workaround will fail.
https://codesandbox.io/p/sandbox/export-master-detail-y6c6vj
In this example we use traderName and traderEmail as our master detail content.

It works in a way where we load the rows for the datagrid and the **rows include the master detail content** as if they were columns.
But then we make sure that those details do not show up in the datagrid, in the column visibility panel nor in the filter menu.
Yet we set the export options to "allColumns: true" in order to include those details regardless.
This way each exported row includes the master detail information as columns with values.

Not sure whether this suits your use case, for me it did work on one occasion so I thought sharing it might be helpful.
I found it easier than using for example excel.js postprocessing, which you might need to opt for if your master detail content cannot be loaded with the data grid rows.

**Comment by lisaWriteJava** [comment]
Thanks I think that this will work. I agree it isn't elegant but since this capability is being pushed I wanted to give the  best option possible.

**Comment by lisaWriteJava** [comment]
1 question, do I need to set a value getter along with the render cell. I tried just render cell, but the data in the column didn't print when I manually hid the column.  I wasn't able to get the column to hide programmatically. Not sure what I may have done wrong.

**Comment by evgeniiarts** [comment]
@lisaWriteJava It would be great if you could provide a minimal example in codesandbox, as it is a bit difficult to understand what you describe.

Regarding your question on valueGetter and renderCell:
A value getter is a helper function for columns to either create values from other columns or transform the value from rows into a desired value, such as turning absolute values into percentage.
https://mui.com/x/react-data-grid/column-definition/#value-getter

There is a great example on the value getter documentation:
`const columns: GridColDef[] = [
  {
    field: 'profit',
    valueGetter: ({ row }) => {
      if (!row.gross || !row.costs) {
        return null;
      }
      return row.gross - row.costs;
    },
  },
];`

In the example a column "profit" is in the data grid, but the rows do not directly have the value. Instead it is calculated from row.gross and row.costs.

RenderCell works only on cells which have a value, be it a value from the rows directly or a value from a valueGetter. You can see it as simple CSS customization of a cell value.
For example it allows showing rating stars instead of a numeric value because it is more appealing and easier to grasp for users. 
RenderCell has no effect on CSV and Excel exports, but it does affect how the Print export looks.

**Comment by lisaWriteJava** [comment]
Thanks, what you gave me got me on the right track and I was able get started on implementing the code. I realized my issue about not hiding had to do with using a common component and not passing the setup to it for the grid I was rendering. Eveything is working as expected.

**Comment by evgeniiarts** [comment]
@lisaWriteJava Regarding the second part of your question on hiding columns and columns not being printed.
If you indeed mean the simple "Print" export, then it is pretty simple. It does not include hidden columns as it literally prints what you see on your screen in the datagrid, except it will go through all the rows. Therefore if you hide a column and it doesn't print it - that is expected behavior.

For Excel and CSV it is a bit different. You can force those two to export hidden columns with this settings(regardless how they were hidden, manually or programmatically):
`<DataGridPremium
        {...data}
        slotProps={{
          toolbar: {
            csvOptions: {
              allColumns: true,
            },
            excelOptions: {
              allColumns: true,
            },
          },
        }}
      />`
      
You can still force some columns not to be printed even with this setting if you set the column definitions to "disableExport: true". 

Hiding columns is pretty straight forward programmatically. One way is to utilize the initialState as such:
`const initialState = {
    columns: {
      columnVisibilityModel: {
        traderName: false,
        traderEmail: false,
      },
    },
  };`
and pass the initialstate={initialState} to the datagrid. 

Oh, now your answer appeared while I was still writing this one. Great to hear that you got it working!

**Comment by lisaWriteJava** [comment]
Here's a sandbox of what I am workign on for this: https://codesandbox.io/p/sandbox/agitated-liskov-cvdlsn?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqfb41z700062v6ihg6tghft%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqfb41z700022v6i54ar2jmb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqfb41z700032v6ii9ikj88t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqfb41z700052v6ihjqybr2p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqfb41z700022v6i54ar2jmb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqfb41z600012v6iw7excqzz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clqfb41z700022v6i54ar2jmb%2522%252C%2522activeTabId%2522%253A%2522clqfb41z600012v6iw7excqzz%2522%257D%252C%2522clqfb41z700052v6ihjqybr2p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqfb41z700042v6iobsm2r4j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqfb41z700052v6ihjqybr2p%2522%252C%2522activeTabId%2522%253A%2522clqfb41z700042v6iobsm2r4j%2522%257D%252C%2522clqfb41z700032v6ii9ikj88t%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqfb41z700032v6ii9ikj88t%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by evgeniiarts** [comment]
@lisaWriteJava When it comes to troubleshooting issues, it is very recommendable to try and isolate those - and provide a _minimal reproduction_ to focus on it. The sandbox you have shared is quite large, therefore it is difficult to pinpoint issues. 
Maybe you could build a minimal reproduction by forking one of the examples on the MUI-X documentation page?

**Comment by lisaWriteJava** [comment]
I'll give it a try and try to get something to you later today or tomorrow.

**Comment by lisaWriteJava** [comment]
ok, here's a sandbox. I hid the desk column but when I print it never shows. The export just doesn't worK https://codesandbox.io/p/sandbox/export-master-detail-y6c6vj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqf8dsqx00062v6ia6k1lxeo%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqf8dsqx00022v6i8z35qg0e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqf8dsqx00032v6ixh899rgf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqf8dsqx00052v6iksblvqzs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.70147709638485%252C44.29852290361515%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqf8dsqx00022v6i8z35qg0e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqf8dsqw00012v6iaj1xetlc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqf8dsqx00022v6i8z35qg0e%2522%252C%2522activeTabId%2522%253A%2522clqf8dsqw00012v6iaj1xetlc%2522%257D%252C%2522clqf8dsqx00052v6iksblvqzs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqf8dsqx00042v6iewig1rht%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqf8dsqx00052v6iksblvqzs%2522%252C%2522activeTabId%2522%253A%2522clqf8dsqx00042v6iewig1rht%2522%257D%252C%2522clqf8dsqx00032v6ixh899rgf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqf8dsqx00032v6ixh899rgf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by lisaWriteJava** [comment]
This sandbox is from one of the examples with the hidden field expanded.

**Comment by lisaWriteJava** [comment]
Got everything working,
