### ISSUE TITLE
[DataGrid] `renderCell` params do not include row values anymore

### ISSUE THREAD

**Issue by fatih-mdous** [mui/mui-x#11461]
### The problem in depth 🔍

I was using params row prop to have row values in mui datagrid premium but after updating license key, it is starting to show `auto-generated-row-null/FNBGOP` this one instead of row value props in row prop in params in rendercell.

Before
![1](https://github.com/mui/mui-x/assets/79893620/cb86a2a6-ab80-4ff8-ab14-058030b41d31)
After licence key
![2](https://github.com/mui/mui-x/assets/79893620/96db204e-91b6-4ade-b5f3-0aa85a223b4e)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: rendercell
**Order ID**: #51399

**Comment by michelengelen** [comment]
Hey @fatih-mdous that is because the grouped cell is now moved to a auto generated row instead. This is expected behaviour, since these rows are not part of the row model and have no attached row.

What exactly are you trying to do with this value? If you could provide us with a minimal example we might be able to help. You can use [this example](https://codesandbox.io/p/sandbox/condescending-rui-fkhgz4) as a starting point. Thanks! 🙇🏼

**Comment by fatih-mdous** [comment]
I solved the issue by following [this example](https://codesandbox.io/p/sandbox/condescending-rui-fkhgz4) you suggested. Thanks

**Comment by fatih-mdous** [comment]
I solved the issue by following [this example](https://codesandbox.io/p/sandbox/condescending-rui-fkhgz4) you suggested. Thanks

**Comment by michelengelen** [comment]
@nurira could you please open a new issue for this? 
It is not exactly related, so we would prefer to keep this clean.
Also please provide a minimal reproduction example for us to work on. This will increase the chance for us to solve your issue quickly!
Thanks! 🙇🏼
