### ISSUE TITLE
[DateTimePicker] Can't change the color for the tabs

### ISSUE THREAD

**Issue by sanjitchh** [mui/mui-x#11532]
### Related page

https://mui.com/x/react-date-pickers/custom-components/

### Kind of issue

Missing information

### Issue description

I wanted to change the color for the Date Time Picker tabs that let us switch between the date and the time sections of the picker. There is no clear explainantion for how to to it. I cannot add sx to the tabs in the slotprops and adding the class somewhere else is also not working.

**Search keywords**: DateTimePicker tab color

**Comment by LukasTy** [comment]
Thank you for reporting this problem! 🙏 
I can confirm that there is an issue here, at a minimum this component should support `className` and `sx` prop.
The `classes` prop is technically optional because it only contains a `root` slot.
At the same time, we should add the missing `classes` prop to the `DateTimePickerToolbar`.

**Comment by iamabhshk** [comment]
Can I look into this? @LukasTy

**Comment by LukasTy** [comment]
> Can I look into this?

Feel free to work on it. 👍 
Just to let you know, we have not groomed this issue yet, thus, the information might not be complete. 🤔

**Comment by iamabhshk** [comment]
I analyzed the code and here's what I found.
![MUIX-1](https://github.com/mui/mui-x/assets/64522190/78b7a941-ea80-4c72-9643-724e372e851c)

In the above screenshot, we are using a **'ToggleButtonGroup'** component and it has a color property. In order to change the color we can replace the 'primary' with these options:  **['secondary'| 'error' | 'info'| 'success'| 'warning']**
For details you can refer to this link https://mui.com/material-ui/api/toggle-button-group/


I hope this is what you were seeking if my understanding to your issue was correct.

**Comment by LukasTy** [comment]
@iamabhshk If we are talking about building your own "DatePicker" various subcomponents - then sure, your example makes sense, but in this case the problem is different.
The issue author is expecting the ability to provide styling props to the `DateTimePickerTabs` component. 😉

**Comment by sanjitchh** [comment]
@LukasTy @iamabhshk Hey! Sorry for not providing more context. I was talking about the color of the tabs of the DateTimePicker component that we get when we have `tabs: {hidden: false}` in the slotProps. I was looking to customize the the tab colors separately using sx as i have done for `day` but the `tabs` slotProp currently does not support sx. 
I have attatched the image of my code and the tabs I am talking about.

![image](https://github.com/mui/mui-x/assets/127385161/5361807d-7704-4634-84d7-ebd09ace656b)
![image](https://github.com/mui/mui-x/assets/127385161/a286537d-d6c4-4a64-8592-f61c0778ea96)

**Comment by iamabhshk** [comment]
Ohh I see, now I am clear. Let me try it and will let you know.
