### ISSUE TITLE
[data grid] Custom columns config are deleted when data are updated

### ISSUE THREAD

**Issue by Chris-FSE** [mui/mui-x#11562]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-2wnksj?file=Demo.tsx

Steps:
1. Change the order of the columns and their sizes.
2. Press the button to change the value of the ID field of the only element present.
3. The previous columns order or sizes are lost.

### Current behavior

When changing the value, all previous configuration (column order/size) is lost.

### Expected behavior

When changing the value, all previous configuration (column order/size) must be retained.

### Context

We need to create a table that can be customized (column width, column order, etc.).
We also have the table data updating via redux (in our case, and we have the same result as the demo added here when the data is changed).
So we need to be able to update the data values via Redux while keeping the customization of the columns in place.

**Search keywords**: datagrid column delete state data update

**Comment by michelengelen** [comment]
Hey @Chris-FSE you can save and restore the `DataGrid` state with the `apiRef`. There is a [section about this](https://mui.com/x/react-data-grid/state/#save-and-restore-the-state-from-external-storage) in the docs.

The rows update re-rendering the grid and therefore resetting the column state is due to a misused column prop. These are constants and should be handled like that. You can either memoize the column definitions inside the component or just define them outside of the component.

I have updated the demo from the docs about the [row updates](https://mui.com/x/react-data-grid/row-updates/) to showcase that: [demo](https://codesandbox.io/p/sandbox/priceless-elion-z6qsd9?file=%2Fsrc%2FDemo.tsx%3A55%2C14).

**Comment by Chris-FSE** [comment]
Hey @michelengelen thank you for your help.
Indeed, in the meantime I had found for my part by coming across examples of the use of states that the definitions of the columns must be outside the body of the component.
I think it would be interesting to notify this in the documentation.
Is this a library bug? Because even if the columns are defined in the component, the state management should work, right?
In my case I have very specific column renderings which depend on declared variables and managed only in the component body. So it's not obvious...

**Comment by Chris-FSE** [comment]
The memoize option also works like exporting the column definition out of the component. 
Thanks again for the information.
This is better for me because the column definitions depend on component variables.
I'm just curious to know if it's a bug from the lib or not.
And I think that you can close the issue now.

**Comment by michelengelen** [comment]
Right ... memoization is a different possibility.
I will close this now as the opening question seems resolved.
Feel free to reopen if you have follow up questions. 🙇🏼
