### ISSUE TITLE
[pickers] How to render custom TextField component in DatePicker (v6)

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#11634]
### Steps to reproduce

In version 5, basically I had a custom TextField(refer sandbox files MyV5DatePicker.tsx and RenderInput.tsx) that I created to match our design system and that was returned in the renderInput prop of the DatePicker . I am having a hard time migrating it to version 6.

https://codesandbox.io/p/sandbox/rough-meadow-qn3324?file=%2Fsrc%2FMyV5DatePicker.tsx%3A17%2C45

I just want to know if my current code can be migrated successfully to version 6 or not.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DatePicker renderInput prop migration

**Comment by noobDev31** [comment]
sure thanks @michelengelen

**Comment by noobDev31** [comment]
@michelengelen  hi i tried to see the custom field example of **JoyUI** Input that you have on the docs but I am unable to understand how can I pass my custom props like **infoIcon** , **infoIconText** from the parent 

I have tried to pass them from **slotProps**  field itself but not sure if it's correct or not and what changes should I do on my **RenderInput** component to accomodate my changes

[
](https://codesandbox.io/p/sandbox/rough-meadow-qn3324?file=%2Fsrc%2FMyBeautifulV6DatePicker.tsx%3A165%2C56)

**Comment by michelengelen** [comment]
> @michelengelen hi i tried to see the custom field example of **JoyUI** Input that you have on the docs but I am unable to understand how can I pass my custom props like **infoIcon** , **infoIconText** from the parent
> 
> I have tried to pass them from **slotProps** field itself but not sure if it's correct or not and what changes should I do on my **RenderInput** component to accomodate my changes
> 
> [Codesandbox ](https://codesandbox.io/p/sandbox/rough-meadow-qn3324?file=%2Fsrc%2FMyBeautifulV6DatePicker.tsx%3A165%2C56)

First of all ... Good job! 👍🏼 

tbh the JoyUI replacement is probably the most complex one, but also the most feature rich.

Now I cannot see where you are going to pass the additional custom props (`infoIcon`, or `infoIconText`) into the component? You can use the `slotProps` for that, or pass just pass it down as an individual prop.

As for the changes on your `RenderInput` component: they solely depend on what you are trying to achieve. The demo you provided is currently not working, so it's hard to tell.

If you could provide a minimal working example this could be easier.

**Comment by LukasTy** [comment]
@noobDev31 Have you tried passing your `RenderInput` component to the `textField` slot instead of `field`? 🤔 

I've tried tinkering with your example a bit up until something got rendered.
Could you please check [the "working" solution](https://codesandbox.io/p/sandbox/nostalgic-jennings-r7htrr) and let us know if it is something that you are leaning towards?

**Comment by noobDev31** [comment]
Hi @LukasTy  I did try it 
![image](https://github.com/mui/mui-x/assets/109504204/6b588325-a75c-48ee-8747-a15e455c2a0a)

so basically if you see the above error it's because the dev who developed it passed two things(**params** which was **OutlinedTextFieldProps** and **datePickerProps** which was the **remainingProps** correctly done by you) to the **RenderInput** in the below sandbox - 

[CodeSandbox](https://codesandbox.io/p/sandbox/zealous-benji-chsfpv?file=%2Fsrc%2FRenderInput.tsx%3A21%2C8)

**Comment by LukasTy** [comment]
@noobDev31 Could you confirm what is missing or what is your question? 🤔 
In regards to the `RenderInput`, you can see that in my example I changed it to expect all the props in one object.
IMHO, that's an easier approach to go about, because the `TextField` naturally receives all the props that are passed down from the `DateField` internally.
If you need anything extra - you can pass it down via `slotProps.textField` as additional props.

**Comment by noobDev31** [comment]
So Lukas its about the typescript errors i get on my **DatePicker** file i get if you see my original **RenderInput** file - 

[CodeSandbox](https://codesandbox.io/p/sandbox/admiring-lehmann-qlgh7d?file=%2Fsrc%2FRenderInput.tsx%3A30%2C14)



![image](https://github.com/mui/mui-x/assets/109504204/36b86b40-5314-4cbc-b8f6-421667c634ae)

![image](https://github.com/mui/mui-x/assets/109504204/33da5f7e-cf01-42ee-a746-191b1d5cb43a)

PS: I am too scared of any BWC because of me

**Comment by noobDev31** [comment]
hi @LukasTy any update on the above?

**Comment by michelengelen** [comment]
@LukasTy gentle ping on this one. Thanks! 🙇🏼

**Comment by LukasTy** [comment]
Hello @noobDev31 
Let's try tackling this problem bit by bit.
1. What is the reason that `DatepickerLCProps` has all the usual DatePicker props duplicated?
We can start by removing the props that seem redundant: `disabled`,  `disablePast`, `disableFuture`, and `readOnly`. They are all already available from `DatePickerProps` as top-level props.
2. Fix the type of `value` in `useState` to not have a `string` type as that can never happen. If you ever pass a string - it will break. That's the main breaking change in V6.
3. Move the styles applied in `styled` to the `sx` prop on the `textField` slot as it seems to only target this particular component.
4. Rename `dateFormat` to `format`.
5. Remove the `onBlur` prop as it does not seem to be used.
6. Refactor `RenderInput` types to extend `OutlinedTextFieldProps` and add the additional `datePickerProps` field.
7. Update `changeHandler` to expect `Dayjs` or `null`.
8. Fix `minDate` and `maxDate` to use `dayjs` instead of `Date`.
9. Spread `{...remainingProps}` on `DatePicker`.
10. I'm not sure where the `onChange` prop is registered, but that's out of my reach to understand what needs to change in its regard as it seems custom and types are unknown. 🤷 
I'd just encourage you to avoid overriding it at all if possible. 🤔 
11. You can ignore the `slotProps.textField.datePickerProps` TS error. We currently do not have the option to pass additional unknown properties to `slotProps` and make TS happy.
12. Remove `slotProps.actionBar.sx`—those are the same styles that are applied by default.
13. The `textField` slot is complaining about types because the `datePickerProps` are marked as required and this slot is unaware of it. We can either make it optional or also ignore or cast it to avoid the error.
14. Rename the `SwitchViewIcon` slot to `switchViewIcon` (make it lowercase).

That seems more or less all of it.
You can check the [updated codesandbox](https://codesandbox.io/p/sandbox/hopeful-meitner-2nqr94) with the mentioned changes.

Is there anything else that is unclear? 🤔

**Comment by noobDev31** [comment]
Well, @LukasTy , it's unclear why you answered from 1 point to 10 points; I had already fixed them on our codebase 😅 .

The 11th point and the 13th point were the ones I was looking for, so thanks a ton for addressing them.

**Comment by LukasTy** [comment]
> it's unclear why you answered from 1 point to 10 points; I had already fixed them on our codebase 😅 .

Well, your provided CodeSandbox did seem to have those issues, I used it as the starting point. 😉 

> so thanks a ton for addressing them.

Glad we could finally help you resolve your problems. 👍 
Enjoy the new major and let us know if you find any further issues. 🙏

**Comment by 100sarthak100** [comment]
I'm getting this issue ->
```
Error: MUI X: The `sectionListRef` prop has not been initialized by `PickersSectionList`
  at /vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:119992:13
  at invokePassiveEffectCreate (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:288904:20))
  at HTMLUnknownElement.callCallback (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:269367:14))
  at Object.invokeGuardedCallbackDev (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:269416:16))
  at invokeGuardedCallback (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:269478:31))
  at flushPassiveEffectsImpl (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:288991:9))
  at unstable_runWithPriority (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:302844:12))
  at runWithPriority$1 (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:276698:10))
  at flushPassiveEffects (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:288864:14))
  at performSyncWorkOnRoot (/vendors-node_modules_mui_icons-material_esm_AccountCircle_js-node_modules_mui_icons-material_-0117ae.iframe.bundle.js:287686:3))
```

Does anyone know how to resolve this?

**Comment by LukasTy** [comment]
@100sarthak100 Are you by any chance passing a generic or custom `TextField` component to the `textField` or `field` slot?
You can check examples on how to use custom text field component for accessible DOM Pickers [here](https://mui.com/x/react-date-pickers/custom-field/#with-another-design-system).
