### ISSUE TITLE
[data grid] Autosizing not working on the column where we use renderCell value

### ISSUE THREAD

**Issue by Laxman2015** [mui/mui-x#11638]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/kind-brahmagupta-w87ynq?file=%2FDemo.js%3A1%2C1-156%2C1
Steps:
1. open 
2. updated renderCell value
3. Autosizing not working on the column where we use renderCell value

### Current behavior

<img width="376" alt="image" src="https://github.com/mui/mui-x/assets/14539326/ea5d6286-c6cc-4306-af09-e69288f6021b">

### Expected behavior

<img width="380" alt="image" src="https://github.com/mui/mui-x/assets/14539326/3440eee9-3479-4ad3-b9d7-e5c110ec30cf">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid column Autosizing

**Comment by evgeniiarts** [comment]
@Laxman2015 The issue is that auto-sizing of columns is based on the cells **value**, while renderCell is designed for _styling_ purposes.
Therefore you need to use valueGetter instead of renderCell and it should work. See here (forked your sandbox):
https://codesandbox.io/p/sandbox/friendly-paper-pvqcjn
