### ISSUE TITLE
[data grid] Debounce subcomponent rendering

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11745]
I am trying to implement a Data table that has more tables as subcomponents. The data is coming dynamically but it is not reflecting in the subcomponent. I am not getting the columns value in the subcomponent because of which it always shows empty sub table. I have attached the link to the sandbox where my code is replicated but it has no data due to security issues. I request you to add dynamic nested data to complete the code.
https://codesandbox.io/p/sandbox/mui-x-issue-template-forked-32t8hj?file=%2Fsrc%2FApp.tsx%3A58%2C30

**Search keywords**:

**Comment by kumar-pratiyush** [comment]
The issue is occurring because the subcomponent is getting rendered before the data is passed to it. Is there any way to delay it so that the render happens after the data is passed?

**Comment by michelengelen** [comment]
Hey @kumar-pratiyush,

Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷. Right now your example is not showing anything because there is no row data present.

A live example would be perfect. [This **codesandbox.io** template](https://mui.com/r/x-issue-template) _may_ be a good starting point. You can find more codesandbox templates in our [docs](https://mui.com/x/react-data-grid/).

Thank you! 🙇🏼
