### ISSUE TITLE
[data grid] Cannot read properties of undefined (reading 'length') in MUI DataGridPro

### ISSUE THREAD

**Issue by aimenzara** [mui/mui-x#11777]
### Steps to reproduce

Im using DataGridPro to add column filter to "Name" and "Designation". Im getting this error on trying to persist the filters. It is working fine for independent filters i.e on applying name filter it shows all results with name filter and on designation filter it clears name filter and filters out the result on the basis of designation only. I want to persist Name filter aswell but cant.
https://mui.com/x/react-data-grid/filtering/header-filters/#simple-header-filters

Here is a code snippet:

https://codesandbox.io/p/sandbox/naughty-elion-vcw34l?file=%2Fdemo.js%3A208%2C54

but is is giving me error of undefined, reading length

### Expected behavior

I want to persist both or all the columns which involve filter to be persisted.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Cannot read properties of undefined (reading 'length') in MUI DataGridPro

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @aimenzara ... sry for the late reply.
I did look at your example and the problem was with the initial value of the `filterModel` state. You did only store the items and not the whole model.

Here is an [updated example](https://codesandbox.io/p/sandbox/festive-montalcini-h5cvh9?file=%2Fdemo.js%3A176%2C28) of your code.

I will close this now, but feel free to reopen, or open a new issue if you encounter another problem! Thanks! 🙇🏼
