### ISSUE TITLE
[data grid] Row Grouping mixed with non grouped rows

### ISSUE THREAD

**Issue by dmartinw-ccms** [mui/mui-x#11807]
### The problem in depth

Hey,

I hope you are doing well.

We are trying to make the `DataGrid` component behave as `Excel`, so we would like to have empty rows in order to separate data rows, and as well being able to groups in the middle. So, if we had something like

- Empty Row
- Grouped Row 1
- Grouped Row 1
- Grouped Row 2
- Empty Row
- Grouped Row 2
- Grouped Row 2
- Grouped Row 2
- Empty Row

MUI Data Grid must render 

- Empty Row
- Group 1
- Empty Row
- Group 2
- Empty Row

The groups may have some aggregations too

is that possible with the current features?

Regards

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: grouping, row, excel
**Order ID**: 79401

**Comment by michelengelen** [comment]
Hey @dmartinw-ccms ... It is generally possible to do either of `grouping` and `empty rows`, but afaik its not possible to use that together. 

For emtpy rows you can just pass a rowdefinition without a value for the fields and row grouping is covered in this doc: [Row grouping](https://mui.com/x/react-data-grid/row-grouping/)

Can you think of a way to allow for such behavior @MBilalShafi ?

**Comment by MBilalShafi** [comment]
It's not something available OOTB, but a workaround to do something similar would be to override the `groupingColDef.renderCell` and add data for the empty rows. Not ideal (some TS issues need to be solved since the test is on the demo data) but I tried to do that in this stackblitz example: https://stackblitz.com/edit/react-foquyn?file=Demo.tsx

@dmartinw-ccms Is there a specific order of empty rows you are interested in? What would be the criteria for that? Right now, I inserted 3 rows at the start, middle, and end of the data. Based on the grouping division they show arbitrarily.

Could this satisfy your use-case by any chance?
