### ISSUE TITLE
[data grid] Hide GetDetailPanelContent expand icon

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11851]
Is there an option to hide the expand icon in subcomponent using GetDetailPanelContent when there is no rows present in the subcomponent table?

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @kumar-pratiyush 

It is possible to hide it with CSS. I have a little example here where only every 2nd row has a detail panel. I did add an entry into the `sx` prop that hides the expand button when it is disabled.

[Example](https://stackblitz.com/edit/react-wrdmuw?file=Demo.tsx)

Let me know if this suits your use case.

Otherwise you can use that example as a starting point for a more specific working example for us to look at! Thanks! 🙇🏼

**Comment by kumar-pratiyush** [comment]
Thanks for the answer, it was helpful
