### ISSUE TITLE
[DataGrid] Improve vertical scrolling performance

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#11866]
The [Sticky headers PR](https://github.com/mui/mui-x/pull/10059) fixed a bunch of issues, improved horizontal scrolling UX, and [reduced the gaps when dragging the scroll thumb](https://github.com/mui/mui-x/pull/10059#discussion_r1371541568).

However, the vertical scroll performance has regressed - see https://github.com/mui/mui-x/pull/10059#issuecomment-1904389411

We can improve the performance according to https://github.com/mui/mui-x/pull/10059#issuecomment-1904425888:
> I think it will be fairly easy to add a wrapping container for the cells and apply the style once. That in conjunction with the CSS contain: strict style should make it much more easy for the browser to layout stuff.

**Search keywords**:

**Comment by oliviertassinari** [comment]
@romgrk A quick progress report on my laptop, using this script to scroll

<details>
  <summary>expand</summary>

```jsx
class Scroller {
    static scroll({ element, distance = 50000, speed = 50, maxSpeed = 1000, acceleration = 0, callback, scrollFn }) {
        let scrollTop = 0;

        const intervalId = setInterval(() => {
            if (scrollFn) {
                scrollFn(scrollTop)
            } else {
                element.scrollTop = scrollTop;
            }

            scrollTop += speed;

            if (speed < maxSpeed) speed += acceleration;

            if (scrollTop > distance) {
                clearInterval(intervalId);
                callback && callback();
            }
        }, 5);
    }
}
Scroller.scroll({ element: document.querySelectorAll('.MuiDataGrid-virtualScroller')[1] })
```

</details>

Before https://deploy-preview-11650--material-ui-x.netlify.app/x/react-data-grid/#pro-plan

<img width="320" alt="SCR-20240226-cuia" src="https://github.com/mui/mui-x/assets/3165635/4d5a5f35-8c54-480f-ab17-29f9826ef450">

After https://github.com/mui/mui-x/pull/10059 (add position: sticky) https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/#pro-plan

<img width="327" alt="SCR-20240226-cumr" src="https://github.com/mui/mui-x/assets/3165635/b69d2a92-6e7c-41e5-bd08-80f4ebc28ac9">

Today on HEAD https://next--material-ui-x.netlify.app/x/react-data-grid/#pro-plan

<img width="322" alt="SCR-20240226-cvao" src="https://github.com/mui/mui-x/assets/3165635/79bafd1d-de0d-47ca-8dd2-18448e4303ac">

AG Grid https://www.ag-grid.com/example/, scrolling at the same speed and with the same number of column / column type

<img width="316" alt="SCR-20240226-cwww" src="https://github.com/mui/mui-x/assets/3165635/a22973b0-350c-4c62-ac8d-562a36adf714">

---

I confirm the regression is pretty much gone, nice job 👍.

---

As for future improvement opportunities, the ones I can see:

1. Being smarter with the overscan, it feels like this #11344 would have the most impact.

2. The time we spend rendering Emotion styles. We might be able to save 50ms We should likely memo that:

<img width="555" alt="SCR-20240226-cywd" src="https://github.com/mui/mui-x/assets/3165635/cb43528c-6495-42c0-8076-ba1a2b38a2ee">

3. Adding a translate3d on each row seems to save 30ms of Painting time, while it costs 20ms of Layout time, saving 10ms. This is because it avoids all the rows to repaint:

https://github.com/mui/mui-x/assets/3165635/f3ac867e-7130-4c08-878f-f24880997d60

I guess positioning each row position absolute could have a similar impact, avoiding a Paint when a row is added or removed to the list.
