### ISSUE TITLE
[pickers] How to access Button props inside Date Picker Shortcut

### ISSUE THREAD

**Issue by wlee-vendelux** [mui/mui-x#11860]
### The problem in depth

How do I access the `Button` inside the new Date picker `Shortcuts` ?

Ideally I'd like to do something like the following:

```
          <StaticDateRangePicker
            slotProps={{
              shortcuts: {
                items: [...],
                slotsProps: {
                  button: {
                    disableRipple: true,
                    variant: "text",
                  }
                }
              },
            }}
          />
```

**Search keywords**: date picker shortcut button prop
**Order ID**: 69589

**Comment by michelengelen** [comment]
Hey @wlee-vendelux ... accessing the props for the single items is not possible via the `slotProps`. For full control over the rendered component and the resulting layout you can customize the `ShortCuts` component. Here is an example of how to do that: [custom layout example](https://stackblitz.com/edit/react-mbg1mz?file=Demo.tsx).

**Comment by wlee-vendelux** [comment]
That looks great! Thanks @michelengelen

**Comment by wlee-vendelux** [comment]
sorry to revive an old thread, but i finally got around to implementing your solution @michelengelen but i ran into another issue. i'd like to be able to color the individual shortcut if it's currently selected. 

i've been able to use a state var to know which shortcut was selected last [from the documentation](https://mui.com/x/react-date-pickers/shortcuts/#know-which-shortcut-has-been-selected), but i'm unable to pass that information down to the custom `Shortcut` component

here's what im looking at:

https://stackblitz.com/edit/react-mbg1mz-9ywqqo?file=Demo.tsx

**Comment by LukasTy** [comment]
Hello @wlee-vendelux, it looks like your example is almost working, it's just that `ListItemText` does not have a `color` property, it expects `primaryTypographyProps` instead and you were probably missing the `onChange` on the `StaticDateRangePicker` to make the state value updating work. 🙈 
Please check the [updated demo](https://stackblitz.com/edit/react-mbg1mz-fsskkh?file=Demo.tsx) for a working example.
Does that solve your problem? 🤔 


Sidenote—consider changing the value of the `Last 7 days` shortcut if you want the selected behavior to work because now the values are unstable and rely on the selection time (i.e. comparison might run a few ms later than the actual value selection and thus the `milliseconds` value won't match).
