### ISSUE TITLE
[Data Grid] changing rowModesModel while having treeData expanded collapses all rows

### ISSUE THREAD

**Issue by JohnMusleh** [mui/mui-x#11934]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/mui-data-grid-premium-toggle-edit-with-tree-data-collapse-bug-kp3s3t

I noticed that this bug happens **only** when providing `getTreeDataPath` as a function defined inside the render function 

when wrapping getTreeDataPath in a useCallback with no dependencies or when defining the function outside the component, the bug does not happen

Steps:
1. expand the first row 
![image](https://github.com/mui/mui-x/assets/17234162/9d620ef4-a4a0-4d7e-97a6-45eba7bb0ef3)

2. click on toggle edit at the top

### Current behavior

The table cells become editable but the expanded row collapses.
![image](https://github.com/mui/mui-x/assets/17234162/d670a3f6-06c6-42a8-9841-f2c0873cdeb1)

### Expected behavior

The table cells to become editable but keep the expanded rows state

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browser: chrome
System:
    OS: macOS 14.2.1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 121.0.6167.139
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react: 11.8.1 => 11.8.1 
    @emotion/styled: 11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.70 
    @mui/material: 5.4.4 => 5.4.4 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/styles: 5.6.1 => 5.6.1 
    @mui/system:  5.14.0 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.7 
    @mui/x-data-grid:  6.10.2 
    @mui/x-data-grid-premium: 6.10.2 => 6.10.2 
    @mui/x-data-grid-pro:  6.10.2 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^17.0.0 => 17.0.38 
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    styled-components: ^5.3.3 => 5.3.3 
    typescript: 4.4.4 => 4.4.4 
```
</details>

**Search keywords**: treeData getTreeDataPath rowModesModel
**Order ID**: 71840

**Comment by michelengelen** [comment]
This is technically not a bug, but expected behavior from react. With every state change inside the wrapping component (in you case the `isEditing` state) the component will rerender. And since the `getTreeDataPath` is being re-initialized on each render it will receive a new signature and will be handled as if it is a newly created function.

As a consequence the grid will rerender with the initial data and all nested tree items closed.

As you already figured out this can be prevented when using the `useCallback` hook or simply by defining it outside of the component.

There is a section about how and when to use `useCallback` on the official react docs: [Skipping re-rendering of components ](https://react.dev/reference/react/useCallback#skipping-re-rendering-of-components)
