### ISSUE TITLE
[data grid] Is there a way to use the onClick function of GridToolbarColumnsButton on other component?

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#11998]
### The problem in depth

Currently, we are using the GridToolbarColumnsButton inside the MenuItem.  When using the mouse event, clicking the menu item using the mouse, we can see the columns option. But when we press enter, it doesn't work. **_Is there a way to access or to use the onClick() functionality of GridToolbarColumnsButton?_**

<img width="125" alt="image" src="https://github.com/mui/mui-x/assets/24405994/9d7c56c0-ea79-4bdb-90da-7d937d827e61">

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Menu, MenuItem, Button, GridToolbarColumnsButton
**Order ID**: 33625

**Comment by michelengelen** [comment]
This is not possible out of the box, but what you can do is build a custom component that uses the behavior of the `GridToolbarColumnsButton`. That way you would have more control over what triggers you want to apply.

This is the default `onClick` handler from the original component

https://github.com/mui/mui-x/blob/fe3d3f8d8c4daf346bbd191ce67633f3e0e80be2/packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx#L32-L47

When you can provide us with a minimal working example in codesandbox we could help you a little better.

**Comment by simbahandiane** [comment]
@michelengelen I'll try to apply your suggested implementation, if not, I'll try to create a sample codesandbox for this.

**Comment by simbahandiane** [comment]
@michelengelen I have created a sample codesanbox. See this [link](https://codesandbox.io/p/sandbox/awesome-margulis-6sqdvy?file=%2Fsrc%2FDemo.tsx%3A83%2C62) for the sample implementation.

**Comment by michelengelen** [comment]
Ok, thanks for the example ... it is due to the fact, that the `MenuItem` is catching the onClick event and since there is nothing defined there it will just not work. This is working 
as intended. The `MenuItem` component is meant to be used as the button. 
Your best option would be to just pass the Buttons directly to the `MenuList` component and then arrange them correctly. This is not ideal, but the best option right now.
On the other hand: If you feel this should be made a feature please feel free to open a ticket on the material-ui repo [here](https://github.com/mui/material-ui/issues/new/choose).

**Comment by simbahandiane** [comment]
@michelengelen your suggestion works fine on my end, hence closing this item. Thank you!
