### ISSUE TITLE
[charts] series prop information is missing in PieChart API page

### ISSUE THREAD

**Issue by andy-root** [mui/mui-x#12020]
### Related page

https://mui.com/x/api/charts/pie-chart/

### Kind of issue

Missing information

### Issue description

Is the PieChart API reference up to date? I'm getting errors that I'm missing the series prop but the API documentation does not list a series prop.  

### Context

Learn the API for PieChart.

**Search keywords**: PieChart

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @andy-root ... thanks for pointing that out. It is indeed missing in the API docs.
If you look at the examples (e.g. [here](https://mui.com/x/react-charts/pie/)) You can see that the `series` prop is essential, since it is the prop to pass in you data to show in the chart.

I will add this to the Charts board so that we can fix this! Thanks again! 🙇🏼
