### ISSUE TITLE
[question] [DataGrid] updateRows method changing order of Rows

### ISSUE THREAD

**Issue by ojhamohit** [mui/mui-x#12065]
### The problem in depth

For updating details of a row, we are using `apiRef.current.updateRows` method.
But after update the order of Rows get changed.This behaviour is seen only for the rows which dont have tree data.

https://codesandbox.io/p/sandbox/affectionate-pine-lds5vl?file=%2Fsrc%2FDataGrid.tsx%3A252%2C10

### Your environment

System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1
    Memory: 159.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Managers:
    Gradle: 7.4.1 - /opt/homebrew/bin/gradle
    Homebrew: 4.1.18 - /opt/homebrew/bin/brew
    pip3: 21.2.4 - /usr/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.3 - /usr/bin/gcc
    Git: 2.39.2 - /usr/bin/git
    Clang: 14.0.3 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.13 - /usr/local/bin/docker
  IDEs:
    Sublime Text: 4126 - /opt/homebrew/bin/subl
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 5.1.16 - /opt/homebrew/bin/bash
    Go: 1.19.4 - /opt/homebrew/bin/go
    Java: 17.0.4.1 - /Users/mohit/.sdkman/candidates/java/current/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.2

**Search keywords**: updateRows
**Order ID**: 68529

**Comment by MBilalShafi** [comment]
Hey @ojhamohit, I checked your example and it feels like there's too much unnecessary re-rendering and recomputation going on. That is the reason the order is being updated on setting the rows because the Grid tree is being recomputed and regenerated on every re-render.

According to the [documentation](https://mui.com/x/react-data-grid/performance/#extract-static-objects-and-memoize-root-props), all the non-primitive props like columns, rows, etc. should have stable references and should ideally not be updated during the lifetime of the component for `apiRef.current.updateRows` to work properly.

As a reference, I've added a small [example](https://stackblitz.com/edit/react-rwe3eh?file=Demo.tsx) where on updating a leaf row, the order persists. Could you try updating your code to have stable references for non-primitive props?
