### ISSUE TITLE
[data grid] New DataGrid header style not properly passed to header

### ISSUE THREAD

**Issue by wieseljonas** [mui/mui-x#12122]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Add borderRadius to DataGrid sx prop
2. Watch it not being applied to header

Works with current stable version but not on v7

### Current behavior

<img width="900" alt="image" src="https://github.com/mui/mui-x/assets/1095469/221b0998-c763-4e99-9da9-1928fa3174a1">

### Expected behavior

<img width="892" alt="image" src="https://github.com/mui/mui-x/assets/1095469/e7d7a5f9-0bad-4f6f-9536-be7a235887b6">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: New DataGrid header style not properly passed to header on 'next'

**Comment by MBilalShafi** [comment]
It's because now we have the header rows sticky and have a background behind them to be able to show the rows properly. @romgrk Do you recommend a way to add a border radius to the grid like the image above?

I [tried](https://codesandbox.io/p/sandbox/interesting-babycat-q36q9f?file=%2Fsrc%2FDemo.tsx%3A28%2C29) to add a border radius to the element:
```js
[`& .${gridClasses["container--top"]} [role="row"]`]
```

But it adds on one side which is removed on scrolling as the row's actual size is greater than the viewport. A recommended way would be appreciated. 🙏

**Comment by romgrk** [comment]
The radius needs to be on the main container: https://stackblitz.com/edit/react-gfzbbj?file=Demo.tsx

**Comment by michelengelen** [comment]
Does this fix your issue @wieseljonas ?

**Comment by one-summers-day** [comment]
God bless @romgrk
