### ISSUE TITLE
[data grid] `renderCell params.row` values on an auto-generated grouping row

### ISSUE THREAD

**Issue by nurira** [mui/mui-x#12246]
### The problem in depth

[Link to live example](https://codesandbox.io/p/sandbox/mui-demo-dgyrw9?file=%2Fsrc%2FDemo.tsx)

`params.row.lastName` and `params.row.someOtherProperty` are undefined within the `renderCell` call of an autogenerated grouping row.

I'm trying to render a custom component using other properties on a row model (that don't have their own columns) for a particular column but also want to use that custom render for the grouping row as well.
The problem is that I can't access the row model in the grouping column.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: latest => 11.11.4 
    @emotion/styled: latest => 11.11.0 
    @mui/icons-material: latest => 5.15.11 
    @mui/material: latest => 5.15.11 
    @mui/x-data-grid-generator: latest => 6.19.5 
    @mui/x-data-grid-premium: latest => 6.19.5 
    @types/react: latest => 18.2.60 
    react: latest => 18.2.0 
    react-dom: latest => 18.2.0 
    typescript: latest => 5.3.3 
```
</details>

**Search keywords**: datagrid renderCell grouping
**Order ID**: 72370

**Comment by michelengelen** [comment]
Hey @nurira sry for the late reply. I have been out sick yesterday.

The use case you are explaining is not possible by definition, since the grouping row is auto generated as you already stated. The problem is, that a grouping row is typically grouping multiple rows, so there is no way to determine which row-values should be passed to the grouping row. 

If you need to access other rows value you can follow this example: [groupingColDef prop](https://stackblitz.com/edit/react-y3f8zc?file=Demo.tsx). It is from [this section](https://mui.com/x/react-data-grid/row-grouping/#custom-grouping-column) of the docs.

Let me know if we can assist you with this.

**Comment by flaviendelangle** [comment]
Even for the element being grouped, it is impossible to have it inside a row model because your column could have `valueGetter`

If you have:

```tsx
const columns = [{
  field: 'name',
  valueGetter: (value, row) => `${row.fistName} ${row.lastName}`,
}]
```

And you group by `name`, then we would be totally unable to build a fake row model for your grouping row, because we have no way of knowing that we need to put the content in the `firstName` and `lastName` properties.
