### ISSUE TITLE
Not able to localize date picker for the date filter

### ISSUE THREAD

**Issue by nehabansal90** [mui/mui-x#12288]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Click header menu of any datetime field
2. Click on filter
3. Click on the date picker

### Current behavior

Date picker is not translated as per the localeText provided to data-grid

### Expected behavior

Date picker should be translated as per the localeText provided to data-grid

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: data-grid localization
**Order ID**: 72507

**Comment by shaharyar-shamshi** [comment]
Hello @nehabansal90 if you can provide us with the demo link it would be great help for us to debug

**Comment by LukasTy** [comment]
Hello @nehabansal90, could you clarify your expectation with a code example or confirm if we understand you correctly?
Do you expect the values provided via `localeText` on `DataGrid` to propagate to the `DatePicker` used in the filters? 🤔 

```tsx
<DataGrid
  localeText={/* translations for DataGrid and Pickers */}
/>
```

If that's the case, then it won't and shouldn't work, because it's different packages and we don't have an intention of coupling these packages together.

Instead, you have to change your approach and pass relevant translations to the respective components:
- `DataGrid` translations on the `DataGrid` component
- `DatePicker` translations on the `LocalizationProvider` or `DatePicker` component

```tsx
<LocalizationProvider
  localeText={/*translations for Pickers */}
>
  <DatePicker />
</LocalizationProvider
...
<DataGrid
  localeText={/*translations for DataGrid */}
/>
```

P.S. The only option to provide localization text in one place is [using the theme](https://mui.com/x/react-data-grid/localization/#locale-text).

**Comment by LukasTy** [comment]
Could you provide a minimal reproduction example in a StackBlitz, CondeSandbox, or a repository?
Which part (how high up the component tree) of the app is wrapped in a `LocalizationProvider`?

**Comment by LukasTy** [comment]
@nehabansal90 I can see that the column is correctly translated:
![Screenshot 2024-03-04 at 16 54 09](https://github.com/mui/mui-x/assets/4941090/de65c52c-ab8d-4925-a434-f112f38ac5ed)

Are you referring to the filter field?
![Screenshot 2024-03-04 at 16 55 52](https://github.com/mui/mui-x/assets/4941090/313bf45a-9396-4146-b155-77594114421b)
If that's the case, then please follow https://mui.com/x/react-data-grid/custom-columns/#date-pickers for a complete setup example.
You are missing the code that replaces the `date` filter with a custom component as well. 😉 

P.S. Does the sandbox have the correct package versions?
If yes, is there any particular reason you are using `@mui/x-data-grid` on v5 and `@mui/x-date-pickers` on v6? 🤔
