### ISSUE TITLE
[data grid] styling disappears on pinned columns in v7.0.0-beta.5

### ISSUE THREAD

**Issue by rajat-brunel** [mui/mui-x#12313]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/inspiring-shadow-cprc2c?file=%2Fsrc%2FDemo.js%3A20%2C36

Steps:
1. Followed the styling tutorial from here: https://next.mui.com/x/react-data-grid/style/#styling-rows
2. Followed the pinned tutorial from here: https://next.mui.com/x/react-data-grid/column-pinning/
3. Combined them and the styling disappears if a column is pinned and comes back on once it's unpinned.
4. Works as intended on version 6.19.6

### Current behavior

The styling for a row or a cell is disappearing if that specific column is pinned.

![pinned-col-no-styling](https://github.com/mui/mui-x/assets/22956834/9bfb63d6-ed2c-425a-b14e-5b12f2973957)

### Expected behavior

The styling for a row or a cell should still be applied if that specific column is pinned.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: component: data grid feature: column pinning
**Order ID**: 79393

**Comment by michelengelen** [comment]
Hey @rajat-brunel could you please make the sandbox public? It seems to be private.

**Comment by rajat-brunel** [comment]
> Hey @rajat-brunel could you please make the sandbox public? It seems to be private.

Hi @michelengelen sorry yea, it's public now. Here is the link : [https://codesandbox.io/p/sandbox/inspiring-shadow-cprc2c?file=%2Fsrc%2FDemo.js%3A20%2C36](url)

**Comment by michelengelen** [comment]
Hey @rajat-brunel ... I have fiddled around a bit with our striped row example myself and here is what I came up with: [striped rows with pinned columns](https://codesandbox.io/p/sandbox/inspiring-shadow-cprc2c?file=%2Fsrc%2FDemo.js%3A20%2C36)

The change I did was simply targeting the cell classes and not the rows.

One thing though: There is still some leftover background on the pinned cells when hovering a row. This is due to a change in `@next`. 

@romgrk the pinned columns cannot be styled anymore. This seems like a little regression. Could you check that please?

**Comment by rajat-brunel** [comment]
> Hey @rajat-brunel ... I have fiddled around a bit with our striped row example myself and here is what I came up with: [striped rows with pinned columns](https://codesandbox.io/p/sandbox/inspiring-shadow-cprc2c?file=%2Fsrc%2FDemo.js%3A20%2C36)

@michelengelen this link opens up the same code sandbox that's on the original post, Can you please post the one that you had changed ? Thank you.

**Comment by romgrk** [comment]
Here is a simplified example covering the default/hover cases, you can add the selected case following this model: https://codesandbox.io/p/sandbox/proud-rain-82w9pr?file=%2Fsrc%2FDemo.js%3A169%2C1

You need to set the background on the cells, not the rows. You also can't use transparent pinned cells, because there is content behind them. If you want a specific color, you need to blend it yourself or use [color-mix()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix).

**Comment by rajat-brunel** [comment]
Ah okay, I see, I will set the colours on the cells not the row. 
Thank you!

**Comment by michelengelen** [comment]
> > Hey @rajat-brunel ... I have fiddled around a bit with our striped row example myself and here is what I came up with: [striped rows with pinned columns](https://codesandbox.io/p/sandbox/inspiring-shadow-cprc2c?file=%2Fsrc%2FDemo.js%3A20%2C36)
> 
> @michelengelen this link opens up the same code sandbox that's on the original post, Can you please post the one that you had changed ? Thank you.

I am sry ... I did miss the notification for this. Thanks @romgrk for providing a solution ... mine was basically the same! :D

Great to see that we could be of help @rajat-brunel
