### ISSUE TITLE
[data grid] processRowUpdate can return undefined

### ISSUE THREAD

**Issue by pcorpet** [mui/mui-x#12475]
### Steps to reproduce

Link to live example: (https://codesandbox.io/s/prod-bird-8d23gq?file=/src/Demo.tsx)

Steps:
1. double click on the age of any person
2. enter "12"
3. press enter

### Current behavior

The row is moved to the bottom of the DataGrid but still visible.

### Expected behavior

The expected behavior is to have the row vanish (because we filter on rows with age >= 18 in the code).

### Context

In my code, I want that the edition of a given row may result in this row being dropped of the DataGrid view.

The alternative would be to return `undefined` in our processRowUpdate callback. This works however this breaks the types as processRowUpdate prop doesn't accept it in Typescript.

I suggest that the library allows the `undefined` result for processRowUpdate and documents how it will handle this result.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.3.1
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
  Browser:
    Chrome: 122.0.6261.129

```
</details>

**Search keywords**: DataGrid processRowUpdate delete row

**Comment by michelengelen** [comment]
Hey @pcorpet,
The problem you are facing is comparable to a race condition. What happens is:
1. you initially filter out all "minors"
2. by editing a row you initiate the `processRowUpdate` method
  2.1 here a new set of rows will be created and the grid updates
  2.2 when returning the new row from `processRowUpdate` it gets "re-added"

Thats why returning `undefined` would basically work.

Is there a strong reason you definitely need to actively remove the rows, or would filtering them also work?

**Comment by pcorpet** [comment]
In my process the row is representing a server config that is actually deleted, so keeping them filtered doesn't make much sense. It's more logical to indeed get a new set of rows (the new config).

**Comment by michelengelen** [comment]
ok, if i understand that right it should be something like this:

1. get initial set of rows
2. edit some field that will lead to a deletion
3. store it to the server
4. receive new set of rows from server

Would that be what you are trying to achieve?

**Comment by pcorpet** [comment]
yes exactly

**Comment by michelengelen** [comment]
In that case you should store the updated row to your server in the `processRowUpdate` method. The server then deletes that row (or removes it from the response) when refetching the rows. Are you manually refetching the rows or are you somehow connected to a webhook?

**Comment by michelengelen** [comment]
cc @MBilalShafi ^^

**Comment by pcorpet** [comment]
> In that case you should store the updated row to your server in the `processRowUpdate` method. The server then deletes that row (or removes it from the response) when refetching the rows. Are you manually refetching the rows or are you somehow connected to a webhook?

Sorry I wasn't clear: this is already what I do. My processRowUpdate is sending the change on the server (I use a mutation with the react-query framework). The server gets updated and my components properly gets the new list of rows to display (without the deleted row). What I'm stuck on is:
- if I return anything from processRowUpdate (after having sent the update to the server), then this row is kept despite the change of rows
- if I return `undefined`, I get the behavior that I want but a Typescript error.
So I'm suggesting to update the typing of `processRowUpdate` to accept an `undefined` value as a valid return and document it. What do you think?

**Comment by michelengelen** [comment]
>   So I'm suggesting to update the typing of `processRowUpdate` to accept an `undefined` value as a valid return and document it. What do you think?

WDYT @mui/xgrid? Would something like that a viable way to remove a row from the internal state as well?

**Comment by MBilalShafi** [comment]
@pcorpet The standard way to delete a row is to pass an `_action: 'delete'` property along with the row as explained in this section: https://mui.com/x/react-data-grid/row-updates/#the-updaterows-method

The `processRowUpdate` also [uses](https://github.com/mui/mui-x/blob/a5d834636de66890c600c2c9d5d67a0b35b9b831/packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts#L530) the `updateRows` method under the hood, which is better than updating rows or using the `setRows` method because of [this](https://github.com/mui/mui-x/issues/210#issuecomment-1006411492) reason.

I tried to accommodate this in your example, here's the updated example: https://stackblitz.com/edit/react-ofzdlv?file=Demo.tsx

Could that be a possible solution for you?

**Comment by pcorpet** [comment]
OK, that sounds perfect to me. Can you change the type of `processedRowUpdate` to be:
```ts
type ProcessedRow<T> = T & { _action?: 'delete' }
...
processRowUpdate: (oldRow: T, newRow: T) => ProcessedRow<T> | Promise<ProcessedRow<T>>
```
That would make it clear from the typing that DataGrid takes the `_action` into account while not requiring our app to do some casting.

**Comment by michelengelen** [comment]
Hey @pcorpet I am not sure how your implementation looks like, but I just tried this and the Props correctly infers the correct type to return for `processRowUpdate`. This is the very basic example i used:

```tsx
import * as React from 'react';
import { DataGridPremium, DataGridPremiumProps } from '@mui/x-data-grid-premium';

type RowTemplate = {
  username: string;
  age: number;
};

const columns = [{ field: 'username' }, { field: 'age' }];
const rows: RowTemplate[] = [
  { username: 'alice', age: 40 },
  { username: 'bob', age: 30 },
  { username: 'carol', age: 20 },
];

export default function BasicExampleDataGrid() {
  const processRowUpdate: DataGridPremiumProps<RowTemplate>['processRowUpdate'] = (_, newRow) => ({
    ...newRow,
    _action: 'delete',
  });

  return (
    <div style={{ height: 400, width: '100%' }}>
      <DataGridPremium<RowTemplate>
        columns={columns}
        rows={rows}
        checkboxSelection={true}
        processRowUpdate={processRowUpdate}
      />
    </div>
  );
}
```

I am not getting any typescript errors.

Maybe this is due to the fact that the type passed into the DataGrid component get extended from `GridRowModel` 🤔 

<img width="724" alt="Screenshot 2024-04-03 at 14 41 37" src="https://github.com/mui/mui-x/assets/32863416/bea4d54c-d076-4620-8c3b-3f2d7241c966">

@MBilalShafi correct me if I am wrong here! :face_with_peeking_eye:

**Comment by MBilalShafi** [comment]
> Maybe this is due to the fact that the type passed into the DataGrid component get extended from GridValidRowModel 🤔

Exactly. Thank you for the updated example @michelengelen. Since `R` always extends `GridValidRowModel` it allows adding more keys to the row model, including `_action`. It does work though it doesn't enforce strict type-checking which is an intended behavior I believe. I updated the above-attached Stackblitz example just in case.

**Comment by MBilalShafi** [comment]
I see an opportunity to explain this part (row delete during editing) in the [`processRowUpdate` documentation](https://mui.com/x/react-data-grid/editing/#the-processrowupdate-callback) as well, just added a docs label to it.
