### ISSUE TITLE
Density is only working on the column header not rows

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#12481]
### The problem in depth

The density was renamed to sized but when the it's changed it only changes the header not the rows. 

This is a sandbox: https://codesandbox.io/p/sandbox/savingandapplystate-xtc493

### Your environment

Chrome Browser
 
   System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 7.24.2 - ~/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.71
  npmPackages:
    @emotion/react: latest => 11.11.3 
    @emotion/styled: latest => 11.11.0 
    @mui/base:  5.0.0-beta.32 
    @mui/core-downloads-tracker:  5.15.5 
    @mui/icons-material: ^5.15.3 => 5.15.5 
    @mui/lab: ^5.0.0-alpha.159 => 5.0.0-alpha.161 
    @mui/material: ^5.15.3 => 5.15.5 
    @mui/private-theming:  5.15.5 
    @mui/styled-engine:  5.15.5 
    @mui/styles: ^5.15.3 => 5.15.5 
    @mui/system:  5.15.5 
    @mui/types:  7.2.13 
    @mui/utils: ^5.15.4 => 5.15.5 
    @mui/x-data-grid:  6.19.1 
    @mui/x-data-grid-generator: ^6.16.2 => 6.19.1 
    @mui/x-data-grid-premium: ^6.19.1 => 6.19.1 
    @mui/x-data-grid-pro:  6.19.1 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react:  17.0.75 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: latest => 6.1.8

**Search keywords**: Density
**Order ID**: 66765

**Comment by MBilalShafi** [comment]
`getRowHeight={() => 'auto'}` overrides (takes precedence over) the `rowHeight` set by the density prop, because density is also essentially setting the `rowHeight` as mentioned [here](https://mui.com/x/react-data-grid/accessibility/#density-prop)

Commenting out the mentioned line in your example makes the density work fine: https://codesandbox.io/p/sandbox/savingandapplystate-xtc493

Could that possibly work for you?

**Comment by lisaWriteJava** [comment]
Yes. Absolutly perfect. Thank you.
