### ISSUE TITLE
[charts] How to avoid  component overflow when using composition

### ISSUE THREAD

**Issue by mckelveygreg** [mui/mui-x#12506]
### The problem in depth

We have a bar graph where the significant portion is too small if the range starts at zero. 
We'd like to be able to set the range to -1 of the min, and +1 of the max. Granted, we can calculate those values, but I do not know where to set them?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.3.1
  Binaries:
    Node: 20.11.1 - ~/.local/share/mise/installs/node/20.11.1/bin/node
    npm: 10.2.4 - ~/.local/share/mise/installs/node/20.11.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.129
```
</details>

**Search keywords**: bar, range, min, non zero
**Order ID**: 86237

**Comment by alexfauquette** [comment]
The min/max properties of the y axis should do the job

```
yAxis={[{ min: -1000, max: 6000 }]}
```
https://mui.com/x/react-charts/axis/#axis-sub-domain

**Comment by mckelveygreg** [comment]
Sorry, I didn't realize how easy it was to make a repro from the demo's in the docs! 🎉 
Here is an illustration of my problem: https://stackblitz.com/edit/react-emgvkt?file=Demo.tsx

You'll see that the bars extend above and below the min and the max values. At the very least, I'm looking to adjust the min, so that it is much closer to where our data can show significant changes. So, displaying from 0 does not allow us to see enough change, and setting `min` for the y axis causes the bars to overflow the bottom of the chart.

**Comment by alexfauquette** [comment]
Ho, you're using composition. In that case, you will need to clip the content. We have an helper `<ChartsClipPath />` for that

```jsx
<g clipPath={`url(#${clipPathId})`}>
  /* ... all the element that need to stay in the drawing area ... */
</g>
<ChartsClipPath id={clipPathId} />
```

Here it your example with the fix: https://stackblitz.com/edit/react-emgvkt-1vja5y?file=Demo.tsx

You can refer to the current implementation for more details about what's inside and what's not: https://github.com/mui/mui-x/blob/master/packages/x-charts/src/BarChart/BarChart.tsx


:::
Notice that in our codebase the id is obtained by using `useId()`. The reason is that if you have multiple charts in the same page each chart needs to get a unique id. Otherwise it will be buggy.
:::

**Comment by mckelveygreg** [comment]
Thank you! This is just what I needed, and it seems to be working great
<img width="1011" alt="image" src="https://github.com/mui/mui-x/assets/16110122/85b286b5-3ed5-4bca-915f-6c091fe8d6c6">
