### ISSUE TITLE
[charts] How do I create a draggable Pie Chart?

### ISSUE THREAD

**Issue by ChristianRaoulis** [mui/mui-x#12702]
### The problem in depth

I'm currently trying to move from AntD to MUI Components in my Web App.

In that Web App I've managed to create a [draggable Pie Chart](https://www.jamesalvarez.co.uk/blog/draggable-piechart-js-class/) using AntDs Graph Lib but since I'm planning to remove all AntD components from my Web App I was wondering if MUI-X Charts allows me to create something similar to the above linked pie chart.

Is something like that possible with MUI-X Charts? And if it is, how would I do something like that?

**Search keywords**: Pie Chart
**Order ID**: 85157

**Comment by JCQuintas** [comment]
Hi @ChristianRaoulis, would it be possible to provide some example of your current working code using AntD? Please provide it in an environment like stackblitz/codesandbox so we can give a better answer.

**Comment by JCQuintas** [comment]
As I understand, that is not using `AntDs Graph Lib` nor `react`, but a custom `canvas` drawing algorithm, is that correct?

**Comment by ChristianRaoulis** [comment]
> As I understand, that is not using `AntDs Graph Lib` nor `react`, but a custom `canvas` drawing algorithm, is that correct?

Yes. It takes a bit for me to remove the personal Information from my AntD Version but the example above in pure javascript works just as good.

**Comment by alexfauquette** [comment]
It's technically feasible. But somewhat hard.

Here is a quick demo. The global idea is to control the `data` and create a  subcomponent that based on those data will allow mouse interaction

The last slice requires modifying the `startAngle` too. Plus some edge cases I did not look into.

https://stackblitz.com/edit/react-kipqzp?file=Demo.tsx

If you are interested in this solution we will need to export more internals, because the `SeriesContext` and
`SvgContext` are not supposed to be exported

**Comment by ChristianRaoulis** [comment]
That demo does exactly what I was looking for. I would love to use it in my project 😄 

Is there a chance that the required exports come in an update soon? Or should I use packet patches for now until the  SeriesContext and SvgContext are accessible?

**Comment by alexfauquette** [comment]
Those utils should be available with #12744
