### ISSUE TITLE
[data grid] Context menu in column headers

### ISSUE THREAD

**Issue by trbagley-gresham** [mui/mui-x#12749]
### Summary

Enhanced API for grid header customisation.

### Examples

Related issue:
#6691

### Motivation

We'd like to show the context menu when right clicking on a column header rather than clicking on the menu icon (three vertical dots). This would involve adding an `onContextMenu` event handler to each header which would open the filter panel. A frequent recommendation is to make use of the `renderHeader` property of `GridColDef`; however, this does not give full control over the header as illustrated in the screenshot below:
![grid](https://github.com/mui/mui-x/assets/135860129/cbc6e2e1-1ebc-4e68-9ab9-4eff5da7784b)
If we add an event handler via `renderHeader`, only the coloured sections are clickable as opposed to the entire header.

Are there currently any props which would facilitate this? The closest implementation I have encountered can be seen [in the MUI docs](https://mui.com/x/react-data-grid/components/#cell). If something similar to this is/was available for the header, I think it would address our requirements.

**Search keywords**: grid header customisation
**Order ID**: 45466

**Comment by cherniavskii** [comment]
Hi @trbagley-gresham 
The suggested approach hear would be to pass the `onContextMenu` callback to the `columnHeaders` [slot props](https://mui.com/x/react-data-grid/components/#slot-props):

```tsx
const onContextMenu = React.useCallback((event: React.MouseEvent) => {
  const headerCell = (event.target as HTMLElement).closest(`[role="columnheader"]`);
  if (!headerCell) {
    return;
  }
  const field = headerCell.getAttribute('data-field');
  console.log('Context menu on column header:', field);
}, []);

// ...

<DataGrid
  rows={rows}
  columns={columns}
  slotProps={{
    columnHeaders: {
      onContextMenu,
    },
  }}
/>
```

But it doesn't work because of a bug on our side – we don't pass the `slotProps` to the `columnHeaders` slot in https://github.com/mui/mui-x/blob/ec2df5cb3dbea7d494d36bc27f193d5b55275d64/packages/x-data-grid/src/components/GridHeaders.tsx#L64

Fortunately, you can override the `columnHeaders` to workaround this issue, here is a working demo:
https://stackblitz.com/edit/react-qkbqyt?file=Demo.tsx
Meanwhile, I'll fix the issue on our end.

Is this what you're looking for

**Comment by cherniavskii** [comment]
@trbagley-gresham 

> We'll need to obtain the GridColDef for the column header from which the event was fired. I think we'll be able to achieve this by extracting the value from data-field and looking it up somehow.

[`apiRef.current.getColumn`](https://mui.com/x/api/data-grid/grid-api/#grid-api-prop-getColumn) would do the trick.
