### ISSUE TITLE
[pickers] Datepicker Onchange event is not firing at every keystroke

### ISSUE THREAD

**Issue by stevenbriscoeca** [mui/mui-x#12753]
### Steps to reproduce

Link to live example: (required)
https://github.com/stevenbriscoeca/mui-datepicker-onchange

Steps:
1. Add datepicker into react project : 
```
        <DatePicker onChange={(value, context) => { 
          console.log(context); 
          console.log(value); 
          console.log("onChangeEvent")}} 
        />
```
2. Notice onChange doesnt fire all the time : 
![datepicker-bug](https://github.com/mui/mui-x/assets/3018441/325ca504-1eea-4496-aa4b-764eeb66970c)

For the second input, nothing happens, for the year only after the third character is the event fired

I made a repo with the bug : 
https://github.com/stevenbriscoeca/mui-datepicker-onchange

### Current behavior

onChange events fires after day is added, ignored for month and only the third and fourth character is the even fired

### Expected behavior

It should fire at every time the input value changes

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Chrome latest version
@mui/envinfo@2.0.19
```
</details>

**Search keywords**: Onchange

**Comment by LukasTy** [comment]
@stevenbriscoeca This is by design and is [documented here](https://mui.com/x/react-date-pickers/lifecycle/#on-simple-fields).
In a nutshell, we have decided to fire `onChange` event only when the value changes and incomplete value is `Invalid Date` until all the individual sections are filled.
As you have probably noticed, the `onChange` fires on every section change, when the value is valid.

Is there any specific behavior that requires you to be aware of every key stroke the user has made? 🤔 

P.S. [The native date input](https://stackblitz.com/edit/react-r4efpq?file=Demo.tsx) also has a similar behavior, where `onChange` is not fired on every section selection.

**Comment by stevenbriscoeca** [comment]
That make sense, thanks for the follow up, I actually discussed this with one my colleagues that this is what I thought! So I'll close this thread, thanks!
