### ISSUE TITLE
[tree view] How to have Selectable Tree component

### ISSUE THREAD

**Issue by Aberkati** [mui/mui-x#12802]
### The problem in depth

I want to have a Tree which I can check/Uncheck childrens, please take a look on a [demo that I created before](https://stackblitz.com/edit/bgcued-prxisd?file=src%2Fservice%2FNodeService.jsx)

I've searched on MUIX documentation but did not found a solution
thank you

### Your environment

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD    
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (122.0.2365.106)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.123 
    @mui/core-downloads-tracker:  5.11.15 
    @mui/material: ^5.11.15 => 5.11.15 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/styled-engine-sc: ^5.11.11 => 5.11.11      
    @mui/system:  5.11.15 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @types/react:  18.0.31 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^5.3.9 => 5.3.9

**Search keywords**: TreeView
**Order ID**: 66242

**Comment by michelengelen** [comment]
Hey @Aberkati ... thanks for raising an issue for the tree view.
I think this might be possible with a custom tree item and the controlled selection.
Let me take a look!

**Comment by Aberkati** [comment]
Thank you for your quick reply!
I'm waiting for your reply, big thanks!!

**Comment by michelengelen** [comment]
Hey @Aberkati sry for taking so long ... I could not finish this yesterday.
I did manage to build a custom example that basically does what you showed: [Selectable Tree view](https://stackblitz.com/edit/react-npcmze?file=Demo.tsx)

You can use this example to build a custom TreeItem that includes a Checkbox component as well.

@flaviendelangle could you also have a look and check if this can maybe be improved?

**Comment by flaviendelangle** [comment]
Hi,

This relates a lot to something we are discussing in #11452 (see my last comment https://github.com/mui/mui-x/pull/11452#issuecomment-2009687309)

It's definitely something we want to support out of the box at some point (probably with an opt-in prop).

But in the meantime, a custom implementation is totally doable.

Several thing about your code:

1. `renderCustomTreeItem` changes on each render since `handleSelectedItemChange` is not memoized. Having a slot that changes on each render is a very bad pattern because it means the React component will remount on every render (if you have a state inside your item it will be lost on every render). If you need to pass a props to your slot that will change across render, you should use `slotProps` instead of dynamically creating your slot (you have one instance of this pattern in my example below).
2. If you don't change the structure of your item, you should be able to use `slotProps` [similar to this example](https://mui.com/x/react-tree-view/rich-tree-view/customization/#limit-expansion-to-icon-container)

I built [an example](https://stackblitz.com/edit/react-npcmze-xkpwya?file=Demo.tsx) where the expansion is limited to the icon (just like on the doc example linked above) and the selection selects the children.
Note that we could expose a method that updates the selected items in `apiRef` so that people don't have to control the selection in order to do this change.

**Comment by Aberkati** [comment]
thank you for your reply, but our requirement is exactly like the example I've sent you before, specially the checkbox that select/deselect items...

**Comment by flaviendelangle** [comment]
For the item selection with checkboxes, we are currently working on it in #11452
You could create your own `TreeItem` component (using `useTreeItem2` this time since you are creating a new UI and not change passing some props to the default elements of the UI).

**Comment by michelengelen** [comment]
> Several thing about your code:
> 
> 1. `renderCustomTreeItem` changes on each render since `handleSelectedItemChange` is not memoized. Having a slot that changes on each render is a very bad pattern because it means the React component will remount on every render (if you have a state inside your item it will be lost on every render). If you need to pass a props to your slot that will change across render, you should use `slotProps` instead of dynamically creating your slot (you have one instance of this pattern in my example below).

🤦🏼 I even put the render function into `useCallback` but forgot to do that with the `handleSelectedItemChange` as well ... my bad! :D

> 2. If you don't change the structure of your item, you should be able to use `slotProps` [similar to this example](https://mui.com/x/react-tree-view/rich-tree-view/customization/#limit-expansion-to-icon-container)

I tried, but it did not work ... not sure why though ... might be me making a mistake! Thanks for pointing that out!

---

@Aberkati as mentioned by @flaviendelangle we are working on a solution that supports this OOTB, but you should be able to add a checkbox and perform selection based on our examples, as a workaround until that feature is available.

**Comment by brammitch** [comment]
> Hey @Aberkati sry for taking so long ... I could not finish this yesterday. I did manage to build a custom example that basically does what you showed: [Selectable Tree view](https://stackblitz.com/edit/react-npcmze?file=Demo.tsx)
> 
> You can use this example to build a custom TreeItem that includes a Checkbox component as well.
> 
> @flaviendelangle could you also have a look and check if this can maybe be improved?

I stumbled across this issue while trying to implement a parent/child aware checkbox with indeterminate values, so I thought I'd share a [minimal example](https://github.com/DevalexLLC/mui-tree-parent-child-indeterminate-checkbox-demo) of my solution. I based a lot of it off the examples in the MUI documentation, but it was @michelengelen's bit about passing the `onClickHandler` to a custom `TreeItem2` that helped me solve the last piece of the puzzle.

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/~/fork/github/DevalexLLC/mui-tree-parent-child-indeterminate-checkbox-demo?file=src%2FApp.tsx)

![image](https://github.com/user-attachments/assets/730336e9-7bd4-421b-91c1-c6e0c872a163)
