### ISSUE TITLE
[RFC] Expose a sort of ActionMap or ActionReducer/EventReducer prop which let you customise actions

### ISSUE THREAD

**Issue by dtassone** [mui/mui-x#1302]
This prop would facilitate customizing action with events and overriding the default behaviour.
At the moment, it's quite cumbersome to customise the event with action such as  selection on click or edition on double click

The idea is to provide a map or a reducer that let's customize events. 
What if you need to enter edit mode on click and selection on double click. And you don't want to stop editing on blur or on Escape key?

```ts
export function EditCellOnClickGrid() {
  const apiRef = useGridApiRef();

  const handleCellClick = React.useCallback((params: GridCellParams) => {
     apiRef.current.setCellMode(id, field, 'edit');
     event.stopPropagation();
  }, []);

  const handleDoubleCellClick = React.useCallback((params: GridCellParams, event: React.SyntheticEvent) => {
    apiRef.current.setSelectionModel({...});
    event.stopPropagation();
  }, []);

  //Prevent from rolling back on escape
  const handleCellKeyDown = React.useCallback((params, event: React.KeyboardEvent) => {
    if (params.cellMode === 'edit' && (event.key === 'Escape' || event.key === 'Delete' || event.key === 'Enter')) {
      event.stopPropagation();
    }

  }, []);

  // Prevent from committing on blur
  const handleCellBlur = React.useCallback((params, event?: React.SyntheticEvent) => {
    if(params.cellMode === 'edit') {
      event?.stopPropagation()
      ;
    }
  }, []);

  return (
        <XGrid
          {...baselineEditProps}
          apiRef={apiRef}
           onCellClick={handleCellClick}
           onCellDoubleClick={handleDoubleCellClick}
           onCellKeyDown = {handleCellKeyDown}
           onCellBlur = {handleCellBlur}
          }}
        />
  );
}

// With the change
export function EditCellOnClickGrid() {

  // Prevent from committing on blur
  const handleCellBlur = React.useCallback((params, event?: React.SyntheticEvent) => {
    if(params.cellMode === 'edit') {
      event?.stopPropagation()
      ;
    }
  }, []);

  return (
        <XGrid
          {...baselineEditProps}
          apiRef={apiRef}
          actionMap={{
             cellDoubleClick: ['selectCell'],
             cellBlur: [handleCellBlur],  //we would have to pass a function for this one, can use the options.onCellBlur here
             cellClick: ['cellEnterEdit']
             cellEditExitKeyDown: null
          }}
        />
  );
}

```

Few edge cases but I would like to consider this option...

**Comment by oliviertassinari** [comment]
> What if you need to enter edit mode on click and selection on double click. And you don't want to stop editing on blur or on Escape key?

I think that the reducer pattern, [as done in Downshift](https://github.com/downshift-js/downshift#statereducer) could be interesting, to make something generic that allows developers to customize how the data grid handles events. We covered it a bit in #190. It would give a lot of customization flexibility.

However, customization flexibility doesn't seem to be the main concern of this RFC. It seems to be about reducing the boilerplate for common use cases.

- How do we know that this problem is frequent enough to **deserve** custom/simpler API? 
- Why adding boolean options to cover the frequent use cases, as we have done so far, e.g. `singleClickEdit` and the current handler solution not **enough**?

I personally think that we should: 1. start by documenting the current solution. 2. Have developers complain about it in the GitHub issue, 3. then discuss with them how they would like to see this problem better solved. 4. implement the solution that resonates the most with the developer.

**Comment by oliviertassinari** [comment]
An xstate implementation might even make sense https://xstate.js.org/viz/.
