### ISSUE TITLE
[data grid] How to combine particular group cell in data grid

### ISSUE THREAD

**Issue by Arata-Yoshida** [mui/mui-x#13195]
### The problem in depth

When I group only some columns in the data grid header, I want to combine the ungrouped columns and display them in one cell.
The problem is that if I group only some columns, blank cells will be added to the ungrouped columns.

![image](https://github.com/mui/mui-x/assets/167494248/ed06e730-5b3e-401b-ae92-380fe440a6bb)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: data grid
**Order ID**: 86901

**Comment by michelengelen** [comment]
Hey @Arata-Yoshida 
I am almost 100% sure that this is not possible.

This is due to the structure the column headers are rendered with.
As you can see from the screenshot below the group headers are rendered within individual header rows.

<img width="1094" alt="Screenshot 2024-05-22 at 12 25 53" src="https://github.com/mui/mui-x/assets/32863416/775d21ba-af53-4cb6-9f7c-e0facc6a18bd">

<img width="1095" alt="Screenshot 2024-05-22 at 12 26 07" src="https://github.com/mui/mui-x/assets/32863416/6d41344a-5b8e-4d78-9087-fe9b029b1ae5">

Maybe @romgrk knows a way with heavy customization, but I am almost sure that this is not possible. 

@cherniavskii are we planning to support spanning the empty header cells when ungrouped?

**Comment by romgrk** [comment]
I'm not sure if I understand the request correctly, more details would be appreciated, but from what I can understand it doesn't sound doable.

**Comment by Arata-Yoshida** [comment]
I'm sorry, it seems that I haven't been able to properly communicate what I want to do and what the problem is, so I've redrawn the image.
Could you support us how we can solve this problem?

![image](https://github.com/mui/mui-x/assets/167494248/fb91ea14-ccf8-4ad2-99a4-de63b648f65d)

**Comment by romgrk** [comment]
That's not possible with the datagrid. Headers are organized in rows, and we don't support rowspan in the headers.

**Comment by Arata-Yoshida** [comment]
I see. But is there any workaround to achieve the table we want?

**Comment by romgrk** [comment]
You could try to use CSS to heighten the cell and float or negative-margin it at the start of the grid, but that's not something we can support.
