### ISSUE TITLE
[pickers][DateRangePicker] timezones handled incorrectly with `dayjs` when timezone extensions are enabled

### ISSUE THREAD

**Issue by oskarkk** [mui/mui-x#13290]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/mui-daterangepicker-error-zphn44

Steps:
1. In the date "04/29/2024" change "29" to e.g. "1" or "2" using keyboard (not clicking in calendar)
2. Error: "MUI X: The timezone of the start and the end date should be the same."

Sometimes it works, maybe depending on the initial value. 

### Current behavior

The error appears only when using dayjs timezone extensions (`dayjs.extend(timezone); dayjs.extend(utc);`).

When I put a breakpoint on [this line of code](https://github.com/mui/mui-x/blob/36e6179a96702d0ec1748b501678e542bf64090b/packages/x-date-pickers-pro/src/internals/utils/valueManagers.ts#L66) (rangeValueManager.getTimezone) I can see that one date has a timezone "system" and the other "Europe/Warsaw" (my system timezone), and that raises an exception. 

### Your environment

x-date-pickers-pro 7.5.1
material 5.15.14
(see codesandbox)

**Search keywords**: DateRangePicker timezone dayjs

**Comment by michelengelen** [comment]
Hey @oskarkk and thanks for raising this issue.
I can confirm this bug on my local instance.

Let me have a look at what might be going wrong here.

**Comment by michelengelen** [comment]
Ok, this happens because the value will be updated with a new timezone on change.
@LukasTy I will have a deeper look tomorrow to fix this. 👍🏼

**Comment by michelengelen** [comment]
OK, I found the issue after a bit of a search around the valueManagement and state.
The problem is with this method: https://github.com/mui/mui-x/blob/70090bf79f4281b9c425e60f857628ddd3c71e39/packages/x-date-pickers-pro/src/internals/utils/valueManagers.ts#L59-L70

When we change one value it gets set to the local timezone (using `value.local()`) and with that it receives the new timezone. As I see it we have 2 options:
1. allow 2 different timezones in the values
2. when changing one value we need to update the timezone on the second value as well.

IMHO we should go for the 1. option, since it will allow for ranges that span multiple timezones. Not a very widely used case, but it can still happen (e.g. in planning software)

WDYT @mui/explore ?

**Comment by LukasTy** [comment]
@oskarkk could you elaborate a bit more about your use case?
I see that you are using `timezone` and `utc` plugins, but the `dayjs` call to create days is the regular one, not `dayjs.utc` or `dayjs.tz` as [documented here](https://mui.com/x/react-date-pickers/timezone/#usage-with-day-js).

As I see it, everything is handled correctly, when the bound values are created with appropriate functions.
If you have a concrete example for a situation, that @michelengelen described, we can discuss supporting multiple timezones for values, but that's not a bug, but a feature request. 🤔

**Comment by oskarkk** [comment]
I would say that the timezones are not different, they're the same timezone, as they are (in my case) "Europe/Warsaw" and "system", and my system timezone is "Europe/Warsaw".

My use case was that I had some fields that worked in user timezone, so I didn't have timezone and utc extensions for dayjs. Then I needed some additional fields that would be in a specific timezone, so I added timezone and utc extensions and made some datetime fields with timezone prop. Then the other fields without timezone prop started throwing errors.

> I see that you are using `timezone` and `utc` plugins, but the `dayjs` call to create days is the regular one, not `dayjs.utc` or `dayjs.tz` as [documented here](https://mui.com/x/react-date-pickers/timezone/#usage-with-day-js).

You don't have to set any initial value to reproduce this issue, you can reproduce it with just this (this time with DateTimeRangePicker):

```
dayjs.extend(timezone);
dayjs.extend(utc);

export default function App() {
  return (
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <DateTimeRangePicker slots={{ field: SingleInputDateTimeRangeField }} />
      </LocalizationProvider>
  );
}
```
Somehow without default values the error show less frequently, I have to change the date many times before it breaks. It seems to work without SingleInputDateTimeRangeField (but maybe it's even rarer then).

**Comment by michelengelen** [comment]
@LukasTy on another note:
using it like this breaks it immediately as well

```tsx
const [value, setValue] = useState<[Dayjs | null, Dayjs | null]>([null, null]);
```

it tries to get the timezone form `value.$x?.timezone`, but value is `null` in this case.
I changed the first value via keyboard and the second value is still `null`.

Maybe we need to somehow update both values at the same time when using the single input range field. 🤷🏼

**Comment by LukasTy** [comment]
> You don't have to set any initial value to reproduce this issue, you can reproduce it with just this (this time with DateTimeRangePicker):

@oskarkk could you provide clear steps to reproduce the issue without having any value bound? 🤔 
I tried various ways, but couldn't get it to throw an error... 🤷 

The root cause of the problem is that we are trying to "guess" the timezone of the value, when a `timezone` plugin is present. It forces the whole application to behave in the same way, either working with or without timezone.

> LukasTy on another note:
using it like this breaks it immediately as well

@michelengelen could provide step by step guide on how to cause the error given your example?
I tried it and couldn't reproduce the error. 🙈 🤷

**Comment by michelengelen** [comment]
@LukasTy using this code:
```tsx
import * as React from 'react';
import { Box } from '@mui/material';
import {
  DateRangePicker,
  LocalizationProvider,
  SingleInputDateRangeField,
} from '@mui/x-date-pickers-pro';
import { AdapterDayjs } from '@mui/x-date-pickers-pro/AdapterDayjs';
import dayjs, { Dayjs } from 'dayjs';
import timezone from 'dayjs/plugin/timezone';
import utc from 'dayjs/plugin/utc';

dayjs.extend(timezone);
dayjs.extend(utc);

export default function App() {
  const [value, setValue] = React.useState<[Dayjs | null, Dayjs | null]>([null, null]);

  return (
    <Box justifyContent={'center'} sx={{ width: '100%' }}>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <DateRangePicker
          value={value}
          onChange={setValue}
          slots={{ field: SingleInputDateRangeField }}
          sx={{ '& .MuiInputBase-root': { width: '250px' } }}
        />
      </LocalizationProvider>
    </Box>
  );
}
```

and then changing one of the values in the inputfield via keyboard will trigger that error.

**Comment by LukasTy** [comment]
@michelengelen I have tried the same code before writing a comment and it's strange that for me locally I do not get any error... 🤷 🙈

**Comment by LukasTy** [comment]
@oskarkk Thank you for providing a detailed guide to reproduce the problem. 🙏 
I can confirm that this behavior does not seem appropriate.
The `dayjs` is a bit picky with timezone/utc management, because the setup is global, while `moment` and `luxon` provide a more elegant API, especially for cases like yours. 🙈
