### ISSUE TITLE
[charts][BarCharts] Is there some information regarding the `BarCharts` having accessibility?

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#13359]
### Summary

I see accessibility for the Gauge Charts - 

https://mui.com/x/react-charts/gauge/#accessibility

But is it something that I can expect for the Bar Charts as well?

### Motivation

My PM wants to know about MUI Bar Charts accessibility as I just replaced the ApexCharts component we had with mui charts. 

**Search keywords**: BarCharts Accessibility

**Comment by michelengelen** [comment]
I am almost 100% sure that we are adding a11y features as well to the other charts. I guess Gauge was added since it is one of the easiest to implement.

There are some guidelines on how to make charts accessible in general, so I think this is just a matter of when we are able to get to this.

Is that about right @alexfauquette ?

**Comment by alexfauquette** [comment]
The Gauge has the advantage of being very specific. So as soon as you provide the value and its range, a screen reader can announce it.

For bar it's much more complex, because you can tel lot of stories with this kind of charts. IMHO the most important is not technical, it's to pick colors with great contrast, and put some summary of the chart when possible.

**Comment by michelengelen** [comment]
@noobDev31 what other features would you expect the barchart to have in terms of a11y?

**Comment by noobDev31** [comment]
@michelengelen  I am the wrong person to ask about this one I don't have any experience with accessibility 😅

**Comment by michelengelen** [comment]
In that case: is this resolved for you? :P

**Comment by alexfauquette** [comment]
Then closing in favor of #13113
