### ISSUE TITLE
Issue with Date / Time pickers v5.0.20

### ISSUE THREAD

**Issue by sandeep-dash** [mui/mui-x#13403]
### Steps to reproduce

Link to live example: (https://codesandbox.io/p/sandbox/zealous-mahavira-g4ti1p?file=%2Fdemo.tsx)

Steps:
1. Select the DateTimePicker 
2. Select a date from the calendar
3. Tab and shift focus to the time clock
4. Press 'Enter' key to make the time selection on the clock
5. The 'Enter' key does not make the time selection
6. Selecting the 'Esc' key selects the time selected by the user

### Current behavior

Steps:
1. Select the DateTimePicker 
2. Select a date from the calendar
3. Tab and shift focus to the time clock
4. Press 'Enter' key to make the time selection on the clock
5. The 'Enter' key does not make the time selection
6. Selecting the 'Esc' key selects the time selected by the user
7. User is also able to save a future date via Keyboard even when future dates are disabled

### Expected behavior

User should be able to select a time via keyboard using the 'Enter' key instead of the 'Esc' key

### Context

What we are trying to accomplish is resolve 508 accessibility compliance issues. These are a must for web based applications in USA and other countries as well. Not being able to solve this issue poses a serious challenge in delivering a bug free web application

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DateTimePicker 508 compliance keyboard issue

**Search keywords**:

**Comment by LukasTy** [comment]
Hello @sandeep-dash, thank you for creating this issue.

Let me start by saying that we already have an issue (https://github.com/mui/mui-x/issues/9636) for adding the keyboard selection in TimeClock. So, if that's the only problem, it looks like the issue is a duplicate. 🤷 

As mentioned in the linked issue, you can use the [DesktopDateTimePicker](https://v6.mui.com/x/react-date-pickers/date-time-picker/) if you'd upgrade to v6, which has a different behavior intended mostly for the desktop use.

A side note: v5 is [no longer maintained](https://mui.com/x/introduction/support/#supported-versions), if you wish to get any bug fixes, consider upgrading [to at least v6](https://mui.com/x/migration/migration-pickers-v5/), but preferably [to v7](https://mui.com/x/migration/migration-pickers-v6/). 😉
