### ISSUE TITLE
[data grid] Lazy loading details when using Master detail feature

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#13437]
### Summary

If users don't have the data for the details locally, fetching details for each row happens when DataGrid is loaded without users querying for the details.

### Motivation

If users don't have the data for the details locally, fetching details should happen on demand for performance reasons.

## Live reproduction case

https://stackblitz.com/edit/react-zru5se-ssomts?file=Demo.tsx,package.json 

**Search keywords**: lazy loading master detail

**Comment by cherniavskii** [comment]
A few comments on this demo:
- Did you consider loading the data in the detail panel content component itself?
- The `getDetailPanelContent` prop should not define the component inline, because for React this means that a different component is rendered every time, so it will unmount/mount it instead of just updating it. Here's a [simple working example](https://stackblitz.com/edit/react-kcpptm?file=Demo.tsx) where you can see the `DetailPanelContent` component that is defined once, and then being used in the `getDetailPanelContent` function. The data loading is done in `DetailPanelContent` (so only when it's mounted).

I've also forked your demo and applied the points above: https://stackblitz.com/edit/react-zru5se-fxsghf?file=Demo.tsx,package.json
You can see the `MovieDetails` component that handles the data fetching.

**Comment by joserodolfofreitas** [comment]
Alright, that solves the issue. Perhaps we can make it into a recipe. Thanks, @cherniavskii!

**Comment by cherniavskii** [comment]
> Perhaps we can make it into a recipe

Opened https://github.com/mui/mui-x/pull/13453
