### ISSUE TITLE
[data grid] Row grouping from server side data fetch

### ISSUE THREAD

**Issue by kishanp1412** [mui/mui-x#13466]
### The problem in depth

i have some server side data like one object have list of object so i want to make row grouping on the object that will shows the related list of object in datagrid , it can be possible ?
data is like:

```
[
  {
    part_number:"xyz",
    limitation:[
      {based:"abc"},
      {based:"pqr"},
    ]
  },
  {
    part_number:"efg",
    limitation:[
      {based:"abc"},
      {based:"pqr"}
    ]
  }
]
```

now need to row grouping on the part number like xyz after expand show all list of limitations ? need some help to improve this 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Row grouping server side
**Order ID**: 88101

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by kishanp1412** [comment]
the issue is need to do this in datagrid 
![image](https://github.com/mui/mui-x/assets/171536761/fdcd7878-ef72-49d1-aed5-79f25b4cfca3)

**Comment by michelengelen** [comment]
It sounds like what you're looking for isn't quite a bug report, new feature request, or an issue caused by a recent update. Instead, it seems you have a specific implementation in mind!

While we'd be happy to assist where we can, a live code example would be incredibly helpful for us to understand your request clearly (think of it like showing us the puzzle pieces!).

If you're unable to provide a code snippet, joining our [official Discord server](https://mui.com/r/discord/) or asking the community on [Stack Overflow](https://mui.com/x/introduction/support/#stack-overflow) might be a great way to find solutions!
