### ISSUE TITLE
Date range picker selecting future date reset the value

### ISSUE THREAD

**Issue by arjaym-dev** [mui/mui-x#13535]
### The problem in depth

[Click this to see the demo of the said behavior](https://codesandbox.io/p/sandbox/mui-x-question-mgqd8c?file=%2Fsrc%2FDemo.js%3A13%2C11)

## Step to produce the said behavior:
- Select from and to date e.g; Jun 19 - Jun 20
- After selecting from and to date. Now select Jun 21

You'll notice that the from date become Jun 21, then the to date is don't have value. Is there any solution or options for that ?

## My workaround solution
- On onchange of daterange the value return the date in way of ['datefrom','dateto'] i have a condition of if dateto is null or typeof object on my case i make it the dateFrom value as is what its prev value then the dateTo value get the one that i select.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: date range picker, reset value, future, selecting future date
**Order ID**: 70493

**Comment by LukasTy** [comment]
Hello @arjaym-dev, your described behavior looks like a general rule that is common among most if not all date range pickers.
Here are the examples (in no particular order, just some unordered result from a google search), which are behaving the same:
- https://www.google.com/travel/flights
- https://www.daterangepicker.com/
- https://nextui.org/docs/components/date-range-picker
- https://rsuitejs.com/components/date-range-picker/
- https://ant.design/components/date-picker
- https://material.angular.io/components/datepicker/overview#date-range-selection
- https://react-spectrum.adobe.com/react-aria/DateRangePicker.html

Could you describe you expected behavior in more detail?
P.S. Your linked `codesandbox` is not accessible (probably set to private).

**Comment by arjaym-dev** [comment]
Hello @LukasTy i've already update the link to public you may be able to view it now. Thanksss

**Comment by LukasTy** [comment]
@arjaym-dev Thank you for making the codesandbox public, but it still unclear what is your expected behavior.
What do you think is lacking from the component side?
Your commented code causes UX issues—users are basically no longer able to reset the range without other external means.
Also, as shown in the other examples—it seems that most if not all other range picker components are behaving in the same way as `@mui/x-date-pickers-pro`.
