### ISSUE TITLE
[license] I just bought a new license and got a new license key, but I don't want to change my previous key.

### ISSUE THREAD

**Issue by Hanqing1234** [mui/mui-x#13571]
### The problem in depth

I have a different key compared to my last key. I don't want a new license key because I can't change my code. My support key is 92886

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: license key

**Comment by michelengelen** [comment]
Hey @Hanqing1234 why can't you change your code?
So there are 2 things to note here:
1. If you have a valid key it should be no problem, since the key is valid for versions that got released before your license expires.
Example: If your license expires 07/01/2024 any version that gets released up until 06/31/2024 is valid for you to be used in production.
2. You only need a new license key if you want to make changes on your code
So, you need to change your code if you intend to use new versions, but don't need to if you are fine with the current version of it.

**Comment by Hanqing1234** [comment]
Hi Michel,

Thanks for your reply. I totally understand what you mean, my current
situation is:

1. I can't change my code because my project is delivered to a company.
It's hard for me to change anything that the code is actually owned by that
company.
2. My last license key has expired, and I got a new valid license key
yesterday. Since I can't change the code which means I can't change my
expired license key to the new license key.

What I want is: make my last license key (has expired) be valid again. So
that I don't need to change any code.

I can provide my last license key if you need it.

Looking forward to hearing from you.

Kind regards,
Hanqing

**Comment by michelengelen** [comment]
Thats simply not possible and for the beforementioned reasons it should not pose a problem if you are not changing anything on the code.
So as long as the company that now uses the code does not change the code related to the Mui X products you have nothing to worry about. It will work as before.
cc @joserodolfofreitas
