### ISSUE TITLE
[question] Can you help me adding code for the ticket https://github.com/mui/mui-x/issues/13298

### ISSUE THREAD

**Issue by sarthak-sit** [mui/mui-x#13630]
### The problem in depth

I have earlier raised a request in the below ticket https://github.com/mui/mui-x/issues/13298
I have a pro plan but the solution that was suggested is in premium version, can you help me to add those code changes in my pro version i.e the demo code I have attached can you add code in that.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: mui-datagrid
**Order ID**: 88959

**Comment by flaviendelangle** [comment]
Hi,

I think you can just use the `checkboxColumn` of the example @michelengelen did and use it in your project that uses Tree Data instead of Row Grouping :+1: 
If you struggle to do it, please add a reproduction case on Codesandbox or Stackblitz in the issue you linked, a zip is super hard to work with for us (and comes with security concerns) :+1:
