### ISSUE TITLE
[data grid] I want to apply conditional cell color and cell selection color at the same time 

### ISSUE THREAD

**Issue by mahammahmood** [mui/mui-x#13681]
### The problem in depth

When I select a cell with conditional formatting applied to the date, the cell selection color is not being applied to it.

In the screenshot, when I select the cells, the cells without color have the cell selection color applied, while the colored cells do not. I want to apply conditional cell color and cell selection color at the same time. Is this possible
![Screenshot 2024-06-21 181103](https://github.com/mui/mui-x/assets/115474187/727b194b-c172-4bad-bf7b-32cf20cf1d03)
![Screenshot 2024-06-21 181145](https://github.com/mui/mui-x/assets/115474187/39ae9b76-f74d-467a-a041-4c7037d45a42)

Here is a live demo of my problem.
[Demo](https://codesandbox.io/p/sandbox/nervous-brattain-45ypgk?file=%2Fsrc%2FDemo.tsx%3A77%2C27)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data, Grid, Premium, cell, selection, color
**Order ID**: 91010

**Comment by KenanYusuf** [comment]
Hi @mahammahmood, thanks for providing the demo.

I have forked your example to show how you can change a cell's background color when it is selected https://codesandbox.io/p/sandbox/issue-13681-2p8rhz

One notable change is that instead of applying the background color to a `<Box />` in your `renderCell` function, you should instead use the `getCellClassName` prop to apply conditional cell formatting. See the [styling docs](https://mui.com/x/react-data-grid/style/#styling-cells).

Hope this helps solve your issue, let me know if you have any further questions on this.
