### ISSUE TITLE
[question] Is it possible to add a column header in the row on a new "line"?

### ISSUE THREAD

**Issue by sanlee13** [mui/mui-x#13699]
### The problem in depth

I have data gird where I need to display some notes as column. But what I'm looking for is something like this:
![image](https://github.com/mui/mui-x/assets/114650117/e25de3ff-0fa0-4b86-ab0f-371134ded631)

As you can see rows 2 and 3 are really one row where the notes are being displayed on a new line.

Thanks for your time.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: add a column header in the row on a new line
**Order ID**: 82571

**Comment by KenanYusuf** [comment]
Hi @sanlee13, I think this would be a good use case for the [master detail functionality](https://mui.com/x/react-data-grid/master-detail). 

Here's a Codesandbox I created based on your screenshot: https://codesandbox.io/p/sandbox/adoring-bird-vlfpsv

If you need the notes to be visible by default you can set that as I have in the initial state:
```tsx
initialState={{
  detailPanel: { expandedRowIds: rows.map((row) => row.id) },
}}
```

Hope this helps.

**Comment by sanlee13** [comment]
Hey @KenanYusuf, sorry for my later reply. I have checked out your example, but it isn't what I'm looking for, I am already using master detail for my gird.
It's something like this https://codesandbox.io/s/nostalgic-mendel-zy659t when I open the master detail, I display my custom details. As you can see the notes is a column in the gird that I am trying to display on the next line of the same row as show in the above screenshot.

**Comment by KenanYusuf** [comment]
Hi @sanlee13

If you need to display the full note, you could try using [dynamic row height](https://mui.com/x/react-data-grid/row-height/#dynamic-row-height) so that the text content does not get truncated.

There is another option, but it comes with a lot of caveats. You could create a new row for notes, and use the [column spanning](https://mui.com/x/react-data-grid/column-spanning/) feature to span the note across multiple columns. The downside to this is you cannot use column sorting, filtering, reordering, pinning or hiding with this approach as none of these features are supported alongside column spanning. Here is a CodeSandbox example: https://codesandbox.io/p/sandbox/13699-note-spanning-all-columns-pgdw62
