### ISSUE TITLE
AM/PM Behavior in the Calendar control

### ISSUE THREAD

**Issue by developingjames** [mui/mui-x#13693]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/compassionate-firefly-vs9597

Steps:
1. Click on the calendar icon
2. Hover over AM/PM
3. Note the presence of the scrollbar for the AM/PM column when it is not necessary.
4. Click PM
5. Note that the dialog immediately closes

### Current behavior

When hovering over the AM/PM Column a vertical scrollbar appears when it is not necessary to scroll.

When clicking either AM or PM, the dialog is closed.

### Expected behavior

Do not show a vertical scrollbar when hovering over the AM/PM column.

Do not close the dialog when I select AM/PM. Instead rely on the OK button to close the dialog. I may want to pick PM for the current day and then my time.

### Context

I was trying to pick a time 2 minutes into the future of the current day for testing a schedule feature in our application when I noticed the behavior. The time was 3:00 pm EDT and I wanted to select 3:02 pm. It was my first time using the control and I picked PM before going to select the time.

I tested in:
Chrome Desktop Version 126.0.6478.114 (Official Build) (64-bit)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.13.1 - ~\AppData\Local\fnm_multishells\19804_1719846675017\node.EXE
    npm: 10.5.2 - ~\AppData\Local\fnm_multishells\19804_1719846675017\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.81)
</details>

**Search keywords**: Calendar AM PM Scrollbar

**Search keywords**:

**Comment by LukasTy** [comment]
Hello @developingjames
Thank you for creating this issue and using the Pickers package. 🙏 

For the meridiem section behavior, there is already an issue (https://github.com/mui/mui-x/issues/9310) and a proposal to do just what you are suggesting (set `closeOnSelect={false}` by default).
P.S. You can do it on your end to get this behavior now. 😉 

As for the scrollbar on the meridiem section—the extra height is necessary because of a design decision to scroll the selected section to the top of the container.

I'm closing this issue as a duplicate.
If you think there are still problems with it—feel free to reopen it, comment, or create a new issue. 😃
