### ISSUE TITLE
[pickers] [field components] Unexpected behavior when updating input with key controls

### ISSUE THREAD

**Issue by xxKeefer** [mui/mui-x#13731]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/cool-rumple-ktjvr7

Steps:
1. select the day section, ie the number of the day
2. use keyboard controls, (arrow up / arrow down) to change the day.
3. notice weekDay section remain the same.
4. decrement the day with arrow down until roll over occurs (ie: decrement from 01)

### Current behavior

changing the day section has no effect on either the weekDay or Month sections

### Expected behavior

1. changing the day section would automatically update the weekDay section to remain accurate
2. decrementing from day = 1 would update the weekDay section, and decrement the month section
3. incremnting the last day of a month would update the weekDay section, and increment the month section

### Context

the ui I am build allows for user to seek through data over time, it is surprising to try and seek backward or forward at the edge of a month and remain in the same month. It is also jarring not to see the day name change, it feel broken to see the date change but the day name remain the same

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.87)
  npmPackages:
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
```
</details>

**Search keywords**: mui-x-date-picker field-components
**Order ID**: 89424

**Comment by LukasTy** [comment]
Hello, @xxKeefer.
Thank you for creating this issue. 🙏 
The current behavior is intentional and has been changed from your described one to cater for a11y (screen reader) support.
Please find more information here: https://github.com/mui/mui-x/issues/7934, https://github.com/mui/mui-x/issues/8189#issuecomment-1462450320.

We have been debating an option to add read-only sections, which would update to reflect the changed data.
But such an option could only be possible with the new [accessibleDOMStructure](https://mui.com/x/react-date-pickers/fields/#accessible-dom-structure).
Would such behavior be more clear and beneficial to your use case?

In the meantime, have you considered [adding an adornment with a computed weekday](https://codesandbox.io/p/sandbox/date-field-with-weekday-adornment-skvgjg?file=%2Fsrc%2FDemo.tsx%3A9%2C1) instead of incorporating it into the format? 🤔

**Comment by xxKeefer** [comment]
Thanks for the prompt feedback, i think the input adornment will suffice for the use case we need.
