### ISSUE TITLE
[DataGrid] columnSortedAscendingIcon is not working

### ISSUE THREAD

**Issue by nataliehanisch** [mui/mui-x#13782]
### Related page

https://mui.com/x/api/data-grid/data-grid#:~:text=columnSortedAscendingIcon

### Kind of issue

Unclear explanations

### Issue description

I would like to be able to use a custom icon for the sorting button, however `columnSortedAscendingIcon` and `columnSortedDescendingIcon` are listed as props in the documentation for MUI X v7.9.0, however they do not work locally when I have tried to use them, e.g.

```
<DataGrid
  ...
  columnSortedAscendingIcon={() => <CustomIcon />}
/>
```

**Search keywords**: columnSortedAscendingIcon, DataGrid

**Comment by arminmeh** [comment]
Hi @nataliehanisch 
`columnSortedAscendingIcon` and `columnSortedDescendingIcon` are indeed slots that can be used to render a custom component in the grid
You are having an issue because you are passing these as regular props instead through `slots` prop. Check [this page](https://mui.com/x/react-data-grid/components/#component-slots) for more information about slots and the option to pass props to your custom component
