### ISSUE TITLE
[pickers] Change of locale adapter import for moment.js

### ISSUE THREAD

**Issue by DanoBroz** [mui/mui-x#13805]
https://github.com/mui/mui-x/blob/d3fad51e98ced81b36c6acea441ffb677169a646/docs/data/date-pickers/adapters-locale/adapters-locale.md?plain=1#L96

There's been an update with moment.js and importing locale adapters. Now you have to import it from the dist folder `import 'moment/dist/locale/de'`
https://github.com/moment/moment/issues/2962

**Search keywords**:

**Comment by LukasTy** [comment]
@DanoBroz Could you provide a reproduction example for this case?
The documented import works without problems in our docs (`Next.js` app), `StackBlitz`, `CodeSandbox` and I've tried it locally on a `create-react-app` setup for good measure.
In all of those cases, there are no problems with locale import. 🤷 

IMHO, those who have a problem importing the locale experience it because of their environment setup issues.
Do you have issues with it? 🤔
