### ISSUE TITLE
[data grid] Cell stealing focus from modal and onClicks for buttons rendered inside cells fire when the user hits the enter key

### ISSUE THREAD

**Issue by RyleySill93** [mui/mui-x#13824]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/interesting-bell-nhwlvx?file=/src/Demo.tsx

Grid cell stealing focus from dialog issue:
1. Click on a button in the grid
2. Try to type into the input in the dialog (or double click the dialog anywhere)
3. The grid cell steals focus from the dialog

Buttons on click is fired when hitting "enter" into the cell it's rendered within:
1. Click in the margins of one of the cells rendering a button to focus that cell
2. Hit enter twice (once to enter the editor, twice to go to the next cell below)
3. Somehow the onClick for the button in the cell is fired

### Context

For the stealing focus issue, I'm rendering a complex modal with many inputs so I don't want to spam `e.stopPropagation()` everywhere - ideally I'd be able to programmatically unfocus the cell when I open the modal so any events happening within the modal aren't forwarded to the cell.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGrid steal focus onClick enter button cell
**Order ID**: 75803

**Comment by romgrk** [comment]
The focus management logic for cells is [here](https://github.com/mui/mui-x/blob/56a6900875aad353bde38ce50340eb7e0f0201df/packages/x-data-grid/src/components/cell/GridCell.tsx#L355-L374). The cell edit stop event runs on `keydown`, and that logic moves the focus to the button in the next cell. The `keypress` event that follows then clicks on the button because the key is `Enter`.

I would suggest running `event.stopPropagation()` on the `cellEditStop` event for those cells. It's a bit messy but cell editing wasn't meant to also have interactive display-mode cells (the buttons).
