### ISSUE TITLE
[tree view][TreeItem] Add support for `href` attribute

### ISSUE THREAD

**Issue by Matt-Butler** [mui/mui-x#13849]
### Summary

I would like to provide a href attribute to the treeitem components. This allows the URL to be displayed on the bottom left before a user clicks on a link. It also ensures that keyboard navigation works as expected.

### Examples

https://mui.com/x/api/tree-view/tree-item/
No href

### Motivation

I want to use the tree view with anchors so that my application is accessible. 

**Search keywords**: treeitem href treeview

**Search keywords**:

**Comment by sohail9744** [comment]
@Matt-Butler  Could you please explain step by step to me about this? I think it falls under a feature or enhancement.

**Comment by michelengelen** [comment]
Hey @Matt-Butler this is currently not available OOTB, but you can always replace the default item with a custom one. Here is a guide on how to do that on the docs: [Headless API](https://mui.com/x/react-tree-view/rich-tree-view/customization/#headless-api)

@flaviendelangle should we maybe add this to the board as a feature request as well?

**Comment by flaviendelangle** [comment]
You can indeed provide a custom `content` slot to your `TreeItem`.
We have some documentation that should be released in the coming months around this topic which is very badly documented for now.
Here is a [basic implementation](https://stackblitz.com/edit/react-n9rtnz?file=Demo.tsx), in the next major we plan to release slots like `itemContent` so that you don't have to create a custom item component for those basic use cases, but the global structure will remain the same (and the example above will still work).
For more info about `TreeItem2`, you can have a look at [this doc section](https://mui.com/x/react-tree-view/#tree-item-components)

As for a OOTB support, I would add a "Waiting for upvote" label, I'm not sure we should support it.

**Comment by Matt-Butler** [comment]
Thanks for getting back to me. I'll check out your recommendation.

**Comment by Matt-Butler** [comment]
Thanks for the info so far. 

I'm seeing that this change does not work with the existing keyboard navigation. 
https://github.com/user-attachments/assets/7b323466-ee11-42a5-bc72-aef229b98bce

I'm also seeing some type errors with typescript(I can fix. I'll share if it helps).

**Comment by flaviendelangle** [comment]
Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

Concerning the TypeScript, you will probably need to cast a `as any` or `as TreeItem2SlotProps['content']`, we don't support well typing when adding new props on a slot for now.
