### ISSUE TITLE
[data grid] Copy and Paste content from origin column cell selection to another column doesn't maintain the sorting set

### ISSUE THREAD

**Issue by rockmsc92** [mui/mui-x#13956]
### The problem in depth

I need a quick support relative to this issue #13703 opened since three weeks.

Thanks for your attention

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: clipboard copy and paste
**Order ID**: 70301

**Comment by michelengelen** [comment]
We appreciate you bringing this to our attention. The issue is already on our radar and we’ll definitely look into it as soon as our schedule allows. We'll see if we can prioritize it, but can't make any promises at this time.

To help us manage our workload effectively, please avoid creating duplicate issues. If you’d like to add more details or follow up on an existing issue, feel free to leave a comment there. Thanks for your understanding!
