### ISSUE TITLE
[DataGridPro] Is it possible to trigger scrollToEnd to the last row on initial load on Datagrid

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#14043]
### Latest version

- [X] I have tested the latest version

### Summary

I have been trying to trigger the scroll to go at the last row of the table on initial load is it even possible to achieve because usually there'd be an API call fetch the data and the apiRef doesn't get triggered until we get the data.

I have tried something on the following Stackblitz link but I was unable to achieve the use case - 
https://stackblitz.com/edit/react-felao9?file=Demo.tsx

### Examples

Couldn't find something like that

### Motivation

Trying to achieve a scrollToEnd on inital load without any event similar to the way we see logs(console output) on Jenkin. 

**Search keywords**: DataGridPro

**Search keywords**:

**Comment by noobDev31** [comment]
Update -  it does happen by using an useEffect with a setTimeout below 
https://stackblitz.com/edit/react-felao9-q1sxdn?file=Demo.tsx

But what i wanted to know is if I can utilize on the apiRef to do the same

**Comment by michelengelen** [comment]
using a setTimeout seems like it should be the best approach for now.
@MBilalShafi do we have another workaround for this use-case?

**Comment by MBilalShafi** [comment]
I guess using `setTimeout` should be fine in most of the use cases. The reason why it doesn't work without timeout is that the `virtualScroller` element is not yet rendered due to which the `scrollToIndexes` results in not _actually_ scrolling to the row.

Another way could be to use an internal event `virtualScrollerContentSizeChange`, but it will fire whenever the virtual scroller content size changes: https://stackblitz.com/edit/react-felao9-qmp5sm

I'm not sure if that could work for you.

**Comment by noobDev31** [comment]
thanks @MBilalShafi and @michelengelen
