### ISSUE TITLE
[pickers] Datepicker loses focus when typing and the dialog changes position on date selection

### ISSUE THREAD

**Issue by martin-trajanovski** [mui/mui-x#14078]
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: (required)

Steps:
1. Create datepicker or datetime picker
2. Add a textField slot
3. The bug is there

Here is a demo: https://stackblitz.com/edit/react-3xdsu7?file=Demo.tsx

### Current behavior

The input loses focus and the dialog jumps or change position on selection

### Expected behavior

The input should not loose focus and the dialog should not jump or change position on selection

### Your environment

MUI v5.16.6
@mui/x-date-pickers v7.12.0

**Search keywords**: datepicker focus

**Comment by LukasTy** [comment]
Hello @martin-trajanovski.
We have documentation on the [recommended usage](https://mui.com/x/react-date-pickers/custom-components/#recommended-usage) of the slots, please check it for more information on how to fix it and why it is happening. 😉 

I'm closing this issue as it is the expected behavior, given the code example.
