### ISSUE TITLE
[data grid] `onRowSelectionModelChange` callback not being called when `rowSelectionModel` changes

### ISSUE THREAD

**Issue by zechuegui** [mui/mui-x#14148]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/s/cranky-blackburn-tk6j9c?file=/src/Demo.tsx:859-876

Steps:
1. Click first cell
2. Click keyboard arrow down

### Current behavior

When I click the first cell with the mouse, the onRowSelectionModelChange callback is correctly called.
But when I click with the keyboard, even though the rowSelectionModel is getting a new value the callback is not called

### Expected behavior

When I click with the keyboard and the rowSelectionModel changes the callback should also be called

### Context

We want to also be able to control the selected rows with the keyboard, and have a callback inside the onRowSelectionModelChange to get the selected rows

We have premium plan, but the client is on holiday and we can't ask for the order id or support key

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: onRowSelectionModelChange rowSelectionModel data grid premium datagrid

**Comment by michelengelen** [comment]
Hey @zechuegui, 

the reason the callback is not fired is simply due to the fact that the selection model change in your example is not really a change. Consider an input as example: You have a onChange method and a value prop. Now if you would change the value prop programatically the new value gets shown in the input, but the onChange callback will not be fired as well, right? 

It's the same principle here: `onRowSelectionModelChange` (= `onChange`) and `rowSelectionModel` (= `value`)

So it is working as expected
