### ISSUE TITLE
[charts] Axis does not show `axis.min` and `axis.max` in some instances

### ISSUE THREAD

**Issue by JCQuintas** [mui/mui-x#14172]
It seems that when the axis `min/max` don't align with expected `nice()` values, the axis extremums aren't labeled.

![Screenshot 2024-08-12 at 12 37 14](https://github.com/user-attachments/assets/351b70c3-5caa-4b2e-9de3-fd10f717f59c)

**Search keywords**:

**Comment by alexfauquette** [comment]
Probably because the computation of tick number don't get the same range when done with `nice` or with `min`/`max`

**Comment by alexfauquette** [comment]
I miss understood the issue. I did not realised you were fixing the min/max in both examples

## What is happening

It's somewhat expected that extremums ticks are not always displayed. In the example you provide, the computation is done as follow:

- The height is around 200px-250px height and by default we place ticks every 50px so we will require 4 or 5 ticks.
- d3 looks for tickets human readable. and pick a step of 20,000. which leads to 3 ticks displayed

For example if you force the tick number, you can see it's quite sensitive at those ranges

https://github.com/user-attachments/assets/2e9bb0ad-c7a4-4e33-980c-ae4599c100c6

On zooming it feel like it's an expected behavior to have tick disapearing

![image](https://github.com/user-attachments/assets/d16755a4-c724-4be5-8012-93357dc08ab1)

## How it works in D3

From the [code of D3](https://github.com/d3/d3-array/blob/main/src/ticks.js), the ticks for linear scales are of the form $x*10^k$ with $x \in \lbrace 1, 2, 5 \rbrace$

The smart aspect is that `nice` use the same rule  to round values. So nice() and ticks work well together 

## Potatnial action

We could have an option to force ticks at the end. But user can already fix the tick they want by using `tickInterval: [-15_000, 0, 15_000, ...]`

![image](https://github.com/user-attachments/assets/71ffad7a-a932-4064-ac17-e7caa8a8c632)
