### ISSUE TITLE
[charts][LineChart] scaleType: "time" not working correctly

### ISSUE THREAD

**Issue by Abhishek332** [mui/mui-x#14367]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Use a LineChart
2. give scaleType: "time" and dataset for 30 days
3. In x-Axis see, it is showing Aug 25, instead of Sun 25
<img width="1197" alt="Screenshot 2024-08-27 at 10 53 01 PM" src="https://github.com/user-attachments/assets/7e90c9b4-cb5a-42ec-849c-314375b9faed">

### Current behavior

Showing random labels in between

### Expected behavior

It should maintain same format for all the labels, if it is showing label after 1 day interval, it should manage that interval all the way. Also it show Month name in some labels if it is showing day date format all labels should show in same format

These are the labels I see when I given 30 days point. 
Mon 29
Wed 31
Sat 03
Mon 05
Wed 07
Fri 09
Aug 11
Tue 13
Thu 15
Sat 17
Mon 19
Wed 21
Fri 23
Aug 25
Tue 27

### Context

When implementing LineChart for 30 days

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: LineChart

**Comment by michelengelen** [comment]
Hey @Abhishek332 the answer given by dosu should get you to a quick workaround. We will look into this though, as it seems there is something wrong about the formatting!
Thanks for raising this! 🙇🏼

**Comment by alexfauquette** [comment]
@Abhishek332 Are you forcing the ticks or the interval with either `min`, `max`, or `tickInterval` properties?

I tried to reproduce your use case and the tick seems ok. Could you provide a reproduction? Otherwise we can do nothing to solve this issue.

https://codesandbox.io/p/sandbox/beautiful-danilo-7rzcf7?file=%2Fsrc%2FDemo.tsx%3A36%2C35

![Image](https://github.com/user-attachments/assets/4b545f2b-fe98-4205-a7ca-9e9c69b8a945)
