### ISSUE TITLE
[tree view] Can't use the `TreeItem` `disabled` prop in `RichTreeView`

### ISSUE THREAD

**Issue by 2u4u** [mui/mui-x#14467]
### Steps to reproduce

Link to live example: [(required)](https://stackblitz.com/edit/react-1n36gk-z6majz?file=Demo.tsx)

Steps:
1. Create RichTreeView with slots using TreeItem
2. Set TreeItem disabled

### Current behavior

TreeItem is not disabled

### Expected behavior

TreeItem is disabled

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: RichTreeView, TreeItem

**Comment by michelengelen** [comment]
I am not 100% sure about the interals, but what I could see from the code is that the disabled prop is being handled by the internal tree view state and overriding it like this might not be possible.
@flaviendelangle could you shed some light here?

**Comment by flaviendelangle** [comment]
You should use the `isItemDisabled` prop to disable items with `RichTreeView`
See [this doc section](https://mui.com/x/react-tree-view/rich-tree-view/items/#disabled-items) for reference.

The goal of the `RIchTreeView` is to define the items and their state at the tree view level instead of the tree item level.
