### ISSUE TITLE
[charts] Smoothen resizing animation

### ISSUE THREAD

**Issue by hyperhand9** [mui/mui-x#14664]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/mui-charts-bug-n9k7kk

Steps:
1. Go to the link.
2. I set the chart of width and height to 500 and 300 initially.
3. Click the resize button to get wider the chart, then some data is hidden.

### Current behavior

When the chart gets wider, some data is hidden.
![chart-current2](https://github.com/user-attachments/assets/f257b48c-ae95-4b90-a470-b047baf81089)

### Expected behavior

All data should always be displayed normally, even when the chart is resized.
![charts-expected](https://github.com/user-attachments/assets/101c4fe5-5abf-413d-bcb2-47ab1be33236)

### Your environment

System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    npm: 10.8.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 128.0.6613.113
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.0 
    @mui/icons-material: ^6.1.0 => 6.1.0 
    @mui/material: ^6.1.0 => 6.1.0 
    @mui/private-theming:  6.1.0 
    @mui/styled-engine:  6.1.0 
    @mui/system:  6.1.0 
    @mui/types:  7.2.16 
    @mui/utils:  5.16.6 
    @mui/x-charts: ^7.11.1 => 7.17.0 
    @mui/x-charts-vendor:  7.16.0 
    @mui/x-data-grid: ^7.11.0 => 7.17.0 
    @mui/x-internals:  7.17.0 
    @types/react: ^18 => 18.3.5 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1 
    styled-components: ^6.1.9 => 6.1.13 
    typescript: ^5 => 5.6.2

**Search keywords**: charts resize

**Comment by alexfauquette** [comment]
Thanks for reporting. This bug should be fixed in the next release (today) thanks to this PR https://github.com/mui/mui-x/pull/14553

The animation is not perfectly fluid, but the plot is not stuck in an intermediate state anymore
https://codesandbox.io/p/sandbox/mui-charts-bug-forked-jwq823?file=%2Fsrc%2FApp.tsx%3A21%2C32

**Comment by Janpot** [comment]
👍 Got here after I noticed glitches in Material UI dashboard template while resizing

> The animation is not perfectly fluid, but the plot is not stuck in an intermediate state anymore

I noticed it's fixed in https://github.com/mui/material-ui/pull/43850 for lines now, but areas still seem to be [affected](https://deploy-preview-43850--material-ui.netlify.app/material-ui/getting-started/templates/dashboard/):



https://github.com/user-attachments/assets/6ab0cb21-28e8-4bbf-9965-40544de1323f

**Comment by alexfauquette** [comment]
@Janpot The fix should be ported to area by #14711

**Comment by hyperhand9** [comment]
My problem was solved.
Thank you for your help.

2024년 9월 27일 (금) 오전 6:58, github-actions[bot] ***@***.***>님이
작성:
