### ISSUE TITLE
[data grid] How to show column separator on a focused header cell

### ISSUE THREAD

**Issue by vmichailidisdev** [mui/mui-x#14709]
### The problem in depth

When a column is resizable when clicking on the column header title the column separator disappears. Is there any workaround for that?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Resizable, Column Header, Separator
**Order ID**: 94505

**Comment by MBilalShafi** [comment]
Could you expand more on what you mean by "column separator disappears", the column separator (blue one) appears on hover and disappears when you hover out of the separator area.

Do you mean the left and right grey separator indicators invisible when a header cell is focused?
![image](https://github.com/user-attachments/assets/12d3b44c-c821-4b4a-82e5-45c80985ac20)

If yes, what would be your expected behavior here?

**Comment by MBilalShafi** [comment]
You could use `sx` prop to show the column separator when the focus outline is hidden.

```js
<DataGrid
  rows={rows}
  columns={columns}
  sx={{
    [`& .${gridClasses.columnHeader}:focus-within, .${gridClasses.cell}:focus-within`]:
      {
        outline: 'none',
      },
    [`& .${gridClasses.columnHeader}:focus,
    & .${gridClasses['columnHeader--siblingFocused']}`]: {
      [`& .${gridClasses.columnSeparator}`]: {
        opacity: 1,
      },
    },
  }}
/>
```

Here's a live example: https://stackblitz.com/edit/react-mnqnuu?file=Demo.tsx

Let me know if it solves your issue.

**Comment by a-vogt** [comment]
The current workaround works, but it is not very maintainable since the nesting of selectors may change over time.
It would be helpful to have a built-in option to hide the outline while keeping the separators visible.

Are there any plans regarding this?

[issue 5783](https://github.com/mui/mui-x/issues/5783) also addresses the problem

**Comment by a-vogt** [comment]
Since [issue 5783](https://github.com/mui/mui-x/issues/5783) is still open, here is a friendly inquiry as to whether and when there will be a built-in solution?
