### ISSUE TITLE
[data grid] Is it possible to add one additional horizontal scrollbar to the DataGrid?

### ISSUE THREAD

**Issue by ternala** [mui/mui-x#14819]
### The problem in depth

I have a horizontal scrollbar in my data grid (on the bottom). We need to have one more on the top, how can I implement this?
One possible way to do this includes customizing MuiDataGrid-main as a slot. Is there a possibility to customize it as a slot?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: scroll datagrid double
**Order ID**: 83389

**Comment by michelengelen** [comment]
AFAIK there is no way of doing this atm and you cannot modify the main component as a slot as well.
I am not sure if what you are trying to achieve is doable at all. Objections @arminmeh?

**Comment by arminmeh** [comment]
You can't have two scrollbars on the same element, but it can be done with two elements that update scroll positions of each other.
I have used [this](https://jsfiddle.net/d7j0pz1m/) as an inspiration to create a [sandbox example](https://codesandbox.io/p/sandbox/top-scrollbar-7sth2l) for the grid.

Because of the performance optimizations in the grid, you can notice that, for very fast scrolls, scrollbars are getting a bit behind.
If you want to use this for a very tall grids, then it is not a problem because you don't see both scrollbars together anyway.

Other option is to use `disableVirtualization` flag.

Example that I have provided may still need some event handling/styling improvements.

Does this help @ternala?

**Comment by ternala** [comment]
> You can't have two scrollbars on the same element, but it can be done with two elements that update scroll positions of each other. I have used [this](https://jsfiddle.net/d7j0pz1m/) as an inspiration to create a [sandbox example](https://codesandbox.io/p/sandbox/top-scrollbar-7sth2l) for the grid.
> 
> Because of the performance optimizations in the grid you can notice that, for very fast scrolls, scrollbars are getting a bit behind each other. If you want to use this for a very tall grid, then it is not a problem because you don't see both scrollbars together anyway.
> 
> Other option is to use `disableVirtualization` flag.
> 
> Example that I have provided may still need some event handling/styling improvements.
> 
> Does this help [@ternala](https://github.com/ternala)?

It works nice, but I want to add this "additional scrollbar" inside the MuiDataGrid-main. But I can't customize it.
I thought about placing it by the pure js, but, in that case, I don't know if I would have trouble with the react or not

**Comment by arminmeh** [comment]
> I want to add this "additional scrollbar" inside the MuiDataGrid-main

Is this a must?
Because you can also make it appear in the main container with CSS. Check the sandbox link again, I moved the scrollbar to appear to be just below the header row (aligned with the other scroller)

> I thought about placing it by the pure js, but, in that case, I don't know if I would have trouble with the react or not

I am not 100% sure, but I think that the virtualization will not work, since it uses scrolling to determine what is the next rendering context (which cells should be in the DOM)
@romgrk can confirm

**Comment by ternala** [comment]
> > I want to add this "additional scrollbar" inside the MuiDataGrid-main
> 
> Is this a must? Because you can also make it appear in the main container with CSS. Check the sandbox link again, I moved the scrollbar to appear to be just below the header row (aligned with the other scroller)
> 
> > I thought about placing it by the pure js, but, in that case, I don't know if I would have trouble with the react or not
> 
> I am not 100% sure, but I think that the virtualization will not work, since it uses scrolling to determine what is the next rendering context (which cells should be in the DOM) [@romgrk](https://github.com/romgrk) can confirm
Ok, I'll give it a try, too bad if the virtualization doesn't work, although I thought it wouldn't be a problem. I will use this way If there is no direct possibility of throwing the component inside MuiDataGrid-main .
thank you very much

**Comment by arminmeh** [comment]
@ternala did you wanted to reply with something?
there is only the quote from the previous comment

**Comment by romgrk** [comment]
The grid already uses virtual scrollbars, but we don't implement a top one.

You could implement one yourself outside the grid. You won't have access to the CSS variables that the virtual scrollbars use, but you have the equivalent data in `gridDimensionsSelector(apiRef)`.

https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx

**Comment by arminmeh** [comment]
> Ok, I'll give it a try, too bad if the virtualization doesn't work

It is only noticeable if you have both scrollers in the view at the same time. If you are building this to support tall grids where both ends are rarely in the same screen, it should be fine.

> ... possibility of throwing the component inside MuiDataGrid-main

There is no slot to inject your component at the place you want, but it might work for you to use
https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx#L97
if you don't have row pinning (together with that feature it might get complex) and use the selector mentioned above.

Since you mentioned that you will give it a try, I will close this issue. Feel free to re-open it if you have further questions or the advices turn out not to be helpful for your case. We can check some other possibilities
