### ISSUE TITLE
[charts] Add `hideLegend` props

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#15186]
Idea from working on #15081 but could benefit [some discussion](https://github.com/mui/mui-x/pull/15081#discussion_r1821977895) before implementing it 

The proposed change:

- Since `slotProps={{ legend: { hidden: true } }}` can be quite lengthy, we introduce a new prop `hideLegend`.
  ```diff
   <BarChart
  -   slotProps={{ legend: { hidden: true } }}
  +   hideLegend
   />
  ```

Extracted from #15081 to be discussed with @JCQuintas

**Comment by JCQuintas** [comment]
I think `hideLegend` is a good alternative. Personally, `slotProps` is very opaque, which means it is hard to find its functionalities. For something as simple as hiding the legend, the `hideLegend` approach looks great. 

Regarding confusion, I don't think it would be too confusing, it is probably less confusing since you are probably not configuring the slots anyways.

We just need to set the order of operations clear, eg: if `hideLegend==false && slotProps.legend.hidden==true`, which takes precedence?

**Comment by alexfauquette** [comment]
> We just need to set the order of operations clear, eg: if `hideLegend==false && slotProps.legend.hidden==true`, which takes precedence?


For me it's a logical OR

- If `hideLegend` is `true` the legend component is not rendered at all. So we don't care about sub props.
- If `hideLegend` is `false` the legend is render and then we apply it's props, including `slotProps.legend.hidden`

Another option is to remove this `hidden` props. With such code, we don't need `slotProps.legend.hidden` and people using composition don't need it too.

```jsx
<ChartsContainer>
  {!props.hideLegend && <ChartsLegend />}
</ChartsContainer>
```

**Comment by JCQuintas** [comment]
🤔 Yeah, removing it would probably be the better approach

**Comment by GuillaumeMeheut** [comment]
Hi, may I take this issue as my first ?

**Comment by alexfauquette** [comment]
@GuillaumeMeheut Sorry, the PR was already kind of ready for this issue (just had to do 2 cherry-pick)

If you're looking for charts good first issue, there are those one

https://github.com/mui/mui-x/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3A%22component%3A+charts%22+label%3A%22good+first+issue%22

**Comment by GuillaumeMeheut** [comment]
No problem

I'll take a look at the Sparkline y-axis
