### ISSUE TITLE
[docs] Date Picker customization `borderRadius` does not round all components

### ISSUE THREAD

**Issue by kizeenn** [mui/mui-x#15263]
### Steps to reproduce

Link to live example: https://mui.com/x/react-date-pickers/date-picker/#customization

Steps:
1. select "DesktopDatePicker"
2. select DateCalendar from components dropdown
3. set borderRadius for maximum (20px)

### Current behavior

DateCalendar is rounded, but there is MuiPaper without rounding still visible (overriding MuiPaper with border-radius: "20px" gives the desired rounding)
![image](https://github.com/user-attachments/assets/04ea499b-e2a8-4e05-ae13-9da0b8af44fc)

### Expected behavior

DateCalendar is rounded correctly
![image](https://github.com/user-attachments/assets/2b40e65f-a9fb-4496-aa0f-7c5f160dac18)

### Context

DateCalendar rounding to be fixed, as it is useless to pass the ‘borderRadius’ property as the other element below it is not rounded.

### Your environment

---

**Search keywords**: DateCalendar borderRadius DesktopDatePicker

**Comment by LukasTy** [comment]
Hello @kizeenn.
This is just a playground to showcase how various slots can be customized and which parts of the component those customizations will affect.
I would say that the result accurately represents what the provided customization will achieve.
In this particular case, indeed, in order to round the border of the Paper, you would need to apply it to a higher level component, but the same would apply to the `StaticDatePicker` as well, it's just not noticeable in that case.

Do you think that the demo should be visually "pleasant" at the expense of the increased example size? 🤔 
cc @noraleonte Do you have thoughts on this? Do you think differently?

**Comment by noraleonte** [comment]
Hi 👋 I agree with @LukasTy that the demo is accurate. Changing the `borderRadius` of the `DateCalendar` does not change the radius of the paper wrapping it. Maybe we can add the paper to the list of items that are customizable to this demo? That might help 🤔

**Comment by LukasTy** [comment]
@noraleonte I've created https://github.com/mui/mui-x/pull/15305 based on your comment. 😉
