### ISSUE TITLE
[charts] line chart tooltip hover issue 

### ISSUE THREAD

**Issue by MainaMwangiy** [mui/mui-x#15268]
### Steps to reproduce

Link to live example: (required)

Steps: Check this link: https://stackblitz.com/edit/react-udtkt5-beatyw?file=Demo.js

### Current behavior

With some dates, it is having only one date visible on hover. 

### Expected behavior

Should be able to hover on different dates and see the value on the tooltip. 

### Context

I want to ensure that when I hover on a single date point, I get the specific date of that point. The solution given for this issue not working on some conditions. Please refer this issue. https://github.com/mui/mui-x/issues/13615

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: line chart hover tooltip

**Comment by JCQuintas** [comment]
Hi @MainaMwangiy, can you show an example of what you are trying to achieve? It seems you want a vertical line chart, which is not really supported at the moment.

**Comment by alexfauquette** [comment]
To be precise the issue you see is that to map the pointer position to a x-value, we assume that points along the x-axis are sorted by increasing order

**Comment by JCQuintas** [comment]
Currently both `point` and `band` scales don't support repeated data values, this is due to how the d3 mapping of the scale is handled behind the scenes. 

This is a know issue, this thread offers more insight: https://github.com/mui/mui-x/issues/13253

If you want to discuss anything related to that, please discuss it on the issue above so we keep everything contained :)
