### ISSUE TITLE
[data grid] Detail panel rerenders on scroll

### ISSUE THREAD

**Issue by achoud444** [mui/mui-x#15413]
### Steps to reproduce

Steps:
1. Open this link to live example: (required)
2.
3.

### Current behavior

I am using a [lazy loading](https://deploy-preview-13453--material-ui-x.netlify.app/x/react-data-grid/master-detail/#lazy-loading-detail-panel-content) detail panel. When I expand a row, scroll to the bottom, and then scroll back to the top, the detail panel reloads. 

You check on the link by putting a log in the `useEffect`

### Expected behavior

The detail panel should not re-render once it has been mounted.

### Context

Since re-rendering is occurring so frequently, it will trigger backend API calls repeatedly, leading to performance issues.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: [data grid] Detail panel rerenders on scroll

**Comment by michelengelen** [comment]
Hey @achoud444 ... this is a "problem" related to virtualization. The row unmounts when scrolled away and remounts when scrolled back into view leading to the rerendering. I am not sure if we can do anything about this. 

@romgrk is this something we can somehow support with a workaround?

**Comment by cherniavskii** [comment]
Hi @achoud444 
This is the optimization that is part of our virtualization engine, thus it's an expected behavior.
Did you consider caching the detail panel content? With libraries like [React Query](https://tanstack.com/query) it's built-in, but for your use case specifically, you can do this on the component level: https://codesandbox.io/p/sandbox/thirsty-austin-mhw6c6?file=%2Fsrc%2FDemo.tsx
Is this what you're looking for?

**Comment by achoud444** [comment]
@cherniavskii , I was aware of this workaround but assumed it wasn’t the default behavior of MUI, which is why I reported it as a bug. For now, this works for me, so I can proceed with it as is.

Thank you! :-)
