### ISSUE TITLE
[DataGrid] Uncatchable Errors thrown if row validation fails

### ISSUE THREAD

**Issue by xadie** [mui/mui-x#1804]
- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When row validation fails the exception thrown is uncatchable. (I guess function checkGridRowIdIsValid is responsible for throwing the error).

## Expected Behavior 🤔

Exception thrown should be able to be handled from the surrounding context. I would expect that if onError callback is provided, the raised error is catched and forwarded to the callback for instance.

## Steps to Reproduce 🕹

https://codesandbox.io/s/peaceful-mclean-nqcnyn?file=/src/App.tsx (v5)

- run example ~https://codesandbox.io/s/priceless-dewdney-9y9ko?file=/src/App.tsx~ (v4)
- check console output

## Context 🔦

Implementing error handling for an application that uses Datagrid for data display

**Comment by dtassone** [comment]
The grid already comes with an error boundary so it should show an error overlay on errors.
There seems to be an issue with that

**Comment by oliviertassinari** [comment]
Having a look at the problem, it seems that there are multiple opportunities:

1. I believe that the main argument we have used in the past to support the idea that the data grid needs a built-in error boundary is that showing a broken UI is worth that showing nothing. We all agreed to this. React as well, so much so that they made it the default behavior:
> errors that were not caught by any error boundary will result in unmounting of the **whole** React component tree. We debated this decision, but in our experience, it is worse to leave corrupted UI in place than to completely remove it.

https://reactjs.org/docs/error-boundaries.html

So it sounds to me that this argument has no foundations after all. We can remove the error boundary and still get the same outcome. @dtassone What's left to defend that we need a built-in ErrorBoundary?

2. The data grid stops the normal propagation of the error: https://codesandbox.io/s/elated-stallman-8y1cy?file=/src/App.tsx. In order to restore the default behavior, users have to rethrow it. Why should any component interfere with how developers want to implement error handling?
@xadie Would it help if there were no `onError` prop and you could use your own `ErrorBoundary` everywhere in the application? as suggested in:

> In practice, most of the time you’ll want to declare an error boundary component once and **use it** throughout your application.

https://reactjs.org/docs/error-boundaries.html

**Comment by dtassone** [comment]
FYI @oliviertassinari the datagrid is NOT swallowing errors as you can see in https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-error-handling--throw-exception

**Comment by oliviertassinari** [comment]
> NOT swallowing errors

@dtassone I meant for developers using the React error boundary pattern. They can't use their own boundery unless we move forward with option a. or b. I have provided proof in:

> The data grid stops the normal propagation of the error: https://codesandbox.io/s/elated-stallman-8y1cy?file=/src/App.tsx.

**Comment by m4theushw** [comment]
This issue doesn't appear to be ready to be worked on. IHMO I would remove our `ErrorBoundary` and let users use their own. I think it's better to not have one than to have that doesn't catch all possible errors, e.g. this one related by the OP. From my experience, most of the errors in application come from promises and these React doesn't catch, so only one root `ErrorBoundary` is enough.

**Comment by oliviertassinari** [comment]
@m4theushw Yeah, I also feel that we don't have enough information around how developers handle error handling. I'm personally in the same boat as you are, and it's what React documents, but it doesn't mean that most devs are.

At least we don't document `onError`, so we could remove the prop if needed during a minor version change.

On the other hand, a prop to display an error inside the data grid seems valuable, e.g. network fail.

**Comment by m4theushw** [comment]
> At least we don't document `onError`, so we could remove the prop if needed during a minor version change.

It's in https://material-ui.com/api/data-grid/.

> On the other hand, a prop to display an error inside the data grid seems valuable, e.g. network fail.

👍

**Comment by oliviertassinari** [comment]
Ah, Last summer, I didn't port https://master--material-ui-x.netlify.app/storybook/?path=/story/1-docs-13-error-handling--page into the docs because the feature felt too premature. 

> Handling error on the UI and in the grid, is critical to avoid breaking the whole application, or even displaying corrupted data. Therefore, XGrid is wrapped with an error boundary internally. So if the component throws an unhandled exception anywhere in the tree, the exception will get handled by the error boundary, and a nice error message overlay will be displayed.

As we have seen "displaying corrupted data" is not a valid argument, the real argument seems around not "breaking the whole application", only the data grid. The behavior comes at the cost of breaking the natural flow React error boundary. You can only get one of the two. 

Maybe we should optimize for the principle of least surprise? Meaning developers don't expect any component to come with an error boundary, we remove it. Most of the time, developers handle gracefully the common errors anyway. And there is a bug, then so be it, you might reload the page anyway

**Comment by dtassone** [comment]
Errors can come from many different sources not only ajax. It's wrong to assume that. It could be a corrupt/bad data in the DB that cause the grid to crash due to a rendercell for example...
The goal is to create a self contained component that handle its errors in a nice way. As mentioned errors are not swallowed they are thrown. So one can easily handle it differently if it suits. 
Async errors should be handled by calling showError of apiRef.

**Comment by oliviertassinari** [comment]
> errors are not swallowed they are thrown. So one can easily handle it differently if it suits.

This is not true, see https://codesandbox.io/s/elated-stallman-8y1cy?file=/src/App.tsx.
