### ISSUE TITLE
[RFC] Clean `x-data-grid` and `x-data-grid-pro`  exports

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#2227]
Relates to #924 
Relates to #18 

## Proposals

1. Stop exporting everything from the grid

```
export * from './components';
export * from './constants';
export * from './hooks';
export * from './locales';
export * from './models';
export * from './utils';
export * from './GridComponentProps';
```

We currently export from the module root almost every variable / type ever exported from any file inside the grid codebase.
We should be able to keep some variables / types private 

And even if we have an `export *` cascade, we almost always import from the leafs to avoid circular imports.

Here are a few things we should stop exporting without reason:

- the features hooks (`DataGrid` exports `useGridColumnReorder` even if it does not use it). We may export them when we'll have a hook-only API but currently they can never be properly used outside of the Grid.

- the internal utilities, (`isMultipleKey`, `isEscapeKey`, `isDesc`, ...)

- the internal data transformation functions (`mergeGridColTypes`, ...)

2. Group the event constants into a single enum

We are exporting dozens of variables (`GRID_RESIZE`, `GRID_KEYDOWN`, `GRID_COLUMN_HEADER_FOCUS`) when we could only export a single enum `GridEvent`. 
This would be more explicit and would also allow to strongly type `publishEvent` first argument (and later on type the second argument).

3. Group the CSS class variables

Probably related to #1950 

## Motivations

- Limit the breaking changes. If we export everything, renaming an internal variable or type is theoretically a breaking change. In a PR currently in work, I stop exporting `DEFAULT_GRID_SLOTS_COMPONENTS` because I moved it inside the single file that is using it, it's breaking because the variable is exported even if never used by anyone.

- Make the import clearer. Having hundreds of imports is a bit overwhelming.

- Never export something related to XGrid in the DataGrid package

- Make it easier to reduce bundle size of DataGrid by knowing what is in it

**Comment by m4theushw** [comment]
> 1. Stop exporting everything from the grid

TypeDoc only generates documentation for what is exported. By not exporting a particular interface we might lose its docs. We have to have this in mind.

> the internal utilities, (isMultipleKey, isEscapeKey, isDesc, ...)

These we can definitely stop exporting them ASAP.

> the internal data transformation functions (mergeGridColTypes, ...)

Same as above. +1 for not exporting.

> 2. Group the event constants into a single enum

I'm not sure if the docs will still be generated correctly. We relay in the @event annotation to know if it's an event. To group events a [string enum](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) has to be used to keep the string value. Basically, the constant (e.g. `GRID_ROW_CLICK`) is for internal use only and, in the markdown and demos, the string (e.g. `"rowClick"`) is encouraged because it's simpler to use. We had this discussion in https://github.com/mui-org/material-ui-x/pull/1299#discussion_r603198895

> 3. Group the CSS class variables

Could you elaborate your idea? We're using constants but there're some classes still hardcoded. We can even leverage more the `generateUtilityClasses` to support our convention. 

https://github.com/mui-org/material-ui-x/blob/21fd8f4606fd101ab657092b45eb7a8fdfc25a12/packages/grid/_modules_/grid/components/panel/GridPanel.tsx#L47

**Comment by flaviendelangle** [comment]
> TypeDoc only generates documentation for what is exported.
We should be able to add a TypeDoc entry point directly on the event file I think.
But I agree, the doc must not be impacted

> I'm not sure if the docs will still be generated correctly

I agree that it must still generate the doc correctly and that if it can't them the enum is not viable.
If you think it's better for the user to use the string directly instead of the constant, then maybe stop exporting all the event constants would be enough.

> Could you elaborate your idea? 

I'm not sure we should touch to the class part since it must be refactored in #1950 
But I'm talking about this file https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/constants/cssClassesConstants.ts
In a general way, I think that if we have more than a few related primitive variables exported, then an object would clean the public API.
Right now to get the class of an element in the IDE, you type `CLASS` and the autocomplete gives you the constants and the utilities, which make quite a few results. I think it would be easier to use if you just import `gridClasses` and then you all the values in it are classes.
But that's pretty much what #1950 will do.

**Comment by oliviertassinari** [comment]
As a side note, rebasing https://github.com/mui-org/material-ui-x/pull/1212 allows having a great overview of the expected modules, see https://deploy-preview-1212--material-ui-x.netlify.app/ for `@material-ui/data-grid`. For instance, It's weird that we export `Signature` to the public.

**Comment by flaviendelangle** [comment]
I was using Webstorm autocomplete, but a raw TypeDoc implementation is a lot easier to follow indeed.

**Comment by flaviendelangle** [comment]
I will do the component cleanup just after the virtualization PR merge to avoid further conflicts.
