### ISSUE TITLE
Collapse component loses transition when used in the data grid footer

### ISSUE THREAD

**Issue by PraveenPeri** [mui/mui-x#2273]
If the Collapse component is used to render a custom footer in the data grid, the slide-down/up transition is lost. Instead, the component just appears and disappears

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Collapse component just appears without any animation/transition

## Expected Behavior 🤔

Collapse component should maintain its transition ability of sliding down and up even when used inside a data grid footer

## Steps to Reproduce 🕹
1. Create a react component with Collapse
2. Use it to pass as footer in the components props of the data grid
3. Add a trigger button for the component
4. See that the component just appears/disappears as you click the button instead of sliding down/up

https://codesandbox.io/s/material-demo-forked-li2vk

## Context 🔦

We have a requirement to display a form that's blended into the data grid which can be used to add new rows to the table. The form should slide down/up for a good UX.
## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Sorry for the delay. Better late than never.

This issue happens because `CustomFooter` is defined inside `DataGridDemo`, so it changes in every rerender and React thinks it's a complete different component. You can fix this my either memoizing the footer component or defining it outside the main component. Here's the CodeSandbox showing the 2nd option: https://codesandbox.io/s/material-demo-forked-qxheem?file=/demo.tsx

> I think it is because the child of Collapse is a text element. Should it mandatorily be a React element for the effect to be noticeable?

@ZeeshanTamboli It's the same explanation from above. In every rerender you render a different component.

I'm closing this issue since there's no action for us.
