### ISSUE TITLE
[DataGrid] Print style is varying between light and dark mode

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#3378]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The colors contrast is less important if the print is done from dark mode than light mode

![image](https://user-images.githubusercontent.com/45398769/145183118-f380c2c1-dd78-4c26-a2d7-53cea2f1a357.png)

![image](https://user-images.githubusercontent.com/45398769/145183224-fcb17fef-6272-4af8-8e67-2a5005be8bfc.png)

### Expected behavior 🤔

The print should be the same in dark and light

### Steps to reproduce 🕹

Steps:

1. go to https://mui.com/components/data-grid/demo/
2. print the DataGrid
3. change light/dark mode
4. print the DataGrid
5. Notice the two preview are different

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hmm, interesting. The question is should the print styles match the page or should it be aways the same basic styling.
In this case, the contrast is off because the background color is not picked up. I would say that it would be best if the print style is the same regardless of it is dark or light mode.

**Comment by m4theushw** [comment]
Taking as example MS Word, even if I use the dark theme, the background in the print version is white. To fix maybe we need to apply the default styles in the page first and copy them, instead of reusing the current styles. Another solution is again to render the DataGrid with a different theme.

**Comment by alexfauquette** [comment]
I had a look at how to solve this issue. We could probably modify the theme used for printing with a `ScopedCssBaseline`. But this sounds like a hack.

We already have `@media print` to specify which style should be applied for printing. We should probably find a way to be sure that by default light theme colors are used by`@media print`.

**Comment by alexfauquette** [comment]
@mui/core Did you encounter similar issues, or do you have some insights about this issue?

The problem is that printing in dark mode is not relevant because text colors will be inappropriate for paper support (see below)

![image](https://user-images.githubusercontent.com/45398769/157263690-586b606b-56ae-47c0-be96-6ad4328847cb.png)

I see two options:
1. Wrap in the DataGrid in a `<ThemeProvider />` such that we could switch between light/dark theme (made o POC in #4086)
2. Using `@media print` to always have the light theme when printing, but it does not seem feasible because `createTheme()` only generates the light or the dark palette, not both.

Did I miss another way of modifying colors?

**Comment by siriwatknp** [comment]
Another option is to do nothing and add some warning to the doc that "print only works in light mode". From #4086, I think it is too much right now because developers can implement the theme toggle on their own.

From the core perspective, we are experimenting on the CSS variables which could give a better solution. Forcing the theme to `light` when user click the print button is only by updating any DOM to have `data-mui-color-scheme: 'light'`.

```js
// on print click, add data-mui-color-scheme
<div data-mui-color-scheme="light">
  ...data grid automatically turn to light color scheme
</div>

// on print finish, remove the dataset
<div>
  ...data grid automatically turn to light color scheme
</div>
```

So I suggest doing nothing and waiting for the feedback (it does not block them from printing).

**Note**: I found that toggle this checkbox can print with dark mode.

<img width="1001" alt="Screen Shot 2565-03-09 at 10 33 22" src="https://user-images.githubusercontent.com/18292247/157367662-b85e789b-4e96-4860-9ddb-83f2aff20731.png">
