### ISSUE TITLE
[data-grid] Restore column position after unpinning

### ISSUE THREAD

**Issue by alexghi** [mui/mui-x#3422]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

So with the latest MUI, and latest MUI Pro version the following occurs:
I have a grid with `checkboxSelection`, I pin a column and after unpinning it, it stays in front of the checkbox column

### Expected behavior 🤔

I expect it to move where it was before pinning it.

I would suggest having a sequence for the columns. this would also be in handy if someone would like to maintain on server the order of the grid columns. And make some of the columns undraggable when having this option turned on

### Steps to reproduce 🕹

Steps:

here: https://codesandbox.io/s/datagridpro-v5-quick-start-5pjhc?file=/src/App.tsx

### Your environment 🌎

sandbox
versions used Material 5.2.3
and MUI Pro 5.2.0.

**Comment by alexfauquette** [comment]
It seems you encounter two bugs

First, the checkbox selection column can be moved somewhere else than the first column, which looks like a bug. A quick fix would be to pin the checkbox column has proposed in the doc https://mui.com/components/data-grid/columns/#pinning-the-checkbox-selection-column
But a long-term fix would be to keep the checkbox selection column in the first position when a column is unpinned.

The second is to be able to "maintain on server the order of the grid columns". For that, you can listen to `columnsChange` event. I made a codesandbox:
https://codesandbox.io/s/datagridpro-v5-quick-start-forked-1rip7?file=/src/App.tsx
@alexghi Does this solution solves your use case?

@m4theushw I'm surprised that `columnOrderChange` is not triggered when pinning/unpinning column, event if is it modifying the column order

**Comment by m4theushw** [comment]
> I expect it to move where it was before pinning it.

It doesn't work as expected because the next hydration, after unpinning a column, occurs with the column orders stored in the state, not the order coming from the `columns` prop: https://github.com/mui-org/material-ui-x/blob/219f11b17cc67352eae754d80f0b6c4c192dc395/packages/grid/_modules_/grid/hooks/features/columns/gridColumnsUtils.ts#L110-L112

To be able to fix this, one option is to keep in the state, for each pinned column, a snapshot of all column positions in the moment they were pinned. It needs to be of all columns because, when unpinning a column, we need to find the position to restore and the first position might also be of a pinned column, so the second one needs to be tested and so on. However, I would propose a more scalable solution which is to convert the reorder feature into a pre-processor. It would work as follow:

1. **Initial hydration.** Takes the `columns` prop and merges with the `columnTypes` prop
2. **Pre-process column orders.** Reorders the previous columns based on a order saved in the state, not the one in `state.columns.all`
3. **Add checkbox column**. Runs the pre-processor that adds the checkbox column in the first position
4. **Add column for tree data**. Runs the pre-processor that adds the column from `groupingColDefField`
5. **Reorder pinned columns.** Runs the pre-processor that reorders the pinned columns
6. **Hydrate widths.** Computes the width of each column. It's the last step.

After running all the pipeline, `state.columns.all` would be ready to be rendered. One implication of this approach is that virtual columns (those added by pre-processors) can't be reordered by dragging or they will mess with the column order state in 2. In the meantime, it seems to be more stable since it always begins with the `columns` prop and all pre-processors are applied at the same order with the same data. Currently, the first hydration occurs with the column order from the `columns` prop but the second hydration uses the positions saved in the `state.columns.all`. Pinging @flaviendelangle since he worked in refactoring the column hydration.

> First, the checkbox selection column can be moved somewhere else than the first column, which looks like a bug. 

Actually, I see this as a feature. 😁 Through column pinning, the checkbox column can finally be moved to somewhere else. An user asked for this possibility in #2380.

> I would suggest having a sequence for the columns. this would also be in handy if someone would like to maintain on server the order of the grid columns. And make some of the columns undraggable when having this option turned on

#820 is supposed to allow this.

**Comment by alexghi** [comment]
@alexfauquette thanks for the suggestions. I think listening on `columnsChange` might be a solution for me when dragging & dropping columns (even though it doesn't get triggered when unpinning).

@m4theushw you're saying that I should/could use `initialState` at first render and that state is not a mutable one, and whenever I do some column reorders I update them to the server. Still don't know how I should export/restore state in a proper manner. I will take a closer look at this.

**Comment by m4theushw** [comment]
> Still don't know how I should export/restore state in a proper manner. I will take a closer look at this.

We now have docs explaining how to save and restore the state of the grid, including the position of the columns: https://mui.com/x/react-data-grid/state/#save-and-restore-the-state

> I have a grid with checkboxSelection, I pin a column and after unpinning it, it stays in front of the checkbox column

Will be fixed by #4512
