### ISSUE TITLE
[DataGrid] valueGetter with typing errors

### ISSUE THREAD

**Issue by magahernandez** [mui/mui-x#3548]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

With the new update of the version `"@mui/x-data-grid": "5.2.0"`, I have the following problem:

When I define my `GridColumns`, if I write

```
valueGetter: (params: GridValueGetterParams) => {
    return TransformFunction(params.value)
},
```

I going to have the error:

```
Property 'value' does not exist on type 'GridValueGetterParams<any, any>'.
Property 'value' does not exist on type 'GridValueGetterSimpleParams<any>'.ts(2339)
```

I don't have this problem with the  version `5.1.0`.
Even though it fails me when writing that, it really does bring me the `value` parameter. Should be type declaration bug.

### Expected behavior 🤔

Should accept the parameter `value`, because exists.

### Steps to reproduce 🕹

Steps:

1. Define the columns value like:

```
valueGetter: (params: GridValueGetterParams) => {
    return TransformFunction(params.value)
},
```

where `TransformFunction` is any function to transform the value I receive to another

2. Im going to have 

```
Property 'value' does not exist on type 'GridValueGetterParams<any, any>'.
Property 'value' does not exist on type 'GridValueGetterSimpleParams<any>'.ts(2339)
```

3. If I check the existing values in `params`, there is a `value` parameter

### Context 🔦

I feel like it's OK to have a more general way of finding a value, other than

```
params.row.field1
params.row.field2
params.row.field3
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.1
  npmPackages:
    @emotion/react: 11.7.1 => 11.7.1 
    @emotion/styled: 11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.62 
    @mui/icons-material: 5.2.5 => 5.2.5 
    @mui/material: 5.2.6 => 5.2.6 
    @mui/private-theming:  5.2.3 
    @mui/styled-engine: 5.2.6 => 5.2.6 
    @mui/styles: 5.2.3 => 5.2.3 
    @mui/system:  5.2.6 
    @mui/types:  7.1.0 
    @mui/utils:  5.2.3 
    @mui/x-data-grid: 5.2.0 => 5.2.0 
    @types/react: 17.0.38 => 17.0.38 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    styled-components: 5.3.3 => 5.3.3 
    typescript: 4.5.4 => 4.5.4 
```
</details>

**Comment by m4theushw** [comment]
You can type the params with `GridValueGetterFullParams` to get access to `value`.

```tsx
import { GridValueGetterFullParams } from '@mui/x-data-grid';

valueGetter: (params: GridValueGetterFullParams) => {
  return `${params.value}`;
}
```

Mistakenly, we added a breaking change in #3314. 

@flaviendelangle In v6, should we give a step back and make `GridValueGetterParams` an interface again, instead of an union?  I didn't notice this while reviewing the PR but if I had I would suggest to make `params` a proxy and warn if users try to access the value when the value getter is called inside the row grouping. This way we keep a single interface.

**Comment by flaviendelangle** [comment]
For me it is not a code breaking change only a typing one, so I did not add it my mistake but intentionnally.
If the user code received the full params in a given situation in 5.0, it still receives the full params in 5.1
The only scenarios without the full params are new ones introduced by the tree.

And I think adding this kind of changes during minors is fine. That we should focus on avoiding code breaking changes on minor at all cost, but that typing ones can make sense. But I am opened to discussion on that topic.

As for the fix for this specific use case. I think the current typing reflect exactly what is going on and I prefer that over a proxy.
Because if we add a proxy, are we making the `value` key nullable ?

- If so, it is a breaking change on the typing because `valueGetter: (params: GridValueGetterParams<{ city: string }>) => params.value.city` will have TypeScript complains whereas now it does not. Having two interfaces or a single one with nullable keys is very subjective. I went for the two interfaces because I think it shows that not all combinations are possible. If you don't have the `value` then you don't have the `rowNode.id` either for instance. Which makes the typing slightly more precise.

- If not so, the typing will not reflect the reality and I think it's the worst solution to make the typing false to avoid breaking TypeScript checks on the projects using the DataGrid.

**Comment by m4theushw** [comment]
> And I think adding this kind of changes during minors is fine. 

@flaviendelangle But it broke the code of an user, it's not compatible according to semver. The code written for 5.1.x does not build with 5.2.x. I found [this issue](https://github.com/react-hook-form/react-hook-form/issues/5122) where it shows a similar situation: a change, affecting only TS users, released as minor. It was considered as "breaking change" by the users.

> Because if we add a proxy, are we making the value key nullable ?

The value is already typed as `any` so it might be null or undefined.

https://github.com/mui-org/material-ui-x/blob/6208886dbb143f7365f8387ef9d91a6261a3a9d3/packages/grid/_modules_/grid/models/params/gridCellParams.ts#L123

About having two interfaces, I don't think this is the problem. The `rowNode` property came later so it makes sense to not exist in the base `GridValueGetterParams`.

Anyway, let's leave this issue open to see if other users are also being impacted and if an action should be taken.

**Comment by flaviendelangle** [comment]
> The value is already typed as any so it might be null or undefined.

Not if you pass the generic.
If a user has the following code in 5.0 because he wanted to use the generic, the code would not have passed the build in 5.1 if we made the `value` option (`value?: V`).

```tsx
valueGetter: (params: GridValueGetterParams<{ city: string }>) => params.value.city
```

And if not for the value, we can have the exact same discussion for the `rowNode` which is the same scenario but without the generic.


My point here is, I don't see how we can have the following three point all at once:

1. Do not break the TS compilation of any user
2. Have a typing that is correct (ie: that describe the actual parameters that can be passed)
3. Use the `valueGetter` for the row grouping 

And if we agree that we can't have the tree of them, I think it is important to agree which one we accept to drop the next time we have a similar case.
Because it will not be the last time we have to edit a typing that way.

**Comment by toddlemoine** [comment]
FWIW, we're using x-data-grid-pro and I had the same issue this morning after upgrading to 5.2.1. Following the advice [here](https://github.com/mui-org/material-ui-x/issues/3548#issuecomment-1004272497), typing params as `GridValueGetterFullParams` didn't fix it, though. Instead, it tells me the types of params are incompatible.

<img width="623" alt="Code 2022-01-05 at 08 47" src="https://user-images.githubusercontent.com/394949/148256351-91a86b85-32ec-468a-b062-68c9f8ef88be.png">

**Comment by flaviendelangle** [comment]
You probably have to use `as` in order to force TS to agree with your typing
See https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/hooks/features/treeData/gridTreeDataGroupColDef.ts#L17

**Comment by zromick** [comment]
The quick fix listed above still leads to a Type error. Any other solutions?

Type '(params: GridValueGetterFullParams) => string' is not assignable to type '(params: GridValueGetterParams<any, any>) => GridCellValue'.
  Types of parameters 'params' and 'params' are incompatible.
    Type 'GridValueGetterParams<any, any>' is not assignable to type 'GridValueGetterFullParams<any, any>'.
      Type 'GridValueGetterSimpleParams<any>' is missing the following properties from type 'GridValueGetterFullParams<any, any>': getValue, api, value, cellMode, and 2 more.ts(2322)
x-data-grid.d.ts(3421, 5): The expected type comes from property 'valueGetter' which is declared here on type 'GridColDef'

> ```tsx
> valueGetter: (params: GridValueGetterFullParams) => {
>   return `${params.value}`;
> }
> ```

**Comment by m4theushw** [comment]
@zromick I updated https://github.com/mui-org/material-ui-x/issues/3548#issuecomment-1004272497 with the correct fix.

**Comment by tlmader** [comment]
We've been able to get past this error using `GridValueGetterSimpleParams<R>`, but it appears this type is no longer exported after updating to 5.4.0.

**Comment by flaviendelangle** [comment]
Sorry for all this mess around `valueGetter`
In the end we changed the approach for the row grouping so it is not needed anymore.
You should be able to remove your `as GridValueGetterSimpleParams<R>` and have no error.

**Comment by yamanidev** [comment]
I was trying the solutions mentioned above but I am getting this error. How is it possible that I am not able to import these types?
- `@mui/x-data-grid`: ^7.7.0

<img width="882" alt="image" src="https://github.com/mui/mui-x/assets/65856786/67a2de9b-f3e3-41bf-a891-ad963914c4af">

**Comment by Communiqueryle** [comment]
> For me it is not a code breaking change, only a typing one, so I did not added it my mistake but intentionally If the user code received the full params in a given situation in 5.0, it still receives the full params in 5.1 The only scenarios without the full params are new ones introduced by the row grouping feature.
> 
> And I think adding this kind of changes during minors is fine. That we should focus on avoiding code breaking changes on minor at all cost, but that typing ones can make sense. I have the feeling the typings of other libraries broke my code on minors. But I am opened to discussion on that topic.
> 
> As for the fix for this specific use case. I think the current typing reflect exactly what is going on and I prefer that over a proxy. Because if we add a proxy, are we making the `value` key nullable ?
> 
> * If so, it is a breaking change on the typing because `valueGetter: (params: GridValueGetterParams<{ city: string }>) => params.value.city` will have TypeScript complains whereas now it does not. Having two interfaces or a single one with nullable keys is very subjective. I went for the two interfaces because I think it shows that not all combinations are possible. If you don't have the `value` then you don't have the `rowNode.id` either for instance. Which makes the typing slightly more precise.
> * If not so, the typing will not reflect the reality and I think it's the worst solution to make the typing false in order to avoid breaking TypeScript checks on the projects using the DataGrid.





https://reactdev.space/questions/the-target-property-is-not-found-on-the-specified-string-type
