### ISSUE TITLE
Grid Filter Panel Customization.

### ISSUE THREAD

**Issue by SowjanyaDG** [mui/mui-x#3804]
### Order ID 💳

36165

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Dear Team,
We are using DataGridPro 5.2.2
We would like to use a custom component (a pop up dialog) for Filtering instead of default GridFilterPanel.
Also we would like to hide the Operators and Link Operators.
Could you please guide us on the same or provide any examples for the same?

### The problem in depth 🔍

![Screenshot_2022-01-31 Data Grid - Filtering - MUI(2)](https://user-images.githubusercontent.com/98762737/151842488-e54ab1c9-e0a7-45ce-993f-abf16282319f.png)

Here in this there is Default filter panel, We would like to use a custom component for Filtering.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by lumonad** [comment]
Hi @ SowjanyaDG ,

`Datagrid` itself has property `components` and that property has `FilterPanel` and `Panel`(used for filters and columns settings) components you can completely override.

If you want to change how `FilterPanel` appear - `Modal` instead of `Popper`, you have to override `Panel` component(it will affect columns settings as well). Or try to override datagrid prop `componentsProps.panel.as` to make it `Modal`, you can assign other properties to configure your future Modal, it will be proxied to the `Panel` component.

If you want to control how you render filter inputs you need to override `FilterPanel`. But from this point I believe you need to recreate a lot of mui components which renders default filters/forms

For some reason mui team hardcoded `Panel` to always be `BasePopper`, which is regular mui `Popper`. But you can override it with another datagrid prop `componentsProps`:

```tsx
import { Modal } from '@mui.material';

<Datagrid
  ....
  componentProps={{ panel: {as: Modal}}}
/>
```

Docs, are good for overall understanding what datagrid is capable of. But you can learn much more by reverse-engineering their source code if you need "deep" customization.

**Comment by SowjanyaDG** [comment]
Thank you for Suggesting componentsProps.panel.as prop for overriding the FilterPanel.
Have created Custom Component, and passed the Component as, componentsProps={{panel: {as: CustomFilterComponent}}}.
As shown in the below picture, added two external buttons, For these 2 button how to pass the onClose prop and other external prop. Is there any way to achieve this.

![Screenshot_2022-02-01 Global EDI Portal](https://user-images.githubusercontent.com/98762737/151998790-276a37e7-d035-4a3f-8906-8b26137ee018.png)

Also Tried by returning the JSX element: 
componentsProps={{
                                panel: {
                                    as: () => {
                                        return (<CustomFilterComponent open={openFilterDialog} 
                                                                                              onClose={handleClose}
                                                                                              params={params}  
                                       >)
                                    }
                                },
                            }}

Could you please provide us any example or any prop to hide the Link Operator and Operator? And also the example for the above mentioned issue?

**Comment by alexfauquette** [comment]
There is an ongoing PR #3497 to customize the filter panel.

To override the component, it is not `componentsProps`. it's `components`. Specifically for filter panel, see [this comment](https://github.com/mui-org/material-ui-x/issues/3082#issuecomment-963953645)

**Comment by SowjanyaDG** [comment]
Hi @alexfauquette  When will this PR #3497 - customize the filter panel props release?

**Comment by flaviendelangle** [comment]
@alexfauquette does #3497 closes this issue ?

**Comment by alexfauquette** [comment]
@SowjanyaDG the PR is merged and will be available in the next release

**Comment by yiranz1** [comment]
Hi all, how can we add a "Save Filter" button next to the "+ ADD FILTER" button using this new feature?

**Comment by slevine3** [comment]
Having the option to turn off auto update and instead add an "Apply Filters" button would be a nice feature update. I don't want to send a request every time someone changes the filter columns or begins typing..

**Comment by alexfauquette** [comment]
@yiranz1 and @slevine3 to be able to keep track of what's done, and what needs to be done and let others find issues up to date about their needs we have to keep issues scoped.

This one is closed and one year old. If you need additional customization, please open another issue such that we can have a discussion about your need :)
