### ISSUE TITLE
Cannot clear filters in MUI Datagrid

### ISSUE THREAD

**Issue by Archcry** [mui/mui-x#3841]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When a filter is set without a value (only column and operators) it is not possible to clear the filters. This is also broken in the [documentation of datagrid](https://mui.com/components/data-grid/filtering/#custom-filter-panel) (click filters -> set operators to "is empty" -> try to clear the filters).

### Expected behavior 🤔

You should be able to clear the filter when clicking on the clear filter button.

### Steps to reproduce 🕹

Steps:

1. Go to [code sandbox](https://codesandbox.io/s/datagrid-v5-quick-start-forked-seycm?file=/src/App.tsx).
2. Try to clear the predefined filter.

### Context 🔦

In our project we want a predefined filter on rows that have no value for a certain column. The people working with this table are now unable to clear the predefined filter. A workaround is to select another operator, this will cause the filter to clear.

Possibly related to https://github.com/mui-org/material-ui-x/issues/3670 and https://github.com/mui-org/material-ui-x/issues/2940.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.16 Arch Linux
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 96.0.3
  npmPackages:
    @emotion/react: 11.4.1 => 11.4.1 
    @emotion/styled: 11.3.0 => 11.3.0 
    @mui/base:  5.0.0-alpha.67 
    @mui/material: ^5.4.0 => 5.4.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/system:  5.4.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid: ^5.5.0 => 5.5.0 
    @types/react: ^17.0.0 => 17.0.19 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.1.2 => 4.3.5 

```
</details>

**Comment by flaviendelangle** [comment]
The current behavior is as follow:

On the DataGrid, you can't have several filters. Instead of removing the filter, we are emptying its value.
But if the operator being used does not require a value, it causes the bug you reported.

We don't want to entirely remove the filter item from the UI when deleting it because as the DataGrid can only have 1 item, there is no notion of adding an item, you just edit the fields of the one created for you.

A quick fix would be to also reset the operator.
The grid would then fallback to the default operator (`contains` in your example).
It's not that great because the bug would occur again if users create a custom column type where the default operator does not require a value.

A deeper change would be to change the behavior of the filter to make the operator optional. 
The panel could then remove the operator and the filter item would not be applied.

**Comment by alexfauquette** [comment]
I made an example comparing Pro and Comunity behavior
- Pro: the filter panel reset to its default behavior
- Community: the filter panel do nothing

https://codesandbox.io/s/datagrid-v5-quick-start-forked-t2bz1?file=/src/App.tsx

The reason is that in Community, we know that the filter panel contains only one item and so we only reset the value.
https://github.com/alexfauquette/material-ui-x/blob/excel-export/packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx#L150:L156

We could add another condition, such as if the current operator has no input component, delete replace the item by the default one.

Notice that the `onFilterModelChange` is called, so you can already implement this behavior. I added an example using it at the end

@flaviendelangle I don't think making the operator optional is a good idea, because it sounds like a hack to disable the filtering.

I propose that the delete button have as follow:
- If multiple items, we delete it
- If only one item with value != undefined we reset the value
- If one item without value we delete the item

When the deleteFilterItem returns an empty list (last case) it close the filter panel.

**Comment by flaviendelangle** [comment]
> If only one item with value != undefined we reset the value
> If one item without value we delete the item

So when pressing the cross, an operator that needs a value but without any value defined would behave like an operator that does not need a value ?

For instance if you pass `{ items: [{ operatorValue: "contains", columnField: "brand", value: undefined }] }` to the grid.
If you press the cross, are you deleting the item ?

**Comment by alexfauquette** [comment]
That's to discuss, but I'm in favor of yes, because if the user presses the cross it's to remove the filter, not to clean the input which is already empty.

**Comment by flaviendelangle** [comment]
In that case, why don't we always delete the filter even if there is a value ?

**Comment by alexfauquette** [comment]
Because it would be a breaking change

For the community version, the feature is "it quickly clean the value". So we can consider that if there is no value, it is an undefined feature, which could be either "the delete button must be disabled" or "the delete button remove the item and close the panel"

**Comment by Archcry** [comment]
Is there an easy way to work around this issue for now? If so what would you suggest?

**Comment by alexfauquette** [comment]
@Archcry it depends on what you want to do. If you just want to clean the filter, you have a workaround in [this comment](https://github.com/mui/mui-x/issues/3841#issuecomment-1029919309).

If you want to close the filter panel, it is more complicated.
With `DataGridPro` you can use `apiRef` which has the `hideFilterPanel` method.
With the community version, I don't see other solution than controlling the state with `onStateChange`. Maybe @flaviendelangle will have another idea

**Comment by Archcry** [comment]
Unfortunately the workaround does not work correctly, I am indeed able to clear the filter when applying the workaround but defining a new filter fails because when I start to type a filter value in the filterbox the filter resets back to default before I finish typing.

**Comment by flaviendelangle** [comment]
I don't think there is a clean solution for the community version no.

@alexfauquette do you want to make the PR for https://github.com/mui/mui-x/issues/3841#issuecomment-1029919309 ?

**Comment by Archcry** [comment]
Looks like the following does work:
```typescript
const onFilterModelChange = (newFilters: GridFilterModel) => {
  if (
    newFilters.items[0]?.columnField === filters.items[0]?.columnField &&
    newFilters.items[0]?.operatorValue === filters.items[0]?.operatorValue &&
    filters.items[0]?.value === newFilters.items[0].value
  ) {
    setFilters({ items: [] });
  } else {
    setFilters(newFilters);
  }
};
```

**Comment by alexfauquette** [comment]
@flaviendelangle yes, I'm doing it

**Comment by oliviertassinari** [comment]
It looks close to be a duplicate of #3140 that I think we are waiting for a UX designer to shine light on.

**Comment by alexfauquette** [comment]
Yes, the reason is not the same, but the request is the same: closing the filter panel when deleting the last filter form

@oliviertassinari Should I write in #3140 an explanation about why we took this decision and we keep the issue open, waiting for a full UX design of the grid, or do we close #3140?

**Comment by flaviendelangle** [comment]
I agree that we are making small fixes on a broader subject
I think this fix was worth doing, but the sooner we have an UX design the better on that subject.

**Comment by oliviertassinari** [comment]
Personally, I wouldn't have gone in the direction of #3910. I share in https://github.com/mui/mui-x/issues/3140#issuecomment-965593402. I think that we should keep #3140 open to leave space for a UX designer to shine in.

In any case, we did an iteration, great, let's release it into the wild and see what's the feedback that we get on it 👍, the best way to move the product forward, plus the course-correction cost is very low if needs it to be.
