### ISSUE TITLE
[DataGrid] Request for keyboard event for CellFocusIn or CellEnter

### ISSUE THREAD

**Issue by ramyab03** [mui/mui-x#3892]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We are using MUI DataGrid @mui/x-data-grid in our React application.

In the DataGrid we have icons with ToolTip in 4 columns. We are using MUI ToolTip and Icons. The Tooltip title displays when we mouse hover the icon. Is there a way we can display Tooltip for keyboard users - when they enter/navigate to the cell using arrow keys?

Did not find any keyboard event for CellFocusIn - to set the Tooltip to open.

**Comment by flaviendelangle** [comment]
Maybe the basic `componentsProps` usecases should be more documented so that we can link the real doc instead of the migration guide.

For instance a new `Add custom cell / row listeners` section may be easier to understand than a `componentsProps` generic section in a `Components` page which looks like an advanced topic.

**Comment by ramyab03** [comment]
Here is the example - [https://codesandbox.io/s/datagrid-v5-quick-start-forked-0t1wx?file=/src/App.tsx]

**Comment by ramyab03** [comment]
Here is the example - https://codesandbox.io/s/datagrid-v5-quick-start-forked-0t1wx?file=/src/App.tsx

**Comment by flaviendelangle** [comment]
I am re-opening it since we have a reproduction case

**Comment by m4theushw** [comment]
@ramyab03 In the example provided you're not using `IconButton` but only non-interactive icons. Wrapping the icon in a `IconButton` shows the tooltip when the cell gets focused.

**Comment by shahidify** [comment]
> By default the [Tooltip](https://mui.com/components/tooltips/) displays its label when its child element receives focus. For its child to receive focus via the keyboard, it needs to have a `tabIndex`. This [demo](https://mui.com/components/tooltips/#basic-tooltip) uses a IconButton so it has `tabIndex=0` for free. In the DataGrid, the current focused cell has `tabIndex=0` which makes the focus to always move to the cell when navigating with the arrows, so not showing the label. I'll wait for the reproduction to understand what you're trying to build, but I believe that only by not adding `tabIndex` to the cell that contains the Tooltip does the trick, not requiring to listen for the events.

Hi, I have a follow up question on a similar issue (sorry, I understand this issue is closed. I will create a new issue if it's needed)
For GridCell, I resolved it using the same approach.
However, the same approach does not work on column
 header cell since it does not have `hasFocus`. Column header tooltip is not displayed on keyboard focus navigation. Our requirement is to display tooltip on keyboard focus especially when header label is not fully displayed (ellipsis).
Any suggestion?
