### ISSUE TITLE
[DataGridPro] `renderCell` is called on each keystroke during cell editing

### ISSUE THREAD

**Issue by atillaaliyev** [mui/mui-x#3924]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using custom InputBase on two columns with renderCell and renderEditCell props. And I'm using custom input component for this InputBase with inputComponent prop (imask library).
But when I clicked anywhere , being render every time for every cell that using renderCell prop.  Actually, I solved it partially, for example , I'm using useMemo hook with JSX expression for renderCell , didn't render.
```
        renderCell: (params: GridRenderCellParams<number>) => (
            <>
                {
                    useMemo(() => {
                        return <InputBase
                            name="old_price"/**/
                            readOnly
                            value={!params.value ? "" : params.value.toString()}
                            inputComponent={VMaskNumber as any}
                            style={{
                                color: '#262626',
                            }}
                        />
                    }, [params.value])
                }
            </>
        )
```

It's perfect , but there's a problem, this column wasn't editable. And this solution was useful. In the same way, I'm trying for editable column , I'm getting error : 
**_"Rendered fewer hooks than expected. This may be caused by an accidental early return statement."_**

But I have to use  useMemo, beacause of it's trouble even for 35 data.

https://user-images.githubusercontent.com/6121871/153591066-7a7d028d-a31c-45ce-9dab-c9f2a189838c.mp4

You can see difference with renderCell prop and without renderCell prop. I'm sharing code and if you can watch console , you will show performance problem.

https://codesandbox.io/s/p0t4z
 

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

37219

**Comment by cherniavskii** [comment]
Hey @atillaaliyev 
Thanks for opening this issue.

Indeed, I can see that `renderCell` on each keystroke while editing cell value.
Seems like an overkill, we'll give it a closer look.

---

Off-topic, but related: `renderCell` (as well as `renderEditCell`) are supposed to be functions, not components.
This means, that you can't use React hooks there, otherwise you'll get the error you've mentioned:
```
Rendered fewer hooks than expected. This may be caused by an accidental early return statement
```
Instead, you can create a component and wrap it with a function - see https://github.com/mui/mui-x/issues/1402#issuecomment-997333464

**Comment by cherniavskii** [comment]
I've just remembered that we added `debounceMs` option to `setEditCellValue` in `v5.5.1` (https://github.com/mui/mui-x/pull/3825).
It seems to solve the issue - see https://codesandbox.io/s/datagrid-quick-start-forked-kx16u?file=/src/GridColumns.tsx:1406-1479

**Comment by atillaaliyev** [comment]
Thank a lot @cherniavskii , it has solved my priority problem.
But you had changed status of issue as bug, for what ? Due to renderCell is called on each keystroke ?

**Comment by cherniavskii** [comment]
@atillaaliyev right, it doesn't look like a bug but maybe there's still something we can do to improve performance

**Comment by m4theushw** [comment]
I didn't understand why you used `React.useMemo` instead of `React.memo`. With `React.memo` you can drastically reduce the number of renders. I updated the CodeSandbox: https://codesandbox.io/s/datagrid-quick-start-forked-kx16u?file=/src/GridColumns.tsx

>  right, it doesn't look like a bug but maybe there's still something we can do to improve performance

Yes, in the CodeSandbox above clicking outside the field being edited renders all cells again. Debugging a bit I found that the `rowNode` prop given to the cell is changed every time that `apiRef.current.updateRows` is called. It begins here: 

https://github.com/mui/mui-x/blob/5a809ceaa53be51297a460bbad28c108c8f885a0/packages/grid/_modules_/grid/hooks/features/editRows/useGridCellEditing.ts#L331

https://github.com/mui/mui-x/blob/5a809ceaa53be51297a460bbad28c108c8f885a0/packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts#L281

https://github.com/mui/mui-x/blob/5a809ceaa53be51297a460bbad28c108c8f885a0/packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts#L177

https://github.com/mui/mui-x/blob/5a809ceaa53be51297a460bbad28c108c8f885a0/packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts#L106

https://github.com/mui/mui-x/blob/5a809ceaa53be51297a460bbad28c108c8f885a0/packages/grid/_modules_/grid/hooks/core/rowGroupsPerProcessing/useGridRowGroupsPreProcessing.ts#L62

The value for `rowNode` comes from `tree[rowId]`. It always recomputes the nodes for all rows in `getFlatRowTree`. In other terms, it doesn't reuse the value from the previous tree.

https://github.com/mui/mui-x/blob/5a809ceaa53be51297a460bbad28c108c8f885a0/packages/grid/_modules_/grid/hooks/core/rowGroupsPerProcessing/useGridRowGroupsPreProcessing.ts#L12-L17

I would expect that it would rerender only the cell that was committed, not the entire grid.

**Comment by atillaaliyev** [comment]
Thank you @m4theushw 
I updated my code: https://codesandbox.io/s/p0t4z
I added to grid 100+ data, and when I wanted to update any cell, renderEditCell component being render in 1 second, it's long time for user experience, Is your solution will solve it , isn't it?

**Comment by flaviendelangle** [comment]
For the flat tree, it is easy to reuse the node since its properties never changed, I just have to check if the node of the previous tree exists.
For non-flat tree, it becomes more complicated, I did a manual comparison of each key (to avoid `isDeepEqual`, see #3954)
