### ISSUE TITLE
[question] My Column is combination of multiple fields and I am trying to allow custom sort based on the custom field name selection

### ISSUE THREAD

**Issue by faizsayed** [mui/mui-x#3970]
### Order ID 💳

#37903

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am Using DataGridPro. And I have a situation where my column values are combination of multiple fields. I want to allow sorting for based on the custom selected field among the combination.
Example: the column Address is combination of city, state and zip code. on this address column I want to perform sorting based on either of the value city, state or zip code. for that I have added one custom component in GridColumnMenuContainer which is allowing user to select any of the field value (city, state or zip code).
As sort works on field name of the column I am changing that field name after user selection (from city, state or zip code).

### Your environment 🌎

System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 97.0
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.65 
    @mui/material: ^5.3.0 => 5.3.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/styles: ^5.3.0 => 5.3.0 
    @mui/system:  5.3.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid-pro: ^5.2.2 => 5.2.2 
    @mui/x-license-pro:  5.2.2 
    @types/react: 17.0.38 => 17.0.38 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.5.4 => 4.5.4

**Comment by flaviendelangle** [comment]
[This demo](https://mui.com/components/data-grid/sorting/#combine-built-in-comparators) show how you can create a custom sort comparator for this kind of columns.
You will probably have to update to the last version of the grid to have the built in comparators and avoid re-implementing them (otherwise you can copy/paste there logic).

You should avoid to change the field of a column because it becomes a whole new column for us so you may loose things like resizing.
