### ISSUE TITLE
Unable to search in AutoComplete when used as ColumnMenu in DataGrid

### ISSUE THREAD

**Issue by sureshHARDIYA** [mui/mui-x#4083]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Sandbox

https://codesandbox.io/s/custommenutoolbar-evbmuz?file=/package.json

### Description

I have created a `customMenu` that renders MUI `Dialog` with `AutoComplete`. The rendering works fine. However, if you search in the AutoComplete, the popup closes for certain keys like `r`, `f`, `s`, `x`. 

### How to reproduce it. 
1. Click on three dots (...) beside any column name. 
2. From the dropdown select `Rename Column`.
3. Click on the `AutoComplete` field and type `r` or `f` or `s`. 
4. The popup closes. 

### Expected behavior 🤔

Should be able to search with all the letter. 

### Steps to reproduce 🕹

Steps:
1. Click on three dots (...) beside any column name. 
2. From the dropdown select `Rename Column`.
3. Click on the `AutoComplete` field and type `r` or `f` or `s`. 
4. The popup closes.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
That's because your `<AutoComplete />` is a child of a `<Menu />`

When you press <kbd>R</kbd> the event propagate from `<AutoComplete />` to `<Dialog />` to `<Menu />`. And since an item start by "R" (Rename Column) the `<Menu />` moves focus to `<MenuItem>Rename Column</MenuItem>`

That's why your input is losing focus.

Putting an input inside a menu item is really specific. I'm not sure we can handle that behavior. But you can solve your problem by adding `onKeyDown={(event) => event.stopPropagation()}` in the `<Dialog />`

https://codesandbox.io/s/custommenutoolbar-forked-syhljl?file=/demo.tsx

**Comment by sureshHARDIYA** [comment]
Thank you @alexfauquette. Your explanation makes sense. 

I agree that this is really specific to my case. The trick to `stopPropagation` worked fine.

**Comment by lucasbasquerotto** [comment]
If someone has this issue in a modal, you can add the `onKeyDown` event with the call to `stopPropagation` in the modal child.

Example:

```tsx
<Modal open={open} onClose={onClose}>
	<Box onKeyDown={(event) => event.stopPropagation()}>
		{children}
	</Box>
</Modal>
```
