### ISSUE TITLE
[data-grid] Last column don't have a right border

### ISSUE THREAD

**Issue by zromick** [mui/mui-x#4200]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://user-images.githubusercontent.com/12862442/158443912-2274bf4c-6af8-4dbb-9c0e-1ca3b7827954.png)

The above image shows a datagrid in which the widths of the columns do not reach the end of the datagrid.
Although showColumnRightBorder is set, there is no right border applied to the final column.

### Expected behavior 🤔

If the combined widths of the columns are less than the datagrid's width, apply a right border to the column header and all cells.

### Steps to reproduce 🕹

Steps:

1. Forked the codesandbox: https://codesandbox.io/s/datagrid-v5-quick-start-forked-ofi0il?file=/src/App.tsx
2. Added "showCellRightBorder"
3. Added "showColumnRightBorder"

### Context 🔦

Helps to add styling options to the table

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by zromick** [comment]
Similarly, a toolbar leaves the top of the datagrid without an option for a border (to separate the toolbar from te rest of the datagrid). Not sure if I should open a separate issue for that.

**Comment by alexfauquette** [comment]
@zromick About the toolbar border, you should be able to customize the Toolbar by using `sx` prop, `style` prop or by using template or CSS classes

**Comment by m4theushw** [comment]
You can display the border in the last column by enabling `disableExtendRowFullWidth`.

```tsx
<DataGrid
  rows={rows}
  columns={columns}
  showCellRightBorder
  showColumnRightBorder
  disableExtendRowFullWidth
/>
```

**Comment by zromick** [comment]
@alexfauquette Thanks for looking into it :))

with style: Didn't apply a border, possibly because I'm using a customToolbar and I lack know-how on supplying props to it
with sx: Works and extends fully

My implementation wasn't working because the GridToolbarContainer has a left and right padding of 4px:
![image](https://user-images.githubusercontent.com/12862442/159988132-2ab1ac10-7606-4dee-afaf-af0fd633ca43.png)

So this worked to remove the padding
`<GridToolbarContainer>
        <Grid
          container
          sx={{
            justifyContent: 'space-between',
            borderBottom: 1,
            borderColor: 'grey.300',
            margin: '-4px',
          }}
        >`

My vote would be to remove any padding provided on that component to allow the devs to configure it if it's needed

**Comment by ajgabryluk** [comment]
Sorry to resurrect this seemingly dead thread, but since none of the proposed solutions worked for me I'll say what fixed the right most border not showing up for me. Simply put, Datagrid automatically sets the width to 'fit-content', which cuts off the right most border. To fix this, all you need to do is manually set the width of the row to your desired size using the "& .MuiDataGrid-row" global class. In my case it looked like

 "& .MuiDataGrid-row": {
                border: "1px solid lightgray",
                borderRadius: "5px",
                backgroundColor: "white",
                **_width: "calc(100% - 2px)",_**
                marginTop: 3
              },

**Comment by petivagyok16** [comment]
I also have a problem: if there is only 1 item in the table the bottom bar cuts off its bottom border, and box-shadow too:


Bad:
<img width="585" alt="Screenshot 2023-08-11 at 9 53 58" src="https://github.com/mui/mui-x/assets/16253571/d3b7f064-8d9c-4da4-9f14-ebff342603b9">

Good:

<img width="571" alt="Screenshot 2023-08-11 at 9 54 45" src="https://github.com/mui/mui-x/assets/16253571/1705121d-cc53-4cc1-80fc-36c03bcb8b3d">


Also bad:
<img width="1276" alt="Screenshot 2023-08-11 at 9 53 06" src="https://github.com/mui/mui-x/assets/16253571/2344fa89-82c9-42b9-ac7d-c002c60eb8b2">

The dashed border coloring can be fixed by adding this to the cellClassName. I couldn't fix the box-shadow at the last element unfortunately
sx={{
          '& .customer-name-cell--empty': {
            border: '1px dashed',
            borderColor: '#ef5350',
            borderBottomColor: '#ef5350 !important'
          },

**Comment by alexfauquette** [comment]
This issue was closed 1 year ago. If you face a similar issue, please open a new one.
