### ISSUE TITLE
[DatePicker] using onBlur leads to inconsistency in the internal state

### ISSUE THREAD

**Issue by aaschmid** [mui/mui-x#4381]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Keep the `DatePicker` focused while using an `endAdornment` to clear its value. While clicking the clear button, the input fields value stays. The `onChange` event is triggered correctly, though. 

Problem appears since I added the followring to the clear buttons `onMouseDown` event:
 ```
const dontGrabFocusOnMouseDown = (event) => {
    event.preventDefault();
    event.stopPropagation();
  };
```

### Expected behavior 🤔

The input field value should be cleared as well. 
(hint: I use the same behavior with various versions `TextField` and `Autocomplete` where it works properly)

### Steps to reproduce 🕹

https://codesandbox.io/s/materialuipickers-material-demo-forked-s7umik?file=/demo.js

Steps to reproduce:
1. Focus the text field
2. Press the clear button

### Context 🔦

I have a customized `DatePicker` where I would like to add a clear button as `endAdornment` if focused (defined by our UX guideline). The input field of the `DatePicker` should stay focused such that I stopped propagating the mouse down event upwards clicking the clear button. This caused the issue.

### Your environment 🌎

```
  System:
    OS: macOS 12.3
  Binaries:
    Node: 16.14.2 - ~/work/customer/son/fe-repo/.direnv/node/bin/node
    Yarn: Not Found
    npm: 8.5.0 - ~/work/customer/son/fe-repo/.direnv/node/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Edge: Not Found
    Firefox: 99.0
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.6.0 => 11.6.0
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.75
    @mui/icons-material: ^5.1.1 => 5.1.1
    @mui/lab: ^5.0.0-alpha.76 => 5.0.0-alpha.76
    @mui/material: ^5.1.1 => 5.6.0
    @mui/private-theming:  5.6.0
    @mui/styled-engine:  5.6.0
    @mui/styles: ^5.1.1 => 5.1.1
    @mui/system:  5.6.0
    @mui/types:  7.1.3
    @mui/utils:  5.6.0
    @mui/x-date-pickers:  5.0.0-alpha.0
    @types/react: ^17.0.34 => 17.0.34
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.4.4 => 4.4.4
```

**Comment by alexfauquette** [comment]
If I understand, the problem is that the value is `null` but the component does not render this new value.

Sounds the problem comes from [here](https://github.com/mui/mui-x/blob/ba1888601852f9be2fc1d279340cd1532e35903a/packages/x-date-pickers/src/internals/hooks/useMaskedInput.tsx#L68-L75) 

The internal value is not updated if the value modification comes from typing in the field. Maybe to avoid an infinite loop.

The problem is that with your `onBlur` you override the `onBlur` of the hook, so it's not aware that you are on the button instead of the <input/>

We should fix it. As a workaround, you can move the focus blur listener to the `<input/>` component instead of the root element as follow

https://codesandbox.io/s/materialuipickers-material-demo-forked-bg1yrf?file=/demo.js:1405-1406

**Comment by aaschmid** [comment]
Thanks for the answer @alexfauquette. I can further try your workaround tomorrow, thanks. I will provide an example of `TextField` most likely tomorrow...

**Comment by aaschmid** [comment]
Had time to do the example quickly now: https://codesandbox.io/s/materialuipickers-material-demo-forked-up21g6?file=/demo.js
Your workaround works!

**Comment by alexfauquette** [comment]
Thanks for your example, I keep the issue open until we fixed this `onBlur` issue

**Comment by PatrykFij** [comment]
Ok, it looks good for fully filled date in mask input but what if we have not completely filled date? Why clear doesn't work ?

Imo it looks like validating the input interferes with cleaning.

**Comment by alexfauquette** [comment]
@PatrykFij Thanks for pointing out this bug.

The problems come from the same lines. The update is done only when the internal value and the proposed value are different.

This is checked as follow: `const valueChanged = previousInputValueRef.current !== currentInputValue;`

The problem is that `null` of invalid date both return an empty string. So moving from invalid to `null` leads to `valueChanged=false` and so no update of the internal value.

I do not think there is a workaround for this bug. We should rethink the internal state management of this commponent
