### ISSUE TITLE
[pickers] DatePicker can't be imported from `@mui/x-date-pickers-pro/DatePicker`

### ISSUE THREAD

**Issue by zzossig** [mui/mui-x#4434]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I was trying to migrate date-picker from the lab.

1. I have installed @mui/x-date-pickers-pro
2. DatePicker not found
```javascript
// module not found error
import { DatePicker } from "@mui/x-date-pickers-pro/DatePicker";
```

### Expected behavior 🤔

DatePicker should be exported from `@mui/x-date-pickers-pro`

### Steps to reproduce 🕹

Steps:

1. install @mui/x-date-pickers-pro
2. import DatePicker component
3. but the module is not found.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

You can find the migration guide [here](https://mui.com/x/react-date-pickers/migration-lab/) (it is not easily accessible on the website, we are actively working on fixing that).

But basically, we took the decision to not re-export the sub-packages from `@mui/x-date-pickers`

So you can do

```ts
import { DatePicker } from '@mui/x-date-picker'
import { DatePicker } from '@mui/x-date-picker/DatePicker'
import { DatePicker } from '@mui/x-date-picker-pro'
```

But not

```ts
import { DatePicker } from '@mui/x-date-picker-pro/DatePicker'
```

This is because we did not create a folder for each "Community Plan" component in the "Pro Plan" package just to re-export the component.

The rational behind this is that sub-packages are not as important of the new packages as they are on `@mui/material` or `@mui/lab` because there is a lot less components so it is not very heavy to load everything in dev mode.
Not that in production, our packages support tree shaking so doing `import { DatePicker } from '@mui/x-date-pickers-pro'` should not bundle the components you are not using.

But it is not a decision impossible to change.
And if we have enough feedbacks we can add those "Community Plan component" sub-packages on `@mui/x-date-pickers-pro`

**Comment by zzossig** [comment]
Thank you for the detailed answer.
As a pro plan user, I thought that it is weird to import components from "Community Plan" package, not from "Pro Plan" package.

It seems that some components are not exported from "Pro Plan" package.
So I have to import components like this.
```javascript
// "Community Plan"
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns"; 
// "Pro Plan"
import { DatePicker, LocalizationProvider } from "@mui/x-date-pickers-pro";
```

But I don't think this is important as it is a matter of personal preference.
So, I'm closing this issue.
