### ISSUE TITLE
[DatePicker] `disableHighlightToday` not working properly

### ISSUE THREAD

**Issue by amthoms2** [mui/mui-x#4443]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

"disableHightLightToday" not working properly.
 
"It looks too much like the user has already selected a date, but when there are no appointments available for today, i'd like to not only have it greyed-out like the rest, but to actually not have it highlighted at all. I'd still like other days highlighted when they are selected, so I don't want to remove the highlight class from CSS, but an invalid date shouldn't be highlighted, even if it is today, because there are no appointments today in this case, so the date is not selected."

I've tried 

`return (
    <LocalizationProvider dateAdapter={AdapterDateFns}>
      <Stack spacing={1}>
        <MobileDatePicker
          label="Select Date"
          value={value}
          disableHighlightToday
          //disableHightLightToday={true} 
          showTodayButton={false}
          onChange={(newValue) => {
            setValue(newValue);
          }}
          renderInput={(params) => <TextField {...params} />}
        />
      </Stack>
    </LocalizationProvider>
  );
}`

### Expected behavior 🤔

Current date should not be highlighed

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
[Reproduction case](https://codesandbox.io/s/date-and-time-pickers-forked-f82r40?file=/src/App.tsx)

@amthoms2 I don't understand what you are trying to achieve
On the code you gave (which I used to make the codesandbox linked above), you have `disableHightLightToday` set to `true`, which removes the special CSS applied on the current day.

What do you mean by "not have it highlighted at all" ?
Could you fork my example to show exactly your problem ? The only CSS specific for the current day I see is the grey circle of the focus because the current day is focused by default when opening the calendar.
