### ISSUE TITLE
[DatePicker] Date format not working when user tries to input the date manually and the input field accepts alphabets as well

### ISSUE THREAD

**Issue by Anusha-HT** [mui/mui-x#4468]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When we start typing in the input field its not formatting the date and input accepting alphabets as well
![image](https://user-images.githubusercontent.com/89907130/158682783-f3f0e510-bba6-4b71-b2f6-7eac639776ef.png)

### Expected behavior 🤔

date should format as soon as user input and it should not accepts alphabets

### Steps to reproduce 🕹

Steps:

1.mui/lab
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

chrome

**Comment by flaviendelangle** [comment]
@sweetkane feel free to open a pull request to solve this problem, I will review it :+1:

**Comment by alexfauquette** [comment]
@Anusha-HT Could you provide a reproduction of your bug. By default, the `DatePicker` is working correctly. The only way to reproduce your problem is to put a wrong `mask`/`inputFormat` props

Here is a codeSandbox with a simple `DatePicker` and one with wrong mask`/`inputFormat` props. Notice the warning in the console
> The mask ... you passed is not valid for the format used ..... Falling down to uncontrolled not-masked input.

https://codesandbox.io/s/basicdatepicker-material-demo-forked-8rljjw?file=/demo.js
