### ISSUE TITLE
DataGrid cell validation does not display validation message

### ISSUE THREAD

**Issue by nickraphael** [mui/mui-x#4481]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I've followed the documentation regarding validation.  However, I can't see a way to display the actual validation failure message under the input control.  Validation failures usually display text detailing the reason for the failure.  The examples just style the input as red.

I'm happy using the default edit controls (type: 'number') and would like to avoid implementing renderEditCell.  Unless I can leverage the default behaviour somehow - perhaps using renderEditCell to render the default control + a conditional validation message?

Can anyone steer me right?

Kind regards
Nick

### Expected behavior 🤔

Validation failure should display a validation failure message.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
We don't display the error message because the `error` prop can be anything. It could be a simple string but also an `Error` object. Instead, it's up to you to display the message, we only care if it's defined or not. The docs for [validation](https://mui.com/x/react-data-grid/editing/#validation) using the new editing API has an example showing how to display the error inside a tooltip. Are you looking at the same page?

![image](https://user-images.githubusercontent.com/42154031/163080924-ec92c7f7-4cc0-477d-a62c-b76a8694a4d6.png)

The examples for persistence also show the error coming from the server, but a global message instead of one per field.

**Comment by nickraphael** [comment]
Holy baloney!!!  That's exactly what I want!  Excellent.  Thank you!
