### ISSUE TITLE
[TimePicker] "Mask" prop on TimePicker doesn't seem to do anything

### ISSUE THREAD

**Issue by alextenb** [mui/mui-x#4488]
Hi,

Thanks for all your hard work, love MUI, please keep it up.

The "mask" prop on TimePicker doesn't seem to enforce any formatting for input the way it does on DatePicker. Here's a codesandbox demonstrating the behavior. As you can see, you can only type numbers into the DatePicker, and they conform to the __/__/____ mask. But you can type anything into the TimePicker.

https://codesandbox.io/s/basicdatepicker-material-demo-forked-dwm8x?file=/demo.js

**Comment by flaviendelangle** [comment]
I agree that having `true` as the default value of `props.disableMaskedInput` makes the DX weird when you provide a custom mask.

I don't know this part of the codebase enough yet.
Maybe `props.disableMaskedInput` could only have an impact when using the default masks.

**Comment by alexfauquette** [comment]
Agree, it is a weird default value. Notice that the input needs also to have an `inputFormat` which matches the `mask`

Here is a demo with the workaround proposed by @dajxd 

https://codesandbox.io/s/basicdatepicker-material-demo-forked-4q7uwb?file=/demo.js

**Comment by alexfauquette** [comment]
@dmtrKovalenko Do you remember why this `disableMaskedInput` has been added?

I managed to find the commit where you add its default values but the link to the PR description is a wrong one https://github.com/mnajdova/material-ui/commit/97aa0a7985c42cf46c7fa5431ea25fb360d1e1b7

**Comment by dmtrKovalenko** [comment]
I am not sure, may be because for luxon we couldn't generate the format text or just as an option, don't know why it becomes true by default.

**Comment by ioev** [comment]
Having the same problem, using the LuxonAdapter.  There is no mask by default, and specifying one doesn't do anything.

**Comment by alexfauquette** [comment]
@ioev Did you tried the workaround proposed? https://github.com/mui/mui-x/issues/4488#issuecomment-1098929737

If it does not work with it, please provide a codesandbox such that we can reproduce and solve it

**Comment by ioev** [comment]
I'm actually not sure what the fix is? disabledMaskedInput={false} did nothing.

I took your demo of the fix and changed it to use AdapterLuxon:
https://codesandbox.io/s/basicdatepicker-material-demo-forked-t4ndne?file=/demo.js

**Comment by alexfauquette** [comment]
@ioev I was wondering why the warning was disabled for luxon, thanks to you I know :)

The problem is that Luxon short date format does not provide a consistent length. It can return `1/1/1987` and `16/11/1987` such that mask is always invalid for dates. You can solve this problem by providing a more specific `inputFormat`

```jsx
mask="__/__/____"
inputFormat="dd/MM/yyyy"
```

Here is the corrected version

https://codesandbox.io/s/basicdatepicker-material-demo-forked-m8ni4i?file=/demo.js

**Comment by ioev** [comment]
This works!

Though is there any way we can also have this display the format hint?  Normally it would show "hh/mm/yyyy" as placeholder text, but when using luxon (and with this solution) it doesn't anymore.  I assume because we're using a custom inputFormat we would also specify a custom "formatHint" is such a prop existed.

**Comment by alexfauquette** [comment]
@ioev This issue is close, about your question, if you need more information, we can continue in the issuer dedicated to Luxon format/helper #4755
