### ISSUE TITLE
[DesktopTimePicker] Can't dismiss/close the time picker using escape key if opened from within a Dialog

### ISSUE THREAD

**Issue by simonbaas** [mui/mui-x#4489]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If the **DesktopTimePicker** is opened from within a Dialog you cannot dismiss (or close it) using escape key.

### Expected behavior 🤔

If not opened from within a Dialog the picker can be dismissed/closed using escape key.

### Steps to reproduce 🕹

Steps:

1. Add a Dialog and a DialogContent component
2. Put you DesktopTimePicker within the DialogContent component
3. Open the picker using the icon
4. Try to close it using escape key

https://codesandbox.io/s/responsivetimepickers-material-demo-forked-3qiglo?file=/demo.js

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

System:
    OS: macOS 11.6.4
  Browsers:
    **Chrome: 99.0.4844.51**
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.3
</details>

**Comment by alexfauquette** [comment]
The problem comes from the [modal that stop event propagation for Escape](https://github.com/mui/material-ui/blob/de11911f2e3b15b9fe07ce2625a3ce1cc593093c/packages/mui-base/src/ModalUnstyled/ModalUnstyled.js#L224:L231), whereas the `<PickersPopper />` used for desktop components set the `keyDown` listener on the `document`. Then it never get keydown event.

A solution could be to follow the same idea as the modal. We set the `onKeyDown` at the root of `<PickersPopper/>` and stop its propagation
