### ISSUE TITLE
How to style ActionsCell MenuList within the DataGrid

### ISSUE THREAD

**Issue by mtshv** [mui/mui-x#4495]
### Order ID 💳

#36792

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi guys! I am struggling to find a correct/recommended way of styling the menu list of the actions Cell:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/11422166/163251523-976631e0-f0a7-4faf-a5b9-ed927d35d987.png">

I was expecting something like this to work:
```
"& .MuiDataGrid-menuList": {
    background: "red"
}
 ```
 
 [CodeSandbox](https://codesandbox.io/s/columntypesgrid-material-demo-forked-gj70h6?file=/demo.tsx:2400-2470)
 
But it does not solve this issue. I assume that the problem that I am having is due to the fact that MenuList is rendered in the paper component, outside of the DataGrid itself.

How would you recommend styling this particular menu list aside from other menu lists (column menu, toolbar columns menu, etc)?

**Comment by alexfauquette** [comment]
Hi, you assume weel, the menu components are popper and so rendered outside of the grid. Then adding a CSS on the grid root component doe not affect them since they are not a child of this element.

To customize items rendering, you can directly use `sx` props on `GridActionsCellItem`

If you want to customize the list parent you can pass props to the popper component using `componentsProps.basePopper`

I modified your codesanbox with the two methods.

https://codesandbox.io/s/columntypesgrid-material-demo-forked-h8rho1?file=/demo.tsx

Notice that the second method impacts all the popper used in the grid (for example the column menu). The idea is that a popper design should be consistent across the grid. Do you have a context scenario in which it is not the case?

**Comment by mtshv** [comment]
Thank you so much for the detailed answer @alexfauquette.
No, I do not have the scenario where popper should have a different design across the grid at the moment.
