### ISSUE TITLE
[DataGrid] Header scroll lag (especially on mobile devices)

### ISSUE THREAD

**Issue by janis-rudis** [mui/mui-x#4506]
### Current behavior 😯

The DataGrid Header part seems to lag behind user input on touch devices when the Grid is horizontally scrollable. If user input is too 'vigorous'  can cause the header part to be completely misaligned and stuck. I tested it on tablets and phones. It seems a consistent issue, tet seems that smaller devices have more issues. (Phones, 7" tablets). 

https://github.com/mui/mui-x/assets/13808724/7e3c784a-1094-47b6-9236-61fa330c4167

The desktop version is fine.

### Expected behavior 🤔

Should be the same speed.

### Steps to reproduce 🕹

Steps:

1. DataGrid with a horizontal scroll
2. Touch Device input 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Unfortunately, this is the trade-off of the virtualization implementation we use. I explained more about it in https://github.com/mui/mui-x/pull/2673#issue-1004950963 The column headers lag behind the content because they're updated in the main thread at intervals, while the content scroll runs in a dedicated thread.

> Should be the same speed.

As I explained in the PR we could force both to be at the same speed, but what we'll actually do is to slow down the scrolling of the content to match with the headers. Currently, the scrolling of the content has the same performance as scrolling a long page. If both are synced you may see micro stutters not only on the headers but also on the content.

**Comment by DevPowers** [comment]
Seconded ! Found this issue as well for all my tables on mobile with horizontal scroll

**Comment by cherniavskii** [comment]
Hi there!
We have reworked the column headers and improved the horizontal scrolling experience in v7, which is [currently in beta](https://github.com/mui/mui-x/releases)! 🎉
You can try out the new Data Grid in the v7 beta docs: https://next.mui.com/x/react-data-grid/

Upgrading from Data Grid v6? Follow our [migration guide](https://next.mui.com/x/migration/migration-data-grid-v6/).
New to the Data Grid? Follow our [installation guide](https://next.mui.com/x/react-data-grid/getting-started/#installation).
Let us know what you think!
