### ISSUE TITLE
[pickers] Unit test fails on master

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#4509]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
<DateTimePicker /> prop `showToolbar` – renders toolbar in DateTimePicker FAILED
TestingLibraryElementError: Found no element with the data-mui-test attribute of: picker-toolbar
```

https://app.circleci.com/pipelines/github/mui/mui-x/16779/workflows/79607ebf-c213-46d4-b2d6-ff4cafc1c2ca/jobs/97926

Indeed, toolbar is not rendered on desktop, but it looks like it's not supposed to be rendered: https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx#L85
The test was added in https://github.com/mui/mui-x/pull/4451/files#diff-229c2675e7f2d80b662fd51d18233c3ce74e3c073e49a8375e0fa504cbbcbe0bR22

### Expected behavior 🤔

All tests pass

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
cc @alexfauquette @flaviendelangle

**Comment by m4theushw** [comment]
https://github.com/mui/mui-x/blob/b6e06bba9abbb9e33ec433bbb514571013270b7b/packages/x-date-pickers/src/DateTimePicker/DateTimePicker.tsx#L51

It fails because `isDesktop` is `true` with `yarn test:karma` but `false` with `yarn test:unit`. As consequence, toolbar is only rendered on mobile.

https://github.com/mui/mui-x/blob/b6e06bba9abbb9e33ec433bbb514571013270b7b/packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx#L85

**Comment by m4theushw** [comment]
@flaviendelangle What would you prefer to be done here?

**Comment by flaviendelangle** [comment]
I would move it to `MobileDateTimePicker` to only have responsive-invariant tests in the responsive test files
