### ISSUE TITLE
[DateRangePicker] Some text is not being translated

### ISSUE THREAD

**Issue by Daria-Kuzminykh** [mui/mui-x#4551]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Some text is not translated in MobileDateRangePicker
![image](https://user-images.githubusercontent.com/75027465/151939373-14e7c5e7-d8a5-457b-a117-a12f996080ae.png)

### Expected behavior 🤔

All texts translated in MobileDateRangePicker

### Steps to reproduce 🕹

I'm use moment.locale for translation

LocalizationProvider dateAdapter={DateAdapter} locale={moment.locale(i18n.language)}

Steps:

1. Create MobileDateRangePicker
2. Use locale 'ru'

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Hi, thanks for raising this issue. It's a confusing topic we should clarify in the doc.

The `LocalizationProvider` is here only to translate date, because this translation relies on third party libraries.

For texts such as "Select date range" the modification is done by `toolbarTitle` prop of [DateRangePicker](https://mui.com/x/api/date-pickers/date-range-picker/)

**Comment by Daria-Kuzminykh** [comment]
Okey, thanks for your answer!

**Comment by flaviendelangle** [comment]
Closing it in favor of #4500 to centralize changes related to the localization.
