### ISSUE TITLE
[DateRangePicker] In static mode, we can't choose to edit the `end` date then the `start` date

### ISSUE THREAD

**Issue by Krasnopir** [mui/mui-x#4564]
Hello. Maybe somebody know, is it possible for a static mode to choose which date is selected first "Check-in"(start) or "Check-out"(end)?

https://next--material-ui.netlify.app/ru/components/date-range-picker/#static-mode

Thank for  answer. sorry for issue

**Comment by MohanadTafeal** [comment]
I have a question if anyone please can help me.
how can I add the ability -if the date in different year - to let the user click in the year to change the year first then choose the day. 
in DateRangePicker. please if anyone one know. thanks and sorry for my poor English.

**Comment by flaviendelangle** [comment]
@gerdadesign on the [Static Date Range Picker](https://mui.com/x/react-date-pickers/date-range-picker/#static-mode), if we allow  the app to say "I want to first select the end date and then the start date".
Do you think we need to add a visual feedback somewhere to show that it's the end date that will be selected on click.
Or would the context in the app be enough ?

**Comment by gerdadesign** [comment]
Hoping I understand this correctly! I would imagine the context should prep the user for selecting an end date first. 

For visual feedback and looking at the current behaviour, I think we are reliant on the hover indicator here. In static mode, if the date first selected is the end date, I would expect the dashed border to appear when I hover behind the selected date. Much like how it does when you select "Check out" first in non-static mode.

**Comment by flaviendelangle** [comment]
On the new pickers, we would just have to add a `defaultRangePosition` prop on static range pickers (jinterface `StaticRangeOnlyPickerProps`) and initialize `rangePosition` with it in `useStaticRangePicker`.

If people need to fully control this state, we could expose a `rangePosition` and `onRangePositionChange` props as well and set a `useControlled` instead of the `useState` used for `rangePosition` in `useStaticRangePicker`.
