### ISSUE TITLE
[data grid] `apiRef` `restoreState` and `exportState` does not support the density

### ISSUE THREAD

**Issue by vakha30** [mui/mui-x#4572]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The density state is not saved. All other state is saved correctly

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Do you mean it is not saved when using `apiRef.current.exportState` ?
If so, yes we did not add it yet

**Comment by vakha30** [comment]
Yes, I meant it. Thanks

**Comment by flaviendelangle** [comment]
Oops forgot to remove the label

**Comment by vaclav-slavik** [comment]
> Hello, @flaviendelangle, i have the same problem. Do you know when density will be supported in apiRef.current.exportState? Thank you :)

Plus one. At the meantime, I'm using workaround (storing the user selected density separate from the rest of the datagrid state), but it would be great to have the support for it in the `exportState` and `restoreState`.

**Comment by flaviendelangle** [comment]
@joserodolfofreitas @m4theushw, I'm the only one notified so I'm adding you to the loop

**Comment by rubenprodev** [comment]
Hi there, is there any news about it? An `onDensityChange` added to the [catalog of events](https://mui.com/x/react-data-grid/events/#catalog-of-events) would be awesome!

**Comment by LironKiloma** [comment]
Hey, I'm joining to the support of density save in the state, would be great to have it

**Comment by ArmandRedgate** [comment]
Hello all,

This issue is causing us pain at the moment, as our customers expect us to save their DataGrid preferences, but there is no way to do so with density specifically.

In the end, we had to do the following ugly workaround:

- **Write and maintain** our own version of the [GridToolbarDensitySelector](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx) that uses externally managed state (getter and setter)
- Detect user changes to that dropdown
- Save those values to local storage separately from the rest of our `GridInitialState` data
- Update via the `density` prop in `DataGridPro`

We've spent hours looking for another way of doing this, but it was our only option.

Like everyone else, we'd like to see density be properly supported in `initialState`, `apiRef.current.exportState` and `apiRef.current.restoreState`.

**Comment by flaviendelangle** [comment]
cc @cherniavskii 
Adding it to your backlog grooming

**Comment by jmcpeak** [comment]
> Hello all,
> 
> This issue is causing us pain at the moment, as our customers expect us to save their DataGrid preferences, but there is no way to do so with density specifically.
> 
> In the end, we had to do the following ugly workaround:
> 
> * **Write and maintain** our own version of the [GridToolbarDensitySelector](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx) that uses externally managed state (getter and setter)
> * Detect user changes to that dropdown
> * Save those values to local storage separately from the rest of our `GridInitialState` data
> * Update via the `density` prop in `DataGridPro`
> 
> We've spent hours looking for another way of doing this, but it was our only option.
> 
> Like everyone else, we'd like to see density be properly supported in `initialState`, `apiRef.current.exportState` and `apiRef.current.restoreState`.

We are in the exact same boat. We did purchase 4 licenses of data-grid-pro. Anything else you need from me to help move it to the top of the backlog?

**Comment by brendonrapp** [comment]
Running into this limitation now as well. The idea of doubling the number of saved states that we're managing so that each table can have a separate density state maintained is unappealing. Feels like a weird omission in an otherwise uniform and easily-managed table state system.

**Comment by jmcpeak** [comment]
I'll try and get a PR out with a fix on Monday
