### ISSUE TITLE
[question] [DataGridPro]

### ISSUE THREAD

**Issue by JPTeasdale** [mui/mui-x#4573]
### Order ID 💳

28858

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

When scrolling through virtualized rows the rows that haven't rendered yet are blank. No grid delineation/etc. Is there an option to specify a lightweight placeholder component to render in place of nothing? Maybe with an increased collum buffer?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.4.0 => 11.8.1
    @emotion/styled: ^11.3.0 => 11.8.1
    @mui/base:  5.0.0-alpha.72
    @mui/core:  5.0.0-alpha.51
    @mui/icons-material: ^5.0.5 => 5.5.0
    @mui/lab: ^5.0.0-alpha.51 => 5.0.0-alpha.51
    @mui/material: ^5.5.1 => 5.5.1
    @mui/private-theming:  5.4.4
    @mui/styled-engine:  5.4.4
    @mui/system:  5.5.0
    @mui/types:  7.1.3
    @mui/utils:  5.4.4
    @mui/x-data-grid:  5.8.0
    @mui/x-data-grid-pro: ^5.8.0 => 5.8.0
    @mui/x-license-pro:  5.7.0
    @types/react: ^17.0.11 => 17.0.39
    react: ^16.4.1 => 16.14.0
    react-dom: ^16.4.1 => 16.14.0
    typescript: ^4.6.2 => 4.6.2
```
</details>

**Comment by cherniavskii** [comment]
Hey @JPTeasdale 

> When scrolling through virtualized rows the rows that haven't rendered yet are blank

I believe those are not blank rows, just the rows that have not been rendered yet.

> Is there an option to specify a lightweight placeholder component to render in place of nothing?

I don't think so, since rows are rendered as soon as possible, but there can be noticeable delay depending on scroll speed.
So as soon as row can be rendered - it is rendered with the data that's already available on the client.

> Maybe with an increased collum buffer?

Did you mean row buffer? You can definitely increase it using `rowBuffer` prop: https://mui.com/x/api/data-grid/data-grid/#props
