### ISSUE TITLE
[pickers] Missing emptyLabel feature on datepicker and timepicker

### ISSUE THREAD

**Issue by sergioavazquez** [mui/mui-x#4592]
In `material-ui-pickers` there's a feature that allows you to set a custom label when the value of the picker is null.
 
Prop name is `emptyLabel` and has the following description: `Message displaying in text field, if null passed`

You can read about it here: https://material-ui-pickers.dev/api/KeyboardDatePicker

- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

I also added a question on StackOverflow in case there's a workaround but haven't found any: https://stackoverflow.com/questions/69815113/how-to-set-an-empty-label-on-material-ui-v5-mui-lab-datepicker-component

## Summary 💡

Provide an `emptyLabel` or similar prop to all date and time pickers so a string can be displayed when the value of the picker is null. 

## Examples 🌈

When the value of the date or time picker is null, instead of showing a blank input display the `emptyLabel` string instead. 

## Motivation 🔦

This feature is present in `material-ui-pickers` and I depend on it to provide useful information to the user when the picker has a `null` value. I'm migrating an app to MUI v5 and replacing `material-ui-pickers` with `@mui/lab` versions but this missing feature prevents me from moving on with it.

**Comment by flaviendelangle** [comment]
Waiting for #4517

**Comment by LukasTy** [comment]
Am I missing something, but isn't the described behavior the responsibility of the `placeholder` attribute/prop? 🤔 
Here is an [example codesandbox](https://codesandbox.io/s/placeholder-mui-v5-xtnzz5).

But this reminds me of another concern I had with v6 pickers (fields).
What do you think about the UX/UI issue of forms with multiple inputs looking weird when using the v6 picker, because even with empty value the pickers/fields will seem like they have a value, which will make them clearly stand out in any form?
@flaviendelangle @alexfauquette @joserodolfofreitas @gerdadesign 

Here is [an example](https://codesandbox.io/s/v6-form-discrepancy-f8g5vw) of what I'm talking about.

**Comment by LukasTy** [comment]
During the grooming, we decided on the following idea to experiment with its feasibility in order to achieve similar UX (behavior) to existing (v5) pickers:
- while `value` is empty and input is not focused—remove the `placeholder` value we currently have
  - this would in turn remove the visual difference in a form having different MUI inputs
- when input is focused—add the `placeholder` `value` we currently have
  - experiment with feasibility of changing the color of `format placeholder`, while value is empty to the one used for actual placeholder to better mimic the "placeholder" behavior (visual feedback)
