### ISSUE TITLE
[pickers] Incorrect typing for `LocalizationProvider::locale` prop

### ISSUE THREAD

**Issue by smac89** [mui/mui-x#4598]
When  using `date-fns` adapter, the constructor for the adapter expects a `Locale` object from `date-fns`, however the type suggests we can pass a string, which leads to runtime errors.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Currently, the type for the `locale` prop to `LocalizationProvider` is a union consisting of `Locale` and `string`, but it should only accept `Locale`. As you can see here:

https://github.com/dmtrKovalenko/date-io/blob/b919b995f7697468b096712a46be666492ca71b8/packages/date-fns/src/date-fns-utils.ts#L90-L96

## Expected Behavior 🤔

The prop should not allow strings
## Steps to Reproduce 🕹
Use `string` locale prop

Sandbox: https://codesandbox.io/s/epic-gagarin-3oznz

**Comment by alexfauquette** [comment]
If I resume, the `date-fns` requires an `object` for the locale, and the other ones (`moment`, `day-js`, and `luxon`) require a `string`.

Not sure we can do better with typescript because the date-io adapters  implements `IUtils<DateTime>` which is defined as follow:
```ts
export interface IUtils<TDate> {
  formats: DateIOFormats<any>;
  locale?: any;
  moment?: any;
  dayjs?: any;
  /** Name of the library that is used right now */
  lib: string;
  ...
```

I see two solutions:
- Put a warning in the documentation about this specificity of date-fns
- Add an error when instantiating the adapter to check format type (see #4615)
