### ISSUE TITLE
[data grid] Export state with hidden columns

### ISSUE THREAD

**Issue by MrTost** [mui/mui-x#4620]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When there is hidden column, the apiRef.current.exportState() does not include columnVisibilityModel.
It only works when there is at least one hidden column added to the initialState.

### Expected behavior 🤔

Hide columns should be exported and restored correctly without initialState.

### Steps to reproduce 🕹

Steps:

1. go to https://mui.com/x/react-data-grid/state/#save-and-restore-the-state
2. click on any three dots at the first table header
3. go to "show columns"
4. click "show all"
5. click "recreate the 2nd grid"
6. the ID column is not added to the second grid

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
We only include in the exported state the columns that are hidden. If the column became visible it won't be included.

https://github.com/mui/mui-x/blob/dc71bd7b4d74cf8c2e7b0028bd0efb551c566eac/packages/grid/x-data-grid/src/hooks/features/columns/useGridColumns.tsx#L316-L318

Including all columns in the export, no matter if they are already visible during initialization, might be a waste of resources. At the same time, checking if the visibility, while exporting, is different than the visibility that the column had when initialized is complex, because the visibility model can be updated from two sources: `initialState` and `columnVisibilityModel`. I think one solution could be to track which columns the user changed the visibility. We have something similar to detect resized columns: `colDef.hasBeenResized`. Adding @flaviendelangle since he implemented this part.

**Comment by m4theushw** [comment]
I took a second look at this problem. The idea in https://github.com/mui/mui-x/issues/4620#issuecomment-1109206658 probably won't work. As a quick solution we could always export `columnVisibilityModel` if there's at least one key.

**Comment by flaviendelangle** [comment]
> As a quick solution we could always export columnVisibilityModel if there's at least one key.

The problem is that when showing all columns, the model is empty.
We could create a model with all columns visible but I'm not sure it's the right solution.

I feel like the idea of cherry picking the state exported in a smart way is not good and is the cause of a certain amount of problems
