### ISSUE TITLE
[question] How to column width contained content?

### ISSUE THREAD

**Issue by linojon** [mui/mui-x#4648]
### Order ID 💳

41465

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm having a lot of difficulty setting the column widths of my grid so the content of a cell doesnt get clipped. Is there a way to automatically adjust the widths to ensure existing content is not truncated? 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by joserodolfofreitas** [comment]
Hi @linojon,

If I understand your use case correctly, you could use the flex property like in the following example:
https://codesandbox.io/s/columnwidthgrid-material-demo-forked-l7z789?file=/demo.js

If that doesn't solve your case, would you mind setting up a codesandbox to explain your issue?

**Comment by m4theushw** [comment]
This was not implemented yet. You can upvote https://github.com/mui/mui-x/issues/1241 What will be soon available is the ability to automatically adjust the row height to fit the content. This feature is being developed in https://github.com/mui/mui-x/pull/4859. The column widths still need to be provided but the content will not be clipped. I'll close this issue since there's already one asking for the same feature.
