### ISSUE TITLE
[pickers] Masking is broken with `MM/yyyy` format and views prop

### ISSUE THREAD

**Issue by benjamin-andersen** [mui/mui-x#4664]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the `inputFormat` prop set to `'MM/yyyy'`, the masking is broken. Adding a custom rifm formatter doesn't seem to help.

https://user-images.githubusercontent.com/70706530/150567891-60b109ae-92ac-419a-9d94-6cd4e05c0554.mp4

### Expected behavior 🤔

The masking shouldn't break when using a `'MM/yyyy'` format.

### Steps to reproduce 🕹

This was forked from the official template for the basic example of date picker usage:

https://codesandbox.io/s/basicdatepicker-material-demo-forked-2ey8d?file=/demo.tsx

### Context 🔦

I'm trying to have my date formatted like `'MM/yyyy'`. Examples are:
- 01/2022
- 12/1989

### Your environment 🌎

Was reproduced on the mui template from code sandbox (see above).

**Comment by flaviendelangle** [comment]
@alexfauquette I think you worked on related topics

**Comment by alexfauquette** [comment]
@cati97 bring a good workaround

The problem seems to come from default settings.

`useDatePickerDefaultizedProps` is using `...getFormatAndMaskByViews(views, utils),` to set the `inputFormat`, `mask` and `disableMaskedInput`.
In the codesandbox example, the `inputFormat` and the `mask` are override by the provided props, but not the `disableMaskedInput` added when there is only month and years.

https://github.com/alexfauquette/material-ui-x/blob/e1b3a6d5804975bdbdf0d735ece812fcf5e16ac6/packages/x-date-pickers/src/DatePicker/shared.ts#L70:L75
```js
  if (isYearAndMonthViews(views)) {
    return {
      disableMaskedInput: true,
      inputFormat: utils.formats.monthAndYear,
    };
  }
```

---

I see two solutions:

- remove the default values for month and year. or set them numerical like in the proposed codesandbox, at least until we manage to handle "Jan", "Fev", ... in the masked input
	- Pro: it avoids having `disableMaskedInput=true` in the default whereas we recommend avoiding it in the doc
	- Cons: It's a breaking change
- do not apply default as soon as one of `inputFormat`, `mask`, `disableMaskedInput` is set
	- Pro: As soon as the `mask` is set, setting the `inputFormat` will have to be adapted so its does not makes sens to add a default for one and use a custom props for the other
	- Cons: hard to explain that de default value is not applied depending on another prop

---

Personally, I prefer the first option, because `monthAndYear` format does not change with the localization. It is not `year-month` for some country and `month-year` for others. The order is fixed by date-io so I do not see any problem to do the same but with numbers instead a natural language for months
https://github.com/dmtrKovalenko/date-io/blob/f96f0929e1a4020db1b171416e18c0e314ee9a31/packages/date-fns/src/date-fns-utils.ts#L74-L75
```js
  monthAndYear: "LLLL yyyy",
  monthShort: "MMM",
  ```

If you have another idea, or find the other solution more suitable, feel free to add a comment
@flaviendelangle

**Comment by alexfauquette** [comment]
This has a problem with special date formatted such as hijri which uses `iMM` for months, so either 
1. we propose in date-io a new feature to get month/year digits, but using them does not solves digit order (following locales supported by core set year first: `'az-AZ'`, `'zh-CN'`, `'zh-TW'`, `'hu-HU'`, `'ja-JP'`, `'ko-KR'`, `'sv-SE'`)
2. we remove the custom default. Even if the views contain yearn and month, we add a demo for this specific case to show how to manage `inputFormat` and `mask`

**Comment by filliperomero** [comment]
> @cati97 bring a good workaround
> 
> The problem seems to come from default settings.
> 
> `useDatePickerDefaultizedProps` is using `...getFormatAndMaskByViews(views, utils),` to set the `inputFormat`, `mask` and `disableMaskedInput`. In the codesandbox example, the `inputFormat` and the `mask` are override by the provided props, but not the `disableMaskedInput` added when there is only month and years.
> 
> https://github.com/alexfauquette/material-ui-x/blob/e1b3a6d5804975bdbdf0d735ece812fcf5e16ac6/packages/x-date-pickers/src/DatePicker/shared.ts#L70:L75
> 
> ```js
>   if (isYearAndMonthViews(views)) {
>     return {
>       disableMaskedInput: true,
>       inputFormat: utils.formats.monthAndYear,
>     };
>   }
> ```
> 
> I see two solutions:
> 
> * remove the default values for month and year. or set them numerical like in the proposed codesandbox, at least until we manage to handle "Jan", "Fev", ... in the masked input
>   
>   * Pro: it avoids having `disableMaskedInput=true` in the default whereas we recommend avoiding it in the doc
>   * Cons: It's a breaking change
> * do not apply default as soon as one of `inputFormat`, `mask`, `disableMaskedInput` is set
>   
>   * Pro: As soon as the `mask` is set, setting the `inputFormat` will have to be adapted so its does not makes sens to add a default for one and use a custom props for the other
>   * Cons: hard to explain that de default value is not applied depending on another prop
> 
> Personally, I prefer the first option, because `monthAndYear` format does not change with the localization. It is not `year-month` for some country and `month-year` for others. The order is fixed by date-io so I do not see any problem to do the same but with numbers instead a natural language for months https://github.com/dmtrKovalenko/date-io/blob/f96f0929e1a4020db1b171416e18c0e314ee9a31/packages/date-fns/src/date-fns-utils.ts#L74-L75
> 
> ```js
>   monthAndYear: "LLLL yyyy",
>   monthShort: "MMM",
> ```
> 
> If you have another idea, or find the other solution more suitable, feel free to add a comment @flaviendelangle

I ended up with this problem today but I think the solution could be simple.
If the `views` is provided with Month and Year only (`['year', 'month']`), we should do an additional check in the code. If the `mask` and `inputFormat` is also provided and different from the default, then we should not set `disableMaskedInput` to `true`.
This would solve the problem since the mask provided would work and we would not need to add additional information to the documents.

**Comment by flaviendelangle** [comment]
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.
