### ISSUE TITLE
[DateTimePicker] Allows to use calendar view for date, and TextField for time

### ISSUE THREAD

**Issue by lmb1987** [mui/mui-x#4740]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When the pickers package was released we issued a request to swap out the analog clock for something more desktop friendly like a keyboard input. The keyboard input option was added when pickers was migrated to MUI X, but there is currently no way to default to it or to disable the analog clock selection.

### Examples 🌈

We want this, just this, as something we can set by default for our designers as the "time" part of DateTime picking and as the UI for time picking in the time picking dialog:

<img width="365" alt="Screen Shot 2022-05-02 at 3 29 29 PM" src="https://user-images.githubusercontent.com/67027530/166312748-52529d00-a6f9-40e9-b82c-3190e240ebd4.png">

It would also be good to be able to use just the TextField input for the Time Picker without opening a time picking dialog, as well. The `disableOpenPicker` prop does not appear to work, if that is the intention of said prop.

### Motivation 🔦

I lead a team that manages the design system for several products with 10 of thousands of users and the single biggest piece of feedback on our MUI-based design system is that virtually no one likes or wants the analog clock as their time-picking device. What would it take to add a prop as a minor or patch that allows us to default to the keyboard picker?

**Comment by alexfauquette** [comment]
It sounds like `disableOpenPicker`are not implemented for static pickers. It remove the open picker button on textfields
I assume it is documented because of some typescript extensions.

For now, the closest I can achieve is the following demo:
https://codesandbox.io/s/statictimepickerdemo-material-demo-forked-tedhfs?file=/demo.tsx

I uses the undocumented `isMobileKeyboardViewOpen` prop

## To allow this view:

First, the toolbar does not allow to remove the button toggling between mobile and desktop view
https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/components/PickersToolbar.tsx#L92:L109

It should be removed with `disableOpenPicker` and `isMobileKeyboardViewOpen` should be set to `true`
This button should maybe get props from `OpenPickerButtonProps` which is for now only added to the adornment button

@lmb1987 Why do you need the toolbar on top of the text field? They both provide exactly the same information

**Comment by lmb1987** [comment]
@alexfauquette when using the DateTimePicker, there is a UI for the calendar with a second tab for time picker. In the event our product teams need DateTime picking, not just date picking, they will need a UI pattern within the modal for time picking.

In the event they're just utilizing the Time Picker, I noted that it would be best if we could disable the dialog completely and utilize just the textfield as our time-picking UI without opening a dialog at all.

**Comment by flaviendelangle** [comment]
> We would prefer not to use the analog time clock for that UI, because it's a pattern that none of our users want.

See #4483

**Comment by lmb1987** [comment]
> > We would prefer not to use the analog time clock for that UI, because it's a pattern that none of our users want.
> 
> See #4483 for a long term solution

I commented on that ticket, nearly 2 years ago!

**Comment by flaviendelangle** [comment]
Yes the pickers support has been... imperfect, thus this migration to make things move faster :+1:

**Comment by flaviendelangle** [comment]
I'm closing this one
We are currently working on #4483 and this one will be fixed as well
