### ISSUE TITLE
[pickers] Adapt masks to the locale

### ISSUE THREAD

**Issue by ronnyroeller** [mui/mui-x#4756]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The Date Picker should provide the correct mask for the set locale.

## Motivation 🔦

The [material-ui docs](https://mui.com/components/date-picker/#localization) show how to create locale-specific masks. Yet, this still requires to map the browser locale to all kind of masks, and that's actually quite complex (see [Wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country)).

Alternatively, we also considered using the MobileDataPicker (which doesn't need masks for entry). But this doesn't work because it uses masks to show the currently selected value. This would work if the Date Picker would allow to change the rendering of the selected value (e.g. to use the browser built-in `Date.prototype.toLocaleDateString()`).

**Comment by alexfauquette** [comment]
I like the idea of generating the mask. To bring some precision, we rely on `inputFormat` and the adapter the format instead of the native `toLocaleDateString`

I have a concern about validating then mask. For now what appends internally, is the following:

```js
// pick dates which contains 1 digit or 2 digits per value
const staticDateWith2DigitTokens = '2019-11-21T22:30:00.000';
const staticDateWith1DigitTokens = '2019-01-01T09:00:00.000';

// format them
const formattedDateWith1Digit = utils.formatByString(utils.date(staticDateWith1DigitTokens)!, format);
const formattedDateWith2Digit = utils.formatByString(utils.date(staticDateWith2DigitTokens)!, format);

// infer the mask from the formated date
const inferredFormatPatternWith1Digits = formattedDateWith1Digit.replace(acceptRegex, MASK_USER_INPUT_SYMBOL);
const inferredFormatPatternWith2Digits = formattedDateWith2Digit.replace(acceptRegex, MASK_USER_INPUT_SYMBOL);

// check validity
const isMaskValid = inferredFormatPatternWith2Digits === mask && inferredFormatPatternWith1Digits === mask;
```

We could generate the mask from `inferredFormatPatternWith2Digits` and replace mask validity check by something like this to check the input format is robust between 1 and 2 digits input formats
```js
const mask = inferredFormatPatternWith2Digits

const isMaskValid = inferredFormatPatternWith1Digits === inferredFormatPatternWith2Digits;
```

Maybe test with another 2 digits date such as `'2019-12-10T11:15:00.000'` to check that inferred mask is not a special case

---

Such a modification would be nice to have because `mask` sounds to be a subset of the information contained in `inputFormat` but it require sometime to think if their is not an edge case we are forgetting
