### ISSUE TITLE
[time pickers] How can I have a time picker that spans 24 hours across 2 different dates. 

### ISSUE THREAD

**Issue by tielushko** [mui/mui-x#4768]
### Order ID 💳

31986

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am looking for a solution based on TimePickers which would only let me select a time range within a 24 hour predefined window that would ignore the date tied to. 

The 24 hour period would start 6:01 pm of the 1st day and end at 6:00 pm on the 2nd day, but I would like to be able to pick minight to 6 pm without the time picker thinking its the same date. 

I guess my question is, is there a way to just ignore the date aspect altogether in the time picker in order to be able to shift this time window as such? 

I would appreciate any advice regarding this! 

THANK YOU!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
I'm not sure to understand your point, because the time picker does not care about the date, so you can only ask for a time, and you will have to manage your-self the day, because the user does not have access to it

Here is a sketch to adapt with your favorite date library
```jsx
  <TimePicker
    value={value}
    onChange={(newValue) => {
		if(isAfter6(newValue)){
			setValue(setDay2(newValue));
		} else {
			setValue(setDay1(newValue))
		}
    }}
    renderInput={(params) => <TextField {...params} />}
  />
```

where `isAfter6` check if time is before/after 6AM and `setDay2`/`setDay1` replace the date with the correct day

**Comment by tielushko** [comment]
Thank you for your help, @alexfauquette. I proceeded with going the different direction with this one. I will be closing the issue.
