### ISSUE TITLE
[DatePicker][Testing Library] Unexpected behaivour when testing with userEvent.type 

### ISSUE THREAD

**Issue by FjVillar** [mui/mui-x#4923]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi everyone,

First of all, thanks to all collaborators within this project and especially to the people that make this possible. 

Lastly, my team and I have been upgrading MUI from v4 to v5, and we have encountered a problem when using the new DatePickers both in the new package @mui/x-date-pickers and the ones that were on the @mui/lab project. The issue came out when testing with Testing Library React, trying to create a test where the user types with the keyboard in a DatePicker. 

I have created a [CodeSandbox](https://codesandbox.io/s/mui-x-datepicker-testing-library-user-event-type-jvhfv4?file=/src/Test.test.tsx) reproducing this problem. I'll explain the CodeSandbox:

I have taken the code from the example "Views playground" on the [MUI-X Docs](https://mui.com/x/react-date-pickers/date-picker/#views-playground), and I have implemented a simple test with Testing Library where I use the [@testing-library/user-event ](https://testing-library.com/docs/user-event/intro) library to recreate a user interaction with the DatePicker input. I have used for this the `userEvent.type` function to write "02/2022" on a DatePicker.

After this, when checking for the existing DOM after this action with `debug()`, we can see that the value within the input has not changed to a valid date. You can check this on the Tests tab of the CodeSandbox on the Console output.

### Expected behavior 🤔

The expected behavior for us should be the value changing to a valid date or an invalid date if the user types a wrong date. 

### Steps to reproduce 🕹

Steps:

1. Create a test with Testing Library React where you render a Mui-x Date Picker with the year/month views.
2. Query for the DatePicker input by using a `data-testid` in the `InputProps={{ inputProps: {} }}` prop.
3. Use `userEvent.type` to type a valid date.
4. Check the Console Output to see that the value withing the input haven't changed.

### Context 🔦

We have many tests where we recreate the user's interactions with our DatePickers by typing, and after that, they do another action, like submitting a form and calling an API. 

### Your environment 🌎

You can check the enviorment on the CodeSandbox.

**Comment by cherniavskii** [comment]
Hey @FjVillar 
Thanks for opening the issue!

I've noticed that your demo doesn't work when typing manually as well:
<img width="238" alt="Screenshot 2022-05-24 at 16 53 40" src="https://user-images.githubusercontent.com/13808724/170066253-fc4c69a5-8153-4583-9fda-f1a0894c3b20.png">

The reason is that you override `inputProps`, to fix it:

```diff
<TextField
  {...params}
  helperText={null}
  // @ts-ignore
- inputProps={{ "data-testid": "date-picker-input" }}
+ inputProps={{ ...params.inputProps, "data-testid": "date-picker-input" }}
/>
```

As for the tests, we use `fireEvent.change` in our codebase:
https://github.com/mui/mui-x/blob/226c65bca8d400d52c8b1bdc3af0f73e9079b82a/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx#L84-L88

**Comment by FjVillar** [comment]
Thank you so much @cherniavskii !. I didn't noted that. I have fixed the Codesandbox implementing the line as you said. But I still think the issue should be open. 

I would like to test my test as a user would do, I would prefer using userEvent if possible. We could go with fireEvent if we dont have other option but.

Do you think userEvent not working with DatePickers should be investigated?

**Comment by FjVillar** [comment]
I have updated the CodeSandbox adding another test with fireEvent. Still I can't change the value of the DatePicker with fireEvent, maybe I have made something wrong within the test but I have copied the one you passed me. 

This could be related with the `views` prop? I've seen other issues relate to the `views` prop when is set to `["year", "month"]` could [this](https://github.com/mui/mui-x/issues/4664#issuecomment-1115942914) be related? @alexfauquette

**Comment by alexfauquette** [comment]
The bug seems to come from the test settings. You are testing keyboard interaction with a `<DatePicker />` which can be either a mobile or desktop picker according to a media query (by default we use the pointer precisions)

Here is your codesandbox with `<DatePicker />` replaced by `<DesktopDatePicker />` in the Demo. that two tests are passing
https://codesandbox.io/s/mui-x-datepicker-testing-library-user-event-type-forked-b6m0pj?file=/src/demo.tsx
