### ISSUE TITLE
[docs] Set up Crowdin for MUI X docs

### ISSUE THREAD

**Issue by m4theushw** [mui/mui-x#4948]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The button to edit the page (or translate the page) is redirecting to the MUI Core dashboard: https://translate.mui.com/project/material-ui-docs/

![image](https://user-images.githubusercontent.com/42154031/169546633-e195f715-6df9-498b-bc49-4100c0d58a63.png)

We should set up the repo in Crowndin and update the page to redirect to the correct dashboard when on a MUI X page. This may require a contribution in the core repo too. Apart from adding the Crowndin GitHub Action, the `crowndin.yml` must also be created. Docs: https://support.crowdin.com/github-crowdin-action/

### Motivation 🔦

Allow the community to send translations.

**Comment by oliviertassinari** [comment]
The translation on MUI Core are kind of broken. I believe that the root cause is that the community is not translating the docs fast enough to catch up with our changes there.

On MUI X, I believe we will face a couple of challenges too, some of our API pages are custom made, not designed with internationalization in mind.

I think that the important question we need to answer is: "Is is worth translating the documentation?" I don't think that we have ever taken the problem seriously, so never attempted to solve the problem properly. It would likely take 12 months of continuous investment to see if the ROI is positive or negative.

**Comment by m4theushw** [comment]
I missed the motivation to have opened this issue. It was because of https://github.com/mui/material-ui/pull/32399#discussion_r878116218

**Comment by cherniavskii** [comment]
This issue is no longer relevant since we disabled translated docs in https://github.com/mui/mui-x/pull/6560
