### ISSUE TITLE
[data grid] Cells stay in edit mode when a validation error is raised

### ISSUE THREAD

**Issue by raphaelfavier** [mui/mui-x#4953]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Whenever a cell is edited and a validation error is thrown (for example via `preProcessEditCellProps` or `processRowUpdate`) the cell stays in an edit state.

Double-clicking the cell or pressing enter does not reset its state. It's just stuck.

This behavior is displayed in the doc examples: 
[validation](https://mui.com/x/react-data-grid/editing/#validation)
[persistence](https://mui.com/x/react-data-grid/editing/#persistence)

### Expected behavior 🤔

After the user has been informed of their error, they should be able to modify the cell further and press enter to validate the new input, or exit edit mode via the escape key

### Steps to reproduce 🕹

This behavior is displayed in the doc examples: 
[validation](https://mui.com/x/react-data-grid/editing/#validation) => type an existing name to trigger error, can't exit edit mode with esc key, changing value and pressing enter does nothing.
[persistence](https://mui.com/x/react-data-grid/editing/#persistence) => enter an empty name to trigger error, can't exit edit mode with esc key, changing value and pressing enter does nothing.

Updated instructions:

1. Go to the first demo in https://mui.com/x/react-data-grid/editing/#persistence
2. Double-click any cell from the first columm
3. Empty the content
4. Press <kbd>Enter</kbd> and wait for the error message
5. Press <kbd>Esc</kbd> or click outside to exit edit mode (doesn't work).

### Context 🔦

I am trying to understand how to validate individual cell's or entire row's edit and provide adequate UX to my users.

### Your environment 🌎

  System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 100.0
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.81 
    @mui/icons-material: ^5.8.0 => 5.8.0 
    @mui/material: ^5.8.0 => 5.8.0 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.0 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-data-grid: ^5.11.0 => 5.11.0 
    @types/react:  18.0.5 
    react: ^18.0.0 => 18.0.0 
    react-dom: ^18.0.0 => 18.0.0

**Comment by m4theushw** [comment]
Thanks for reporting this bug. I updated a bit the instructions to make more clear how to reproduce it. This bug happens because, when a failed attempt to change the cell mode to `view` occurs, we don't update the internal ref to allow a 2nd attempt. For us it's like if the cell went to `view` mode normally.

It begins by defining that in the next render, the cell which received the <kbd>Enter</kbd> event, should go to `view` mode in https://github.com/mui/mui-x/blob/e5b548f6744f6d000436879839067055205e07db/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts#L326-L332

Then, when the effect runs, it tries to change the mode...

https://github.com/mui/mui-x/blob/e5b548f6744f6d000436879839067055205e07db/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts#L488-L497

...but the cell has a validation error and it must exit.

https://github.com/mui/mui-x/blob/e5b548f6744f6d000436879839067055205e07db/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts#L363-L365

Note that, although this was a failed attempt, it stills updates the state as if it went well. When <kbd>Esc</kbd> is pressed, it checks that the next cell mode is the same as the previous mode and does nothing.

The following diff should fix:

```diff
diff --git a/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts b/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
index 407fab70a..71478933a 100644
--- a/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
+++ b/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
@@ -361,6 +361,9 @@ export const useGridCellEditing = (
       const { error, isProcessingProps } = editingState[id][field];
 
       if (error || isProcessingProps) {
+        // Attempt to change cell mode to "view" was not successful
+        // Update previous mode to allow another attempt
+        prevCellModesModel.current[id][field].mode = GridCellModes.Edit;
         return;
       }
 
@@ -368,6 +371,8 @@ export const useGridCellEditing = (
 
       if (processRowUpdate) {
         const handleError = (errorThrown: any) => {
+          prevCellModesModel.current[id][field].mode = GridCellModes.Edit;
+
           if (onProcessRowUpdateError) {
             onProcessRowUpdateError(errorThrown);
           } else {
```

The same fix also works in the row editing.

**Comment by Cr0WD** [comment]
Same error for me 🔥
