### ISSUE TITLE
[docs][pickers] Document the bundle size impact of the various adapters

### ISSUE THREAD

**Issue by ruifernando7** [mui/mui-x#5076]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using`import AdapterDateFns from '@mui/lab/AdapterDateFns';` to make custom dateAdapter for `LocalizationProvider`. After that, i try to build it with webpack on mode `production`.  The tree shaking not working for this library
![image](https://user-images.githubusercontent.com/42912189/171085066-f26bedea-1978-4108-bc6a-4410996ed5f7.png)
I took about 254 kb which too large

### Expected behavior 🤔

The size should be lower than that

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi

Thanks for your report
Could you tell me which version of our packages you are using (you can use `npx @mui/envinfo` to generate a detailed report).

**Comment by flaviendelangle** [comment]
Did you try migrating from the lab to our new package ?
The lab is re-exporting the pickers from `@mui/x-date-pickers` but they will be removed from the lab in a few weeks.
I don't think it will change a lot the problem here though...

I'll try to have a look

**Comment by ruifernando7** [comment]
@flaviendelangle I just tried it and the tree shaking still not working properly

**Comment by flaviendelangle** [comment]
I think the problem is directly in `@date-io`
If I do a simple Create React App importing `'@date-io/date-fns'`, I get a bundle of 471kb (without React deps)
If I do the exact same app, without importing `'@date-io/date-fns'`, I get a bundle of 209kb.

The diff of 262kb being close to what you get through `@mui/x-date-pickers`

**Comment by lytovka** [comment]
Hey @flaviendelangle, any luck figuring out how to reduce the bundle of `'@date-io/date-fns'` in `AdapterDateFns`? I saw your [ongoing discussion](https://github.com/dmtrKovalenko/date-io/issues/626) with `@date-io` maintainers, but I'm not sure what direction this will eventually take for this project. Curious if bundle size improvements such as this one are on the roadmap at the moment.

Thanks!

**Comment by flaviendelangle** [comment]
Hey

We did not have the time to focus on that aspect yet :grimacing:

**Comment by joshkel** [comment]
If I understand correctly, the problem is that it's [hard to do tree-shaking on ES classes](https://www.reddit.com/r/typescript/comments/ft7wj6/webpack_cant_treeshake_class_methods_how_are_you/fm62r92/)  such as the date-io project uses. (date-io's purpose is to say, "Here's a standard date/time abstraction that you can pass to any third-party library you want, and date-io will support any method calls that third-party library wants." So it has to import every date-fns function that it might need to implement any of its API methods.)

If I use `@date-io/date-fns` with `@mui/x-date-pickers`, run webpack-bundle-analyzer, and enable its "Show content of concatenated modules (inaccurate)" option, then I can see that it is importing individual date-fn functions, as desired - it just needs a lot and is not able to do much tree-shaking.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/476338/192797233-186f6305-f204-49d2-9ec5-413c334da89b.png">

**Comment by flaviendelangle** [comment]
If it only imports content that is being used on the adapter (even on method you are not using), then I agree that it is the expected behavior.

Most of the code is in very common method (like `parse` / `format`) that are used all over the place, so we won't be able to optimize much.

I have the feeling the `date-fns` is significantly heavier than `dayjs`, which we also support.
It may be interesting to add on the doc the bundle size added by each of these libraries, when used on the pickers (for `dayjs` we use plugins so the size advertised on their website is not realistic).

**Comment by andriijas** [comment]
Feels wierd that the date-fns adapter is so much heavier than the dayjs one

but the picker and grid is also heavy, so i created a new issue with cloneable repo
https://github.com/mui/mui-x/issues/7332
