### ISSUE TITLE
[DataGrid] preProcessEditCellProps causes renderEditCell Textbox to jump cursor to the end

### ISSUE THREAD

**Issue by nickraphael** [mui/mui-x#5089]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm defining a column with a defined renderEditCell.  In the edit cell I'm rendering a TextField.  This works fine until I also define preProcessEditCellProps on the same column for validation purposes.  When I do this the cursor jumps to the end of the textfield on every keypress.

### Expected behavior 🤔

Textfield should behave normally.

### Steps to reproduce 🕹

Steps:
https://codesandbox.io/s/data-grid-community-forked-fsnmmc

1. Click Edit at the top.  All rows go into edit mode.
2. Click into one of the col2 values.  Let's say row 1 between the 1 and the 2.
3. Press a number
4. See the cursor jump to the end.
5. Comment out lines 73-75 and try again.  (remove the preProcessEditCellProps which isn't really doing anything in this example)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

41833

**Comment by m4theushw** [comment]
This is expected when the `onChange` is not synchronous. It also happens with a simple `input` if we provide similar conditions.

Calling `apiRef.current.setEditCellValue` is always an async task. It means that the value will be updated asynchronously at some time. Because of this, there's a conflict between which value the input should have. First the `input.value` is updated when the user types a new character, then React observes this changes and forces the input to honor the value in the `value` prop. Later, the async task resolves and React updates again the input value but now the cursor jump occurs because it's how the browser behaves. A better explanation is in https://stackoverflow.com/a/28922465

To avoid this issue, you can debounce the value change and first update the value inside the edit component. For this, it's better to use the new editing API. We have instructions about how to add debounce: https://mui.com/x/react-data-grid/editing/#with-debounce

I updated the CodeSandbox with the solution I proposed: https://codesandbox.io/s/data-grid-community-forked-vds335?file=/src/App.tsx

Note that it was mixing methods from the legacy and new editing APIs, now everything uses the latest API.

**Comment by m4theushw** [comment]
I'm closing since we haven't received any feedback.

**Comment by nickraphael** [comment]
Hi, yes the provided solution fixed my problem.  Sorry for not replying.  You rock!
