### ISSUE TITLE
[DateTimePicker] LocalizationProvider with adapterLocale raise InvalidDate when user changes input

### ISSUE THREAD

**Issue by eblanco-soincon** [mui/mui-x#5140]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

Whenever a user tries to change the value by writing in the TextField, if an adapterLocale is being provided to LocalizationProvider, it will always say the date is an InvalidDate object. Should you remove the adapterLocale, the TextField will work as intended.

Not sure if the bug comes from DateTimePicker or from AdapterDayjs.
The picker works fine, It is just the keyboard input change

### Expected behavior 🤔

Whenever the user changes the TextField, validate the date based on the Locale.

### Steps to reproduce 🕹

[DateTimePicker demo forked to reproduce bug](https://codesandbox.io/s/basicdatetimepicker-material-demo-forked-2o4uht) Try to change the day to the following day (by keyboard, the picker works fine) for instance

### Order ID 💳 (optional)

44269

**Comment by alexfauquette** [comment]
The problem is the locale format. With dayjs, to indicate which locale must be used, you have to provide a two letter string to that adapter as shown in [the example](https://day.js.org/docs/en/durations/locale)

Here is your code with `adapterLocale="en"` which works (the mask input should be fixed in the next release)
https://codesandbox.io/s/basicdatetimepicker-material-demo-forked-hxi6xl?file=/demo.tsx

---

It's a bit confusing because they require `dayjs/locale/en-gb` for its side effect. Infact `dayjs/locale/en-gb` is an object containing all the translations necessary to make the translation

**Comment by alexfauquette** [comment]
With `adapterLocale="en-gb"`?

**Comment by alexfauquette** [comment]
With `adapterLocale="en-gb"`?

**Comment by eblanco-soincon** [comment]
Thank you so much! It worked like a charm.
