### ISSUE TITLE
[pickers] Broken behavior when minDate or maxDate set to null

### ISSUE THREAD

**Issue by owen-c** [mui/mui-x#5190]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When `minDate` or `maxDate` are `null` the picker exhibits odd behavior as opposed to when they are set to `undefined` or not provided.

The month picker component will be broken and the back or forward arrows will be disabled.

### Expected behavior 🤔

Setting `minDate` or `maxDate` to `null` should have the same behavior as setting `undefined` or  not suppling the props.

### Steps to reproduce 🕹

Steps:

1. Render DatePicker
2. Set minDate or maxDate as null
3. Picker will behave as if it has a min or max Date and the month picker will not be functional.

You can find a codesanbox example [here](https://codesandbox.io/s/basicdatepicker-material-demo-forked-oru8f2?file=/demo.js)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 12.4
  Binaries:
    Node: 16.14.2 - ~/.asdf/installs/nodejs/16.14.2/bin/node
    Yarn: 1.22.17 - ~/.asdf/shims/yarn
    npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Not Found
    Firefox: 101.0.1
    Safari: 15.5
```
</details>

**Comment by alexfauquette** [comment]
The `minDate` and `maxDate` are expecting a date object compatible with the library of your choice.

I tested with other libraries, DateFns handle the `null` as an invalid date. The three other libraries make the app crash:
https://codesandbox.io/s/basicdatepicker-material-demo-forked-i6z8yd?file=/demo.js:772-782


For which reason do you set `minDate` to `null`?

When `minDate` is not set (or `undefined`) it falls back to the default value which is `1900-01-01`

**Comment by owen-c** [comment]
Our case is we have a DatePicker that either has a minDate or does not based on some conditions. I think most developers would do this like so and expect it to work?

It's just odd and confusing behavior IMO. Also it worked back in alpha.1 release so something changed with this behavior.

```
const myMinDate = hasMinDate ? new Date(....) : null;

<DatePicker minDate={myMinDate} ... />
```

**Comment by alexfauquette** [comment]
Yes, it comes from [this modification](https://github.com/mui/mui-x/pull/4814/files#diff-0d8f8d553708aa62c5639dfad098c043f808671affdc9ada1299cbaf61f56369L218-L220)

### Before
```ts
const defaultDates = useDefaultDates<TDate>();
const minDate = minDateProp ?? defaultDates.minDate;
const maxDate = maxDateProp ?? defaultDates.maxDate;
```
### After
```ts
const {
    ...
    minDate = defaultDates.minDate,
    maxDate = defaultDates.maxDate,
} = props
```

---
For me there is a distinction between `null` and `undefined`:
- `undefined` means "I do not specify the value" -> falls back on the default one
- `null` means "It does not exist" -> do not apply a min date

The problem being we can not consider that `minDate` does not exist because we need it when displaying the year select, and some other components. 
So the notion of `hasMinDate` is not exact. Your code in alpha-1 is equivalent to 

```js
const myMinDate = hasMinDate ? new Date(....) : undefined;
// or
const myMinDate = hasMinDate ? new Date(....) : new Date(1900, 0, 1);
```


@flaviendelangle Do you have an opinion on the topic

**Comment by flaviendelangle** [comment]
Oh yes my bad for this behavior change :/

I would be in favor of migrating all components to the `useDefaultizedXXXProps` pattern to avoid this mistake.
I did the change because it's cleaner visually and forgot the `null` difference.

As for the behavior itself, would you be ok with going back to what was existing before ?
We do need to fallback the the default value in all scenario as you said.

**Comment by alexfauquette** [comment]
Sounds that props frequently have problems with either
- it's `null`
- it is a `string` of a `Date` not a date object of the library
- it is an invalid date

maybe we should introduce an helper `parseDateProp(value, utils, defaultValue)` such the management of date props is consistent on all props

**Comment by flaviendelangle** [comment]
Could make sense yes !

**Comment by ewarrenG** [comment]
+1 I am still experiencing with this line

`maxDate={endDate ? dayjs.utc(endDate) : undefined}` 

when endDate is initialized to `undefined`. How can I resolve this?

**Comment by alexfauquette** [comment]
Does it also fail with `null`

This issue is old (it got fixed for the v5, and we are currently at the end of the v6). Could you open an new one with a basic reproduction?

**Comment by LukasTy** [comment]
Agreed, I wasn't able to reproduce the mentioned problem. 🤷 
Please open a new issue with a reproduction example. 👍 🙏
