### ISSUE TITLE
[DataGridPro] column pinning stuck rows in hover style

### ISSUE THREAD

**Issue by newsiberian** [mui/mui-x#5198]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you take this example https://mui.com/x/react-data-grid/column-definition/#expand-cell-renderer and add pinned column to it, you will see that hover effect will stucks when you have popup and move mouse over this popup

https://user-images.githubusercontent.com/11130487/173566873-5b222146-b7ec-4085-81fb-263c4e2e6b40.mov

### Expected behavior 🤔

hover effect w/o pinned columns works differently. It goes away right after cursor moves to popup area, I guess, you are using pure css hover. I think expected behavior here must be similar

### Steps to reproduce 🕹

Steps:

1. Go here https://codesandbox.io/s/renderexpandcellgrid-demo-mui-x-forked-82opbx?file=/demo.tsx
2. move mouse over the cell with popup
3. move mouse to popup
4. move mouse from the popup directly to the next row 

### Context 🔦

We need to have pinned rows and an ability to expand some cells which could contain lists

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

```bash
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 18.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Not Found
    Firefox: 101.0.1
    Safari: 15.4
```

Browser is Chrome 102.0.5005.115

### Order ID 💳 (optional)

42561

**Comment by alexfauquette** [comment]
If I get it correctly, the bug is the light gray applied on the rows when the mouse is hover

### Why does pinning column break row hover

With column pinning, we can not use CSS selector because the left and right pinning are not in the same div so a row is in reality made of 3 rows (left pinned, right pinned, and main) so we have to manage internally the row hover by adding/removing classes

So the row is listening at `onMouseEnter`/`onMouseLeave` to set classes correctly. But the publish event has a protection against modals:
https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/GridRow.tsx#L186:L191

So in your case, it stops the propagation of the event responsible for removing the hover style.

Maybe this `publish` makes sense for `click` event but not for `mouseEnter`

@m4theushw do you have an opinion on the subject?

**Comment by newsiberian** [comment]
> Is it not better for your use case?

Not really. Potentially, could look ugly for us, so we prefer to wait for some other solution @m4theushw

**Comment by joserodolfofreitas** [comment]
@corneliushka, would you mind opening a new issue for your question?

**Comment by rony-arnac** [comment]
We experience the same issue! `.Mui-hovered` is stuck when a popover is in the mix.

Order ID: 69416

**Comment by cherniavskii** [comment]
Fixed by https://github.com/mui/mui-x/pull/10252
