### ISSUE TITLE
Cannot start editing with Shift+[key] while using newEditingApi?

### ISSUE THREAD

**Issue by zamojo** [mui/mui-x#5228]
### Order ID 💳

43201

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

According to the documentation, one can start editing by [Pressing any printable key, such as a, E, 0, or $](https://mui.com/x/react-data-grid/editing/#start-editing); but this doesn't work with the newEditingApi.  

While using `experimentalFeatures={{ newEditingApi: true }}`, click in a cell, type E (Shift+e) or $ (Shift+4).  Nothing happens.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used:
Chrome 102.0.5005.63
Edge 102.0.1245.39

  Output from `npx @mui/envinfo`:
  System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: Not Found
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
```
</details>

**Comment by alexfauquette** [comment]
The problem seems to come from the special key detection which is too strict
```js
if (isPrintableKey(event.key)) {
  if (event.shiftKey || event.ctrlKey || event.metaKey || event.altKey) {
    return;
  }
  reason = GridCellEditStartReasons.printableKeyDown;
}
```
https://github.com/alexfauquette/mui-x/blob/fix-quickFilter-rowGrouping/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts#L148:L153)

I assume shift was added to avoid conflicts with <kbd>Shift</kbd>+<kbd>Arrow</kbd> which is used for multiple row selection. But it's not a problem for printable characters

**Comment by zamojo** [comment]
Thank you, Alexandre, for diagnosing the issue.  Any idea when we can expect a fix?
