### ISSUE TITLE
[DateRangePicker] Difficulty styling the DateRangePicker calendar

### ISSUE THREAD

**Issue by sumnercommajohn** [mui/mui-x#5232]
### Order ID 💳

#36792

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hey there folks,
This may be related to https://github.com/mui/mui-x/issues/4669#issuecomment-1115044196, but I don't see mention of DateRangePicker mentioned there. Or this may be a case of me just not understanding, apologies if so.

I cannot for the life of me figure out how to style the contents of the Popper/Paper in DateRangePicker. 
[Sandbox Example of the problem](https://codesandbox.io/s/basicdaterangepicker-demo-mui-x-forked-rviunt)

My first approach was to use overrides for `MuiCalendarPicker` in the theme to style both `DatePicker` and `DateRangePicker`, I don't know if this was a reasonable expectation but i now see that `.MuiCalendarPicker-root` class doesn't appear in `DateRangePicker`, ([see theme.js](https://codesandbox.io/s/basicdaterangepicker-demo-mui-x-forked-rviunt?file=/theme.js:216-285))

Second approach, i tried using the name `MuiDateRangePicker` for style overrides in the theme, as recommended in the  [DateRangePicker API docs](https://mui.com/x/api/date-pickers/date-range-picker/). This does not seem to target anything. ([also in theme.js](https://codesandbox.io/s/basicdaterangepicker-demo-mui-x-forked-rviunt?file=/theme.js:1004-1072))

I've also tried using the `sx` prop directly on `DateRangePicker` but it seems to only target the PickersSlideTransition slot. ([see BasicDateRangePicker.js](https://codesandbox.io/s/basicdaterangepicker-demo-mui-x-forked-rviunt?file=/BasicDateRangePicker.js:628-757))

Is there supposed to be a way to customize this component? Thanks in advance for any help you can offer.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
A workaround could be the following one
``jsx
PopperProps={{
  sx: {
    "& .MuiPaper-root": { backgroundColor: "lightgreen" }
  }
}}
```

https://codesandbox.io/s/basicdaterangepicker-demo-mui-x-forked-rg5ocw?file=/BasicDateRangePicker.js:603-731


But the clean way to solve it is clearly to pass the classes to sub components

**Comment by sumnercommajohn** [comment]
Thank you that's what I was missing - much appreciate it, this unblocks me for now at least. How would you assess the long-term stability of this workaround?

**Comment by alexfauquette** [comment]
It will work as long as we use a `Paper` inside a `Popper`

The only breaking change that I can imagine is we remove `PopperProps` in favor `componentsProps: { popper: { }}`

But that should be an easy migration if we take this path

**Comment by sumnercommajohn** [comment]
ah one last q i forgot to ask, you mentioned the clean solve via subcomponent classes, do you have any impression of how soon we can expect that?

**Comment by alexfauquette** [comment]
Not really, it's on the todo list, but for now, maintainers are quite busy with some features implementations, maybe some users of the MIT will bring contributions on this topics

I assume it should be done by the end of the summer

**Comment by flaviendelangle** [comment]
@LukasTy wasn't it solved by your new `PaperContent` slot ?

**Comment by LukasTy** [comment]
There will be various ways on how to apply styling after the next release, I'll look into providing a most appropriate example to the author a bit later.

**Comment by flaviendelangle** [comment]
I move it to "In Progress" then :+1:

**Comment by LukasTy** [comment]
The styling of date range picker popper is still a bit strange due to it being wrapped in [this div](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerView.tsx#L267)

Regarding `styleOverrides` on `MuiDateRangePicker` not being applied - the issue is two-fold.
In JS land you don't get typing and can't know what can actually be overridden, if you were to use TS, then `themeAugmentation` provides the possible overrides and in `MuiDateRangePicker` case there are none, because this component does not have any `styled` components, it just decides on what to render (Mobile or Desktop picker).
The possible overrides for this components are only `defaultProps` (`styleOverrides` will be ignored).

With the existing version I'd say the easiest solution from theme overriding side would be the following:
```js
MuiDateRangePicker: {
  defaultProps: {
    className: 'custom-range-picker',
  },
},
MuiPaper: {
  styleOverrides: {
    root: {
      '.custom-range-picker': {
        backgroundColor: 'salmon',
        border: '1px solid red',
      },
    },
  },
},
```

With the upcoming `v5.0.2` release you will be able to target a more specific `Paper` with the following overrides:

```js
MuiDateRangePicker: {
  defaultProps: {
    className: 'custom-range-picker',
  },
},
MuiPickersPopper: {
  styleOverrides: {
    paper: {
      '.custom-range-picker': {
        backgroundColor: 'salmon',
        border: '1px solid red',
      },
    },
  },
},
```

But in any case, it doesn't change the fact that the passed `className` is applied to both the `input container` and the popper container without it having a distinct class of its own, which we could target.

We ought to make it better in v6.
Applying the same class to both the input container and popper does not seem like the most correct approach.
I'd say we should only apply the passed class to the root element and provide a `MuiDateRangePickerView` class on the root element wrapping the range picker calendar(s).

**Comment by LukasTy** [comment]
It looks like the main problem was the fact, that the `className` was being applied to both the inputs wrapper as well as the popup, creating problems.
In v6 that's no longer the case, the `className` is correctly applied only to the root element, which is the input wrapper in this case.
For styling other parts of the picker, there are [multiple new slots](https://mui.com/x/api/date-pickers/date-range-picker/#slots) that can be used to add the styles to.
