### ISSUE TITLE
[pickers] Unable to clear the pickers

### ISSUE THREAD

**Issue by saadhashmi** [mui/mui-x#5350]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi,
 I have a following scenario

- Select a date in the datepicker
- Based on radio button selection i have to reset the value of the datepicker to empty value (which is required field) so i need to set it to empty string so that i can trigger the required check.
- Current the required check gets triggered and the field gets red, at the backend in the datepicker, my value is empty but on the UI its still retaining the old value and not getting cleared
- i reproduced similar behavior here
- 
[Sandbox](https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-vrf229?file=/demo.tsx)

### Expected behavior 🤔

The UI should get clear (DatePicker field should get empty)

### Steps to reproduce 🕹

Steps:

1. Set a value in the datepicker
2. try to empty the field on any external input like selection of radio button or even in useEffect like the sandbox.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
I think this is because empty strings are not considered to be a valid value, and the component does not update input when it receives an invalid value.

For now, only `null` can be used to define an empty field. Based that, you can use the following workaround:

```jsx
renderInput={({ error, ...params }) => (
  <TextField required error={error || value === null} {...params} />
)}
```

https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-diyw9t?file=/demo.tsx

**Comment by saadhashmi** [comment]
Hi Alex, this isAcceptedValue fix, will that be in the coming release or is it something we can do currently as well?

**Comment by alexfauquette** [comment]
In fact, it will not exactly fix your problem. You will still need to manage `error` as proposed in the workaround

The reason why `set("")` leads to an error state is not linked to `required` prop. That's because the value is parsed with `adapter.parse("")`. Since an empty string is not a valid ISO date, it returns an "invalid date" which is the reason why the `TextField` get in error state

To reset the content, setting the value to `null` is the only correct way I know

**Comment by saadhashmi** [comment]
thanks
