### ISSUE TITLE
[testing-library] TimePicker onChange never trigger

### ISSUE THREAD

**Issue by JuanSeBestia** [mui/mui-x#5655]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm trying to test this component with testing-library, but I can't trigger onChange event

This issue is related https://github.com/mui/mui-x/issues/4985

### Expected behavior 🤔

the components has an example to use with some framework to do atomatizated tests 

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/react-testing-library-timepickerexample-f1wly6?file=/src/__tests__/TimePickerExample.test.js

See the tab tests

### Context 🔦

Integration tests

### Your environment 🌎

All the env information are available in live example

**Comment by LukasTy** [comment]
Hello @JuanSeBestia 
Thank you for creating a detailed issue.
Could you confirm your expected test flow in detail?
I've played with `codesandbox` and narrowed down the issue towards the fact that `useMediaQuery` hook returns false in `jsdom` environment, hence the `MobileTimePicker` is actually rendered instead of `DesktopTimePIcker`.

Could you confirm whether you were expecting to test a desktop picker flow?

I was unable to mock `useMediaQuery` in codesandbox due to it not supporting [jest globals](https://github.com/codesandbox/codesandbox-client/issues/513).
I've successfully resolved an error in a simple controlled TimePicker test case by mocking `@mui/material/useMediaQuery` response as `true`:
```js
import useMediaQuery from '@mui/material/useMediaQuery';
...
sinon.stub(useMediaQuery).returns(true)
```

If this is actually your root cause, please use the mock as a temporary workaround and we'll look into whether we can do anything about it on our side.

**Comment by JuanSeBestia** [comment]
I believe that I write something before but I write it again

Thanks  very much to clarify that another component is rendered that I don't expect. Really I just want a way to test my flow using your components, So knowing that is rendered mobile version, I used the input in edit view with the input, I'm implement in the same live demo with the name `TimePickerExample test with input mobile`, So you can close this issue or wait until your MR are ready to re implement my tests
