### ISSUE TITLE
showtodaybutton not working with autook

### ISSUE THREAD

**Issue by learechdan** [mui/mui-x#5685]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hello, 

This is a part of my code. I am using the latest version.

```
<DatePicker
        autoOk
        showTodayButton={props.showToday ? true : false}
        }
  />
```

In my DatePicker, when I click on any day, the autoOk closes the calendar. However, when I click on Today, the autoOk doesn't seem to work. The calendar stays open until I quit it manually. 

I know this was an issue fixed in an older version, but it doesn't seem to be working on this one. Does anyone have any solution? 

Thank you

### Expected behavior 🤔

When I click on Today, the calendar should apply the changes and close when autoOk is set to true

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

npx : 2 installé(s) en 2.917s

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.56)
  npmPackages:
    @types/react: 16.9.56 => 16.9.56
    react: 16.13.0 => 16.13.0
    react-dom: 16.13.0 => 16.13.0
    typescript: ^3.7.5 => 3.9.10

```
</details>

**Comment by alexfauquette** [comment]
@learechdan I doubt you're using the last version because the prop `showTodayButton` has been removed in `v5.0.0-alpha.4`

Could you provide a minimal reproduction of your bug?

Here is the component with latest versions
https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-nikzin?file=/demo.tsx:569-584

If you need, the new way to add buttons is explained [here](https://mui.com/x/react-date-pickers/custom-components/#action-bar)
