### ISSUE TITLE
[pickers] Allow to choose which date to focus on all date views

### ISSUE THREAD

**Issue by unpxre** [mui/mui-x#5702]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm facing exactly the same problem which was mentioned in previous repository:

> In material-ui v3 the date picker has the ability to set initialFocusedDate what gives an initially highlighted date on opening the picker. I am missing the ability to set this variable in v4. Is there a motivation why this is removed or will this be added again on the stable version?
https://github.com/mui/material-ui-pickers/issues/2032

### Motivation 🔦

Our need is applicable for every app where users selects multiple dates from past - for example for making public tenders archive. 

In that cases we want users to choose dates that often are in not current year, because users picks multiple dates, after first completion we can suggest next ones.

Default date not suits us because that forms are really long and users rewrites a lots of dates so with default date they can easily omit some.

**Comment by alexfauquette** [comment]
is `defaultCalendarMonth` the prop you are looking for?

Maybe the naming is wrong or it should be more documented

https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-8cb217?file=/demo.tsx

**Comment by unpxre** [comment]
@alexfauquette Yes that is exactly what i needed, I don't know how i cant saw it. Thanks. :D

**Comment by alexfauquette** [comment]
I just keep it open such that we can know this element is not trivial to find in our documentation

**Comment by unpxre** [comment]
I suggest also to rename that prop to `defaultCalendarDate` or back to `initialFocusedDate`. I think `defaultCalendarMonth` is a little misleading

**Comment by simoncereska** [comment]
Sadly this doesn't work with `views={['year']}`

**Comment by flaviendelangle** [comment]
> I suggest also to rename that prop to defaultCalendarDate or back to initialFocusedDate. I think defaultCalendarMonth is a little misleading

I agree that this naming is not great...

**Comment by sam-woodridge** [comment]
The `defaultCalendarMonth` does not apply to the `year` or `month` view. Can this be fixed/added? Currently I don't see any way to change the default year or month in the corresponding views, it always defaults to the current year/month

**Comment by flaviendelangle** [comment]
Yes, that's the whole point of this issue

**Comment by svenhorner** [comment]
@flaviendelangle I might actually be able to get some resources to fix it and submit a PR, I already discussed it with my lead. 

Setting a value with the Date doesn't solve the problem in our case, as the DatePicker is used to select a birth date. So the user should be able to select 1. month, 2. year and 3. day, without any jumping back and forth.

We can open to the month view with `openTo="month"`. If the value passed to defaultCalendarMonth will also be used to set up the month and the year view, not only the day view, we should be able to cover the behaviour we need.

If there is anything I need to know, before implementing a possible fix, please let me know.

**Comment by flaviendelangle** [comment]
Thanks to propose your help !

>  the DatePicker is used to select a birth date

For a birthday, we are working on some recommendation for our next major version and we would advise using the new [DateField](https://next.mui.com/x/react-date-pickers/date-field/) component.

But it does not invalidate the fact that we should have a clean solution to this problem.

My proposal (to be discussed with @joserodolfofreitas , @LukasTy and @alexfauquette ) is to:

1. Add a new prop `defaultCalendarDate` that would replace `defaultCalendarMonth in v7
2. Deprecate `defaultCalendarMonth`  with a clear JSDoc message
3. Use `defaultCalendarMonth` as the default value of `defaultCalendarDate` to avoid a breaking change
4. Create a new optional prop `defaultYear?: TDate` in `MonthCalendar`
5. In `MonthCalendar`, change `selectedDateOrStartOfMonth` to use `defaultYear` if defined as the 1st fallback
6. In `DateCalendar`, pass the following `defaultYear` to `MonthCalendar`: `defaultYear={utils.startOfYear(calendarState.currentMonth}` (memoized)


I'm calling the prop `defaultYear` and not `calendarYear` like on `DayCalendar` because `MonthCalendar` can be used as a standalone component, so the prop has to be optional.

**Comment by flaviendelangle** [comment]
Fixed by #5702
The doc is [here](https://mui.com/x/react-date-pickers/date-calendar/#choose-the-initial-year-month) :+1:
