### ISSUE TITLE
Support async `valueGetter`s for DataGrid

### ISSUE THREAD

**Issue by hamza1311** [mui/mui-x#5705]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The [valueGetter](https://mui.com/x/react-data-grid/column-definition/#value-getter) currently only supports sync operations. It should also support accepting a `Promise` and displaying the results when it resolves, while also having a fallback that is rendered while the Promise is resolved.

The API could look something like this:
```ts
valueGetter?: (params: GridValueGetterParams<any, R>) => V | Promise<V>;
```
There could be a new field for fallback, which is to be rendered while the Promise is being resolved, or if the `Promise` is rejected.

### Motivation 🔦

This is needed to be able to render, say, user's name in a column when the value in the row object is the user's id

The data that database is provides looks like:
```json
{
    "userId: "some-id",
    ...
}
```
Column def would be:
```ts
{ 
    field: 'user', 
    headerName: 'User', 
    valueGetter: async (params) => {
        const user = await userService.fetchUser(params.row.userId);
        return user.name
    },
    valueGetterFallback: (params) => params.row.userId // rendered during fetch or if the request fails
}
```

**Comment by cherniavskii** [comment]
Hey @hamza1311 
Thanks for your suggestion!

Supporting async `valueGetter` is problematic, because the value returned by `valueGetter` may be used for sorting, filtering, row grouping, etc. So data grid will not be able to initialize properly until it has all the data.

From a data fetching perspective, the use case you've mentioned is usually solved on the server side.
For example, in RESTful API services this is commonly named as `expand` functionality - see [link](https://helpcenter.veeam.com/docs/vac/rest/expand.html?ver=60) and [link](https://developer.atlassian.com/server/confluence/expansions-in-the-rest-api/).
This is much more efficient than multiple HTTP requests for each row.

If, for some reason, you cannot do this on the server, you can always fetch missing data on the client and provide data to the grid when all the data is ready.

Also, your suggestion with async `valueGetter` can be implemented with `renderCell` - you can pass a component that would render the id while fetching profile data on mount. We do not recommend this approach though, because it won't work with sorting, filtering and potentially with other features.
