### ISSUE TITLE
[data grid] AutoComplete results window is being clipped by pinned columns and footer 

### ISSUE THREAD

**Issue by PraveenPeri** [mui/mui-x#5745]
### Order ID 💳

33625

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have a cell that is editable and that contains an autoComplete component. We are using useAutoComplete() hook to render the results in the tabular format instead of a list. See the screenshot below
![InlineEditing](https://user-images.githubusercontent.com/6571000/183745616-b1b5bb89-8df2-4597-b9d4-35a7ad478961.jpg)

The problem we are seeing is that the results are being clipped by the pinned columns on the right and the footer at the bottom of the data grid. I have been trying to play with CSS to fix that but couldn't get it to work. Any help here would be appreciated

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi, @PraveenPeri thanks for raising this!
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

That being said if you are using `disablePortal` then the modal or popover will not be rendered in a new subtree outside of the current DOM hierarchy. Because the grid has `overflow: hidden` when the `autoHeight` is not enabled this causes the content of your modal or popover to be clipped.

**Comment by PraveenPeri** [comment]
Please find a repro here https://codesandbox.io/s/data-grid-community-forked-fq3esc?file=/src/AutoCompleteComponent.tsx
For some reason, I couldn't repro the inability to vertically scroll but at least you could see the content getting clipped horizontally and there is no way to look at that. Imagine this case where a listbox is replaced by a table which is what we are doing

**Comment by PraveenPeri** [comment]
I updated the repro to use autoHeight on the data grid and if you double click on column 3 to edit, you will notice the problem with the options list

**Comment by PraveenPeri** [comment]
I was able to solve this through css change. Basically, on the component where I am using data grid with inline editing, I set this
```
sx={{
  "& .MuiDataGrid-virtualScroller": {
        overflowY: "auto !important"
   }
}}
```
