### ISSUE TITLE
[data grid] setEditCellValue doesn't update cell

### ISSUE THREAD

**Issue by atillaaliyev** [mui/mui-x#5748]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi,
I have a checkbox on cell and I want to update without focusing. By the way, I can have lots of checkbox. And I created two custom component for `renderCell `and `renderHeader`. And when I checked or unchecked for `renderHeader`, I want to update all rows. I used `setEditCellValue` but it's not working. When I controlled with `getRowModels ` function, it's not updated.

In the same way, I created custom component for `renderCell `,it's checkbox and when I checked or unchecked, I'm expecting to update row model, but doesn't. I'm using  `setEditCellValue` again.

I don't understand problem, long story short I want to use custom chekbox component on cell without `chekboxSelection`.
Thanks,

https://codesandbox.io/s/datagrid-checkbox-svcb4l

### Expected behavior 🤔

`setEditCellValue ` function should update cell.

### Steps to reproduce 🕹

Link to live example:

Steps:
1.You can click checkbox cell and header.
2.And you should see current value while click "Get Row Models" button.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

37219

**Comment by m4theushw** [comment]
The cells have two modes: `view` and `edit`. While the `view` is the normal mode, the `edit` is when you double-click or press <kbd>Enter</kbd> in a focused cell. In a DataGrid without CSS customizations, a cell in edit mode can be distinguished by having a shadow around it. With that being said, `apiRef.current.setEditCellValue` will only work if the cell is in the edit mode. You're trying to use it without changing the mode. Once the cell is in the edit mode, the component provided to `renderEditCell` will be rendered instead of `renderCell`.

If you don't want to change the cell mode and just want to update the cell value, then use [`apiRef.current.updateRows`](https://mui.com/x/react-data-grid/row-updates/#the-updaterows-method). But note that using this last method you're not using the editing API, so anything from https://mui.com/x/react-data-grid/editing/ is not applicable.

**Comment by atillaaliyev** [comment]
Thank u @m4theushw . I understood clearly. It's solution for me.
