### ISSUE TITLE
[DatePicker] Always return 'invalid date'.

### ISSUE THREAD

**Issue by hqlovely** [mui/mui-x#5753]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The date always show 'Invalid Date' when using keyboard as the input

### Expected behavior 🤔

The date should be valid

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-msl8m5?file=/demo.tsx

Steps:
1. Open this Code Sandbox
2. Change the year to '2564'  or '2566' or whatever Buddhist year greater than or less than 2565 **'using keyboard'**.

### Context 🔦

I would like to use the Buddhist era.

### Your environment 🌎

 System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0
    @emotion/styled: ^11.10.0 => 11.10.0
    @mui/base:  5.0.0-alpha.92
    @mui/icons-material: ^5.8.4 => 5.8.4
    @mui/material: ^5.9.3 => 5.9.3
    @mui/private-theming:  5.9.3
    @mui/styled-engine:  5.8.7
    @mui/system:  5.9.3
    @mui/types:  7.1.5
    @mui/utils:  5.9.3
    @mui/x-date-pickers: ^5.0.0-beta.4 => 5.0.0-beta.4
    @types/react:  18.0.15
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.7.4

**Comment by LukasTy** [comment]
Hello @hqlovely 
Thank you for opening this interesting issue.

Sadly, the issue is with the `dayjs` `buddhistEra` plugin, it only supports formatting date and [not parsing](https://github.com/iamkun/dayjs/issues/990) it.
The [plugin source](https://github.com/iamkun/dayjs/blob/dev/src/plugin/buddhistEra/index.js) shows, that only `format` portion is handled.
Feel free to open an issue for `dayjs` library or possibly look into addition the option of `parsing` date in such format.

Another options to look into:
- consider disabling manual date entry to avoid reliance on the need for `parsing`
- look into using a very fresh [adapter for date-fns](https://github.com/tarzui/date-fns-be) (I've tested this one and it seems to handle both date selection and manual date entry parsing)
