### ISSUE TITLE
[question] Rerendering after saving state in storage causes reseting columns.

### ISSUE THREAD

**Issue by SirAndrii** [mui/mui-x#5766]
### Order ID 💳

48869

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

My aim is to save the config of the Datagrid table in redux storage. But updating the state with initialConfig causes resetting actual columnWidth and columnOrder.  OnColumnOrderChange fires before mousedown. I can't figure out why I see such behavior.

https://codesandbox.io/s/restorestateinitialstate-demo-mui-x-forked-wlzrbf?file=/demo.js:0-2752

https://user-images.githubusercontent.com/24919819/184196085-9a6266b3-1272-4558-beb7-b1221d83fd9d.mov

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi, @SirAndrii thanks for raising this!
I've checked the demo you provided and there seems to be 2 problems. The firrst and main one is that the state after column reorder is not persisted because you have `{...eventsRedux}` in the `DataGrid` component. Commenting out this like or memoizing it solves that problem.
The second issue is when you reorder a column, click the toggle button to hide the grid, and click it again to show it. Then the columns are reset back to their initial state. To solve this either opt out of removing the grid from the DOM all together (si just hide it) or capture the latest grid state and then provide it after the grid is recreated via the `initialState` prop.
