### ISSUE TITLE
[question] How to adjust DataGrid height to total height of its rows?

### ISSUE THREAD

**Issue by shetamitesh** [mui/mui-x#5822]
### Order ID 💳

46861

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-gu8uez?file=/demo.tsx

See this link.

DataGrid border is well below the last row. How to fix it?

Also if we want to add a custom density level, how to do it?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
```
</details>

**Comment by m4theushw** [comment]
You see the space after the last row because the grid is calculating the space required based on the default row height, but the row height is later customized with CSS. To change correctly the row height use only the `getRowHeight` prop:

```tsx
<DataGrid getRowHeight={() => 24} />
```

Updated CodeSandbox: https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-81wzr0?file=/demo.tsx

> Also if we want to add a custom density level, how to do it?

We only allow 3 density levels. But you can customize the final row height using the `densityFactor` passed to `getRowHeight`. The demo in https://mui.com/x/react-data-grid/row-height/#variable-row-height has an example.

**Comment by shetamitesh** [comment]
Thanks. getRowHeight is what I need.
