### ISSUE TITLE
[DataGrid] GroupingValueGetter function not re-executed if dependency changes

### ISSUE THREAD

**Issue by mormir2** [mui/mui-x#5917]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When grouping rows and using a GroupingValueGetter to modify the row grouping value for the autogenerated row, the GroupingValueGetter function is not executed again if any of the dependencies in the dependency array of this function change. Instead, the value remains unchanged and the function is not re-executed.

### Expected behavior 🤔

When a dependency changes, the GroupingValueGetter function should be executed again, just like the other getter functions.

### Steps to reproduce 🕹

I created a simple example to simulate additional data, that is loaded after the first render of the grid. 
When grouping by "Company", the expected result is that after a timeout,  the grouping row value is changed to
_"(CompanyName) updated"_ - instead, the name remains the same.
When commenting the rowGrouping-line in the initialState
`model: ["company"]`
and reloading the page, the names are correctly updated after the timeout.

Link to live example: https://codesandbox.io/s/mui-x-datagrid-groupingvaluegetter-rqrt3w?file=/demo.tsx:1647-1666

Steps:
1. load page and open codesandbox console
2. wait for console output "Dependency has updated" and find that the "Company" row grouping value has not changed
3. comment the  rowGrouping-line in the initialState `model: ["company"]` and reload the page
4. "Company" values will be updated

**Comment by flaviendelangle** [comment]
Indeed...

We can change the update behavior to be closer from the aggregation one.
On aggregation, instead of comparing the models, we are comparing objects,t (the `GridAggregationRule`) containing everything used to aggregate.
We are not using things like `colDef` inside the aggregation process because it could change.

Implementing a similar approach for row grouping would work, we would just have to store the `groupingValueGetter` inside this object instead of accessing it from the `colDef`.

But for grouping, we are passing the whole `colDef` to the `groupingValueGetter`
So in theory, any change to `colDef` can change the output and the grouping result.


@cherniavskii which one is the best for you ?

- we resign to execute the grouping process everytime one of the columns used for grouping changes
- we only update on `groupingValueGetter` change and maybe provide a manual apiRef method to cleanly re-trigger the grouping

I did a draft of a fix just for the  `groupingValueGetter` update in https://github.com/mui/mui-x/pull/5919

**Comment by flaviendelangle** [comment]
Indeed...

We can change the update behavior to be closer from the aggregation one.
On aggregation, instead of comparing the models, we are comparing objects,t (the `GridAggregationRule`) containing everything used to aggregate.
We are not using things like `colDef` inside the aggregation process because it could change.

Implementing a similar approach for row grouping would work, we would just have to store the `groupingValueGetter` inside this object instead of accessing it from the `colDef`.

But for grouping, we are passing the whole `colDef` to the `groupingValueGetter`
So in theory, any change to `colDef` can change the output and the grouping result.


@cherniavskii which one is the best for you ?

- we resign to execute the grouping process everytime one of the columns used for grouping changes
- we only update on `groupingValueGetter` change and maybe provide a manual apiRef method to cleanly re-trigger the grouping

I did a draft of a fix just for the  `groupingValueGetter` update in https://github.com/mui/mui-x/pull/5919

**Comment by cherniavskii** [comment]
@flaviendelangle I think handling `groupingValueGetter` for now is fine, since I don't see any other use cases similar to this one related to other properties in GridColDef

**Comment by flaviendelangle** [comment]
I guess that's a good first step that fixes an actual problem, we can see later to fix the broader problem.

**Comment by flaviendelangle** [comment]
I guess that's a good first step that fixes an actual problem, we can see later to fix the broader problem.

**Comment by flaviendelangle** [comment]
Closed by #5919
