### ISSUE TITLE
[license] "MUI X invalid license" message does not disappear

### ISSUE THREAD

**Issue by Kevin-TWRT** [mui/mui-x#6039]
### Order ID 💳

49284

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I bought a datagrid Pro license. I added the license key in the code but the message "MUI X invalid license" still appears.

### Your environment 🌎

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
  npmPackages:
    @mui/core:  5.0.0-alpha.47
    @mui/icons-material: 5.0.0 => 5.0.0
    @mui/lab: 5.0.0-alpha.47 => 5.0.0-alpha.47
    @mui/material: 5.0.0 => 5.0.0
    @mui/private-theming:  5.1.1
    @mui/styled-engine:  5.1.1
    @mui/styled-engine-sc: 5.0.0 => 5.0.0
    @mui/styles: 5.0.0 => 5.0.0
    @mui/system: 5.0.0 => 5.0.0
    @mui/types:  7.1.0
    @mui/utils:  5.1.1
    @mui/x-data-grid: 5.0.0-beta.1 => 5.0.0-beta.1
    @mui/x-data-grid-generator: ^5.0.1 => 5.0.1
    @mui/x-data-grid-pro: ^5.0.1 => 5.0.1
    @mui/x-license-pro:  5.0.1
    @types/react: 17.0.22 => 17.0.22
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: 5.3.1 => 5.3.1
    typescript: 4.4.3 => 4.4.3

**Comment by flaviendelangle** [comment]
Hey
You are using an old `@mui/x-data-grid` version, probably too old for your new license (which most likely requires `5.11.0` or above)
Is there something preventing you from updating ?
There should be no breaking change and a good amount of improvements. It will even be more stable since you are currently using a beta version. 

By the way, we strongly recommence you using the same version of all our `x` packages. You can have incompatibilities even between very close versions. We are only guaranteeing semver if you consider those packages as a whole.

If for some reason you can't update, please contact us at *contact@mui.com* and we will provide you a license in the old format that will be compatible with your version.
