### ISSUE TITLE
[pickers] opening MobileTimePicker incorrectly selects the hour

### ISSUE THREAD

**Issue by BC-M** [mui/mui-x#6063]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If the time selection is opened at the position of the mouse pointer, an input is incorrectly detected. The hour which is at the position of the mouse pointer is confirmed as input.

### Expected behavior 🤔

Open the input dialog without selecting a hour.

### Steps to reproduce 🕹

Steps:
1. Open picker (it must be opened at the position of the mouse pointer)
2. look at it

## GIF:

![Bildschirmaufnahme-2022-09-07-um-11 18 26](https://user-images.githubusercontent.com/40334865/188842130-d14687a9-5b8c-4fb6-8cba-fcf33be03f4e.gif)

## Codesandbox:

https://codesandbox.io/s/eager-carlos-zmr9yu?file=/demo.tsx

### Context 🔦

We have a time selection in a dialog, which is why the picker opens automatically at the position of the mouse pointer.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.6.1
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.96 
    @mui/core-downloads-tracker:  5.10.4 
    @mui/icons-material: ^5.10.3 => 5.10.3 
    @mui/material: ^5.10.4 => 5.10.4 
    @mui/private-theming:  5.10.3 
    @mui/styled-engine:  5.10.4 
    @mui/system: ^5.10.4 => 5.10.4 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.3 
    @mui/x-date-pickers: ^5.0.0 => 5.0.0 
    @types/react: ^18.0.18 => 18.0.18 
    react: ^18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.2 => 4.8.2 

</details>

**Comment by LukasTy** [comment]
This is a regression caused by [the change from `onClick` to `onMouseDown`](https://github.com/mui/mui-x/pull/5651/files#diff-017d2066c0c4aa534dd10bbbfcce1af4230ecbcbca35f1c170639cb85ecf540bR168) for picker opening.
The regression happens on Mobile Time Picker, because of [this `onMouseUp`](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/ClockPicker/Clock.tsx#L277).
In order not to break anything around the clock picker itself, the easiest solution to this problem is to change `onMouseDown` to `onMouseUp`:
```diff
diff --git a/packages/x-date-pickers/src/internals/components/PureDateInput.tsx b/packages/x-date-pickers/src/internals/components/PureDateInput.tsx
index cf7a97d8..2e16b802 100644
--- a/packages/x-date-pickers/src/internals/components/PureDateInput.tsx
+++ b/packages/x-date-pickers/src/internals/components/PureDateInput.tsx
@@ -165,7 +165,7 @@ export const PureDateInput = React.forwardRef(function PureDateInput<TInputDate,
       'aria-readonly': true,
       'aria-label': getOpenDialogAriaText(rawValue, utils),
       value: inputValue,
-      ...(!props.readOnly && { onMouseDown: onOpen }),
+      ...(!props.readOnly && { onMouseUp: onOpen }),
       onKeyDown: onSpaceOrEnter(onOpen),
     },
     ...TextFieldProps,
```
This would make the opening of the picker a bit less snappy (actually, the same as previously, where we used `onClick`), but we would no longer have issues, of `onMouseUp` being picked up by the `Clock` component.
What do you think @oliviertassinari @flaviendelangle?

**Comment by flaviendelangle** [comment]
If its the behavior we had before I don't see any problem to use `onMouseUp`
