### ISSUE TITLE
[MobileDatePicker] Date set when dialog is closed by pressing escape

### ISSUE THREAD

**Issue by howlettt** [mui/mui-x#6135]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When the mobile date picker is closed by pressing escape or clicking on the mask the selected date is updated

### Expected behavior 🤔

Selected date should not update when the dialog is closed by pressing escape or clicking on the mask

### Steps to reproduce 🕹

Link to live example:
"For mobile" field under the "Responsiveness" example https://mui.com/x/react-date-pickers/date-picker/#responsiveness

Steps:
1. Open the date picker dialog
2. Select a different date
3. Press the escape key (or click outside the dialog on the mask)
4. Selected date is updated

### Your environment 🌎

Chrome desktop browser
@mui/x-date-pickers@5.0.1

**Comment by alexfauquette** [comment]
The date is not selected when pressing the  <kbd>Escape</kbd>. It's selected when you select the date (click on the day)

But you can customize this behavior.

In the documentation, we use `onChange` to update the `value` prop each time the user selects a new date. But you can use `onAccept` to update the `value` only when the user accepts the selected value.

Does it make sens?

**Comment by howlettt** [comment]
Yes using `onAccept` would work, but I believe there is still a bug here, in that I think pressing `Escape` should behave the same as pressing the `Cancel` button. Pressing the `Cancel` button in the documentation example reverts the selected date back to the date when the dialog was opened, and pressing `Escape` currently does not.

**Comment by flaviendelangle** [comment]
It was a decision we took a few months back in #4408
You can have a look at the discussion for context

What was clear is that there is no perfect behavior and we have people asking for incompatible things.
We fixed a set of built in behaviors (what happens when you click "Accept", when you click "Cancel", when you press Escape, when you click outside etc...).
I would be cautious before changing this built in behaviors.
But I think we need to give users a way to customize them (not sure how).

**Comment by howlettt** [comment]
Ok, seems inconsistent to me, but I guess there are arguments both ways
