### ISSUE TITLE
[DataGridPro] Remove autofilter when you stop typing

### ISSUE THREAD

**Issue by lincolnmqs** [mui/mui-x#6145]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello, is it possible to remove the automatic filter application when stopping searching for a value in the table column?

It's causing some problems as the user is typing, stops to look at something and comes back and the filter applies to a lot of data. 

Is it possible to apply only by clicking the enter button on the keyboard or increasing the timer?

Automatic filter gif:

![image](https://i.ibb.co/n8b8Shp/apply-filter.gif)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
For now the debounce is hardcoded in the `<GridFilterInputValue/>` :

https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx#L93:L117

An improvement could be to add a prop to control it as follow: `componentsProps: { filterPanel: { inputDebouceMs: 1000 } } }`

For now a solution is to create your own `GridFilterInputValue`. This solution would allow to support custom behavior like validating the value when pressing <kbd>Enter</kbd> or `onBlur`.

If you go for the custom component, a lot of the [`<GridFilterInputValue/>`](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx) can be reused. Notice that for legacy reason this component support both text and select. The select aspect is not needed anymore since we now have a dedicated component for that

**Comment by alexfauquette** [comment]
Somewhat linked to #5078

**Comment by lincolnmqs** [comment]
@alexfauquette do you have an example of using the GridFilterInputValue component?

**Comment by alexfauquette** [comment]
Not sure to get your question.

There is an [example in the documentatin](https://mui.com/x/react-data-grid/filtering/#custom-input-component) where we create a  `RatingInputValue`.

You can replace the definition of `RatingInputValue` with the definition of [GridFilterInputValue](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx?rgh-link-date=2022-09-14T08%3A04%3A19Z) and then customize this definition according to your needs.

**Comment by lincolnmqs** [comment]
@alexfauquette this example is a customization of the filter directly on the table column, is it possible to customize the general filter?

My problem:
![image](https://i.ibb.co/LvykhNB/2022-09-14-17-48.png)

Example:
![image](https://i.ibb.co/mynXb66/2022-09-14-17-48.png)

**Comment by alexfauquette** [comment]
It's the same. The difference between opening by clicking on "Filtros" or the "Rating" is the next one:
- On "Filtros" the filter panel opens with the first column set by default
- On "Rating" the filter panel opens with the "Rating" column set by default

To customize all the TextFIled input you need to override them for all the columns and all the filter operator


@m4theushw maybe it's an opportunity for slots
