### ISSUE TITLE
The focus on edit mode loses when I use fieldToFocus

### ISSUE THREAD

**Issue by jfbenavid** [mui/mui-x#6175]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm implementing the edit on my grid with RowModesModel to use tab in order to create a new row and also to create a new row when I click on a button. I'm able to edit and delete the rows in my grid but when I try to use the "Add new" button after an edit, this changes automatically the edit mode to view mode the row and loses the focus.

Please use [this](https://codesandbox.io/s/data-grid-community-forked-8lqzg8?file=/src/App.tsx) sandbox to see what I'm doing

### Expected behavior 🤔

When I click on the button it should keep the focus and edit mode on the row/column I want to

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/data-grid-community-forked-8lqzg8?file=/src/App.tsx

Steps:
1. In the sandbox example try to edit any of the rows
2. Commit the changes (click outside the row / push enter)
3. Try to add a new row using the button "add new"

### Context 🔦

I want to be able to add new rows and select the column I want to focus programatically

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
I struggle to get what going wrong with the codesandbox.

What I did:
1. Edit a row
2. validate with Enter
3. Click on "new row"
4. fill the new row with keyboard, Tab and Enter
5. Redo to operation

I do not see what is unexpected

https://user-images.githubusercontent.com/45398769/190980402-0ec9f041-a455-4214-bcb5-0a18203c5673.mp4

**Comment by jfbenavid** [comment]
Hello Alex, thanks, you are right, that happens when I use any of the action buttons (the right column)
![sandbox](https://user-images.githubusercontent.com/8607604/191118697-40a1cfaf-e740-4651-84e6-03845a717ef9.gif)
![edit with button](https://user-images.githubusercontent.com/8607604/191119366-73115399-52f5-4315-a6cd-4d242c247a05.gif)

**Comment by m4theushw** [comment]
The CodeSandbox is using React 17. I tested with React 18 and I couldn't reproduce the bug. This is one way to fix it: upgrade React. I investigated what is happening and the problem is that `cellFocusOut` is published while the button is being clicked. What happens is:

- Click the button
- `setRows` is called adding a new row
- `setRowModesModel` is called to change the edit mode to "edit" and moves the focus to "col1"
- The click reaches the listener added `document` in https://github.com/mui/mui-x/blob/2d9cc6baee400a5c85617a47180313e10ed0ea16/packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts#L200
- Triggers `cellFocusOut` https://github.com/mui/mui-x/blob/2d9cc6baee400a5c85617a47180313e10ed0ea16/packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts#L239-L242 that is interpreted as if a click happened outside the newly added row, so it stops its edit mode.

One dirty way to fix this is wrap `setRowModesModel` in a `setTimeout` to make it be called slightly after the new row is added. Here's the updated CodeSandbox: https://codesandbox.io/s/data-grid-community-forked-bm659r?file=/src/App.tsx
