### ISSUE TITLE
Allow custom indentation width for DataGrid Tree Data rows

### ISSUE THREAD

**Issue by harrycollin** [mui/mui-x#6371]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The current implementation of DataGrid with tree data defines indentation steps of 16px per level. It would be nice if this were customisable either through a prop or class override via the SX prop. 

![image](https://user-images.githubusercontent.com/10602138/193588323-5c0a1393-26a1-4e1d-aa02-0e8ed23cc86b.png)
![image](https://user-images.githubusercontent.com/10602138/193588092-75cc0032-8e69-45fb-9343-678127ac790b.png)

### Examples 🌈

Here is an example were I manually made the indentation half the original size. 
![image](https://user-images.githubusercontent.com/10602138/193588900-b9a9e81a-9917-49ff-a48b-147cf55a32a2.png)

### Motivation 🔦

This would be useful were heavy customisation is needed. In my case I have a width limitation on how wide the DataGrid can be on the page and a compact indentation would be a nice addition.

### Order ID 💳 (optional)

41099

**Comment by DanailH** [comment]
Hi, @harrycollin thanks for raising this!
The problem is this line https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx#L69

Currently, we don't support a way for you to use the `sx` prop to overwrite this value but you can extend the entire component. We have an example of how to do that - you can check the Children lazy-loading section here https://mui.com/x/react-data-grid/tree-data/#children-lazy-loading. If you check the code example you can see how to overwrite the entire component and provide your own spacing.

**Comment by harrycollin** [comment]
Hi @DanailH, thank you for the example. I will consider this option, although it's a shame to go to all the extra effort to maintain a custom grouping cell for such a small tweak :P
