### ISSUE TITLE
[DateRangePicker] Allows to select year from the header

### ISSUE THREAD

**Issue by jb-thery** [mui/mui-x#6458]
it would be super cool if we could change the years in the Date Range Picker by clicking directly on the years, which would make a select appear with the possibility of changing only the years

![https://i.ibb.co/YXDQb1j/Capture-d-e-cran-2021-07-26-a-19-37-26.png](https://i.ibb.co/YXDQb1j/Capture-d-e-cran-2021-07-26-a-19-37-26.png)

**Comment by alexfauquette** [comment]
It sounds to be a good idea. At least, we could add a slot for the `DateRangePickerViewDesktopArrowSwitcher` such that the `Typography` could be replaced by a `Menu`.

Maybe there is a deeper topic, about large range selection. Because when selecting between 2019 and 2021 It does not make sense to see two months in 2019 of two months in 2021. I would prefer to see the selected month in 2019 and the selected month in 2021 with a small UI bteeen them to highlight that the months are not the same

**Comment by spiftire** [comment]
I would love this feature. my Order ID credit_card is: 45069

**Comment by flaviendelangle** [comment]
Duplicates #4546
