### ISSUE TITLE
[pickers] Translation not working properly

### ISSUE THREAD

**Issue by pimentaro** [mui/mui-x#6461]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

translate not working properly
![image](https://user-images.githubusercontent.com/59784588/195222278-12d75ea8-974b-4bc5-9455-2caf1a2f98c9.png)

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by yaredtsy** [comment]
@flaviendelangle I think its Brazilian Portuguese, his address on GitHub says in brazil, I have recreated it https://codesandbox.io/s/still-lake-1ylqzy?file=/demo.tsx . the Portuguese also look wrong

**Comment by LukasTy** [comment]
Hello @pimentaro 
Following up on the above comment.
You could also [provide a custom `dayOfWeekFormatter`](https://codesandbox.io/s/busy-cherry-s14ks7?file=/demo.tsx) to print the full minimal weekday string.

___

Root cause of the issue is the fact that date-io [uses `dd` as the format](https://github.com/dmtrKovalenko/date-io/blob/master/packages/dayjs/src/dayjs-utils.ts#L349) to get the values to build an array of week days and in case of `dayjs` those values are [somewhat interesting](https://github.com/iamkun/dayjs/blob/dev/src/locale/pt-br.js#L8) and not on par with other libraries like `date-fns`.
[Here is an example](https://codesandbox.io/s/optimistic-pond-xyqr7f?file=/demo.tsx) using same localization with date-fns and the resulting weekdays shorthands.

TL.DR.: This is not an issue with MUI or it's localization/translation.
If you think it is an error—please open an issue in `dayjs` library. 😉
