### ISSUE TITLE
[DataGridPremium] How to make rowGrouping with pinnedColumns working with colSpan that should be only for group headers

### ISSUE THREAD

**Issue by KarafiziArtur** [mui/mui-x#6462]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when I implement `pinnedColumns` for the Day column with known workaround by using `GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD` - 

```
pinnedColumns: {
  left: [GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD]
},
```

I get `colSpan` broken
<img width="1006" alt="Screen Shot 2022-10-12 at 11 14 20" src="https://user-images.githubusercontent.com/6214770/195241418-1570be9d-cd66-47a5-bf56-1bd7af33ef03.png">

### Expected behavior 🤔

I expect that `colSpan` will be working fine with pinned columns as well as without pinning

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-data-grid-premium-pinned-grouping-colspan-nlg8o1?file=/demo.tsx

Steps:
1. go to https://codesandbox.io/s/mui-data-grid-premium-pinned-grouping-colspan-nlg8o1?file=/demo.tsx
2. uncomment row:188
3. see and check how colSpan not working

### Context 🔦

Hi! We want to use DataGridPremium for a big project but there are several unexpected behaviours with tables

I have an example table with `rowGrouping` enabled. I used `colSpan` for `groupingColDef` only for headers

```
const groupingColDef = {
    leafField: "day",
    colSpan: (params: GridCellParams) => {
      if (`${params.id}`.startsWith("auto-generated-row")) {
        return columns.length - 1;
      }

      return 1;
    },
  };
```

and it works fine to make spanning only for group headers in one row and other rows is without `colSpan`.

<img width="997" alt="Screen Shot 2022-10-12 at 11 11 31" src="https://user-images.githubusercontent.com/6214770/195241157-360ccbb3-fce7-4466-9024-f8fd9db78550.png">

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.6
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Not Found
    Firefox: 104.0.2
    Safari: 16.0
  npmPackages:
    @mui/x-license-pro: 5.17.0 => 5.17.0 
```
</details>

**Comment by cherniavskii** [comment]
Hey @KarafiziArtur 
Thanks for submitting an issue, that's an interesting use case!

### `colSpan` + pinned columns behaviour

When setting a `colSpan` value to N, it means that the cell will be merged with the next (N - 1) cells.
But you cannot merge pinned and unpinned cells together, because it would defeat the purpose of pinned columns.
Still, you can use `colSpan` to merge cells inside pinned columns.

Consider this demo: https://codesandbox.io/s/sleepy-sky-8xxilo?file=/demo.tsx
The cells in the first column have `colSpan: 2`.

Without pinned columns it means that first cell is merged together with the second one:
<img width="459" alt="Screenshot 2022-10-12 at 11 40 17" src="https://user-images.githubusercontent.com/13808724/195308708-1eaee189-29f6-43b2-91b6-56c28a58f86d.png">
WIth first column being pinned, there's only one column in the pinned columns scope, therefore `colSpan` has no effect there:
<img width="458" alt="Screenshot 2022-10-12 at 11 40 25" src="https://user-images.githubusercontent.com/13808724/195309138-71af5ce7-88ad-4400-a35a-7835bb02a7b8.png">
But when you pin another column, `colSpan` would work because now there is one more cell to merge with:
<img width="459" alt="Screenshot 2022-10-12 at 11 40 33" src="https://user-images.githubusercontent.com/13808724/195309298-4c3bea46-8c82-44ea-b677-cc0f66c40898.png">

### `colSpan` + row grouping

Setting `colSpan` in `groupingColDef` applies `colSpan` **only** to the cells in grouping column.
As you pointed out, this works. Because there are cells in the same scope of columns ("unpinned") that can be merged together.

### `colSpan` + row grouping + pinned columns

As soon as your grouping column is pinned, there are no cells in the scope of grouping column (left pinned columns) that can be merged together (similar to the screenshot above with one pinned column).

I'm not sure what is your expectation in this case, but I assume you would expect all unpinned cells in the grouping rows to be merged together, like this:
<img width="846" alt="Screenshot 2022-10-12 at 11 49 46" src="https://user-images.githubusercontent.com/13808724/195310872-4b51b788-544f-454b-bd95-4b5e570de925.png">

In order to achieve that, you should set the `colSpan` to the first unpinned column instead of the grouping column:
```tsx
{
  field: "0",
  headerName: slotTimesLookup[0],
  ...slotColumnCommonFields,
  colSpan: (params: GridCellParams) => {
    if (`${params.id}`.startsWith("auto-generated-row")) {
      console.log(params.id);
      return columns.length - 1;
    }

    return 1;
  }
}
```
Here's the demo: https://codesandbox.io/s/mui-data-grid-premium-pinned-grouping-colspan-forked-zjz0go?file=/demo.tsx

Is this what you are trying to achieve?

**Comment by KarafiziArtur** [comment]
> Hey @KarafiziArtur Thanks for submitting an issue, that's an interesting use case!
> Is this what you are trying to achieve?

Hi [@cherniavskii](https://github.com/cherniavskii),

Thanks for the expanded answer. In our case, the title of the group header will be quite long - almost half of the table so we need to make it full width, not only to join 2 or 3 columns so that the solution will be to enable `colSpan` work with `pinnedColumns` and `rowGrouping` but I'm not sure how it will be easy to implement it

**Comment by KarafiziArtur** [comment]
Right now I end up with the second column as the grouping of rows
<img width="1078" alt="Screen Shot 2022-10-13 at 14 55 22" src="https://user-images.githubusercontent.com/6214770/195523911-543e1fa2-a367-42e8-bfa0-2d0cf9943ab0.png">

[Codesandbox demo](https://codesandbox.io/s/mui-data-grid-premium-pinned-grouping-colspan-nlg8o1?file=/demo.tsx)
But it's not what we expected. It will be better to have some parameter to join scopes for specific rows

**Comment by cherniavskii** [comment]
> the solution will be to enable colSpan work with pinnedColumns

I don't think this is possible. Pinned columns position is fixed, while the rest of the columns may scroll.


https://user-images.githubusercontent.com/13808724/195554396-acaeb842-3787-4343-9916-9f3b2523b694.mov

How would horizontal scrolling work if `colSpan` of the pinned columns will impact non-pinned columns?

**Comment by cherniavskii** [comment]
> Right now I end up with the second column as the grouping of rows

That's a good idea! You might also consider pinning Day column on the right side to make it look a bit cleaner.

**Comment by KarafiziArtur** [comment]
> I don't think this is possible. Pinned columns position is fixed, while the rest of the columns may scroll.
> How would horizontal scrolling work if `colSpan` of the pinned columns will impact non-pinned columns?

I understand the problem and see that the current implementation of the DataGridPremium doesn't support the expected behaviour with `colSpan + rowGrouping + pinnedColumns`


> That's a good idea! You might also consider pinning Day column on the right side to make it look a bit cleaner.

It's not in the example case but in our working case, we already have pinned columns on the right side

Anyway thanks for the explanation and help. I'm closing the issue
