### ISSUE TITLE
[DataGrid] Filter not editable in Bootstrap Modal 

### ISSUE THREAD

**Issue by radu-nicoara-bayer** [mui/mui-x#6710]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/datagriddemo-material-demo-forked-qp04qg?file=/demo.tsx

Steps:
1. Add the datagrid inside a bootstrap modal, as in the link above
2. Go to a column -> filter -> try to add a value
3. Clicking on the field "Filter Value" will temporarily focus on it, and then immediately lose focus

### Current behavior 😯

Clicking on the field "Filter Value" will temporarily focus on it, and then immediately lose focus

### Expected behavior 🤔

Filter should be editable

### Context 🔦

We have a popup in which we need to display a list of things. They should be filterable

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Used Edge and Chrome to test the issue
```
</details>

### Order ID 💳 (optional)

39991

**Comment by DanailH** [comment]
Hi, @radu-nicoara-bayer thanks for reporting this!

The problem is with the Bootstrap `Modal` component itself. By default, it enforces focus on itself. You can disable this via the `enforceFocus={false}` prop. You can check the example below:
https://codesandbox.io/s/datagriddemo-material-demo-forked-inxxmi
