### ISSUE TITLE
[data grid] One Parent cannot have similar children(same names) with different values

### ISSUE THREAD

**Issue by nalim-mdosl** [mui/mui-x#6796]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Example : 
const rows = [
  {
    hierarchy: ['Thomas'],
    jobTitle: 'Head of Sales',
    recruitmentDate: new Date(2017, 3, 4),
    id: 1,
  },
  {
    hierarchy: ['Thomas', 'Robert'],
    jobTitle: 'Sales Person',
    recruitmentDate: new Date(2020, 11, 20),
    id: 2,
  },
  {
    hierarchy: ['Thomas', 'Robert'],
    jobTitle: 'Business Person',
    recruitmentDate: new Date(2020, 10, 20),
    id: 23,
  },

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/90594423/200913367-2289a295-aefb-46d0-93a9-8452f5b9a99c.png">

Here Thomas is Parent and he has 2 childrens called Robert. Both childrens names are same but different in jobTitle and id.
But getTreeDataPath will not work for this data set.
In my project we have same kind of data set. childrens names are same but values different. 

### Examples 🌈

https://codesandbox.io/s/nbfi4q?file=/demo.js

Change 2 children names into same names under one parent and check.

### Motivation 🔦

We are working in a Hotel related data. So one hotel can have same set of children data but with different values. When we apply "getTreeDataPath" prop it will not work. I need a fix for this.

### Order ID 💳 (optional)

51399

**Comment by MBilalShafi** [comment]
@nalim-mdosl Tree data path has to be unique as we have to generate leaves based on that but you can add a new field in data and use `groupingColDef.valueGetter` to show the same label more than once.

Here's an example sandbox: https://codesandbox.io/s/condescending-browser-oztf3z?file=/demo.js

Can you check if that could work for you?

**Comment by alexfauquette** [comment]
@flaviendelangle Is their something preventing from generating leaves from hierarchy and the row id, such that multiple rows could have the same parent hierarchy?

**Comment by flaviendelangle** [comment]
Nothing prevents from doing it, it's probably even the recommended approach.
The hierarchy have to be built in a way its unique.
We could add an example in the doc about it.

**Comment by alexfauquette** [comment]
I was thinking about doing that internally. For example if you have hotels and want to group them by country, I would expect to be able to do

```js
{hierarchy: ['Europe', 'Italy'], name: 'Milano-central Hotel'},
{hierarchy: ['Europe', 'Italy'], name: 'Roma Hotel'},
{hierarchy: ['Europe', 'France'], name: 'Charles V'},
{hierarchy: ['Europe', 'France'], name: 'Carlton Lille'},
```

Such that I automatically get 2 levels (continents and country) that can be collapse/expend.

Currently it have to be written as follow, which sounds counter intuitive
```js
{hierarchy: ['Europe', 'Italy', 'Milano-central Hotel']},
{hierarchy: ['Europe', 'Italy, 'Roma Hotel']},
{hierarchy: ['Europe', 'France', 'Charles V']},
{hierarchy: ['Europe', 'France', 'Carlton Lille']},
```

My idea was to support the first option. But after writing it clearly, it appears that we can not support both, because we need to know if the `hierarchy` leads to a leaf or to the last parent of leafs

I propose to write a section "Duplicate hierarchy paths" with the [following example](https://codesandbox.io/s/pensive-edison-9xcvyl?file=/demo.js:624-625):

```js
const groupingColDef = {
  headerName: "Location",
  valueGetter: (args) => {
    return args.rowNode.groupingKey === args.row.id
      ? ""
      : args.rowNode.groupingKey;
  }
};

const getTreeDataPath = (row) => [...row.hierarchy, row.id];
```

**Comment by flaviendelangle** [comment]
For me you don't have to change your dataset but just your path building, just like on your last example.

```ts
const getTreeDataPath = (row) => [...row.hierarchy, row.id];
```

And not caring about the data itself allow people to really group how they want depending on there use case.
For instance, imagine you only want to have a deeper tree when 2 elements have the same hierarchy.

```
Thomas
  Robert
    Robert 1
    Robert 2
  John
```

instead of

```
Thomas
  Robert
    Robert 1
    Robert 2
  John
    John 1
```

Then you can do a lookup and only append your additional id-based element if several users have the same name.
Something like

```tsx
const getTreeDataPath = React.useMemo(() => {
  const lookup  = rows.reduce((acc, row) => {
    const hierarchyStr = row.hierarchy.join('/')
    if (!acc[hierarchyStr]) {
      acc[hierarchyStr] = []
    }
    acc[hierarchyStr].push(row.id)
  }, {});

  return (row) => {
    const hierarchyStr = row.hierarchy.join('/')
    if (lookup[hierarchyStr].length > 1) {
      return [...row.hierarchy, `${row.hierarchy[row.hierarchy.length - 1} ${lookup[hierarchyStr].indexOf(row.id) + 1}`];
    }

    return row.hierarchy
  }
}, [rows]);
```

**Comment by nalim-mdosl** [comment]
> 

valueGetter solved this issue.

**Comment by nalim-mdosl** [comment]
> @nalim-mdosl Tree data path has to be unique as we have to generate leaves based on that but you can add a new field in data and use `groupingColDef.valueGetter` to show the same label more than once.
> 
> Here's an example sandbox: https://codesandbox.io/s/condescending-browser-oztf3z?file=/demo.js
> 
> Can you check if that could work for you?

valueGetter solved this issue. The above approach is working.
