### ISSUE TITLE
[data grid] Support other languages in Data Grid as in MUI

### ISSUE THREAD

**Issue by dqfort** [mui/mui-x#6865]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Some languages are available in MUI https://mui.com/material-ui/guides/localization/,
but not in Data Grid https://github.com/mui/mui-x/tree/HEAD/packages/grid/x-data-grid/src/locales

### Examples 🌈

Thai language

**Comment by flaviendelangle** [comment]
The translations are handled by the community, both on `@mui/material` and on the X packages.
Otherwise we would not be able to provide that many languages.

You can see https://github.com/mui/mui-x/issues/3211 for more information concerning the X packages.

@joserodolfofreitas maybe we could improve the wording on the core page, replacing "MUI" by "MUI Material".
Right now it is indeed unclear that those locals only cover this library.
