### ISSUE TITLE
[DatePicker] Input with `standard` variant

### ISSUE THREAD

**Issue by stefc** [mui/mui-x#6991]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want to reach the same look as the Select component where I'm using ```variant="standard"``` without a border. How I can reach that with a workaround for now ?

![image](https://user-images.githubusercontent.com/464696/203801790-9c506436-fa0b-40d9-ba04-1174ebd224b7.png)

### Examples 🌈

![image](https://user-images.githubusercontent.com/464696/203802445-d5a75e62-dbe2-458c-b39a-2a4e73bbd487.png)

Here you see a TextField with variant=standard, the same look I want for the datepicker and can't see how I can archive this at the moment.

**Comment by LukasTy** [comment]
Updating the suggested `renderInput` from demos should do the trick. 🤔 
Is it not working for you?
```diff
-renderInput={(params) => <TextField {...params} />}
+renderInput={(params) => <TextField {...params} variant="standard" />}
```

If it does not solve your problem—please provide a reproduction example. You can use any of the documentation demos as a base.

**Comment by stefc** [comment]
@LukasTy  Thanks it works good find it in the demos and change it to standard. 
![image](https://user-images.githubusercontent.com/464696/203810149-d4a3eaea-0544-41ca-9541-441386656f26.png)
very fine !
Would be nice if this property would be directly supported on the DatePicker itself ;) ?

**Comment by LukasTy** [comment]
> Would be nice if this property would be directly supported on the DatePicker itself ;) ?

This property has nothing to do with `DatePicker` itself. It's relevant only to the rendered input.
With v6 the `renderInput` will be replaced by a unified way to pass props to various internal components. then it hopefully will make more sense as to which props are where. 😃

**Comment by stefc** [comment]
> > Would be nice if this property would be directly supported on the DatePicker itself ;) ?
> 
> This property has nothing to do with `DatePicker` itself. It's relevant only to the rendered input. With v6 the `renderInput` will be replaced by a unified way to pass props to various internal components. then it hopefully will make more sense as to which props are where. 😃

ok understand this for a newbie like me it's a little bit confusing that the DatePicker is not unified with Select & TextField that having such a 'variant' property. I'm waiting forward for v6 for a replacement ;) 

Greetings from Germany

**Comment by LukasTy** [comment]
> ok understand this for a newbie like me it's a little bit confusing that the DatePicker is not unified with Select & TextField that having such a 'variant' property.

Those components are serving single responsibility and having all props on the root certainly makes sense.
In the pickers case there are two distinct ways of interacting with the component:
- changing the input value
- interacting with the picker popper or dialog (in mobile)

That's why the props passing is split between the two.

**Comment by marcusjwhelan** [comment]
@LukasTy I have the newest version of DatePicker that doesn't have the `renderInput` option. Now that the ability to edit the input element has been taken away how will I have custom code applied to the input component? 

With the `TextField` adding a background color change when readonly was a nice addition because otherwise you don't know why you can't edit the field, unless you have a screen reader announcing it is readonly. 

How can I apply my own TextField or Input component and supply the prop types to the DatePicker component so I can use my old component like before.

**Comment by LukasTy** [comment]
@marcusjwhelan You can use `componentsProps.textField` or `slotProps.textField` to achieve the same behavior as before.
An example is given [in the migration doc](https://mui.com/x/migration/migration-pickers-v5/#input-renderer-required-in-v5). 😉

**Comment by charith-dianahr** [comment]
This worked
`slotProps={{ textField: { variant: "standard" } }}`

<img width="236" alt="Image" src="https://github.com/user-attachments/assets/fa8876ab-47ff-4f85-96d7-7bcdf144ae73" />
