### ISSUE TITLE
[data grid] Is there a way to fix this right pin issue when using column grouping?

### ISSUE THREAD

**Issue by fionaDawn** [mui/mui-x#7041]
### Order ID 💳

51218

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Weird behavior  when pinning any column to the right under the last column group

Codesandbox straight from [MUI's Defining Column Group demo](https://mui.com/x/react-data-grid/column-groups/#define-column-groups)

https://user-images.githubusercontent.com/15187771/204563407-fb6c743a-049d-479b-a8b8-bb65ba64a9fc.mov

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 12.6
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/base:  5.0.0-alpha.85 
    @mui/icons-material:  5.8.4 
    @mui/lab:  5.0.0-alpha.86 
    @mui/material:  5.8.4 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/styles:  5.8.4 
    @mui/system:  5.8.4 
    @mui/types:  7.1.4 
    @mui/utils:  5.10.6 
    @mui/x-data-grid:  5.17.9 
    @mui/x-data-grid-pro:  5.17.9 
    @mui/x-date-pickers:  5.0.0-alpha.6 
    @mui/x-license-pro:  5.17.0 
    @types/react:  17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.7.4 
```
</details>

**Comment by mamodev** [comment]
up vote! this is an annoyng issue

**Comment by fionaDawn** [comment]
Is there a way to disable or remove "Pin to the right" in the meantime?

**Comment by MBilalShafi** [comment]
> Is there a way to disable or remove "Pin to the right" in the meantime?

With the new implementation of the column menu API released in v6, you can [customize](https://mui.com/x/react-data-grid/column-menu/#customize-column-menu-items) the custom pinning item in the `ColumnMenu` to achieve the desired behavior until a proper fix for the bug is there.

I stripped off some logic from the [default PinningItem](https://github.com/mui/mui-x/blob/380c12ad998d54b49e6ae798b249b925db125f00/packages/grid/x-data-grid-pro/src/components/GridColumnMenuPinningItem.tsx) to keep only **Pin to Left** part in this [codesandbox example](https://codesandbox.io/s/customize-column-menu-pinning-item-4urub1?file=/src/App.tsx).

For more examples of how to customize the column menu, see the [documentation](https://mui.com/x/react-data-grid/column-menu/).

**Comment by claudioctonha** [comment]
Is there any way to fix this? I am facing the same issue.

**Comment by RubtsovAV** [comment]
the same

**Comment by saikumarf9** [comment]
Hey, Any update on this?

**Comment by hafley66** [comment]
Hi in the same boat here. I am trying to use pinned columns with columns that do not belong to column groups. Here is another repro, https://codesandbox.io/s/icy-sun-fx7kdr?file=/Demo.tsx

The issue happens when the "Age" column disappears after uncommenting out the pinnedColumns prop. 

The true error is that the pinned columns first row of the headers is too long, you can see it in the "data-fields" attribute, it has not just the pinned columns, but also the next ungrouped column.

<img width="1358" alt="Screen Shot 2023-09-28 at 10 36 52" src="https://github.com/mui/mui-x/assets/6750483/99a74c2f-6262-4ad5-8bc6-fea05aaa3e65">

**Comment by hafley66** [comment]
https://codesandbox.io/s/pinned-and-grouped-fix-vgdpxm?file=/Demo.tsx

I manage a library that wraps this one for my company. I have spots where i add special fields to the columns defs and such, and i just figured out how to get around this. 

i made sure that any col def that had no grouping was given a "phantom" group definition on behalf of the user. feel free to adopt this code.

if you dont want to center the column headers like i do in the demo, just remove the styled code

**Comment by matthewbennett** [comment]
The below should do the trick! 
```
  .MuiDataGrid-cell--pinnedLeft': {
      position: 'sticky',
      left: 0,
      zIndex: 1,
  }
```
