### ISSUE TITLE
[pickers] Support days of the week in date and time fields

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#7254]
### Summary 💡

Developers may need to support formats containing the day of the week. 
The day of the week section, as with other sections, should be editable through text-typing and, ideally, up/down arrow keys, which should lead to navigation through the days in the calendar.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/550141/208475863-625abd20-92fe-434c-8388-9814b5cf5955.png">

### Motivation 🔦

Proper support for some edge cases with date formats.

**Comment by alexfauquette** [comment]
> Should be editable through text-typing and, ideally, up/down arrow keys

Do you have an example in mind of an interface doing that? 

If I focus on the weekday and press arrow up/down, I can expect it to move to the next/previous day in the calendar. 

But if I replace Wednesday with Monday, I don't know:
- Which Monday will I get (the first of the month, the one after the current date, the one before, ...)
- How are managed intermediate states. For example, I press "T"
	- The field will propose "Tuesday"
	- I press "h"
	- The field will propose "Thursday"
  What appends to the date selected when it's Tuesday?

**Comment by flaviendelangle** [comment]
> If I focus on the weekday and press arrow up/down, I can expect it to move to the next/previous day in the calendar.

We do agree with that one

> Which Monday will I get (the first of the month, the one after the current date, the one before, ...)

That's the main issue indeed.
Right now, I am applying a similar as for the meridiem.
For the merdiem, if you are in `PM` and press `A` it goes to the `AM` of the same day.

For the week day, my approach would be to stay in the same week.
In some cases that might be debatable (for a week starting on `Sunday`, if you type `Sa` you might expect to go to the day before and not 6 days ahead.

We could change the logic to go to the closest day, but that could lead to other problem (in the next point, staying in the same week guarantees that when typing `Th`, I am going on the `Thursday` of the same week I had 2 steps back).
The editing is not as smooth as for the rest of the sections because of the tight link with the date section.

I am also applying a less strict parsing on the format, to consider dates with every section filled except the week day as valid, since we have all the information we need.

> How are managed intermediate states. For example, I press "T"

We can manage them just like for the months, when I press "J" I go to January, when I then press "U" I go to "June" etc...
But with the same caveat as you raised in the previous point.
