### ISSUE TITLE
[data grid] Improve column separators to display ability to resize columns

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#7268]
### Summary 💡

The column headers separators present no distinguishable difference between columns that can be resized and columns that don't. This is a follow-up on #1623.

On https://github.com/mui/mui-x/pull/7067, we started exploring ways to make this difference clear, but there're also some [challenges to validate](https://github.com/mui/mui-x/pull/7067#issuecomment-1356745665) and other solutions to explore.

### Examples 🌈

![image](https://user-images.githubusercontent.com/550141/208650593-a0b89117-c509-4338-83d2-3f03c686e4d8.png)

### Motivation 🔦

- Discoverability and identification of resizable columns (Better UX).

### Design
- [Figma Process](https://www.figma.com/file/W6TItYkiGJZjL5zLnfeSjy/Data-grid?node-id=1227%3A62449&t=PrKs3y9Cx0tIZdmK-0)
- [Prototype](https://www.figma.com/proto/W6TItYkiGJZjL5zLnfeSjy/Data-grid?node-id=1367%3A64345&scaling=contain&page-id=1227%3A62449&starting-point-node-id=1367%3A64345)

**Comment by oliviertassinari** [comment]
The proposed design makes sense to me 👍. In  this example, I feel like I would be able to resize but I'm not:

<img width="498" alt="Screenshot 2023-05-30 at 13 29 47" src="https://github.com/mui/mui-x/assets/3165635/b055d31b-078d-438a-8f40-4fb26cd332aa">

https://mui.com/x/react-data-grid/#mit-version

---

Minor. I think that it could be interesting to see what's the UI for when the mouse down is pressed. I wonder if it's not a bit off today: 1. the resize handle isn't tall enough, it can be hidden behind the cursor. 2. the color isn't contrasting enough. This a quick benchmark, not sure. None feels like they make a major difference.

MUI X 
<img width="345" alt="Screenshot 2023-05-30 at 13 26 01" src="https://github.com/mui/mui-x/assets/3165635/b248cc85-f310-48cd-82fa-57647b4e87b1">

Notion
<img width="149" alt="Screenshot 2023-05-30 at 13 23 53" src="https://github.com/mui/mui-x/assets/3165635/3a0cab3e-fccd-4aca-b207-4f37a1f6b076">

Airtable
<img width="170" alt="Screenshot 2023-05-30 at 13 24 15" src="https://github.com/mui/mui-x/assets/3165635/b0afa9b4-7d99-430c-9f60-64b617af2f5c">

Google Sheet
<img width="285" alt="Screenshot 2023-05-30 at 13 28 33" src="https://github.com/mui/mui-x/assets/3165635/be56a0fa-185e-4938-8a18-458d82e69a19">

**Comment by MBilalShafi** [comment]
I tried to validate the idea, here's a codesandbox with comparisons between different features: https://codesandbox.io/s/purple-shadow-c8l2xk?file=/demo.tsx

> is the resize handle tall enough

I've made it a bit taller to test if it resolves the concerns. What do you think?

CC @gerdadesign

**Comment by oliviertassinari** [comment]
@MBilalShafi Sweet, a few design execution ideas:

1. I think that the handle should stay active when moving the cursor out of the header:

https://github.com/mui/mui-x/assets/3165635/0dae23f5-b053-435d-b92b-e7a05253e605

2. I think that a small visual notch could improve the affordance that there is a handle to drag:

<img width="696" alt="Screenshot 2023-06-01 at 14 25 46" src="https://github.com/mui/mui-x/assets/3165635/6d43d91b-22c0-4374-be5f-753939719096">

But I don't see how we can pull it off without forcing a background color on the whole data grid. I'm not sure this potential UX win is worth the DX customization pain.

3. Maybe it would make sense to make the drag handle blue when it's active, and only dark when hovered. I'm saying maybe because I think it requires experimenting with it to be sure. I haven't seen other to benchmark against.
