### ISSUE TITLE
[data grid] Export to Excel fails

### ISSUE THREAD

**Issue by Richard87** [mui/mui-x#7273]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I have a DataGridToolbar like this, with export csv and export Excel buttons:

```tsx
export const DataGridToolbar = ({specialActions, showQuickFilter = true, ...props}) => {
    const apiRef = useGridApiContext()
    const theme = useTheme()

    const defaultActionButtonStyleProps: SxProps<Theme> = {
        borderRadius: 0,
        marginLeft: 1,
        marginBottom: 0.5,
        padding: theme.spacing(0.5, 1.5),
        lineHeight: 'initial',
        textTransform: 'initial',
        color: `inherit`,
        backgroundColor: theme.palette.grey[300],
        minHeight: theme.spacing(3.75),
        border: `none`,
        '&:hover': {
            backgroundColor: theme.palette.grey[400],
            border: 'none',
        },
    }

    const downloadExcel = () => apiRef.current.exportDataAsExcel()
    const downloadCsv = () => apiRef.current.exportDataAsCsv()

    return (
        // Grid Toolbar Container is a flexbox with the QuickFilter off to the left and the button groups off to the right.
        // The QuickFilter and the block of button groups stack on smaller screens, with QuickFilter going full-width.
        <GridToolbarContainer
            sx={{
                display: 'flex',
                flexDirection: 'row',
                marginBottom: 1,
                gap: 1,
                padding: 0,
                alignItems: 'flex-end',
                justifyContent: 'space-between',
            }}
            {...props}
        >
            {showQuickFilter && <GridToolbarQuickFilter sx={{flexGrow: 1}} />}
            <Box display='flex' flexDirection='column' flexGrow='1'>
                <ButtonGroup sx={{gap: 1, justifyContent: 'flex-end'}} aria-label='default datagrid action buttons'>
                    {/* @ts-expect-error */}
                    <GridToolbarColumnsButton sx={{...defaultActionButtonStyleProps}} />
                    {/* @ts-expect-error */}
                    <GridToolbarFilterButton sx={{...defaultActionButtonStyleProps}} />
                    <Button sx={{...defaultActionButtonStyleProps}} size='small' startIcon={<FileDownloadIcon />} onClick={downloadExcel}>
                        {nbNO.components.MuiDataGrid.defaultProps.localeText.toolbarExportExcel} (testing)
                    </Button>
                    <Button sx={{...defaultActionButtonStyleProps}} size='small' startIcon={<FileDownloadIcon />} onClick={downloadCsv}>
                        {nbNO.components.MuiDataGrid.defaultProps.localeText.toolbarExportCSV}
                    </Button>
                </ButtonGroup>
                {specialActions}
            </Box>
        </GridToolbarContainer>
    )
}
```

### Current behavior 😯

```
excelSerializer.js:256 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Workbook')
    at excelSerializer.js:256:32
    at step (tslib.es6.js:104:87)
    at Object.next (tslib.es6.js:88:52)
    at asyncGeneratorStep (_async_to_generator.mjs:3:24)
    at _next (_async_to_generator.mjs:25:9)
```

### Expected behavior 🤔

A excel file :) 

### Context 🔦

I have thes relevant package installed:
```
    "@mui/icons-material": "^5.10.16",
    "@mui/lab": "^5.0.0-alpha.111",
    "@mui/material": "^5.10.17",
    "@mui/styled-engine": "npm:@mui/styled-engine-sc@latest",
    "@mui/styled-engine-sc": "^5.10.16",
    "@mui/styles": "^5.10.16",
    "@mui/system": "^5.10.17",
    "@mui/x-data-grid": "^5.17.16",
    "@mui/x-data-grid-pro": "^5.17.16",
    "@mui/x-data-grid-premium": "^5.17.16",
    "@mui/x-date-pickers-pro": "^5.0.9",
```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.0.1
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124 ***TESTED***
    Edge: 108.0.1462.54
    Firefox: 108.0
    Safari: 16.1


```
</details>

### Order ID 💳 (optional)

56440

**Comment by alexfauquette** [comment]
Hi, I do not manage to reproduce the bug. Here is a codesandobox with the toolbar you provided https://codesandbox.io/s/blazing-field-02vr0h?file=/demo.tsx


From the `(reading 'Workbook')` of the error message, it might be the following function that returns `undefined` instead of the `exceljs` default export.

const getExcelJs = async () => {
  const { default: excelJsDefault } = await import('exceljs');
  return excelJsDefault;
};

We already had kind of similar issue that was affecting users with Vite and Remix #5035

Could provide more information about your environment, and the exceljs verison you're using

**Comment by Richard87** [comment]
Hi! Thanks for responding so fast!

I'm using exceljs 4.3.0 and Parcel 2.8.0 to bundle the application

**Comment by Richard87** [comment]
I downloaded your demo and ran it with Parcel, and i got the exact same error as in our main project.

```shell
git clone https://github.com/Richard87/d2ebun
cd d2ebun
npm install
 ./node_modules/.bin/parcel public/index.html
```

![Skjermbilde 2022-12-21 kl  14 35 41](https://user-images.githubusercontent.com/5749715/208917840-b6dc3b5d-0e0b-4d61-a447-b44d6c012c05.png)

**Comment by alexfauquette** [comment]
Thanks for the reproduction repository, it saved a lot of time :)

I confirm it's an error due to the use of parcel:

Here is the result of `await import('exceljs')` with our default stack.

![image](https://user-images.githubusercontent.com/45398769/208927730-70e59ec9-2df2-438e-8523-9f668b3b1ff2.png)

Here is the same but wiht parcel

![image](https://user-images.githubusercontent.com/45398769/208928008-68d52f75-7e51-41e1-b0e2-73d0da9bb414.png)


As you can see the default is not present with parcel.

I'm opening a PR to do the following, which should quick fix your problem.
```js
const exceljsModule = await import('exceljs')
return exceljsModule.default ?? exceljsModule
```

The closest problem I saw is this one. Since you have a nice reproduction exemple, you could open an issue in Parcel repository. The closest issue I found is this one:
https://github.com/parcel-bundler/parcel/issues/112#issuecomment-1056869249

**Comment by Richard87** [comment]
Wow, thanks for the quick fix! I'll create a issue over at Parcel as well! :)
