### ISSUE TITLE
[fields] Deleting all section does not delete the value

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#7502]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Go to https://next.mui.com/x/react-date-pickers/date-range-picker/
2. click to open the range calendar and select a range
3. move focus to the start date input
4. Delete months, delete days and delete year
5. press tab, and delete the second input (Ctrl+A and Suppr)
6. now you can open the calendar and see the start date is still marked as selected

https://user-images.githubusercontent.com/45398769/212112809-73cc6502-640c-4d02-8901-ac8d228dac7c.mp4

**Comment by flaviendelangle** [comment]
https://user-images.githubusercontent.com/3309670/212114592-3d19bfb0-7b1a-445d-96f5-c6c3a4920ca4.mp4

It's the same on the single item pickers.
And the reason seems simple:

- When doing Ctrl A + Backspace, we don't clear the sections, we directly set the value to equal the empty value
- When doing Backspace on each section, we clear the sections, so we end up with an invalid date which is just ignored by the picker.


The best solution I see is when pressing `Backspace`, we check if the active section is the only non-empty one. If so we reset the value to equal the empty value
This solves the problem in the pickers but it is also more coherent on standalone usage.
