### ISSUE TITLE
[pickers] Open Datepicker could be wired, what about a hook? 

### ISSUE THREAD

**Issue by gscocozzabd** [mui/mui-x#7604]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

An alternative way to open the datepicker programmatically could be a nice addition to prevent wired React behaviors

### Examples 🌈

In this video, you can see my current implementation for multiple datepickers, the problem is that after blurring the input, the input is focused because of how React works under the hood, but this doesn't happen with the default "open picker" button (the calendar at the right), so, if there is a way to trigger that, it would be awesome

https://user-images.githubusercontent.com/86738388/213149973-702dcf65-663a-4fa6-b118-914beced09ec.mp4

[https://codesandbox.io/s/wizardly-bash-p7cvtt?file=/src/DatePicker.tsx](https://codesandbox.io/s/wizardly-bash-p7cvtt?file=/src/DatePicker.tsx)

### Motivation 🔦

Better functionality, the current behavior is problematic

**Comment by flaviendelangle** [comment]
Hi,

Could you describe why you need to render two pickers next to one another and switch between the two ?

**Comment by flaviendelangle** [comment]
We are providing range components (`DesktopDateRangePicker`) for example on our pro package, which should handle correctly the dual picker scenario.

I hope you will understand that we won't spend time trying to create a workaround.

___

Playing with your demo, I noticed that you totally changed the way to open a picker (on click instead of with an end adornment).
That's something we could support out of the box at some point :+1:
