### ISSUE TITLE
[pickers] Static picker versions call `onClose`, but it's not documented

### ISSUE THREAD

**Issue by joshkautz** [mui/mui-x#7895]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/api/date-pickers/static-date-range-picker/

### Kind of issue

Missing information

### Issue description

The `onClose` prop is a real prop that I use for `StaticDateRangePicker`, but there is no mention of it in the documentation for the `StaticDateRangePicker` API. It exists for both `MobileDateRangePicker` and `DesktopDateRangePicker`, so perhaps there is a reason for its omission; or perhaps it was just simply an oversight. Happy to create a PR to help if needed.

**Comment by LukasTy** [comment]
Hello @joshkautz 
That is a really good observation.
We indeed exclude this callback from static picker version as it sort of does not make sense at first sight, because there is nothing you are closing when using it.

Looking at it, a more correct approach would seem to correctly not even call this callback in case of a static picker. 🤔 
Do you have a concrete (or simplified) use case for it that you could share so that we could better decide on the most proper solution?

**Comment by joshkautz** [comment]
Just to follow up on this, I did replace my usage of onAccept and onClose; I now override with Date Picker ActionBar component using the Date Picker slots. Hopefully my terminology so somewhat accurate. I agree with you that the onAccept and onClose props shouldn't be accessible with the Static Date Range Picker component.

I'm sure your team is all over it and has it under control, but I'm happy to share more or help out if needed. Thanks!

**Comment by LukasTy** [comment]
> Just to follow up on this, I did replace my usage of onAccept and onClose; I now override with Date Picker ActionBar component using the Date Picker slots.

Thank you for following up on this! 👌 I'm glad to hear that you were able to solve your case using a documented and typed API. 👍 
We are a bit tied up at the moment with more pressing matters, but we'll discuss the best course of action on this topic. 😉
