### ISSUE TITLE
Pinning all Columns causes columns to miss align with table data.

### ISSUE THREAD

**Issue by Joshua-Kay** [mui/mui-x#7997]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Pin all the columns to either left or right
2. Resize and expand one or some of the columns
3. Use the scroll bar.

### Current behavior 😯

The columns are static and the headers can be aligned to a different column.

### Expected behavior 🤔

The headers are prevented from being aligned to a different column.

### Context 🔦

Resizing columns to fit fields with long values can be an issue if all the columns are pinned.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

50070

**Comment by cherniavskii** [comment]
Hi @Joshua-Kay 
I can reproduce it with this demo: https://codesandbox.io/s/cocky-fermi-dedg7g

We also have this warning in the [Column pinning docs](https://mui.com/x/react-data-grid/column-pinning/): 
<img width="831" alt="Screenshot 2023-02-21 at 13 18 37" src="https://user-images.githubusercontent.com/13808724/220343252-f4b1aee5-ab11-473b-97b9-c4fd47c4a0e6.png">

Do you have a real-world use case where this issue is causing a problem? Would appreciate a codesandbox demonstrating the problem!

**Comment by cherniavskii** [comment]
Also, I found such an issue reported previously in https://github.com/mui/mui-x/issues/4150
Let's track it there - feel free to upvote it and provide any additional details about your use case 🙂

Closing this issue as a duplicate.
