### ISSUE TITLE
[pickers] `onChange` need to be called when cleaning a single section

### ISSUE THREAD

**Issue by sebastian-ludwig** [mui/mui-x#8033]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/happy-bhabha-xb64l0
(@mui/x-date-pickers@6.0.0-beta.5)

Steps:
1. Enter a valid date
2. Delete one part of the date with the keyboard (for example the months, so that "MM" will appear)
3. No update and no error is triggered (only after all parts are deleted)
4. Value is still the entered one from step 1

**Comment by flaviendelangle** [comment]
Hey

That's the expected behavior, we are only firing `onChange` when we have a valid value or when the value is truly empty.
What is your use case for listening to those intermediary steps ?
What would you expect to get as a value ? An invalid date object ?

**Comment by sebastian-ludwig** [comment]
Hey, thanks for your response.

- From UX-Perspective I would like to see the internal-date-value and the displayed-value always in sync. When it's valid --> date, if not valid or empty --> null.  Because if the User has invalidated the date by purpose, there is still an "old" valid date in the background, that could cause errors.
- From Error-Perspective I would like to see the `onError` fired in this case indeed. If there is valid date and it turns into an invalid one, I want to know this. Maybe there is a property `errorStrategy` for more fine grained handling:
  - `always` - fire `onError` when switching from valid to invalid value
  - `onBlur` - fire `onError` when leaving the field in an invalid state, that has been valid before entering

**Comment by flaviendelangle** [comment]
@LukasTy that's an interesting topic

**Comment by LukasTy** [comment]
@flaviendelangle I've looked into Teleric and Spectrum and they both seem to follow the suggested practice of emitting an `onChange` event on every input change.
It does make sense, because it would be more in line with v5 approach, and lets take a hypothetical scenario:
- user inputs data in a form having a date field
- changes one of the date field section values to be invalid
- user submits the form
- the expected outcome would probably be to get either `null` (that's what both mentioned libraries do) or an `Invalid date`, but instead the previous valid value would be submitted

This case is of course valid given that there is no additional external validation reacting to the fact, that `onError` has thrown an error. Correctly reacting to it and disallowing the form to be submitted could be one of the solutions.
We again get back to the original issue of how often and with what kind of data we should be emitting the changes in the components.

**Comment by flaviendelangle** [comment]
> There's also an onAccept callback maybe that's where only valid values should be sent?

This callback only exists on the pickers, we could add it to the field components if needed.
I personnally, would prefer to add information to the 2nd argument of the `onChange` callback to let people ignore some calls if they want. Because not everybody agrees on what `accept` means.
