### ISSUE TITLE
[pickers] Add support for Hebrew

### ISSUE THREAD

**Issue by itayperry** [mui/mui-x#8217]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi there,
I do not wish to waste your time but I'm using the latest version of "@mui/x-date-pickers" and I've noticed there's no Hebrew language support.

### Motivation 🔦

User-Experience for Hebrew-speaking users 🎆

**Comment by LukasTy** [comment]
Hello @itayperry 
Thank you for being interested in localizing pickers.
You can look at any of the [PRs created](https://github.com/mui/mui-x/pulls?q=is%3Apr+label%3Al10n+label%3A%22component%3A+pickers%22+is%3Aclosed) adding a new locale, for example [`hu-HU`](https://github.com/mui/mui-x/pull/7776).

In essence, you need to add the new locale file, export it, translate the labels, and test labels with the `view` variable, because if the variable is used in the label directly—it will be in English.
After that is done, run `yarn l10n` to generate other necessary changes.

**Comment by itayperry** [comment]
Do you know when it'll appear in "supported locales"?

![image](https://user-images.githubusercontent.com/37377389/224693156-759954b4-2ac9-4ba5-be4b-56b7d7699d42.png)

**Comment by LukasTy** [comment]
> Do you know when it'll appear in "supported locales"?

When we release a new package version and deploy the updated docs.
Based on our schedule, that would be this Thursday. 😉
