### ISSUE TITLE
[fields] Make the spaces between slashes (`/`) in the format optional

### ISSUE THREAD

**Issue by rikusen0335** [mui/mui-x#8243]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/slash-splitted-with-spaces-2d23e0?file=/src/App.tsx

Steps: No steps

### Current behavior 😯

Slash format will automatically add space between them like `2222 / 02 / 22`

### Expected behavior 🤔

I am expecting writing format `'yyyy/MM/dd'` will be `2222/02/22` and NOT `2222 / 02 / 22`

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.0
  Binaries:
    Node: 18.14.2 - ~/.local/share/rtx/installs/nodejs/18.14.2/bin/node
    Yarn: 1.22.19 - ~/.local/share/rtx/installs/nodejs/18.14.2/bin/yarn
    npm: 9.5.0 - ~/.local/share/rtx/installs/nodejs/18.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64 <- Only used Chrome
    Edge: Not Found
    Firefox: 110.0.1
    Safari: 16.1
npmPackages:
    @mui/types:  7.2.0
    @mui/utils:  5.11.12
    @mui/x-date-pickers: ^6.0.1 => 6.0.1
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

We added the spaces for visual readability when editing inside the field.
Is their a specific problem you are encountering with it, or would you just prefer the visual rendering without the spaces ?

We could add an option to remove those spaces if several people prefer not to have them.

**Comment by rikusen0335** [comment]
> Is their a specific problem you are encountering with it, or would you just prefer the visual rendering without the spaces ?

Yes, well simply I encontered a situation that needs no gap between dates.

> We could add an option to remove those spaces if several people prefer not to have them.

I need this option or just make not format to use spaces if we wouldn't specify.
Only spaces around slash even we are using `format`, seems bit weird

**Comment by YuLingCheng** [comment]
Hello @flaviendelangle I'm also in a case where I would like not to have these spaces, I'm working on a UI that needs to be dense (table view), so adding spaces is not convenient.

While is issue is being upvoted, could you point me to the code that adds these spaces? So I could try to figure out a workaround in the meantime 🙏 
Thanks a lot for your help!

**Comment by rikusen0335** [comment]
I agree. I think we need to specify space gaps explicitly.

**Comment by flaviendelangle** [comment]
> I think we need to specify explicitly if we need space gaps between

The logic of adding them ourselves was as follow:

- It looks better out of the box in our own opinion (totally understand the dense UI argument though)
- Date libraries encourage you to use formats like `LLL` or `PPP` (meta tokens) that contain different formats depending on the locale. Having them by default allow you to keep using those type of format and have the spaces.

**Comment by YuLingCheng** [comment]
Thank you @flaviendelangle for getting back to us on this topic :) 

> It looks better out of the box in our own opinion (totally understand the dense UI argument though)

I would say "look better" is a relative/personal criteria 😄 but more seriously, if it's about aesthetics it should impact the style (css ideally), or the configuration (setting a prop), but not be chore to the logic (changing the value on the fly).

> Date libraries encourage you to use formats like LLL or PPP (meta tokens) that contain different formats depending on the locale. Having them by default allow you to keep using those type of format and have the spaces.
 

I find these flexible formats “LLL/PPP” quite handy and I use them on my projects. 
But setting this rules of adding spaces before/after a “/" seems quite invasive and hard to discover.
If I specify a format “DD/MM/YYYY” I expect to get that format without the spaces (As I would do if I specify “DD-MM-YYYY”.
This does not seem like a standard behaviour.

If I wanted the “DD / MM / YYYY” format I would specify it in the [localisation provider overrides](https://day.js.org/docs/en/customization/customization), so it’s clear and easy to override. With the [implementation embedded in the code](https://github.com/mui/mui-x/blob/v6.0.3/packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts#L538-L540), there is no way around that choice (which is not very flexible for a component from a library in my opinion).

What do you think about deciding on the format outside of the date picker component? Using the date formatting provider decide on the default formatting seems more logical to me, as it’s one of their purpose.

**Comment by samosad** [comment]
it would be nice to make those spaces optional at least
cc @flaviendelangle

**Comment by flaviendelangle** [comment]
> I would say "look better" is a relative/personal criteria smile 

For sure !

>  if it's about aesthetics it should impact the style (css ideally)

If it was possible to specify the `letter-spacing` depending on the character, we would do this customization with pure CSS of  course.
And by the way, for totally independent reasons, we might migrate from one HTML input to one HTML input per section in a future version, or support both. In which case, the field with one HTML input per section would have this behavior in pure CSS.

> If I specify a format “DD/MM/YYYY” I expect to get that format without the spaces

I want to make clear that what is rendered inside the input is not the format but a placeholder of the edited value.
We render `YYYY` for the year (or `AAAA` in french) even if the format token for the year is `yyyyy` (date-fns) or `yyyy`.
For the day, we render `DD` even if you use the token `do`.

We think that most end users are not familial with the format tokens themselves and that it's better to have localized placeholders instead.
If for some reason your application would benefic from rendering the actual tokens, you can take a look at [this doc section](https://mui.com/x/react-date-pickers/adapters-locale/#custom-field-placeholder) to customize the formats. We would need to add an argument with the token so that you can customize based on it. Let us know if that's something you need.

Going back to the spacing between the dashes.
I totally understand the need for a compact representation of the date, in which case the spaces can feel like lost space.

I am not a huge fan of saying to people that the should put the space themselves if they want to.
- If they put it using the `format` prop of the component, then they can't use the meta-token (`LLL` / `PPP`) which would lead to a bad experience for multi-language applications.
- If they override the meta token behavior in the date library locale, then they will have this space everywhere, not only on the field. I feel like the space makes the input easier to read but I would not like to have those spaces when logging some dates for example. Unless you have a way to do this override locally (and for each date library).

But I do agree that we should allow people to easily remove them.

I'd propose to introduce a `formatDensity?: 'dense' | 'regular'` prop (strings to be determined) and to only add the spaces for `regular`.
This has the benefit to easily scale if we want to do other customization (add space next to `-` for example).
I think this prop should be `regular` by default, at least on v6 because changing the input value in a minor can be considered a breaking change. As for the default value in the next major version, I like the space but I don't have a strong opinion to be honest.

**Comment by LukasTy** [comment]
> I am not a huge fan of saying to people that the should put the space themselves if they want to.

Wouldn't avoiding spaces help with reducing the things that users need to account for when testing and parsing dates?
Some adapters might not like that the format has spaces and could require the user to pass a format as well.
Also testing. Imagine someone having a huge set of tests for pickers and after the v6 upgrade, they all need to be updated to account for an opinionated change in how value is saved. 🙈

**Comment by flaviendelangle** [comment]
> Wouldn't avoiding spaces help with reducing the things that users need to account for when testing and parsing dates?

In any case, for me we can't just remove them in v6, it's a breaking change.

**Comment by flaviendelangle** [comment]
> Could this apply to both placeholder and value? (for consistency)

Sure, the generation logic is the same for both, any fix to one should apply to the other :+1:

**Comment by YuLingCheng** [comment]
Thank you so much, this would be awesome!

**Comment by YuLingCheng** [comment]
Thanks @flaviendelangle for handling this so quickly 🚀
