### ISSUE TITLE
[date pickers] Document events and component input cycle.

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#8310]
### Summary

We need to document the input life cycle to set a clear expectations of behavior and help users understand when to proper use the callbacks to achieve custom scenarios.

We've already documented the [onChange](https://mui.com/x/react-date-pickers/fields/#when-is-onchange-called), but we need to document others like onAccept and onClose, and how the callbacks fit together in the input cycle.

Related:
https://github.com/mui/mui-x/issues/4438#issuecomment-1098816661
https://github.com/mui/mui-x/issues/8129
#8375

### Topics to document:

- The `onChange`  behavior of the field
- The `onChange` behavior of the views
- The `onAccept` behavior
- The opening (and `onOpen`) behavior (open on focus vs open on click on the adornment)
- The closing (and `onClose` ) behavior (close when pressing Escape etc...)

**Comment by sagrawal-code** [comment]
I was just creating an issue on this topic, as I was struggling with understanding the difference between `onChange` and `onAccept` in the context of date range pickers, specially when using shortcuts. 

With an `onAccept` and no `onChange`, when I select the start date and end date for a range (not clicking on a shortcut), the onAccept fires nicely with the new values using which I can update the state.

However, when I click on a shortcut, the `onAccept` doesn't fire and on a controlled picker, without an `onChange`, the range doesn't get updated as well. So what's the correct way to handle this scenario: the user clicks a shortcut, correct range gets selected, `onAccept` fires and the picker closes.

**Comment by joserodolfofreitas** [comment]
Hi @sagrawal-code,

Shortcuts simply select a range with one click, and `onAccept` is called only when the modal closes. 
You can add the "accept" action to your calendar so users can confirm their selection, like in the following example: https://codesandbox.io/s/date-range-and-shortcuts-with-accept-button-2sbh50

Now, I'm curious about your expectation of the behavior of the shortcuts.
Would it be useful (or more intuitive) in your use case that clicking on shortcuts also accepts and closes the calendar modal?

**Comment by sagrawal-code** [comment]
> Would it be useful (or more intuitive) in your use case that clicking on shortcuts also accepts and closes the calendar modal?

I feel that the behavior when a user manually selects a date range differs from when a shortcut is clicked. In the example you provided, if a user selects a date range manually, the selection is "accepted" and the modal closes. However, this doesn't happen when a range is selected using a shortcut.

Is there a way to make the behavior of manual selection consistent with shortcut selection? In other words, can we ensure that the selection is not accepted unless the user clicks the "OK" button?

Alternatively, I am open to your suggestion as well, where clicking on a shortcut accepts the date range and closes the modal.

**Comment by joserodolfofreitas** [comment]
> Is there a way to make the behavior of manual selection consistent with shortcut selection? In other words, can we ensure that the selection is not accepted unless the user clicks the "OK" button?

In this case, @sagrawal-code, you can use the `closeOnSelect` prop to get the Manual selection consistent with shortcuts.

`<DateRangePicker closeOnSelect={false} />`

**Comment by sagrawal-code** [comment]
> In this case, @sagrawal-code, you can use the closeOnSelect prop to get the Manual selection consistent with shortcuts.

Thank you, the solution works well overall. I do have one remaining concern. When using a controlled date range picker and choosing not to update the external state in `onChange`, but only in `onAccept`, the shortcuts seem to not function as intended (though I can somewhat understand why). In this situation, I must manage both local and external states. This issue is demonstrated in the example provided here: https://codesandbox.io/s/date-range-and-shortcuts-with-accept-button-forked-kmyvmt?file=/demo.tsx. Is there a more efficient approach to handle this?

I apologize if I am missing an obvious solution.

**Comment by alexfauquette** [comment]
@joserodolfofreitas I'm adding https://github.com/mui/mui-x/issues/8375 to the related issue

TLTR; The issue is about `onAccept` is called only when using view, not the keyboard. I'm not sure keyboard have an obvious way to accept a new value. Maybe the solution would be to add examples depending on if users want to detect blur event, or debounce the `onChange`
