### ISSUE TITLE
[pickers] `shouldDisableClock` and `componentsProps` are recommended in V6 migration guide but deprecated in code?

### ISSUE THREAD

**Issue by mogrady88** [mui/mui-x#8346]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

Both `shouldDisableClock` and `componentsProps` are deprecated in code but are recommended code changes in the V6 migration guide.

[shouldDisableClock](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/hooks/validation/models.ts)

[componentsProps](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/DatePicker/DatePicker.types.ts)

### Expected behavior 🤔

They shouldn't be deprecated or we shouldn't be asked to migrate to those new props

### Context 🔦

Currently migrating to V6 `x-date-pickers` and `x-date-pickers-pro` and I'm a little confused on which direction to take

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by mogrady88** [comment]
`DateRangePicker` also has the same issue. Weirdly enough, I was able to use `slotsProps` for `Date/Time Pickers` but I had to stick with the deprecated `componentsProps` on `DateRangePicker` as `slotsProps` wasnt working

**Comment by LukasTy** [comment]
Thank you for reporting this issue! 👍 
The `shouldDisableClock` and `shouldDisableTime` conundrum is our bad. 🤦 
The `shouldDisableTime` is a new prop added in v6 and the old `shouldDisableClock` with limited API is now deprecated.
We'll adjust the migration guide and the codemod accordingly. 👍 

___

As for the `componentsProps` vs `slotProps`—both are equally fine in v6. We plan to drop `componentsProps` in v7 only. We have a section about it [in the migration guide](https://mui.com/x/migration/migration-pickers-v5/#rename-components-to-slots-optional), the codemod to rename the usage is not included in `preset-safe`, because it's not mandatory in v6. If you wish to no longer see the deprecated usage in IDE—consider running the provided codemod. 👍 

___


> Weirdly enough, I was able to use `slotsProps` for `Date/Time Pickers` but I had to stick with the deprecated `componentsProps` on `DateRangePicker` as `slotsProps` wasnt working

Could you please provide more information as to what wasn't working with `slotProps` specifically? 🤔 
Ideally, they should just be 1:1 in support, but just a bit different API casing/naming.

**Comment by flaviendelangle** [comment]
For the `slotsProps` I think it's just a spelling issue: `slotProps` not `slotsProps`

**Comment by mogrady88** [comment]
I can open up another issue for that `sx` if it makes more sense. Thank you for your help!

**Comment by flaviendelangle** [comment]
Another issue would be great :pray:

**Comment by LukasTy** [comment]
> It seems like Im forced to add the `!important` tag to the `sx` on my customized `fieldSeparator`. Am I using this correctly? I wasnt expecting the specificity issue but the styling doesnt work otherwise

Consider targeting `fieldRoot` instead and setting it's `spacing` as the underlying `Stack` component is responsible for maintaining the spacing and it has a very peculiar way of applying styles.

This should do the trick:
```tsx
<DateRangePicker
  slotProps={{
    fieldRoot: { spacing: 1 },
    fieldSeparator: { children: 'to' },
  }}
  onChange={newValue => { setValue(newValue); }}
  value={value}
/>
```

**Comment by mogrady88** [comment]
Ok awesome. This gives me something to go on. Ill play around with the slotProps a bit more. Thank you both!
