### ISSUE TITLE
onSelectionModelChange not trigger any event

### ISSUE THREAD

**Issue by aizaz-react** [mui/mui-x#8374]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I need controlled checkboxes mui/x-data-grid and follow the documentation properly but 'onSelectionModelChange' did not give me any selected ids as like the documentation.

here is my code:

```
<DataGrid
   columns={columns}
   rows={rows}
   loading={loading}
   checkboxSelection
   onRowSelectionModelChange={(ids) => console.log(ids)}
   autoHeight
/>
```

but unable to get any thing from this function.

I also tried it on codesandbox official example it works fine in codesandbox nut not in my local machine 

my versions are:

```"@mui/lab": "^5.0.0-alpha.114",
    "@mui/material": "^5.11.3",
    "@mui/styles": "^5.11.2",
    "@mui/system": "^5.11.14",
    "@mui/x-data-grid": "6.0.3"`

### Current behavior 😯

_No response_

### Expected behavior 🤔

_No response_

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>


### Order ID or Support key 💳 (optional)

_No response_

**Comment by MBilalShafi** [comment]
Hey @aizaz-react, in order for us to better understand the use-case and suggest you a solution, we need you to reproduce it in some codesandbox or other live example.

You can use this [codesandbox](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) as a staring point.

**Comment by aizaz-react** [comment]
@MBilalShafi the problem is it works perfectly in codesandbox but not on my local machine with the same code.

**Comment by NVGHuy** [comment]
Have you fixed it yet? Please help me as I am having the same problem as you

**Comment by laurentchretienmarquet-cmyk** [comment]
Same question in 2026 :-).. Many warnings during the installation via npm i -- force x-tatagrid .. Happy to see eventual following. Cheers.

**Comment by laurentchretienmarquet-cmyk** [comment]
OnRowSelectionModelChange has replaced OnSelectionModelChange  but the ids given to the callback is desperately empty (ids.id equals {}). Thus unusable. 
OnRowClick event gives a ids.id ok, but is not triggered for the checkbox column. ;:-

(.Il looks like there is no more working activity on the project). So bad. A lot had been achieved.

**Comment by laurentchretienmarquet-cmyk** [comment]
The fact that OnRowClick gives a right ids.id is a real value. It il a little "heavy", but possible thanks  to it to elaborate a way to program a "good click" and even to create a new alternate checkbox column that works. It is indeed a pity but it is faisable. Perhaps The price to pay to have a real good datagrid really free.. At least while waiting for the bug to be debugged (onRowSelectionMoel giving a non empty ids.id).

**Comment by laurentchretienmarquet-cmyk** [comment]
//most div tags are or may be (!.. sometimes.. ) automaricaly suppressed. due to an anomaly of the present editor, that I don't master. Sorry.. In this case you have to put them back in the return section (begin one, end is still in place, before and after the "Selected Person.."). With that it will work ok.
The most important part is clearly how to find the index of the selected element using the map.)

import * as React from 'react'
import {DataGrid} from "@mui/x-data-grid"

const data = [
  { id: "Mohammad", surname: "Faisal", birthYear: 1995 },
  { id: "Nayeem Raihan ", surname: "Shuvo", birthYear: 1994 },
  { id: "Mohammad2", surname: "Faisal", birthYear: 1995 },
  { id: "Nayeem Raihan2 ", surname: "Shuvo", birthYear: 1994 },
  { id: "Mohammad3", surname: "Faisal", birthYear: 1995 },
  { id: "Nayeem Raihan3 ", surname: "Shuvo", birthYear: 1994 },
];
// Thanks to Mohammad end Nasseem :-)

const columns = [
  { title: "id", field: "id" },
  { title: "Surname", field: "surname" },
  { title: "Birth Year", field: "birthYear", type: "numeric" },
];

function BasicTable() {
  const [id, setId] = React.useState("")
  let index=-1, i=-1
  if (id !== ""){ data.map(e=>{i++;if(e.id==id)index=i}) }
  return ( <div>
    
{id !==""&&<div>Selected person : {data[index].id}{data[index].surname}</div>}
      
      <DataGrid 
      rows={data} columns={columns} 
      onRowClick={(ids) => {setId(ids.id) }}
      pageSize={5} />
 
    
    </div>)
} 

export default BasicTable

**Comment by laurentchretienmarquet-cmyk** [comment]
the above example can be seen here : https://codesandbox.io/p/sandbox/trusting-night-qzz8dm?file=%2Fsrc%2FMV4.jsx%3A3%2C1
the exact code for the datagrid is in the MV4.jsx file. Works ok.
