### ISSUE TITLE
[docs] Pickers migration uses deprecated `componentsSlots`

### ISSUE THREAD

**Issue by boldurean** [mui/mui-x#8403]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/migration/migration-pickers-v5/#✅-input

### Kind of issue

Unclear explanations

### Issue description

```
 <DatePicker
-  InputProps={{ color: 'primary' }}
+  componentsProps={{ textField: { InputProps: { color: 'primary' } } }}
 />

```

### Context 🔦

Migration guide is saying that the inputProps has to be replaced by componentsProps but the actual component API showing that this prop is Deprecated and has to be replaced by the slotProps and ts also highlights that the prop is deprecated :|

**Comment by LukasTy** [comment]
Thank you for opening this issue! 👍 
There is already an open PR #8341 trying to solve it, but we are still under discussion on the best approach.

In regards to the question itself: the plan is to keep `componentsProps` deprecated, but available throughout v6 and only remove it in v7.
It was our initial decision to deprecate `componentsProps` while introducing the new `slotProps`.
We have [a codemod](https://mui.com/x/migration/migration-pickers-v5/#rename-components-to-slots-optional) ready to migrate to the new slots API, but we decided not to include this transformation by default, because it is not mandatory and not a breaking one.
