### ISSUE TITLE
[DataGrid] Column header tooltip does not render when column filter is applied

### ISSUE THREAD

**Issue by rohitnatesh** [mui/mui-x#8406]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/datagrid-column-header-tooltip-not-rendering-4n99kg?file=/src/App.tsx

Steps:
1.  Column header must occupy almost the entire available column width, but it should not be truncated.
2. Column filters must be enabled.
3. Apply filter on the column, and this will add column filter button on the header.
4. Since the column header was initially occupying the entire column width, adding the filter column button truncates the column header text with ellipsis.
5. Try hovering over the title.

### Current behavior 😯

The tooltip for the column header does not display. 
![image](https://user-images.githubusercontent.com/30684703/227966905-7e9b2fa2-ecb5-4487-993d-cee49072ae93.png)

### Expected behavior 🤔

Tooltip for the column header should display.

### Context 🔦

- I did some digging into the codebase to understand the logic used to display the tooltip.
- A `isOverflown` DOM utility was responsible to find if the DOM content is overflowing,
![image](https://user-images.githubusercontent.com/30684703/227969090-7620c079-48e9-4a22-9e1f-98c033e9fac1.png)
[isOverflown utility link](https://github.com/mui/mui-x/blob/67cffb1cf5fec20361faffde92020d208849d901/packages/grid/x-data-grid/src/utils/domUtils.ts#L4-L6)
- Upon manually checking the `scrollWidth` and `clientWidth` values on the overflowing header, I found the isOverflown condition to be true.
- This led me to believe that the `useEffect` in `GridColumnHeaderTitle` component responsible to check the overflow is not getting triggered when a column filter button is added/removed.
![image](https://user-images.githubusercontent.com/30684703/227969982-2faf5855-5b93-4533-b5ee-66ea1327c0b9.png)
[GridColumnHeaderTitle useEffect link](https://github.com/mui/mui-x/blob/67cffb1cf5fec20361faffde92020d208849d901/packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx#L65-L74)

I was exploring the following the solution,
https://github.com/mui/mui-x/compare/master...rohitnatesh:mui-x:DataGrid-Track-column-filter-visibility-in-header
I can raise a PR with the same, if the changes are okay.

With the changes,
![image](https://user-images.githubusercontent.com/30684703/227987647-e037dc52-d224-4f5c-a331-50101f346f7f.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

- MUI X DataGrid version: `6.0.2`
- Browser: Chrome
</details>

**Comment by MBilalShafi** [comment]
Thanks @rohitnatesh for reporting the issue, I think you are right, the reason why the tooltip doesn't automatically show on hover when the content overflows is the effect not running whenever a new icon is added to the header.

But the problem is a little bit deeper, it's not only the filter button but also other reasons like the sort button and kebab button which may reduce the width and add ellipses to the text. We don't store a hover state somewhere to achieve this rather we handle this with the CSS:
https://github.com/mui/mui-x/blob/df56fd0b639377d7cfc49efa747caf2371160251/packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx#L28-L30

Here's an example of ellipses being shown in different interactions:
![overflow-grid-issue](https://user-images.githubusercontent.com/12609561/228141386-600ee333-7e3c-4034-a74a-69eb55c59102.gif)

The ideal solution would be to somehow recalculate `isOverflown` on hover so that if the icons showed on hover hid some portion of text, it's accommodated and the tooltip is shown. Probably listening to some mouse events and re-computing isOverflown on let's say `mouseEnter` and `mouseLeave` could be a possible solution 🤔 
https://github.com/mui/mui-x/blob/df56fd0b639377d7cfc49efa747caf2371160251/packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx#L130-L133

CC @cherniavskii 

**A small workaround meanwhile:** You can pass a `description` property to `ColDef` to show a tooltip for a specific column.

```tsx
const columns = [
  {
    field: 'name',
    headerName: 'Some really long header name',
    description: 'Some really long text explaining about the column',
  }
);
```

**Comment by cherniavskii** [comment]
This looks like a good example for https://github.com/mui/mui-x/issues/8373
I don't think we need an effect here, we can compute everything we need during render:

```diff
diff --git a/packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx b/pack
ages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx
index 3f87a4000..1ff0666b9 100644
--- a/packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx
+++ b/packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx
@@ -57,27 +57,17 @@ export interface GridColumnHeaderTitleProps {
 
 // No React.memo here as if we display the sort icon, we need to recalculate the isOver
 function GridColumnHeaderTitle(props: GridColumnHeaderTitleProps) {
-  const { label, description, columnWidth } = props;
+  const { label, description } = props;
   const rootProps = useGridRootProps();
   const titleRef = React.useRef<HTMLDivElement>(null);
-  const [tooltip, setTooltip] = React.useState('');
 
-  React.useEffect(() => {
-    if (!description && titleRef && titleRef.current) {
-      const isOver = isOverflown(titleRef.current);
-      if (isOver) {
-        setTooltip(label);
-      } else {
-        setTooltip('');
-      }
-    }
-  }, [titleRef, columnWidth, description, label]);
+  let tooltip = description;
+  if (!tooltip && titleRef && titleRef.current && isOverflown(titleRef.current)) {
+    tooltip = label || '';
+  }
 
   return (
-    <rootProps.slots.baseTooltip
-      title={description || tooltip}
-      {...rootProps.slotProps?.baseTooltip}
-    >
+    <rootProps.slots.baseTooltip title={tooltip} {...rootProps.slotProps?.baseTooltip}>
       <ColumnHeaderInnerTitle ref={titleRef}>{label}</ColumnHeaderInnerTitle>
     </rootProps.slots.baseTooltip>
   );
```

What do you think?

**Comment by cherniavskii** [comment]
Hi @rohitnatesh,
Would you like to submit a PR? :)
