### ISSUE TITLE
 Version 5 to 6 behaviours input Field issue 

### ISSUE THREAD

**Issue by Aswinma85** [mui/mui-x#8430]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-date-pickers/date-range-calendar/

### Kind of issue

Missing information

### Issue description

Material UI X community,

We would like to bring your attention to an issue we have encountered in Version 6.0.3 MultiDateRangeField. When we set the current date "29-03-2023" in both the startDate and endDate, and then we change the endDate to "15-03-2023", the behavior of the field starts with 01 on Version 6, whereas in Version 5, it starts with 1 when we type the 15th date on the endDate.

We kindly request your assistance in fixing this issue to match the behavior of Version 5. We have included links to both Version 5 and Version 6 for your reference.If you understand the issue please reply us on aswinma@xminds.com

Version 5 : https://codesandbox.io/s/wandering-wood-te7e49?file=/demo.tsx:48-53
Video : https://drive.google.com/file/d/1HL63MzapIP2C2YwV4NYoQUpqG4AvUkdH/view?usp=share_link

Version 6 : https://codesandbox.io/s/pensive-sound-ue12d6?file=/demo.js:490-1139
Video : https://drive.google.com/file/d/10vShdDWOB83Rj3hE1835Bkp-PWr-Qkqy/view?usp=share_link

Sincerely
Aswin

**Comment by alexfauquette** [comment]
I do not think it is feasible to go back to the v5 behavior, and not sure it's a good behavior.

In v5 the modification steps, were the following:
```
- 03/19/2023
- 03/12/023 <- The intermediate state
- 03/15/2023
```

The intermediate state is ugly, but because users had to write `01` and was not able to write only `1` you knew the date was incomplete.

Now, pressing <kbd>1</kbd> set directly the value to `01` and there is no way to know if the user wants to stop here or if they will press <kbd>5</kbd> to write `15`.

If I understand correctly, what you're trying to enforce user to select a range containing today with the following behavior:
- If start date after today, set it to today
- If end date before today, set it to today
- If end date before today, set it to today

This kind of behavior is strange. Usualy you do not take control over what the user is writing. You have two options to enforce such a behavior:

1. You display an error when the date is incorrect (for example end date before start date automatically display error state)
2. You debounce the input, letting for example 500ms to press the second digit

And of course you can mix the two behavior



---
small note: GitHub is now supporting `webm` video. you can directly add them to the issue without having to use G-drive 😉

**Comment by Aswinma85** [comment]
Thank you for your support

**Comment by alexfauquette** [comment]
I'm closing the issue since it's not something that seems to lead to a PR
