### ISSUE TITLE
DataGrid width transition and flex columns not working 

### ISSUE THREAD

**Issue by Kai-W** [mui/mui-x#8511]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/datagrid-transition-x70g9x?file=/Demo.tsx

Steps:
1. Render a DataGrid with flex columns
2. Add a width transition to the DataGrid 
3. Trigger the transition

### Current behavior 😯

The Datagrid gets transitioned as expected. But the flex columns inside the DataGrid  only get updated at the end of the transition.

### Expected behavior 🤔

Flex Columns should resize during the transition

### Context 🔦

I used the Persistent Drawer example as a base of my application. So The Menu collapse is triggering a transition of the main content. 
DataGrids in the main content are not transitioning as i would expect

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Chrome: Version 111.0.5563.147
 mui@latest
```
</details>

**Comment by Kai-W** [comment]
Extending the row could help to hide the artifacts on an extending container.
Is there no possibility to use the browser build in flexbox to handle the column width?

**Comment by lindapaiste** [comment]
I'm having this problem too.  Usually I can find a way to force the DataGrid to do what I want through some combination of component overrides and event handling but I cannot figure out any way to circumvent this!  There needs to be some prop that can disable the debouncing, like `disableDebounceResize` or something.

I played around with the grid events and I can see that the `resize` event gets called like 10 times with varying dimensions before the `debouncedResize` gets called with the final dimensions.  I can attach a listener to the `resize` event, but what would it do?  Is there a function that can imperatively force a resize?  `apiRef.current.resize()` would be an infinite loop, and [`setContainerDimensions`](https://github.com/mui/mui-x/blob/425856f9d10b281ad664ecfb025cb1a8d8b4a839/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx#L263-L272) is not exposed externally.

> Is there no possibility to use the browser build in flexbox to handle the column width?

I started playing around with this.  I could do it for the rows, but not for the headers.  There's no property on `slots` to replace/wrap the `GridGenericColumnHeaderItem` [which sets the style](https://github.com/mui/mui-x/blob/425856f9d10b281ad664ecfb025cb1a8d8b4a839/packages/grid/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx#L106-L111) like I can for the `cell`.

You can set the `flex` property on the style but naturally that would not work with draggable column resizing. 

If the goal is just to have a smooth transition, then a better way to override the width would be to set the `width` of the cell to a percentage value based on the `computedWidth` of the column.  This may or not not work with draggable resizing (on some of my tables it works and on others dragging the resizer causes the column to disappear due to `NaN` width).  But I come to the same brick wall where it's not simple to overwrite the `style` property on the `.MuiDataGrid-columnHeader` elements so I cannot put the same treatment on the header row.

Pasting my half-baked code here in case it helps:

```
import {
    DataGridPro,
    DataGridProProps,
    GridCell,
    GridCellProps,
    gridClasses
} from '@mui/x-data-grid-pro';
import React from 'react';

const OverrideWidthCell = (props: GridCellProps) => {

    const { field, height  } = props;

    const apiRef = useGridApiContext();

    const column = apiRef.current.getColumn(field);

    const containerWidth = apiRef.current.getRootDimensions().viewportInnerSize.width;

    return (
        <GridCell
            {...props}
            // Overwrite the assigned width and height
            style={{
                minHeight: height,
                maxHeight: height,
                width: `${100 * column.computedWidth / containerWidth}%`,
                minWidth: column.minWidth,
                maxWidth: isFinite(column.maxWidth) ? column.maxWidth : 'auto',
            }}
        />
    );
}

export default function MyDataGrid() {
    return (
        <DataGridPro
            // ...other props
            slots={{
                cell: OverrideWidthCell,
            }}
            sx={{
                // Needed for custom column width
                [`& .${gridClasses.virtualScrollerRenderZone}, & .${gridClasses.row}`]: {
                    width: 1
                }
            }}
        />
    );
}
```

**Comment by arsicdejan** [comment]
Hey @m4theushw, I agree with @lindapaiste that there needs to be some prop that can disable the debouncing. Or is there any other way to handle this issue?

**Comment by romgrk** [comment]
v7 was released last week. If you need assistance open a new issue and be sure to fill the template.
