### ISSUE TITLE
[pickers] minDate and maxDate in DatePicker Component are expecting the wrong type with AdapterDateFns

### ISSUE THREAD

**Issue by ermakov95** [mui/mui-x#8528]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Use LocalizationProvider with AdapterDateFns
2. Use DatePicker

### Current behavior 😯

![image](https://user-images.githubusercontent.com/89069249/230342126-a13c709a-3c51-4ea6-aee6-14d94db95401.png)
These parameters expect strings, but do not know how to work with them. The calendar stops at one month and does not allow you to change it.
But if you pass the Date object, then the component works fine.

### Expected behavior 🤔

Process strings correctly or change the typing

### Context 🔦

https://codesandbox.io/s/bold-maria-x022yp?file=/demo.tsx

**Comment by ermakov95** [comment]
@LukasTy added minimal working example

**Comment by LukasTy** [comment]
With the release of v6, [we have dropped](https://mui.com/x/migration/migration-pickers-v5/#update-the-format-of-the-value-prop) the dangerous and potentially buggy option to provide dates in mixed formats or strings.
If you are using `date-fns` - make sure that the dates you are passing to picker components are JS `Date` objects or `null` if empty. `''` (empty strings) are also invalid, because `new Date('')` produces an `Invalid Date`.

Here is [an updated version](https://codesandbox.io/s/date-fns-example-hknp29) of your example.
