### ISSUE TITLE
[pickers] Unable to assign custom TextField with custom props to DatePicker

### ISSUE THREAD

**Issue by marcusjwhelan** [mui/mui-x#8589]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Attempt to assign a custom extended TextField to slots.textField, check props for textField in slotProps still shows TextFieldProps even though a custom component with different props is assigned.
2.
3.

### Current behavior 😯

DatePicker does not pull the props from the assigned slots.textField instead has TextFieldProps hard coded into the types for DatePicker. 

### Expected behavior 🤔

Assigning a custom component to the textField of slots would then perpetuate the types from slots.textField to slotProps.textField. 

### Context 🔦

My TextField takes in readOnly at the BaseTextFieldProps which I extended to do so. In the custom component some styling is done to the TextField when readOnly is set, not the readOnly you all provide. 

Attempting to use my custom TextField like what used to be possible in v5 with `renderInput` is now impossible. 

Need to be able to use a custom input component with custom internal functionality for the textField of the new DatePicker. 

I don't see a way to do this any other way. It is not something I can see being done at the theme level since it needs an attribute and some logic to be done inside the custom component that returns a TextField. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by marcusjwhelan** [comment]
@flaviendelangle When making the example I found that my typings did work as for the export of the new component. I tried wrapping the MyDatePicker again and then you can see the types show the right TextField. However it looks like even when setting the TextField with my component the properties are not passed to the component? Otherwise my TextField would have a dull background https://codesandbox.io/s/date-and-time-pickers-forked-5ixirx?file=/src/App.tsx 

So the question I have is how can I get MyTextField to be used for the input instead of what is provided. Or will I have to do the same work on the DatePicker as the TextField to get the same affect?

**Comment by flaviendelangle** [comment]
Using `slots={{ textField: MyTextField }}` should work 

Which properties would you expect to be passed to your textfield and that are not passed ?
If it's just `readOnly`, I think the issue is that we are passing it to `inputProps.readOnly` instead of `InputProps.readOnly` so the input container is not aware of it (thus the background issue you are experiencing).

Note that the `TextField` from `@mui/material` is not supposed to receive a `readOnly` prop at the root.
You can have a look at [this example](https://codesandbox.io/s/date-and-time-pickers-forked-wjxou8?file=/src/App.tsx), the `readOnly` prop is ignored.
So I would advise you to do the same on your component :+1: , the `textField` of the picker will receive props in the shape of the MUI Material TextField, so if you diverge, you will have to convert your props :+1: 

____

As a quick fix, you could pull the `readOnly` prop from `inputProps` and inject it inside `InputProps`.
That's ugly and we clearly need to fix it on our side, but it will work.

**Comment by marcusjwhelan** [comment]
@flaviendelangle yes, I know how TextField is supposed to work. If you take a look at the `MyTextField` code you will see I added `readOnly` to the root attributes of the component and have the `MyTextField` then add css and `readOnly` to the `inputProps`. So applying the `MyTextField` to the `textField` section doesn't work in the way I expect because it doesn't take the `readOnly` root attribute and apply it to `MyTextField` component. It looks like under the hood it still uses the TextField component. I found that if I apply `MyTextField` to the `field` of `slots` it does work as far as applying the styling I am looking for but then all the input formatting is wrong.

**Comment by flaviendelangle** [comment]
>  I found that if I apply MyTextField to the field of slots it does work as far as applying the styling I am looking for but then all the input formatting is wrong.

If you pass `slots={{ field: MyTextField }}` then you lose all the logic of the field because you basically override the `DateField` component that has smart date editing with your component which just wraps the `TextField`.

____


> It looks like under the hood it still uses the TextField component.

I don't understand this point.
In your codesandbox, you can clearly see that `MyDatePicker` is calling `MyTextField` (you can add a console log in `MyTextField` or add `sx={{ border: "1px solid red" }}` to the `MyTextField` file to see that it does use it).

___

I don't understand what you are trying to accomplish
The `textField` slot receives props from the picker in the shape of the `TextField` component from `@mui/material`.
If you pass a custom `textField` slot, then the component you are passing should be compatible with this kind of props.
The picker will never pass `readOnly` as a root prop to your `MyTextFIeld` because it's not how the the default `TextField` works.

If for some reason you want `MyTextField` to support `props.readOnly`, then it should also support `props.InputProps.readOnly` for when you use it as a slot.
Or you should have a `MyTextFieldForPicker` little wrapper it you really don't want to change your `MyTextField` abstraction.

**Comment by flaviendelangle** [comment]
If this does not answer your question, could you please explain exactly what you want to achieve (which props you want your component to receive, the expected behavior etc...) ?

**Comment by marcusjwhelan** [comment]
@flaviendelangle 

If you take a look at the code sandbox and what is rendered, you will see on the left `MyDatePicker` that has a white background

Then on the right of that input you will see a `MyTextField` that has a shaded background. 

> The textField slot receives props from the picker in the shape of the TextField component from @mui/material.
If you pass a custom textField slot, then the component you are passing should be compatible with this kind of props.
The picker will never pass readOnly as a root prop to your MyTextFIeld because it's not how the the default TextField works.

The functionality I and really anyone who applies their Custom `MyTextField` would be that it takes the same props of their Custom `MyTextFieldProps`. It is a mistake to hard code the type for `DatePicker` to only receive what `Mui` has  determined the props for `TextField` when you have provided me the option to use my own. 

> In your codesandbox, you can clearly see that MyDatePicker is calling MyTextField (you can add a console log in MyTextField or add sx={{ border: "1px solid red" }} to the MyTextField file to see that it does use it).

Yes the console log does work.

However, you will see that the css has not changed on the `DatePicker` to have a shaded background like the `MyTextField` receiving the same `readOnly` at root right next to it on the rendered view in the **SANDBOX.** If you look at the internal code in the **SANDBOX** of `MyTextField` the props are looking for a `readOnly` at root to apply `readOnly` into `InputProps` and also to apply specific css to the `InputProps` to cause the SHADING of the background. Which works and is proven in the **SANDBOX** right next the my Custom DatePicker. If DatePicker applied the props I provided for my `prop` model then it would work but it doesn't proving the bug.

So, just to be clear here is a visual of what is expected vs what is happening
```text
// expected
Dev -> sends readOnly(props) to MyDatePicker -> sends reaOnly(props) to MyTextField -> MyTextField shows with shaded background in the DatePicker.

// what is happening
Dev -> sends readOnly(props) to MyDatePicker -> sends (mui only props) to MyTextField -> MyTextField does not show shaded background in the DatePicker.
```

Basically what I expect: If I am allowed to create my own text field and apply it as the text field that the props that I am allowed to apply to my custom text field should also be passed down from the Date Picker even though they done exist on the Mui TextField.

When using the regular `DatePicker` is the `Field` what I am seeing or the `TextField` I have a suspicion that I am only seeing the `Field` and not the `TextField`. I think this is so because when I applied `MyTextField` the readOnly view changes were present.

In either case if nothing is fixed I will just need to make a whole new DatePicker since I cannot reuse `MyTextField` functionality. Looking at the source code the Typescript is not using any generics and it looks like

Basically this is what `MyTextField` is doing which works
```typescript
interface MyProps extends TextFieldProps {
  readOnly: boolean
}
function MyTextField(props: MyProps, ref: ForwardedRef<HTMLDivElement>) {
  const {readOnly, ...rest} = props
  
  return <TextField ref={ref} {...rest} 
     InputProps={{readOnly: readOnly}}
     sx={(theme: Theme) => ({
         ...(readOnly && {
            [`&.${inputBaseClasses.root}`]: {
              background: "unset",
              backgroundColor: theme.palette.action.disabledBackground
            }
         })
     })
  />
}
```
The `readOnly` prop for `MyTextField` does all the work to apply changed I want for the `TextField` those props are not being passed down if not already described by Mui's `TextFieldProps`.

**Comment by flaviendelangle** [comment]
I think I understand what is happening.

You are passing `readOnly` to your `textfield` slot:

```tsx
<DatePicker
    slotProps={{
        textField: {
            readOnly
        }
    }}
    slots={{ textField: MyTextField }} 
/>
```

The `slotProps` is then passed to `DateField` which replaces it with the one passed by the picker and forwards it to `inputProps.readOnly` (`InputProps.readOnly` after #8659).

Not sure how we could avoid losing this piece of information.
This behavior should only impact the `readOnly` prop because it is a root prop on `DateField` and not on `TextField` so `DateField` automatically moves it.

To be convinced that we don't only pass "Mui props", you can try the following code

```tsx
<DatePicker
    slots={{
        textField: MyTextField
    }}
    slotProps={{
        textField: {
          'data-test': 'test',
        }
    }}
/>
```

You should see the `data-test` prop on your DOM element.

I can understand that it's not entirely coherent, but since it's only impacting one prop, and a prop that should not be used that way (see paragraph below), I don't think it's worth the additional complexity and bundle size to be fixed.

___

For me, you are doing something wrong.
Because in your example, the `DatePicker` component is not aware of the `readOnly`, so it can render very incoherent states.
You want the picker to be read-only, not only the text field in it.

For me, the right way to is still:

1. Pass the `readOnly` prop to the picker

```tsx
<DatePicker  
  readOnly={readOnly} 
  slots={{ textField: MyTextField }}
 />
```

2. Wait for #8659

3. Update your `MyTextField` as follow: 

```tsx
const { inputProps: temp, InputProps, readOnly = InputProps?.readOnly } = props;
```

Or alternatively, if you don't want to wait for #8659, replace it with

```tsx
const { inputProps: temp, InputProps, readOnly = InputProps?.readOnly ?? props.inputProps?.readOnly } = props;
```

Or if you want to keep your `MyTextField` abstraction untouched, create a small wrapper as follow:

```tsx
const WrappedMyTextField = (props) => <MyTextField {...props} readOnly={props.InputProps?.readOnly ?? props.inputProps?.readOnly}/>

<DatePicker  
  readOnly={readOnly} 
  slots={{ textField: WrappedMyTextField }}
 />
```

**Comment by LukasTy** [comment]
I did try to apply Flavien's suggestions to your demo and it works without issues... 🤷 

```diff
- const { InputProps, readOnly } = props;
+ const { InputProps, readOnly, inputProps: inInputProps } = props;

   const readOnlyProps = useMemo(() => {
-    if (readOnly) {
+    if (readOnly ?? InputProps?.readOnly ?? inInputProps?.readOnly) {
      return { ...TextFieldReadOnlyInputProps };
     }
     return {};
-  }, [readOnly]);
+  }, [readOnly, InputProps, inInputProps]);
```

**Comment by marcusjwhelan** [comment]
@LukasTy @flaviendelangle that solution worked. Yes this is a solution but it doesn't solve the underlying issue. That I couldn't have custom attributes for my custom text field. I am having to piggy back off the fact that luckily the readOnly field is passed to my component by another means. However if I were to need a custom attribute for my text field I would not be able to pass it through the DatePicker slotProps because it doesn't accept any different attributes than what Mui has said TextField takes.

For example adding an attribute `test: boolean` on the MyTextField right next to where I added `readOnly` to the base text field interface. I then try to add test to the `slotProps` and I get this error 

```text
Warning: Received `true` for a non-boolean attribute `test`.

If you want to write it to the DOM, pass a string instead: test="true" or test={value.toString()}.
```
even though it was applied
```typescript
slotProps={{
  textField: {
    readOnly: readOnly,
    test: true
  }
}}
```
So I will stand by that this bug issue I have presented is still valid. slot props dont allow for custom props for a custom textField

**Comment by marcusjwhelan** [comment]
@flaviendelangle @LukasTy  after the updates I am on the current latest as of 5/16/2023 and now none of this works again. Is there an example of how this would work currently?

**Comment by hannx00** [comment]
@flaviendelangle using this thread as I am running to a similar issue if that's okay. 

<img width="792" alt="Screenshot 2024-01-08 at 12 35 41 PM" src="https://github.com/mui/mui-x/assets/59639968/81972bdf-004a-43a8-a2ee-ed25212f9c54">

I have a custom textfield that adds the close icon to clear the textfield of datepicker as follow. 
```
import { Close } from '@mui/icons-material';
import { IconButton, TextField, type TextFieldProps } from '@mui/material';

type DatePickerTextFieldsProps = TextFieldProps & {
  onClear?: () => void;
};

export const DatePickerTextFields = ({ onClear, ...props }: DatePickerTextFieldsProps) => (
  <TextField
    {...props}
    InputProps={{
      endAdornment: (
        <IconButton
          sx={{ visibility: props.value ? 'visible' : 'hidden' }}
          onClick={() => onClear?.()}
        >
          <Close aria-label={props['aria-label']} />
        </IconButton>
      ),
    }}
  />
);
```
In this, I reuse all textfield props and add a custom `onClear` prop to my custom datepicker. I then add the behavior as follow in the `Datepicker` implementation.
```
      <DesktopDateRangePicker
        slotProps={{
          fieldSeparator: { children: '' },
          textField: ({ position }) => ({
            'onClear':
              position === 'start'
                ? () => setDates([null, dates[1]])
                : () => setDates([dates[0], null]),
          }),
        }}
        slots={{
          textField: DatePickerTextFields,
        }}
        value={dates}
        onChange={(newValue) => setDates(newValue)}
      />
  ```
  
This however works just fine. 
```
      <DesktopDateRangePicker
        ref={dateRangePickerRef}
        maxDate={maxDate}
        slotProps={{
          fieldSeparator: { children: '' },
          textField: ({ position }) => ({
            'InputProps': {
              endAdornment: (
                <IconButton
                  sx={{ visibility: dates ? 'visible' : 'hidden' }}
                  onClick={() =>
                    position === 'start' ? setDates([null, dates[1]]) : setDates([dates[0], null])
                  }
                >
                  <Close />
                </IconButton>
              ),
            },
          }),       
        value={dates}
        onChange={(newValue) => setDates(newValue)}
      />
  ```
Instead of passing in the custom textfield in `slots`, doing it inside `slotProps` seems to work just fine. I however want to avoid this as I have a few datepickers that need the same functionality, so it would be nice to be able to pass in the custom component with its behavior. I also read an issue that you handled (can't find it rn) that says to keep `slotProps` as minimal as possible. I also want to understand why passing custom component through `slotProps` stops working for me.

**Comment by flaviendelangle** [comment]
Hi,


Could you provide a reproduction case for both your examples, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

Unless I missed it, you did not describe your problem, is it that the opening icons is not rendered?

**Comment by hannx00** [comment]
@flaviendelangle my apology as I am not being clear. The close icon appears, but functionality is not working. In my custom TextField, I have a custom onClear prop that I am referring to in `slotProps` under this implementation 
```
      <DesktopDateRangePicker
        slotProps={{
          fieldSeparator: { children: '' },
          textField: ({ position }) => ({
            'onClear':
              position === 'start'
                ? () => setDates([null, dates[1]])
                : () => setDates([dates[0], null]),
          }),
        }}
        slots={{
          textField: DatePickerTextFields,
        }}
        value={dates}
        onChange={(newValue) => setDates(newValue)}
      />
```

This icon doesn't clear the date field here but works fine if I use `InputProps`
```
      <DesktopDateRangePicker
        ref={dateRangePickerRef}
        maxDate={maxDate}
        slotProps={{
          fieldSeparator: { children: '' },
          textField: ({ position }) => ({
            'InputProps': {
              endAdornment: (
                <IconButton
                  sx={{ visibility: dates ? 'visible' : 'hidden' }}
                  onClick={() =>
                    position === 'start' ? setDates([null, dates[1]]) : setDates([dates[0], null])
                  }
                >
                  <Close />
                </IconButton>
              ),
            },
          }),       
        value={dates}
        onChange={(newValue) => setDates(newValue)}
  ```
  
  So the underlying issue is `onClear` prop in my custom `TextField` isn't being picked up through `slotProps`. I verify `slotProps` is working just fine by adding ` 'data-test': 'test',` per your recommendation above.

**Comment by flaviendelangle** [comment]
Thanks for your reproduction case!
Our field have a built-in clearing behavior that is not available yet for multi input range fields (like the one you are using).
Right now, those multi input range field are removing the `clearable` and `onClear` props to make sure that our props are not drilled down to the DOM (since we are not using them).

I would suggest you use a different prop name to avoid this bug, it should work fine.
And I do agree that it's not ideal to remove some props like this... it would have been better that our component do not create them in the 1st place, that way if people use props with the same name it would work fine.
But given that their is an easy fix in user-land I think we should focus on supporting correctly the built-in clearable behavior for multi input range fields.

Hope this anwers your problem.

Here is the updated [example](https://codesandbox.io/p/sandbox/date-and-time-pickers-forked-2snfxs?file=%2Fsrc%2FCustomTextField.tsx%3A15%2C22)
