### ISSUE TITLE
Data Grid Virtual Scroller isn't sizing appropriately in v6

### ISSUE THREAD

**Issue by tjgibbs92** [mui/mui-x#8705]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/angry-platform-16b4rx?file=/src/App.js

Steps:
1. Change the @mui/x-data-grid-premium package version between 5.17.26 and 6.2.1

### Current behavior 😯

The data grid is pushed off the screen and the vertical scroll doesn't exist which prevents seeing the content of data grid.

### Expected behavior 🤔

We expect the data grid to fit the contents of our Grid allow us to horizontally scroll.

### Context 🔦

We have a side bar that shrinks and resizes on button click, and before the v6 release, our virtual scroller sized appropriately and would allow the content to stay within the width of the screen.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

58533

**Comment by bdamicoei** [comment]
We are also experiencing a similar issue!

**Comment by yaredtsy** [comment]
hey @tjgibbs92 

The problem is mostly from using 'display: "table"'. for some reason `table` does not support `overflow`. you must wrap the `Grid` with a container that supports `overflow`.

```jsx
<div style={{ display: "block", overflow: "auto" }}>
      <Grid
            container
            style={{
              display: "table",
              margin: "8px 16px 0px 0px",
              padding: "8px",
              marginLeft: "8px",
              height: "min-content"
            }}
          >
           ...
    </Grid>
</div>

```
Demo: https://codesandbox.io/s/elated-wing-b5dcxd?file=/src/App.js:4318-4350

Have you considered using `flex` or `grid` instead of `display: table`? They can achieve the same result and provide more flexibility. If you remove `display: table`, you can simply add `overflow: auto` to the outer `Grid` container to enable horizontal scrolling.

Demo: https://codesandbox.io/s/xenodochial-goldwasser-wjbqoi?file=/src/App.js
