### ISSUE TITLE
[question] How to filter DataGrid date and dateTime Columns in UTC instead of local time

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#8855]
### Order ID or Support key 💳 (optional)

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We display data retrieved from various devices and locations in UTC in several tables in our application. If the user has the machine where they are using our app set to local time (a timezone which is not UTC), and tries to filter on a dateTime type table column, the filter pops up showing local time. See example shown below, where I am running on a machine set to EST:

![image](https://user-images.githubusercontent.com/39837891/236001597-ad07373f-a4d4-481b-8a99-e59c7af8799c.png)

In order for the filtering to work, the user needs to know that they are entering local time (it's not obvious on the filter window what timezone is being entered) and they need to convert the value from local to UTC.

![image](https://user-images.githubusercontent.com/39837891/236002545-65cd0625-4ff5-454e-9187-c2d5caac3773.png)

Is there anyway to configure the table filter to use UTC instead of the timezone set on the user's machine?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.121
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.87
    @mui/icons-material: ^5.8.0 => 5.8.4
    @mui/material: ^5.8.1 => 5.8.6
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system: ^5.9.1 => 5.9.1
    @mui/types:  7.1.4
    @mui/utils:  5.10.6
    @mui/x-data-grid: ^5.13.1 => 5.14.0
    @mui/x-data-grid-premium: ^5.14.0 => 5.14.0
    @mui/x-data-grid-pro:  5.14.0
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-beta.2
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.2
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  18.0.14
    react: ^18.1.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript:  4.7.4
```
</details>

**Comment by cherniavskii** [comment]
Hi @conerye 
How do you format the value of the `dateTime` column?
I believe you can use `valueGetter` to strip off the timezone offset from the date: https://codesandbox.io/s/unruffled-morse-ubifbd?file=/demo.tsx
Then filtering should work as expected - the time in filter input would match the time displayed in the column.
Would this work for you?

**Comment by cherniavskii** [comment]
Hey @conerye 
Thanks for the update!

> All of the date/time values are numbers (this is always what the devices send), the number of seconds since base time.

Given the statement above and that you pass this value to the `new Date()` constructor, I assume you don't store the time zone in which the time was recorded.
`new Date(value)` returns a date in the local timezone.
I don't really understand the point of using `zonedTimeToUtc`, because you pass the local timezone to it. So it returns the same date that you pass in.


> I'm not sure I understand the code sandbox above, stripping off the timezone, and how it could apply in our scenario... we want to display everything in UTC, not strip off the timezone?

My point is that instead of using the `valueFormatter` to show the date in UTC, you can subtract the local timezone offset from the js `Date` object. This gives you a date object that behaves like you were in the UTC time zone, making filtering work out of the box.

Could you recheck the sandbox demo?
It uses the current time in the `lastLogin` column. But because it subtracts the timezone offset, you will see the cell values displayed in UTC. And the filtering should work as expected.

Let me know if I'm missing something!

**Comment by conerye** [comment]
I'm so sorry... In my rush to get back here and post something to reopen this case, I gave incorrect information above... The example above is for a task that our app reaches out to and does on the device. So, we record the time the task started and completed in local time but display it in UTC. I will look further into what you have written above regarding filtering on those columns where we have the date time in the local time zone and we display it in UTC.

As for an example where the device comes from the data, here is what I should have originally posted for the column def:
{
    field: 'systemTime',
    flex: 1,
    headerName: 'System Time',
    type: 'dateTime',
    valueGetter: (params) => {
        return params.value && zonedTimeToUtc(params.value, 'UTC');
    },
    valueFormatter: (params) => formatUtcDateTimeStr(params.value),
}

**Comment by cherniavskii** [comment]
No worries, let me know if the demo I posted above is useful for you :)

**Comment by conerye** [comment]
ok, worked on the first case (which I accidentally posted, lol!), our app commands the device to perform a task and we record the time requested and time completed. those timestamps are local time, we display them in UTC. Using the method in the code sandbox:

            {
                field: 'timeCompleted',
                flex: 1,
                headerName: 'Time Completed',
                minWidth: 190,
                type: 'dateTime',
                valueGetter: (params) => getUtcDateIgnoreTz(params.value),
                valueFormatter: (params) => formatUtcDateStrIgnoreTz(params.value),
            }

export const getUtcDateIgnoreTz = (value) => {
    const localDate = new Date(value);
    const utcTime = value + localDate.getTimezoneOffset() * MS_SEC_AMPL * SEC_MIN_AMPL;
    return value && new Date(utcTime);
};

export const formatUtcDateStrIgnoreTz = (date) => {
    const datetimeStr = format(date, 'yyyy-MM-dd HH:mm:ss');
    return `${datetimeStr} UTC`;
};

**Comment by cherniavskii** [comment]
> The other question this brings up - we need to display the timestamps in 24 hr format. Can the filter be configured to use that instead of the 12 hr with AM/PM?

We use [`<input type="datetime-local">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local), so the format depends on the user's locale. I don't think this can be configured.

**Comment by cherniavskii** [comment]
Do I understand correctly, that the issue with timezone during filtering is resolved on your end?

**Comment by conerye** [comment]
no, I would not call it resolved...
The real issue is that the filter does not support time zone and 24 hour clock. There is a workaround/hack to alter the cell values of the dateTime column to have an incorrect timezone in order for the filter to work somewhat. There is no workaround for the am/pm issue. The Date and Time Pickers support time zone and 12h/24h view... Is there any plans for the filter to support these as well?

**Comment by conerye** [comment]
We are preparing for a release and have determined we are unable to use the dateTime type column type due to lack of filtering support for date/time format and timezone. Please advise if this is a feature that can be requested to be included in a future version of MUI.

**Comment by romgrk** [comment]
Do you have a live codesandbox example of what you're trying to achieve? AFAIK, date filtering is based on `valueFormatter` so you should be able to modify it to achieve what you want.

**Comment by conerye** [comment]
sure, I will put something together and post it here tomorrow...

**Comment by conerye** [comment]
@cherniavskii @romgrk any update after taking a look at the codesandbox?

**Comment by romgrk** [comment]
So as far as I know, the date formatter turns the date into a string as seen by the user. But I'm not sure what the date filter component is doing with its value.

You can take a look at the [filtering customization docs](https://mui.com/x/react-data-grid/filtering/customization) to see how to replace the `getApplyFilterFn` function, or how to replace the date filter input component. You can check out our own date operators [here](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/colDef/gridDateOperators.ts) if something in the doc is unclear.

**Comment by conerye** [comment]
I will check out the links you sent... thanks

**Comment by romgrk** [comment]
Ok, if you don't have more questions you can close this issue.

**Comment by conerye** [comment]
would like to leave it open until it is determined that there is a way to have the date and dateTime columns filter panel with UTC instead of local time... ok?

**Comment by gmconte** [comment]
I don't think this bug issue should be closed: 
I am working on a system that stores the values in UTC and I want to display the dates in UTC/GMT format.
In my case I use the `renderEditCell` function returning a `GridEditDateCell` component initialized to the value I want, so when the user start editing the cell, I can display the current value.

The issue appears right away, as the datepicker automatically changes the value displayed to local date format, which is very confusing.


It should be possible to set the timezone used by the datepicker tool, which is the reason why both the filter and the cell editing show confusing datetime values.

Even setting the LocalizationProvider doesn't help as it misses the UTC/GMT locale (maybe adding that would be the best solution?)

Reading the previous comments, I understand the hack mentioned causes the data to be displayed with the wrong format: the timezone is in local timezone but the data is displayed with the "UTC" string, which is completely wrong.

So I'm wondering if at this point I should show the data in local time, but I would really prefer a solution to this problem as it is a real case scenario when talking about transactions and would avoid the confusion caused by the BST change during the year.

**Comment by Shudhanshu-Appnox** [comment]
Hello, there are there any updates on how to customise the Time Format in dateTime type column? I want to Display the 24-hour time format in the Filter.
