### ISSUE TITLE
[bug] DatePicker error after vite build

### ISSUE THREAD

**Issue by PhilipeGatis** [mui/mui-x#8938]
### Order ID or Support key 💳 (optional)

65890

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

![image](https://github.com/mui/mui-x/assets/4982462/61a290df-14e1-40e2-af7d-5b92af81ec24)
After building the bundle got this error when accessing any route that uses any DateComponent.
This project is built using VITE 3.2.3

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: macOS 13.3
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 9.6.0 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.10.5 => 11.11.0 
    @emotion/styled: ^11.10.5 => 11.11.0 
    @mui/base:  5.0.0-alpha.128 
    @mui/core-downloads-tracker:  5.12.3 
    @mui/icons-material: ^5.10.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.110 => 5.0.0-alpha.129 
    @mui/material: ^5.10.16 => 5.12.3 
    @mui/private-theming:  5.12.3 
    @mui/styled-engine:  5.12.3 
    @mui/system: ^5.10.16 => 5.12.3 
    @mui/types:  7.2.4 
    @mui/utils: ^5.10.16 => 5.12.3 
    @mui/x-data-grid:  6.3.1 
    @mui/x-data-grid-pro: ^6.3.1 => 6.3.1 
    @mui/x-date-pickers: ^6.3.1 => 6.3.1 
    @mui/x-date-pickers-pro: ^6.3.1 => 6.3.1 
    @mui/x-license-pro:  6.0.4 
    @types/react: ^18.0.24 => 18.2.6 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.6.4 => 4.9.5 

```
</details>

**Comment by LukasTy** [comment]
Hello, it looks like the issue could be `vite` itself.
I've been able to replicate the issue using production build, but at the same time, the issue is not present using the latest vite version (`4.3.5`).
Is upgrading the `vite` version feasible for you? 🤔 
Inspecting the generated JS, it really seems like an issue on the bundler side, because I can't understand, how such a [simple function](https://github.com/mui/material-ui/blob/master/packages/mui-utils/src/useEnhancedEffect.js) (`useEnhancedEffect`) could fail to work. 🤷

**Comment by PhilipeGatis** [comment]
Thanks, @LukasTy. I just update vite to the latest version and works.
