### ISSUE TITLE
[DateTimePicker] "closeOnSelect" can't prevent to close DateTimePicker

### ISSUE THREAD

**Issue by plaknight** [mui/mui-x#9081]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://github.com/mui/mui-x/issues/new?assignees=&labels=status%3A+needs+triage&projects=&template=1.bug.yml

Steps:

 1.  just add closeOnSelect to DateTimePicker, and then It wasn't Expected behavior

### Current behavior 😯

https://github.com/mui/mui-x/assets/52069851/3b63dfc5-1225-4b11-b6fe-34ad72587249

### Expected behavior 🤔

closeOnSelect should prevent to close it

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
The `closeOnSelect` prop determines if the picker should close its view when reaching the last one.

In your scenario, the time views are non-existent and the editing is done using the field.
So the picker closes the view to allow you to edit the time.
I don't think keeping the calendar open is a good solution here. @LukasTy what's your opinion here.

By the way, we have a new UI for the time picking, it's available since 6.3.0 on the `TimePicker` and hopefully very soon on the `DateTimePicker` (see #8946 to track the progress).
Once we have this new UI, your problem should go away.

**Comment by plaknight** [comment]
>  thank you for your comment, that is why I need this, if you have this new UI, I don't need customize DateTimePicker

**Comment by LukasTy** [comment]
> I don't think keeping the calendar open is a good solution here. LukasTy what's your opinion here.

Just adding a note that yes, I agree with your proposal.
The previous UI can be brought back now and will work as expected, also, the new desktop UI should be released in the coming weeks. 🤞
