### ISSUE TITLE
[DateRangePicker] Get changed value during onClose

### ISSUE THREAD

**Issue by Bubinoluk** [mui/mui-x#9082]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: [DateRangePickerTest](https://codesandbox.io/s/quiet-forest-3o258f?file=/src/DateRangePickerTest.js)

Reproduce:
1) Set from date by DateRangePicker
2) Set to date by DateRangePicker
3) take a look at the console log -> the status variable contains only the from date, not the to date during the onClose

### Current behavior 😯

Using the DateRangePicker and trying to perform some operations during the onClose and not during the onChange, notice that the value react status is updated after the onClose, looks like onClose is triggered before the onChange.

### Expected behavior 🤔

When the onClose is triggered expect to have both date values set by DateRangePicker

**Comment by oliviertassinari** [comment]
A quick comparison with https://mui.com/material-ui/react-autocomplete/#controlled-states

<img width="806" alt="Screenshot 2023-05-23 at 11 55 55" src="https://github.com/mui/mui-x/assets/3165635/7a14ea23-ae2f-4611-bd74-40745b6bc325">

https://codesandbox.io/s/jovial-thompson-0tfclm?file=/demo.tsx

**Comment by LukasTy** [comment]
Hello @Bubinoluk 
Everything seems to be working as expected.
[Here is a more detailed codesandbox](https://codesandbox.io/s/damp-mountain-lsu0v7?file=/src/DateRangePickerTest.js) showcasing all options.
The call order: `onChange` -> `onAccept` -> `onClose`.
If you need to execute certain actions after a range is selected, consider using the `onAccept` callback.

The problem you are talking about is the expected behavior of React hooks state. The state is updated asynchronously.
