### ISSUE TITLE
[pickers] I cannot override all styles in PickersDay

### ISSUE THREAD

**Issue by alyssaButlerIntegrityNext** [mui/mui-x#9192]
### Order ID or Support key 💳 (optional)

65965

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to change the color of 'today' and 'selected' dates in the Date Picker (to use our secondary color and not the default primary color). What is the most appropriate way to override these colors? And is it possible to change the 'today' border color without using !important?

I would expect that we could override the PickersDay in the theme using the css rules from the [documentation](https://mui.com/x/api/date-pickers/pickers-day/#css) for 'today' and 'selected', however they do not seem to make any difference. 

Please see [this demo](https://codesandbox.io/s/jolly-moser-1piiqw?file=/src/App.js) to highlight that some css rules work and others do not ('root' does work, 'today' works but NOT the override of the border color, and selected does not seem to work). 

I could override some of the styles using slotProps (see below code) but I would have expected that we could also just use only the theme. 
```
  slotProps={{
          layout: {
            sx: {
              '& .MuiPickersDay-root.Mui-selected': {
              border: (theme) => `1px solid ${theme.palette.secondary.main}`,
              background: (theme) => theme.palette.secondary.main,
                '&:hover': {
                background: (theme) => theme.palette.secondary.main,
                },
               },
            },
          },
  }}
```

### Your environment 🌎

  From using Cloud version of Code Sandbox;
  
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found

**Comment by LukasTy** [comment]
Hello,

regarding the `selected` overrides—that's an issue on our side. Based on how CSS overrides work, our infrastructure does not allow such types of overrides. The same would to `disabled` overrides. Technically, we ought to remove those from possible fields to override them as they do not take any effect and do produce an error when running in dev mode. Please check the console in the linked codesandbox to find the mentioned error.

In regards to the `today` border overrides, we bump at the CSS specificity problem, because our own styles apply the border only in case, when the `today` is also not selected.

Consider going with the following updated `styleOverrides` to achieve your desired outcome:
```ts
styleOverrides: {
  root: {
    background: 'pink',
    '&.Mui-selected': {
      background: 'green', // works
    },
  },
  today: {
    background: 'orange',
    '&:not(.Mui-selected)': {
      borderColor: 'orange', // works
    },
  },
},

```

As for a fix from our side: we should remove the `disabled` and `selected` slots from every component `styleOverrides` themeAugmentation options (would only apply to TS users) as they wouldn't take any effect.

**Comment by alyssaButlerIntegrityNext** [comment]
Ah great, thanks!
