### ISSUE TITLE
Is there any way to add horizontal scrollbar on top of MUI DataGridPremium?

### ISSUE THREAD

**Issue by NjegosR** [mui/mui-x#9256]
### Order ID or Support key 💳 (optional)

67541

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We would like to add a horizontal scrollbar to the top of the MUI DataGrid, we searched throughout your documentation but couldn't find a solution for this. This is a [link](https://codesandbox.io/s/elastic-nightingale-1mtob2?file=/demo.tsx) with a mockup of our setup. We have implemented a fixed/sticky header (first row of the data grid), and we would like to add the horizontal top scrollbar. We would like it to be there all the time and not to be scrolled when a user starts scrolling. Is there any option we can implement this?

<img width="558" alt="Screenshot 2023-06-07 at 11 16 24" src="https://github.com/mui/mui-x/assets/33623900/5cc8fce4-318f-4a6e-9b22-9f890ea51e8a">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment]
Are you trying to add the scrollbar on top because the bottom scrollbar is hidden below the scroll viewport with your custom styling?

Have you considered using the grid's default style instead: https://codesandbox.io/s/nifty-field-dbvr3t?file=/demo.tsx

**Comment by romgrk** [comment]
It's currently not possible to add a working scrollbar on top.

Related: #8343, #9171 

Any reason in particular why you can't let the scrollbar be on the content of the grid instead of the body of the document?

**Comment by romgrk** [comment]
If your app corresponds to the codesandbox you shared above, you're using `autoHeight`, so the scrollbar would not be on the grid's content. I would suggest to remove `autoHeight` if you're using it.

**Comment by NjegosR** [comment]
Yes, we are using `autoHeight` and we can't remove it, you can read [here](https://github.com/mui/mui-x/issues/7588) why we use these custom styles. But even with `autoHeight` the horizontal scrollbar is on the grid content, and removing it won't fix the issue we are trying to solve.

**Comment by romgrk** [comment]
Let us know if there is anything more to do for this issue, we can keep the other one to track the root issue.

**Comment by NjegosR** [comment]
Since there is no a way to add a working scrollbar on top we will come up with some other approche. Thank you.

**Comment by romgrk** [comment]
It sounds like the feature you want is "autoHeight up to the container maxHeight". I would phrase it like that in your other issue, or if you want you can open a feature request issue so we can track it.

**Comment by mmudge** [comment]
I also found myself needing a scrollbar at the top of the table, and came up with a hacky css solution by just just targeting the virtual scrollbar and then rotating the content.

Example:
```<DataGridPro
    sx={{
        '& .MuiDataGrid-virtualScroller': {
          transform: 'rotateX(180deg)',
        },
        '& .MuiDataGrid-virtualScrollerContent': {
          transform: 'rotateX(180deg)',
        },
  }}
/>```

**Comment by PayalVerma21** [comment]
Hi Team,

I need one help here.

I am using MUI DataGridPro and I have always more than 25 columns. The requirement is to always show horizontal scrollbar without going down to the table.

is there anyway?
Thank You!

**Comment by epicstar** [comment]
> Hi Team,
> 
> I need one help here.
> 
> I am using MUI DataGridPro and I have always more than 25 columns. The requirement is to always show horizontal scrollbar without going down to the table.
> 
> is there anyway? Thank You!

I'm assuming you want the horizontal scroll bar to appear at the bottom of the datagrid without having to scroll down the page. Which means the problem is that you're seeing your datagrid overflow its container(s).

You'll first want to ensure that you have a vertical scrollbar and ensure the datagrid doesn't overflow vertically.

If you're using a flexbox (we are using MUI Grid V2), what you have to do is all flex containers must have a height, going from the highest parent container all the way down to the lowest one.

I noticed that the lowest level container must have the following:
1. `flexWrap=nowrap`
2. `direction` defined -> our lowest level containers use `column`

Then the item that contains the datagrid must have the following:
1. `flex={1}` (though I think any other value is acceptable as long as `flex` is defined and not `0`...)
2. `minHeight={0}`

Please make sure `autoHeight` on the `DataGrid` is not enabled; otherwise, the datagrid will overflow.

To get the horizontal scroll bar, just ensure a `minHeight` for some, if not all, columns. As long as you also define a `flex` value on every column, the datagrid should scale accordingly. And you won't have to scroll all the way down the page to find the horizontal scroll bar.

**Comment by WCMC-vblanque** [comment]
It would be great to be able to display horizontal scrollbar at the top. I hope this feature request will gain traction.
When you have more than 20 rows and 10 columns you want to let the user moving to the right of the table without having to go at the bottom (if it makes sense).

**Comment by chachra** [comment]
need this!
