### ISSUE TITLE
[question] [maybe bug] single digit number wrongly typed as string even if column type is number

### ISSUE THREAD

**Issue by Kohei909Otsuka** [mui/mui-x#9281]
### Order ID or Support key 💳 (optional)

68257

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

https://codesandbox.io/s/currying-night-xpfv64?file=/demo.tsx

```
const columns = [
  {
    field: "userName",
    type: "string",
    editable: true
  },
  {
    field: "age",
    type: "number",
    editable: true
  }
];
```

even if "age" column is typed as "number",
when I type with keyboard only "1" or "2" or something single degit number.("10" or "11" is fine)
MUI X Grid takes it as "string" wrongly.

How can I get number As it it's expected.

https://github.com/mui/mui-x/assets/11783802/1768d73f-af6f-46f1-8078-dff94acc5c23

### Your environment 🌎

  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: Not Found
    npm: 9.6.7 - ~/develop/nitoel/tenant/supplier-frontend/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/core-downloads-tracker:  5.10.13
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.13 => 5.10.13
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.2
    @mui/utils:  5.13.1
    @mui/x-data-grid:  6.6.0
    @mui/x-data-grid-premium: ^6.6.0 => 6.6.0
    @mui/x-data-grid-pro:  6.6.0
    @mui/x-license-pro:  6.6.0
    @types/react: 18.0.14 => 18.0.14
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.7.4 => 4.7.4

**Comment by victorct-tradeengage** [comment]
This bug is also applying to filters, here is a [codesandbox](https://codesandbox.io/p/sandbox/thirsty-browser-lm7cjg?workspaceId=bdadc1c4-71b6-49af-9206-c8b4b14580f7&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm08yie7m00073b6ir4p4hwmz%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm08yie7m00033b6ilxiqsqqs%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm08yie7m00043b6ijz4va2uf%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm08yie7m00063b6i9rkyjp0v%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm08yie7m00033b6ilxiqsqqs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm08yie7m00023b6i63aprs7b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A23%257D%255D%257D%255D%252C%2522id%2522%253A%2522cm08yie7m00033b6ilxiqsqqs%2522%252C%2522activeTabId%2522%253A%2522cm08yie7m00023b6i63aprs7b%2522%257D%252C%2522cm08yie7m00063b6i9rkyjp0v%2522%253A%257B%2522id%2522%253A%2522cm08yie7m00063b6i9rkyjp0v%2522%252C%2522activeTabId%2522%253A%2522cm08ynzs300153b6i0c1g1muk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm08yie7m00053b6i1pm8321k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm08ynzs300153b6i0c1g1muk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm08yie7m00043b6ijz4va2uf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm08yie7m00043b6ijz4va2uf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D):
