### ISSUE TITLE
[getRowMode] Not return great row mode

### ISSUE THREAD

**Issue by mespeche** [mui/mui-x#9576]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

[Link to live example:](https://codesandbox.io/s/admiring-sound-mlskmf?file=/demo.js)

Steps:
1. Set your row to edit mode using `apiRef.current.startRowEditMode`
2. Use `apiRef.current.getRowMode` to check if your row mode is "edit"

### Current behavior 😯

Instead of return "edit" after a manuel `startRowEditMode`, the `getRowMode` return "view". If you click into a row field or outside this row, the `getRowMode` return "edit".

### Expected behavior 🤔

After a `startRowEditMode`, the `getRowMode` should return "edit".

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
When you control the `rowModesModel`, the grid relies on the value passed as prop in the `rowModesModel`. As a general rule, the controlled prop is always preferred over the internal state, so on when `startRowEditMode` is called it returns the updated value in `onRowModesModelChange`, which updates your `rowModesModel` local state, but due to the imperative nature of `apiRef`, it is not reflected in the `getRowMode` until next render.
Since you have the `rowModesModel` state readily available, you can rely on it rather then trying to fetch the value from `getRowMode`. I tried this is https://codesandbox.io/s/jolly-snowflake-vkggf2?file=/demo.js and it seems to show the correct icons.

Is there another reason you specifically want to use `getRowMode` and not the controlled state?

**Comment by mespeche** [comment]
In fact, it works by using the `rowModesModel` state, and I've modified my code accordingly.

The reason for my ticket is that I've migrated from V5 to V6 and haven't found any indication in the documentation indicating that the `getRowMode` method has changed its behavior.

For me, it's like a breaking change. This change in behavior may have a big negative impact, and I think it's important to communicate on this.

If I've understood correctly, it's better to use the rowModel rather than the api's `getRowMode` method.

Thank you very much for your feedback 😉

**Comment by VegarRingdalAibel** [comment]
Hi

From what I can tell this broke in 6.8.0 release
Maybe this issue should be reopened since it worked before?


Tried to make a very small sample to show the issue.

In 6.7.0 it works
https://stackblitz.com/edit/react-qtzade?file=Demo.tsx

After 6.8.0 it fails
https://stackblitz.com/edit/react-qtzade-zngdgm?file=Demo.tsx

**Comment by mespeche** [comment]
Hi !

Thanks for investigating and supporting me ! 😂

Another issue indicating the same problem is already open [here](https://github.com/mui/mui-x/issues/10030), maybe it would be better to leave this one closed to avoid a duplicate ?
