### ISSUE TITLE
Filtering in x-data-grid broken after update to v6.10.1 due to eval content-security-policy

### ISSUE THREAD

**Issue by superkartoffel** [mui/mui-x#9771]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. update your project to latest v6.10.1
2. set content-security-policy header to include script-src: "'self'" 
3. open your application and try to use filter

### Current behavior 😯

filters are not applied and console shows errors that eval expressions have been blocked due to content-security-policy.

### Expected behavior 🤔

filters should work without having to enable unsafe-eval CSP header.

### Context 🔦

I report this as a bug, since I consider it a breaking change in a patch version update. The same content-security-policy works fine with v6.10.0

The change has most likely been introduced in https://github.com/mui/mui-x/pull/9635 and can easily be worked around by including content-security-policy header script-src: 'unsafe-eval'. But I do not consider it safe to do so.

Hence my question: Is there another way of enabling eval expressions just for this script instead of globally?
Also, please update you changelog to warn others about this change.

### Your environment 🌎

Firefox and chrome are affected, I did not test any other browser.

**Comment by cherniavskii** [comment]
Yeah, I totally forgot that eval might be a problem for CSP 🙃

**Comment by peterhirn** [comment]
`eval` usage also adds a cool 300KB to my bundle size using vite.

```
WARN  ../../.yarn/__virtual__/@mui-x-data-grid-virtual-e60fa12330/0/cache/@mui-x-data-grid-npm-6.10.1-a169528a91-7ae6335b82.zip/node_modules/@mui/x-data-grid/hooks/features/filter/gridFilterUtils.js (171:21) Use of eval in "../../.yarn/__virtual__/@mui-x-data-grid-virtual-e60fa12330/0/cache/@mui-x-data-grid-npm-6.10.1-a169528a91-7ae6335b82.zip/node_modules/@mui/x-data-grid/hooks/features/filter/gridFilterUtils.js" is strongly discouraged as it poses security risks and may cause issues with minification.
```

**Comment by romgrk** [comment]
I'll check if we can feature-detect `eval` at runtime.

@peterhirn 300KB seems excessive for what we do with `eval`, are you sure about those numbers? Could it be a bundler issue?

**Comment by romgrk** [comment]
Size at `6.10.0`: [406.1kb](https://bundlephobia.com/package/@mui/x-data-grid@6.10.0)
Size at `6.10.1`: [417.5kb](https://bundlephobia.com/package/@mui/x-data-grid@6.10.1)

I'm not sure what's going on with your bundle but there might be an issue there. I would open an issue in your bundler's repo so we can get some assistance from the maintainers there, it will be easier to figure out.

**Comment by oliviertassinari** [comment]
@peterhirn I had a quick look. It seems to be because Terser (used by Vite) can no longer minify function names as eval has global scope access. I got this lead from https://github.com/terser/terser/issues/455. It's referenced in https://rollupjs.org/troubleshooting/#avoiding-eval too and terser seems to have an option for this: https://github.com/terser/terser/tree/27c0a3b47b429c605e2243df86044fc00815060f#mangle-options

@romgrk maybe we should hide the eval call to code analyzer tools? using something like `window[atob('ZXZhbA==')]("true")`.

**Comment by romgrk** [comment]
It's a bit different, `eval` does magic to preserve the lexical context in which it is called. Any indirect call doesn't:

![image](https://github.com/mui/mui-x/assets/1423607/9651d4a5-6305-41eb-aa31-7506c3d47d21)

I think we can work around that by adding another real closure around and passing arguments instead of closure values.
