### ISSUE TITLE
[question] [DataGrid] Custom Grid Tree data grouping cell

### ISSUE THREAD

**Issue by ojhamohit** [mui/mui-x#9880]
### Order ID or Support key 💳 (optional)

68529

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a requirement to show custom group column with icons in expanded and collapsed states.

https://codesandbox.io/s/wild-rgb-g9z4dz?file=/src/DataGrid.tsx

Observed Behavior:
When I expand a collapsed row and Update the value for any row, it will result in the collapsing of all groups.

### Your environment 🌎

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 66.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Managers:
    Gradle: 7.4.1 - /opt/homebrew/bin/gradle
    Homebrew: 4.0.14 - /opt/homebrew/bin/brew
    pip3: 21.2.4 - /usr/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.3 - /usr/bin/gcc
    Git: 2.39.2 - /usr/bin/git
    Clang: 14.0.3 - /usr/bin/clang
    Curl: 7.87.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.54 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.13 - /usr/local/bin/docker
  IDEs:
    Sublime Text: 4126 - /opt/homebrew/bin/subl
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 5.1.16 - /opt/homebrew/bin/bash
    Go: 1.19.4 - /opt/homebrew/bin/go
    Java: 17.0.4.1 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.4

**Comment by DanailH** [comment]
Hey @ojhamohit, your example is quite complicated and has a lot of unnecessary core that is not really related to the problem you are experiencing. I had a quick look and it seems that the problem is related to the fact that you persist the rows in the state and you update that state when there is an interaction with a row which causes the grid to rerender.

**Comment by ojhamohit** [comment]
Hey @DanailH , sorry for the inconvenience. I have removed the extra code.
Yes we are updating the state on interaction with the row.This issue comes only for the rows which have Tree data.

Basically the current workflow is

**Set rows => Generate the tree => Render**

Set rows causes a complete regeneration of the tree, even if you just change a single row, you lose any information about the children expansion. Is there any way to handle the information about the expanded state of Tree data?

**Comment by MBilalShafi** [comment]
>  Is there any way to handle the information about the expanded state of Tree data?

Instead of managing `rows` array in external state and updating it when needed, you could pass an initial `rows` array and then utilize the `apiRef.current.updateRows` method whenever update on `rows` is needed, which keeps the tree expansion state as full regeneration of the tree is not done.

Check out it's example usage here: https://mui.com/x/react-data-grid/row-updates/#the-updaterows-method

Let us know if it works for you?

**Comment by ojhamohit** [comment]
Yes we have tried this but we need updated rows to perform some other operations.

**Comment by DanailH** [comment]
@ojhamohit you can perform any operation you want when the row updates. What @MBilalShafi is saying is that the grid maintains an internal state with the initially provided rows so you don't have to. The issue you are experiencing happens because you are maintaining the row's state outside of the grid and then providing a new row set when any of the rows changes which causes the grid to rerender and this reset its current state.
To prevent this from happening once you provide your initial rows you then use the `apiRef.current.updateRows` method to update any of then if needed.

**Comment by ojhamohit** [comment]
I got your point.But we have to perform addition actions on the updated rows like get the count of updated rows,display additional buttons.

https://github.com/mui/mui-x/issues/210#issuecomment-1006411492 
@flaviendelangle has mentioned about the same issue in this comment.
Is it possible to handle my issue with the points mentioned by him?

**Comment by MBilalShafi** [comment]
For that purpose, you got a bunch of [selectors](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/hooks/features/rows/gridRowsSelector.ts#L6) available to access updated rows state, like `gridRowCountSelector`, `gridRowsStateSelector`, etc, you could use [`useGridSelector`](https://mui.com/x/react-data-grid/state/#with-usegridselector) hook to access different portions of state.
