### ISSUE TITLE
[Charts] X-axis with time creates unecessary ticks 

### ISSUE THREAD

**Issue by EzhnoFR** [mui/mui-x#9881]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/elegant-sound-8rc6l3

Steps:
1. Use two dates, and two datas
2. Display the full date in ISO format (in this case fr-FR)

### Current behavior 😯

The X axis show 10 scales instead of the only two provided. (It will show the same date more than once)
The lines of the graph have the correct number of steps. 
![image](https://github.com/mui/mui-x/assets/75476898/57ec6a8f-16fb-4081-9623-020b0d7a7190)

### Expected behavior 🤔

The X axis should show only 2 axis scales, which are the two dates 
![image](https://github.com/mui/mui-x/assets/75476898/2c90e8bb-24bb-4875-aeb8-c104db20edd8)

### Context 🔦

I'm trying to display a set of datas by days between two dates. 
The chart should only be displaying on the x-axis the dates that are in my datasets, in this case "2023-07-01" and "2023-08-01" but for some reason it keeps adding in between ticks and scales. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  I'm using BRAVE as a web browser, I tried the same on Chrome and Edge with no success
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
    Memory: 1.78 GB / 15.78 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 21.2.4 - C:\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.36.0. - C:\Program Files\Git\cmd\git.EXE
    FFmpeg: 12.2.0 - C:\FFMPEG\bin\ffmpeg.EXE
  SDKs:
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    VSCode: 1.80.2 - C:\Users\Bruno\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Go: 1.19.2 - C:\Program Files\Go\bin\go.EXE
    Java: 19.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
    Python: 3.10.2 - C:\Python310\python.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.19041.1566
   BRAVE
```
</details>

**Comment by alexfauquette** [comment]
Effectively it's problematic.


I can see distinct strategies about ticks management:
1. Stick to data: If the charts has between 2 and 10 points equally spaced, it can be expected that ticks fall on those values
2. Ignore data point: If their is a lot of data point, or if they are not equally spaced it makes sense to ignore the data distribution and just split it.

I could be managed by multiple option in the axis config such as


- Improve the number of ticks guessing for small dataset: If the data set length is smaller than the proposed number of tick, we use the data length
- `tickNumber` to enforce a number of ticks instead of the automatic computation
- `tickValues`: an array of value that by pass the current tick generation

**Comment by EzhnoFR** [comment]
Also, I forgot to mention that the ticks are not properly aligned with the lines datas as shown on the following image : 
![image](https://github.com/mui/mui-x/assets/75476898/72592137-9061-4786-9242-144a85485705)

Is there any way to ignore data points already ?

**Comment by alexfauquette** [comment]
> ticks are not properly aligned with the lines data

Yes, I assume your data points are not on a precise day (for example: `2023-05-01T16:15:00Z` instead of `2023-05-01T00:00:00Z`)

I noticed in your codesandbox you use `new Date('2023-10-05')` to create dates. It's recommended to either provide a full ISO string or use the number constructor (i.e. `new Date(2023, 9, 5)`) because the string parsing is not well defined accros browser for partial dates

**Comment by alexfauquette** [comment]
> Is there any way to ignore data points already ?

No but it can be added :) What do you have in mind exactly?

**Comment by EzhnoFR** [comment]
> It does not solve the over number of ticks. Maybe a granularity for time scale could be interesting

This is really problematic. In a range of 2 days there's already 10 ticks. Adding one date makes it even worst. 
It would be good to have an option to set the steps for ticks manually indeed. Maybe forcing it to only show days, weeks, months or even years depending on period selected.

**Comment by EzhnoFR** [comment]
> > Is there any way to ignore data points already ?
> 
> No but it can be added :) What do you have in mind exactly?

At this point I think I rather hide the X axis considering that hovering the graph give me the needed informations. But a chart missing an axis is a bit weird.

**Comment by alexfauquette** [comment]
@EzhnoFR would this new config solve your issue?

https://deploy-preview-9922--material-ui-x.netlify.app/x/react-charts/axis/#ticks-positions
