### ISSUE TITLE
[data grid] How to fetch data inside master detail panel?

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#9907]
### Order ID

2023-7934

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello I'm trying to fetch data with master/detail example here: https://codesandbox.io/s/snowy-dawn-zwzs7z?file=/Demo.js

however the data fetches but never is placed id the details. The click on the + doesn't work so it seems I'm missing a step

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
In order for the Grid to know a master detail is available for showing, `getDetailPanelContent` [must return a valid React element](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts#L145), instead of returning _JSX_ from `useCallback` wrapped function, you could create a proper component and return from the `useCallback` wrapped function, I tried to do that in this fork of your codesandbox example and it seems to work now: https://codesandbox.io/s/hopeful-bartik-f87c2d?file=/Demo.js

Does that work for your use case?

P.S: You could add a loading icon till the data is not available to make it a bit more interactive.

**Comment by MBilalShafi** [comment]
Glad it worked 🎉 
I'll close the issue then, feel free to reopen if a related problem pops up again.
