### ISSUE TITLE
[pickers] No keyboard entry possible in date/time picker with Firefox

### ISSUE THREAD

**Issue by pkuenemann** [mui/mui-x#9911]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open your example page https://mui.com/x/react-date-pickers/ in the latest Firefox Browser 115.0.3 (64-Bit) on a Windos computer
2. Klick in the date (or date/time) field and try to enter the value manually through your keyboard
3. You will see: keyboard entries do not work

### Current behavior 😯

nothing

### Expected behavior 🤔

Try the same with the chrome or edge browser. That's the way it should work within Firefox as well.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MonstraG** [comment]
<details>
<summary>Seems to be working for me</summary>

![Recording 2023-08-05 at 16 00 14](https://github.com/mui/mui-x/assets/17963791/13f1b7c0-097f-4ba0-bd38-6f5811802c78)

</details>

Windows 11, Firefox 117.0b3 (64-bit)

**Comment by pkuenemann** [comment]
...our customers do not work with the 117 beta of Firefox, they use the released 115.0.3 version. The funny thing is: this behaviour does not appear on all computers. On some the keyboard entry is possible as expected. 

We compared the Firefox versions and settings but could not find any differences. We hoped we are not the only ones facing this problem...

**Comment by alexfauquette** [comment]
It is weird because I'm on Ubuntu 22.04 / Firefox 116.0.1 (64-bit) and I don't see any keyboard issue

Id the arrow up/down working?
What is their language? This could be due to some keyboard configuration

**Comment by pkuenemann** [comment]
...yes, it is weird cause on my laptop it is also working well. Me as well as the customer are using the Germasn Firefox 115.0.3 (64-Bit) without any Plugins or translation-mode. The arrow-keys are working. 

When you klick in the date/time field on those computers, the picker is opened automatically while usually it opens only when you klick on the regarding symbol. I can enter the field only through the tab key, move to e.g. the hours by using the right-key but cannot enter any numbers...

**Comment by pkuenemann** [comment]
...yes German, sorry. So I have to wait till tomorrow, they got their day off today but then I will try and come back to you. Thanx so far. 👍

**Comment by pkuenemann** [comment]
OK, I could try your sandbox code now on the regarding comupter and Firefox browser and it shows the same result as it does on your computer "onChange, eventData: 1". I was puzzled and opened your example on https://mui.com/x/react-date-pickers/ again to see what happens now but there still keyboard entries are not possible,

Any further ideas?

**Comment by LukasTy** [comment]
> Any further ideas?

Could you confirm the version of the doc that this particular computer is on?
<img width="288" alt="Screenshot 2023-08-09 at 10 33 37" src="https://github.com/mui/mui-x/assets/4941090/388345b3-99ba-463b-9ea5-5791773b1d36">

Other things to check:
1. Have you tried clearing the cache and hard reloading or opening a private window?
2. Did you make sure that there is no magic of the keyboard changing when switching tabs? Maybe the German keyboard has some special characters on the number keys..?
3. Is it only happening in docs? Or it's the same if you open any of the docs codesandbox examples? As well as the app you are developing.
4. The part where you are talking about opening the picker when clicking on the input is a bit puzzling. Could you provide a video showing the broken behavior? Preferably with a tool overlaying the keys pressed as well

**Comment by pkuenemann** [comment]
Hi Lukas,

ok, I visited our customer again (virtualy) and checked your points. I also made a short screen video, not shure, if that really helps:

1. I did and opened your dt-picker example as well as our application in an incognito window of Firefox. Same behaviour.
2. Nope. I tried different other input components in other apps as well as from your website and all keyboard entries work fine except within the date/time pickers.
3. It also happens when I open the example from your website in the sandbox (see video). I am not shure about the used version from mui x: which one is used as example on your website?
4. Check the short screen video. Hope this helps...

https://github.com/mui/mui-x/assets/34913709/7c1e462e-adce-489f-b0ca-dedd44307f1b

Greets, Lemmi.

**Comment by LukasTy** [comment]
Thank you for your feedback.
It has helped clarify the situation.
It is pretty clear in the video, that all the pickers are rendered as mobile variants because they all lack the trigger to open the picker and we see the opening of the picker modal once you click on the input.
I don't know if you were aware, but for mobile pickers, we do put the `field` (input) into read-only mode and allow input only via the view.
We use `desktopMediaQuery` with a default value of `@media (pointer: fine)` to resolve when a desktop variant should be rendered.
Have you mentioned that this is happening only on Firefox on these machines and not other browsers?
This suggests, that there either are certain settings on Firefox (maybe some accessibility settings) that are making it report as not having a precise pointer (mouse, laptop touchpad, etc.).
Could you clarify the hardware setup of those machines? Do the machines having this behavior by any chance have touchscreens? Or maybe they have other unusual input devices connected?

I believe that the browser should always report the main/primary input device precision, regardless of what is connected to the device (i.e. a mouse connected to a tablet will not start reporting as having a precise pointer), but maybe Firefox could be treating this behavior differently..? 🤔

**Comment by pkuenemann** [comment]
OK, that's the issue, you are right: The terminals showning this problem within Firefox do have a touch-screen as well as external mouse and keyboard. Obviously Firefox handles this setting a bit different than the oder browsers. At the moment they are using MS edge and there the keyboard handling of your date/time pickers works fine.

Anything you can/must change in your components for that or is it an issue of Firefox?

Greetings, Lemmi.

**Comment by LukasTy** [comment]
Thank you for clarifying.
Could you open [this codesandbox](https://codesandbox.io/s/pointer-testing-jz5zd8?file=/src/App.tsx) on the mentioned machine, click anywhere to register the pointer details, and provide a screenshot of the result?

Given the result, we could consider using a different default `desktopMediaQuery` prop value or/and at least suggest one to unblock you. 🤔

**Comment by pkuenemann** [comment]
![mouse-pointer-firefox](https://github.com/mui/mui-x/assets/34913709/c65cf9b5-bf95-4228-8d93-cf2f17369aa3)

**Comment by LukasTy** [comment]
Well... That is a case I did not want to see, but I kind of was expecting for...
Given this weird behavior, where CSS resolves the pointer to `coarse`, but the fired button is reported as a `mouse` in JS is just plain wrong in my book...
This deserves an investigation into Firefox issues or possibly filing an issue.

I've added one more rule to the list ('any-pointer: fine'). Could you double-check if maybe that one actually results in `true`? 🤔 

In regards to unblocking your use case: do you need to support responsive behavior and actually render mobile picker variants on mobile? Or is it an internal application only used via desktop computers and having only desktop picker variants would be better than having this inconsistency?

Because given your screenshot, it seems that if you need the responsive behavior, then we might be left with targeting the device-width rule (the false-positive one used by for example bootstrap).

```tsx
<DatePicker desktopModeMediaQuery="(min-width: 576px)" />
```

**Comment by LukasTy** [comment]
P.S. [This is](https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/) probably an even better place to check the same logic as I've replicated. 🤦

**Comment by LukasTy** [comment]
Looks like a known issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1638556, https://techcommunity.microsoft.com/t5/discussions/incorrect-media-query-pointer-coarse-not-fine-on-windows-10/m-p/3667184.
[Here](https://bugzilla.mozilla.org/show_bug.cgi?id=1638556#c21) a user is having a similar case and it looks like in their case the `(any-pointer: fine)` does actually resolve to `true`. If it is the case on your mentioned machines, then probably specifying `desktopModeMediaQuery` as `(any-pointer: fine)` would be a temporary fix. 👌

**Comment by pkuenemann** [comment]
...yes, that will help a lot. Thank you for your support! 

Greets, Lemmi.
